export interface ColoringCategory {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  tagline: string;
  description: string;
  gradient: string;
  color: string;
  accentBg: string;
  sheetCount: number;
}

export interface ColoringSheet {
  id: string;
  slug: string;
  title: string;
  categoryId: string;
  categoryName: string;
  subtitle: string;
  prompt: string;
  difficulty: "Easy" | "Medium" | "Advanced";
  ageRange: string;
  tags: string[];
  emoji: string;
  pdfFilename: string;
  svgType: string;
}

export const COLORING_CATEGORIES: ColoringCategory[] = [
  {
    id: "animals",
    name: "Animals",
    slug: "animals",
    emoji: "🦁",
    tagline: "Cute wildlife & pets",
    description: "Printable coloring pages of friendly lions, cute bears, baby hippos, elephants, puppies, and more.",
    gradient: "from-amber-500 to-orange-600",
    color: "#f59e0b",
    accentBg: "bg-amber-50 text-amber-800 border-amber-200",
    sheetCount: 10,
  },
  {
    id: "birds",
    name: "Birds",
    slug: "birds",
    emoji: "🦜",
    tagline: "Feathered friends of the sky",
    description: "Coloring sheets of owls, parrots, flamingos, penguins, peacocks, eagles, and hummingbirds.",
    gradient: "from-sky-500 to-blue-600",
    color: "#0ea5e9",
    accentBg: "bg-sky-50 text-sky-800 border-sky-200",
    sheetCount: 10,
  },
  {
    id: "flowers-and-plants",
    name: "Flowers & Plants",
    slug: "flowers-and-plants",
    emoji: "🌻",
    tagline: "Blooms, trees & botanicals",
    description: "Sunflowers, roses, tulips, daisies, lotus flowers, mushrooms, and lush garden botanicals.",
    gradient: "from-rose-400 to-pink-600",
    color: "#f43f5e",
    accentBg: "bg-rose-50 text-rose-800 border-rose-200",
    sheetCount: 10,
  },
  {
    id: "dinosaurs",
    name: "Dinosaurs",
    slug: "dinosaurs",
    emoji: "🦖",
    tagline: "Prehistoric Jurassic giants",
    description: "T-Rex, Triceratops, Brachiosaurus, Stegosaurus, Pterodactyls, and baby hatching dinosaurs.",
    gradient: "from-emerald-500 to-teal-700",
    color: "#10b981",
    accentBg: "bg-emerald-50 text-emerald-800 border-emerald-200",
    sheetCount: 10,
  },
  {
    id: "vehicles",
    name: "Vehicles",
    slug: "vehicles",
    emoji: "🚀",
    tagline: "Cars, planes, trains & rockets",
    description: "Sports cars, school buses, airplanes, fire trucks, steam engines, and space rockets.",
    gradient: "from-red-500 to-rose-600",
    color: "#ef4444",
    accentBg: "bg-red-50 text-red-800 border-red-200",
    sheetCount: 10,
  },
  {
    id: "nature",
    name: "Nature",
    slug: "nature",
    emoji: "🌈",
    tagline: "Landscapes, waterfalls & skies",
    description: "Rainbows, mountains, waterfalls, sandy beaches, starry nights, and volcanic wonders.",
    gradient: "from-teal-500 to-cyan-600",
    color: "#14b8a6",
    accentBg: "bg-teal-50 text-teal-800 border-teal-200",
    sheetCount: 10,
  },
  {
    id: "food",
    name: "Food",
    slug: "food",
    emoji: "🍕",
    tagline: "Yummy treats & sweet snacks",
    description: "Ice cream sundaes, pizza slices, cupcakes, birthday cakes, donuts, and fruit bowls.",
    gradient: "from-orange-400 to-amber-500",
    color: "#f97316",
    accentBg: "bg-orange-50 text-orange-800 border-orange-200",
    sheetCount: 10,
  },
  {
    id: "space",
    name: "Space",
    slug: "space",
    emoji: "🪐",
    tagline: "Astronauts, planets & galaxies",
    description: "Astronauts, solar system planets, alien UFOs, Planet Saturn, satellites, and shooting stars.",
    gradient: "from-indigo-600 to-violet-800",
    color: "#6366f1",
    accentBg: "bg-indigo-50 text-indigo-800 border-indigo-200",
    sheetCount: 10,
  },
  {
    id: "people-and-professions",
    name: "People & Professions",
    slug: "people-and-professions",
    emoji: "👩‍⚕️",
    tagline: "Doctors, teachers & heroes",
    description: "Doctors, teachers, firefighters, police officers, chefs, pilots, and scientists in action.",
    gradient: "from-blue-500 to-indigo-600",
    color: "#3b82f6",
    accentBg: "bg-blue-50 text-blue-800 border-blue-200",
    sheetCount: 10,
  },
  {
    id: "fantasy-and-fairy-tales",
    name: "Fantasy & Fairy Tales",
    slug: "fantasy-and-fairy-tales",
    emoji: "🦄",
    tagline: "Unicorns, dragons & castles",
    description: "Magical unicorns, friendly dragons, fairy castles, mermaids, wizards, and pegasus steeds.",
    gradient: "from-purple-500 to-fuchsia-600",
    color: "#a855f7",
    accentBg: "bg-purple-50 text-purple-800 border-purple-200",
    sheetCount: 10,
  },
  {
    id: "festivals-and-holidays",
    name: "Festivals & Holidays",
    slug: "festivals-and-holidays",
    emoji: "🎄",
    tagline: "Christmas, Diwali, Easter & parties",
    description: "Christmas trees, Halloween pumpkins, Easter bunnies, Diwali diyas, and festive balloons.",
    gradient: "from-pink-500 to-rose-600",
    color: "#ec4899",
    accentBg: "bg-pink-50 text-pink-800 border-pink-200",
    sheetCount: 10,
  },
  {
    id: "sports",
    name: "Sports",
    slug: "sports",
    emoji: "⚽",
    tagline: "Soccer, basketball & athletes",
    description: "Soccer goals, basketball hoops, baseball bats, tennis matches, cyclists, and swimmers.",
    gradient: "from-lime-500 to-emerald-600",
    color: "#84cc16",
    accentBg: "bg-lime-50 text-lime-800 border-lime-200",
    sheetCount: 10,
  },
  {
    id: "places-and-buildings",
    name: "Places & Buildings",
    slug: "places-and-buildings",
    emoji: "🏰",
    tagline: "Castles, schools & famous landmarks",
    description: "School houses, cozy cottages, stone castle towers, ocean lighthouses, and windmills.",
    gradient: "from-amber-600 to-yellow-600",
    color: "#d97706",
    accentBg: "bg-amber-50 text-amber-800 border-amber-200",
    sheetCount: 10,
  },
  {
    id: "educational-coloring",
    name: "Educational Coloring",
    slug: "educational-coloring",
    emoji: "🔤",
    tagline: "ABC, numbers, shapes & clocks",
    description: "Alphabet ABC fun, number counting 1-10, geometric shapes, color-by-number, and body parts.",
    gradient: "from-cyan-500 to-blue-600",
    color: "#06b6d4",
    accentBg: "bg-cyan-50 text-cyan-800 border-cyan-200",
    sheetCount: 10,
  },
  {
    id: "seasons-and-weather",
    name: "Seasons & Weather",
    slug: "seasons-and-weather",
    emoji: "⛄",
    tagline: "Summer, winter, autumn & spring",
    description: "Winter snowmen, summer beaches, autumn leaves, spring blossoms, rainy umbrellas, and kites.",
    gradient: "from-sky-400 to-indigo-500",
    color: "#38bdf8",
    accentBg: "bg-sky-50 text-sky-800 border-sky-200",
    sheetCount: 10,
  },
];

// Complete list of 150 coloring sheets (15 categories × 10 sheets)
export const COLORING_SHEETS: ColoringSheet[] = [
  // ── 1. ANIMALS ───────────────────────────────────────────────────────────
  {
    id: "animals-elephant",
    slug: "elephant",
    title: "Elephant",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Grab your crayons or markers and give this friendly elephant some colour.",
    prompt: "Color the Elephant!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["elephant", "safari", "animal", "easy coloring"],
    emoji: "🐘",
    pdfFilename: "color-elephant.pdf",
    svgType: "elephant",
  },
  {
    id: "animals-cute-bear",
    slug: "cute-bear",
    title: "Cute Teddy Bear",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Give this adorable smiling teddy bear warm and cozy fur colours.",
    prompt: "Color the Cute Bear!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["bear", "teddy bear", "cute", "animal"],
    emoji: "🧸",
    pdfFilename: "color-cute-bear.pdf",
    svgType: "cute-bear",
  },
  {
    id: "animals-baby-hippo",
    slug: "baby-hippo",
    title: "Baby Hippo",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Color this cheerful baby hippo splashing with a big happy smile.",
    prompt: "Color the Baby Hippo!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["hippo", "safari", "water animal", "cute"],
    emoji: "🦛",
    pdfFilename: "color-baby-hippo.pdf",
    svgType: "baby-hippo",
  },
  {
    id: "animals-friendly-lion",
    slug: "friendly-lion",
    title: "Friendly Lion",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Make the king of the jungle look glorious with a golden mane.",
    prompt: "Color the Friendly Lion!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["lion", "safari", "king of jungle", "cats"],
    emoji: "🦁",
    pdfFilename: "color-friendly-lion.pdf",
    svgType: "friendly-lion",
  },
  {
    id: "animals-playful-puppy",
    slug: "playful-puppy",
    title: "Playful Puppy",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Color this happy wagging puppy with floppy ears and paws.",
    prompt: "Color the Playful Puppy!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["dog", "puppy", "pet", "cute animals"],
    emoji: "🐶",
    pdfFilename: "color-playful-puppy.pdf",
    svgType: "playful-puppy",
  },
  {
    id: "animals-cute-kitten",
    slug: "cute-kitten",
    title: "Cute Kitten",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Bring this sweet kitten with whiskers and a bow tie to life.",
    prompt: "Color the Cute Kitten!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["cat", "kitten", "pet", "whiskers"],
    emoji: "🐱",
    pdfFilename: "color-cute-kitten.pdf",
    svgType: "cute-kitten",
  },
  {
    id: "animals-tall-giraffe",
    slug: "tall-giraffe",
    title: "Tall Giraffe",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Color the long neck, friendly face, and spotty patterns of this giraffe.",
    prompt: "Color the Tall Giraffe!",
    difficulty: "Medium",
    ageRange: "Ages 4-8",
    tags: ["giraffe", "tall animal", "safari", "spots"],
    emoji: "🦒",
    pdfFilename: "color-tall-giraffe.pdf",
    svgType: "tall-giraffe",
  },
  {
    id: "animals-cheeky-monkey",
    slug: "cheeky-monkey",
    title: "Cheeky Monkey",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Color this playful monkey holding a banana on a jungle branch.",
    prompt: "Color the Cheeky Monkey!",
    difficulty: "Medium",
    ageRange: "Ages 4-8",
    tags: ["monkey", "jungle", "banana", "playful"],
    emoji: "🐒",
    pdfFilename: "color-cheeky-monkey.pdf",
    svgType: "cheeky-monkey",
  },
  {
    id: "animals-happy-dolphin",
    slug: "happy-dolphin",
    title: "Happy Dolphin",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Watch this joyful dolphin leap over shimmering ocean waves.",
    prompt: "Color the Happy Dolphin!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["dolphin", "ocean", "sea animal", "water"],
    emoji: "🐬",
    pdfFilename: "color-happy-dolphin.pdf",
    svgType: "happy-dolphin",
  },
  {
    id: "animals-striped-tiger",
    slug: "striped-tiger",
    title: "Striped Tiger",
    categoryId: "animals",
    categoryName: "Animals",
    subtitle: "Fill in the bold stripes and proud paws of this friendly jungle tiger.",
    prompt: "Color the Striped Tiger!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["tiger", "stripes", "wild cat", "jungle"],
    emoji: "🐯",
    pdfFilename: "color-striped-tiger.pdf",
    svgType: "striped-tiger",
  },

  // ── 2. BIRDS ─────────────────────────────────────────────────────────────
  {
    id: "birds-wise-owl",
    slug: "wise-owl",
    title: "Wise Owl",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Color big round eyes and feathered wings perched under the moon.",
    prompt: "Color the Wise Owl!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["owl", "night bird", "wise", "forest"],
    emoji: "🦉",
    pdfFilename: "color-wise-owl.pdf",
    svgType: "wise-owl",
  },
  {
    id: "birds-colorful-parrot",
    slug: "colorful-parrot",
    title: "Colorful Parrot",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Use your brightest rainbow shades for this tropical talking parrot.",
    prompt: "Color the Colorful Parrot!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["parrot", "tropical", "rainbow bird", "rainforest"],
    emoji: "🦜",
    pdfFilename: "color-colorful-parrot.pdf",
    svgType: "colorful-parrot",
  },
  {
    id: "birds-cute-penguin",
    slug: "cute-penguin",
    title: "Cute Penguin",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Give this little waddling penguin an icy scarf and cozy belly.",
    prompt: "Color the Cute Penguin!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["penguin", "ice", "antarctica", "cute"],
    emoji: "🐧",
    pdfFilename: "color-cute-penguin.pdf",
    svgType: "cute-penguin",
  },
  {
    id: "birds-graceful-flamingo",
    slug: "graceful-flamingo",
    title: "Graceful Flamingo",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Color this elegant pink flamingo standing on one slender leg.",
    prompt: "Color the Graceful Flamingo!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["flamingo", "pink bird", "water", "nature"],
    emoji: "🦩",
    pdfFilename: "color-graceful-flamingo.pdf",
    svgType: "graceful-flamingo",
  },
  {
    id: "birds-royal-peacock",
    slug: "royal-peacock",
    title: "Royal Peacock",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Decorate the magnificent fan of eye-patterned peacock feathers.",
    prompt: "Color the Royal Peacock!",
    difficulty: "Advanced",
    ageRange: "Ages 5-10",
    tags: ["peacock", "feathers", "national bird", "detailed"],
    emoji: "🦚",
    pdfFilename: "color-royal-peacock.pdf",
    svgType: "royal-peacock",
  },
  {
    id: "birds-little-duckling",
    slug: "little-duckling",
    title: "Little Duckling",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Color this sweet yellow duckling swimming in a pond of lilypads.",
    prompt: "Color the Little Duckling!",
    difficulty: "Easy",
    ageRange: "Ages 3-6",
    tags: ["duck", "duckling", "pond", "farm"],
    emoji: "🦆",
    pdfFilename: "color-little-duckling.pdf",
    svgType: "little-duckling",
  },
  {
    id: "birds-mighty-eagle",
    slug: "mighty-eagle",
    title: "Mighty Eagle",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Color the soaring wings and sharp watchful gaze of this mountain eagle.",
    prompt: "Color the Mighty Eagle!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["eagle", "raptor", "mountain", "wings"],
    emoji: "🦅",
    pdfFilename: "color-mighty-eagle.pdf",
    svgType: "mighty-eagle",
  },
  {
    id: "birds-tiny-hummingbird",
    slug: "tiny-hummingbird",
    title: "Tiny Hummingbird",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Color this speedy little hummingbird sipping nectar from a blossom.",
    prompt: "Color the Tiny Hummingbird!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["hummingbird", "nectar", "flower", "speedy"],
    emoji: "🐦",
    pdfFilename: "color-tiny-hummingbird.pdf",
    svgType: "tiny-hummingbird",
  },
  {
    id: "birds-tropical-toucan",
    slug: "tropical-toucan",
    title: "Tropical Toucan",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Make the giant curved bill of this toucan burst with tropical hues.",
    prompt: "Color the Tropical Toucan!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["toucan", "jungle bird", "big beak", "rainforest"],
    emoji: "🪶",
    pdfFilename: "color-tropical-toucan.pdf",
    svgType: "tropical-toucan",
  },
  {
    id: "birds-sweet-robin",
    slug: "sweet-robin",
    title: "Sweet Robin",
    categoryId: "birds",
    categoryName: "Birds",
    subtitle: "Color the friendly red-breasted robin singing on a springtime branch.",
    prompt: "Color the Sweet Robin!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["robin", "songbird", "spring", "garden"],
    emoji: "🐤",
    pdfFilename: "color-sweet-robin.pdf",
    svgType: "sweet-robin",
  },

  // ── 3. FLOWERS & PLANTS ──────────────────────────────────────────────────
  {
    id: "flowers-bright-sunflower",
    slug: "bright-sunflower",
    title: "Bright Sunflower",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Give this happy smiling sunflower bright yellow petals and big green leaves.",
    prompt: "Color the Bright Sunflower!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["sunflower", "summer", "flower", "sunshine"],
    emoji: "🌻",
    pdfFilename: "color-bright-sunflower.pdf",
    svgType: "bright-sunflower",
  },
  {
    id: "flowers-beautiful-rose",
    slug: "beautiful-rose",
    title: "Beautiful Rose",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color the spiraled blooming petals of this classic garden rose.",
    prompt: "Color the Beautiful Rose!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["rose", "garden", "petals", "romantic"],
    emoji: "🌹",
    pdfFilename: "color-beautiful-rose.pdf",
    svgType: "beautiful-rose",
  },
  {
    id: "flowers-spring-tulip",
    slug: "spring-tulip",
    title: "Spring Tulip",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Cup-shaped spring tulips blooming in a fresh grassy meadow.",
    prompt: "Color the Spring Tulip!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["tulip", "spring", "garden", "simple"],
    emoji: "🌷",
    pdfFilename: "color-spring-tulip.pdf",
    svgType: "spring-tulip",
  },
  {
    id: "flowers-desert-cactus",
    slug: "desert-cactus",
    title: "Desert Cactus",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color this friendly prickly cactus in a terracotta pot with a flower topper.",
    prompt: "Color the Desert Cactus!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["cactus", "desert", "pot plant", "succulent"],
    emoji: "🌵",
    pdfFilename: "color-desert-cactus.pdf",
    svgType: "desert-cactus",
  },
  {
    id: "flowers-cheerful-daisy",
    slug: "cheerful-daisy",
    title: "Cheerful Daisy",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color round petal daisies dancing gently in a spring breeze.",
    prompt: "Color the Cheerful Daisy!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["daisy", "meadow", "wildflower", "cheerful"],
    emoji: "🌼",
    pdfFilename: "color-cheerful-daisy.pdf",
    svgType: "cheerful-daisy",
  },
  {
    id: "flowers-sacred-lotus",
    slug: "sacred-lotus",
    title: "Sacred Lotus",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color the layered serene petals of a lotus floating upon calm water.",
    prompt: "Color the Sacred Lotus!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["lotus", "water lily", "peaceful", "lake"],
    emoji: "🪷",
    pdfFilename: "color-sacred-lotus.pdf",
    svgType: "sacred-lotus",
  },
  {
    id: "flowers-mighty-oak-tree",
    slug: "mighty-oak-tree",
    title: "Mighty Oak Tree",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color the spreading leafy canopy and deep roots of a noble oak tree.",
    prompt: "Color the Mighty Oak Tree!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["tree", "oak", "forest", "nature"],
    emoji: "🌳",
    pdfFilename: "color-mighty-oak-tree.pdf",
    svgType: "mighty-oak-tree",
  },
  {
    id: "flowers-magic-mushroom",
    slug: "magic-mushroom",
    title: "Magic Mushroom",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color this storybook polka-dot toadstool with woodland ferns.",
    prompt: "Color the Magic Mushroom!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["mushroom", "toadstool", "fairy forest", "dots"],
    emoji: "🍄",
    pdfFilename: "color-magic-mushroom.pdf",
    svgType: "magic-mushroom",
  },
  {
    id: "flowers-exotic-orchid",
    slug: "exotic-orchid",
    title: "Exotic Orchid",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color the delicate petals and arching stem of an exotic orchid.",
    prompt: "Color the Exotic Orchid!",
    difficulty: "Advanced",
    ageRange: "Ages 6-11",
    tags: ["orchid", "exotic flower", "botanical", "tropical"],
    emoji: "🌸",
    pdfFilename: "color-exotic-orchid.pdf",
    svgType: "exotic-orchid",
  },
  {
    id: "flowers-butterfly-and-flower",
    slug: "butterfly-and-flower",
    title: "Butterfly & Blossom",
    categoryId: "flowers-and-plants",
    categoryName: "Flowers & Plants",
    subtitle: "Color the patterned butterfly wings visiting a blooming garden flower.",
    prompt: "Color the Butterfly & Flower!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["butterfly", "flower", "garden", "insects"],
    emoji: "🦋",
    pdfFilename: "color-butterfly-and-flower.pdf",
    svgType: "butterfly-and-flower",
  },

  // ── 4. DINOSAURS ─────────────────────────────────────────────────────────
  {
    id: "dinosaurs-t-rex",
    slug: "mighty-t-rex",
    title: "Mighty T-Rex",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the king of the dinos with mighty jaws and prehistoric scales.",
    prompt: "Color the Mighty T-Rex!",
    difficulty: "Medium",
    ageRange: "Ages 4-10",
    tags: ["trex", "tyrannosaurus", "dinosaur", "jurassic"],
    emoji: "🦖",
    pdfFilename: "color-mighty-t-rex.pdf",
    svgType: "mighty-t-rex",
  },
  {
    id: "dinosaurs-triceratops",
    slug: "three-horned-triceratops",
    title: "Triceratops",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the three sharp horns and great shield collar of this herbivore.",
    prompt: "Color the Triceratops!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["triceratops", "three horns", "dino", "jurassic"],
    emoji: "🦕",
    pdfFilename: "color-three-horned-triceratops.pdf",
    svgType: "three-horned-triceratops",
  },
  {
    id: "dinosaurs-brachiosaurus",
    slug: "long-neck-brachiosaurus",
    title: "Brachiosaurus",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color this giant friendly long-necked dino reaching high treetops.",
    prompt: "Color the Brachiosaurus!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["brachiosaurus", "long neck", "giant dinosaur", "leaves"],
    emoji: "🦕",
    pdfFilename: "color-long-neck-brachiosaurus.pdf",
    svgType: "long-neck-brachiosaurus",
  },
  {
    id: "dinosaurs-stegosaurus",
    slug: "armored-stegosaurus",
    title: "Stegosaurus",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the diamond back plates and spiked thagomizer tail.",
    prompt: "Color the Stegosaurus!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["stegosaurus", "back plates", "spikes", "dino"],
    emoji: "🐊",
    pdfFilename: "color-armored-stegosaurus.pdf",
    svgType: "armored-stegosaurus",
  },
  {
    id: "dinosaurs-pterodactyl",
    slug: "flying-pterodactyl",
    title: "Flying Pterodactyl",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color this winged reptile soaring high above prehistoric volcanoes.",
    prompt: "Color the Flying Pterodactyl!",
    difficulty: "Easy",
    ageRange: "Ages 4-9",
    tags: ["pterodactyl", "flying dino", "wings", "sky"],
    emoji: "🦅",
    pdfFilename: "color-flying-pterodactyl.pdf",
    svgType: "flying-pterodactyl",
  },
  {
    id: "dinosaurs-velociraptor",
    slug: "speedy-velociraptor",
    title: "Speedy Velociraptor",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the swift legs, curved claws, and agile tail of the raptor.",
    prompt: "Color the Velociraptor!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["raptor", "velociraptor", "speedy", "predator"],
    emoji: "🦎",
    pdfFilename: "color-speedy-velociraptor.pdf",
    svgType: "speedy-velociraptor",
  },
  {
    id: "dinosaurs-ankylosaurus",
    slug: "club-tailed-ankylosaurus",
    title: "Ankylosaurus",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the heavy armor shell and heavy tail club of this tank dino.",
    prompt: "Color the Ankylosaurus!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["ankylosaurus", "tank", "armored dinosaur", "tail club"],
    emoji: "🐢",
    pdfFilename: "color-club-tailed-ankylosaurus.pdf",
    svgType: "club-tailed-ankylosaurus",
  },
  {
    id: "dinosaurs-spinosaurus",
    slug: "sail-backed-spinosaurus",
    title: "Spinosaurus",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the giant webbed spine sail and crocodile snout of the Spinosaurus.",
    prompt: "Color the Spinosaurus!",
    difficulty: "Advanced",
    ageRange: "Ages 5-10",
    tags: ["spinosaurus", "sail", "river hunter", "giant"],
    emoji: "🐉",
    pdfFilename: "color-sail-backed-spinosaurus.pdf",
    svgType: "sail-backed-spinosaurus",
  },
  {
    id: "dinosaurs-baby-dino-hatching",
    slug: "baby-dino-hatching",
    title: "Baby Dino Hatching",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color a super-cute baby dinosaur peeking out of a cracked eggshell.",
    prompt: "Color the Baby Dino Hatching!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["baby dino", "egg", "hatching", "cute"],
    emoji: "🥚",
    pdfFilename: "color-baby-dino-hatching.pdf",
    svgType: "baby-dino-hatching",
  },
  {
    id: "dinosaurs-giant-diplodocus",
    slug: "giant-diplodocus",
    title: "Giant Diplodocus",
    categoryId: "dinosaurs",
    categoryName: "Dinosaurs",
    subtitle: "Color the whip-like tail and immense length of the Diplodocus.",
    prompt: "Color the Giant Diplodocus!",
    difficulty: "Easy",
    ageRange: "Ages 4-9",
    tags: ["diplodocus", "whip tail", "herbivore", "jurassic"],
    emoji: "🦕",
    pdfFilename: "color-giant-diplodocus.pdf",
    svgType: "giant-diplodocus",
  },

  // ── 5. VEHICLES ──────────────────────────────────────────────────────────
  {
    id: "vehicles-sports-car",
    slug: "speedy-sports-car",
    title: "Speedy Sports Car",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Give this aerodynamic race car your favorite bold racing colors.",
    prompt: "Color the Sports Car!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["car", "sports car", "racing", "wheels"],
    emoji: "🏎️",
    pdfFilename: "color-speedy-sports-car.pdf",
    svgType: "speedy-sports-car",
  },
  {
    id: "vehicles-school-bus",
    slug: "yellow-school-bus",
    title: "School Bus",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the big cheerful school bus ready to pick up all students.",
    prompt: "Color the School Bus!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["bus", "school", "yellow bus", "transport"],
    emoji: "🚌",
    pdfFilename: "color-yellow-school-bus.pdf",
    svgType: "yellow-school-bus",
  },
  {
    id: "vehicles-jet-airplane",
    slug: "jet-airplane",
    title: "Jet Airplane",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color this sleek passenger jet soaring through white fluffy clouds.",
    prompt: "Color the Jet Airplane!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["airplane", "jet", "flying", "travel"],
    emoji: "✈️",
    pdfFilename: "color-jet-airplane.pdf",
    svgType: "jet-airplane",
  },
  {
    id: "vehicles-fire-truck",
    slug: "fire-truck-rescue",
    title: "Fire Truck",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the rescue ladder, flashing sirens, and hoses of the fire engine.",
    prompt: "Color the Fire Truck!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["fire truck", "rescue", "ladder", "heroes"],
    emoji: "🚒",
    pdfFilename: "color-fire-truck-rescue.pdf",
    svgType: "fire-truck-rescue",
  },
  {
    id: "vehicles-steam-train",
    slug: "choo-choo-steam-train",
    title: "Steam Train",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the billowing steam clouds, engine wheels, and railroad track.",
    prompt: "Color the Steam Train!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["train", "steam engine", "railway", "choo choo"],
    emoji: "🚂",
    pdfFilename: "color-choo-choo-steam-train.pdf",
    svgType: "choo-choo-steam-train",
  },
  {
    id: "vehicles-police-cruiser",
    slug: "police-cruiser",
    title: "Police Car",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the bold badge, roof lights, and wheels of this city police car.",
    prompt: "Color the Police Car!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["police", "patrol car", "emergency", "siren"],
    emoji: "🚓",
    pdfFilename: "color-police-cruiser.pdf",
    svgType: "police-cruiser",
  },
  {
    id: "vehicles-space-rocket",
    slug: "blast-off-rocket",
    title: "Space Rocket",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the fiery thruster flames launching a rocket toward deep space.",
    prompt: "Color the Space Rocket!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["rocket", "blast off", "spacecraft", "launch"],
    emoji: "🚀",
    pdfFilename: "color-blast-off-rocket.pdf",
    svgType: "blast-off-rocket",
  },
  {
    id: "vehicles-bicycle",
    slug: "two-wheel-bicycle",
    title: "Two-Wheel Bicycle",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the spokes, handlebar bell, and frame of a fun outdoor bicycle.",
    prompt: "Color the Bicycle!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["bike", "bicycle", "cycling", "outdoor"],
    emoji: "🚲",
    pdfFilename: "color-two-wheel-bicycle.pdf",
    svgType: "two-wheel-bicycle",
  },
  {
    id: "vehicles-sailboat",
    slug: "ocean-sailboat",
    title: "Ocean Sailboat",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the big billowed sails gliding across peaceful seaside waves.",
    prompt: "Color the Sailboat!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["boat", "sailboat", "sea", "ocean"],
    emoji: "⛵",
    pdfFilename: "color-ocean-sailboat.pdf",
    svgType: "ocean-sailboat",
  },
  {
    id: "vehicles-helicopter",
    slug: "rescue-helicopter",
    title: "Rescue Helicopter",
    categoryId: "vehicles",
    categoryName: "Vehicles",
    subtitle: "Color the spinning rotor blades, cockpit glass, and tail propeller.",
    prompt: "Color the Rescue Helicopter!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["helicopter", "rotor", "rescue", "aviation"],
    emoji: "🚁",
    pdfFilename: "color-rescue-helicopter.pdf",
    svgType: "rescue-helicopter",
  },

  // ── 6. NATURE ────────────────────────────────────────────────────────────
  {
    id: "nature-rainbow-clouds",
    slug: "rainbow-and-clouds",
    title: "Rainbow & Clouds",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color every vibrant band of the rainbow arching between fluffy clouds.",
    prompt: "Color the Rainbow & Clouds!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["rainbow", "clouds", "sky", "weather"],
    emoji: "🌈",
    pdfFilename: "color-rainbow-and-clouds.pdf",
    svgType: "rainbow-and-clouds",
  },
  {
    id: "nature-mountain-sunrise",
    slug: "mountain-sunrise",
    title: "Mountain Sunrise",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color the golden sun rising behind grand snow-capped mountain peaks.",
    prompt: "Color the Mountain Sunrise!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["mountains", "sunrise", "landscape", "sun"],
    emoji: "🌄",
    pdfFilename: "color-mountain-sunrise.pdf",
    svgType: "mountain-sunrise",
  },
  {
    id: "nature-forest-waterfall",
    slug: "forest-waterfall",
    title: "Forest Waterfall",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color cascading fresh water tumbling into a crystal jungle pool.",
    prompt: "Color the Forest Waterfall!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["waterfall", "river", "forest", "nature"],
    emoji: "🏞️",
    pdfFilename: "color-forest-waterfall.pdf",
    svgType: "forest-waterfall",
  },
  {
    id: "nature-tropical-island",
    slug: "tropical-island",
    title: "Tropical Island",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color palm trees, coconuts, and sunny sandy shores in the blue ocean.",
    prompt: "Color the Tropical Island!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["island", "palm tree", "tropical", "beach"],
    emoji: "🏝️",
    pdfFilename: "color-tropical-island.pdf",
    svgType: "tropical-island",
  },
  {
    id: "nature-sandy-beach",
    slug: "sandy-beach-and-waves",
    title: "Sandy Beach & Waves",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color a sandcastle, beach umbrella, seashells, and rolling waves.",
    prompt: "Color the Sandy Beach!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["beach", "sandcastle", "waves", "summer"],
    emoji: "🏖️",
    pdfFilename: "color-sandy-beach-and-waves.pdf",
    svgType: "sandy-beach-and-waves",
  },
  {
    id: "nature-starry-night",
    slug: "starry-night-sky",
    title: "Starry Night Sky",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color a shining crescent moon surrounded by twinkling constellations.",
    prompt: "Color the Starry Night Sky!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["stars", "moon", "night", "astronomy"],
    emoji: "🌌",
    pdfFilename: "color-starry-night-sky.pdf",
    svgType: "starry-night-sky",
  },
  {
    id: "nature-smoking-volcano",
    slug: "smoking-volcano",
    title: "Smoking Volcano",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color glowing lava streams flowing down a smoking volcanic mountain.",
    prompt: "Color the Volcano!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["volcano", "lava", "earth science", "geology"],
    emoji: "🌋",
    pdfFilename: "color-smoking-volcano.pdf",
    svgType: "smoking-volcano",
  },
  {
    id: "nature-coral-reef",
    slug: "coral-reef-fishes",
    title: "Coral Reef & Fishes",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color colorful coral branches and cheerful tropical clownfish.",
    prompt: "Color the Coral Reef!",
    difficulty: "Advanced",
    ageRange: "Ages 5-10",
    tags: ["coral reef", "fish", "underwater", "ocean life"],
    emoji: "🪸",
    pdfFilename: "color-coral-reef-fishes.pdf",
    svgType: "coral-reef-fishes",
  },
  {
    id: "nature-pine-forest",
    slug: "pine-forest-trail",
    title: "Pine Forest Trail",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color evergreen spruce trees and forest pinecones along a hiking path.",
    prompt: "Color the Pine Forest!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["pines", "forest", "evergreen", "woodland"],
    emoji: "🌲",
    pdfFilename: "color-pine-forest-trail.pdf",
    svgType: "pine-forest-trail",
  },
  {
    id: "nature-desert-dunes",
    slug: "desert-sand-dunes",
    title: "Desert Sand Dunes",
    categoryId: "nature",
    categoryName: "Nature",
    subtitle: "Color sweeping golden sand dunes under a shining warm sun.",
    prompt: "Color the Desert Dunes!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["desert", "sand dunes", "sahara", "warm"],
    emoji: "🏜️",
    pdfFilename: "color-desert-sand-dunes.pdf",
    svgType: "desert-sand-dunes",
  },

  // ── 7. FOOD ──────────────────────────────────────────────────────────────
  {
    id: "food-ice-cream-sundae",
    slug: "ice-cream-sundae",
    title: "Ice Cream Sundae",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color delicious scoops of ice cream with cherry, fudge, and sprinkles on top.",
    prompt: "Color the Ice Cream Sundae!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["ice cream", "dessert", "sundae", "sweet"],
    emoji: "🍨",
    pdfFilename: "color-ice-cream-sundae.pdf",
    svgType: "ice-cream-sundae",
  },
  {
    id: "food-pizza-slice",
    slug: "cheesy-pizza-slice",
    title: "Cheesy Pizza Slice",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color gooey melting cheese, pepperoni slices, and crispy crust.",
    prompt: "Color the Pizza Slice!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["pizza", "cheese", "pepperoni", "snack"],
    emoji: "🍕",
    pdfFilename: "color-cheesy-pizza-slice.pdf",
    svgType: "cheesy-pizza-slice",
  },
  {
    id: "food-sweet-cupcake",
    slug: "sweet-cupcake",
    title: "Sweet Cupcake",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color fluffy swirl frosting and heart sprinkles in a bakery wrapper.",
    prompt: "Color the Sweet Cupcake!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["cupcake", "bakery", "frosting", "treat"],
    emoji: "🧁",
    pdfFilename: "color-sweet-cupcake.pdf",
    svgType: "sweet-cupcake",
  },
  {
    id: "food-birthday-cake",
    slug: "birthday-cake",
    title: "Birthday Cake",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color a multi-tiered birthday cake topped with burning party candles.",
    prompt: "Color the Birthday Cake!",
    difficulty: "Medium",
    ageRange: "Ages 4-8",
    tags: ["cake", "birthday", "candles", "party"],
    emoji: "🎂",
    pdfFilename: "color-birthday-cake.pdf",
    svgType: "birthday-cake",
  },
  {
    id: "food-burger-fries",
    slug: "burger-and-fries",
    title: "Burger & Fries",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color sesame seed buns, lettuce, juicy patty, and golden french fries.",
    prompt: "Color the Burger & Fries!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["burger", "french fries", "fast food", "tasty"],
    emoji: "🍔",
    pdfFilename: "color-burger-and-fries.pdf",
    svgType: "burger-and-fries",
  },
  {
    id: "food-glazed-donut",
    slug: "glazed-donut",
    title: "Glazed Donut",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color sweet strawberry icing and colorful rainbow sprinkles.",
    prompt: "Color the Glazed Donut!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["donut", "doughnut", "sprinkles", "pastry"],
    emoji: "🍩",
    pdfFilename: "color-glazed-donut.pdf",
    svgType: "glazed-donut",
  },
  {
    id: "food-fruit-bowl",
    slug: "fresh-fruit-bowl",
    title: "Fresh Fruit Bowl",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color healthy apples, bananas, oranges, and grapes in a fruit bowl.",
    prompt: "Color the Fresh Fruit Bowl!",
    difficulty: "Medium",
    ageRange: "Ages 4-8",
    tags: ["fruits", "healthy", "apple", "banana"],
    emoji: "🍎",
    pdfFilename: "color-fresh-fruit-bowl.pdf",
    svgType: "fresh-fruit-bowl",
  },
  {
    id: "food-sweet-strawberry",
    slug: "sweet-strawberry",
    title: "Sweet Strawberry",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color tiny seeds, a green leaf cap, and juicy red berry fruit.",
    prompt: "Color the Strawberry!",
    difficulty: "Easy",
    ageRange: "Ages 3-6",
    tags: ["strawberry", "berry", "fruit", "sweet"],
    emoji: "🍓",
    pdfFilename: "color-sweet-strawberry.pdf",
    svgType: "sweet-strawberry",
  },
  {
    id: "food-tasty-taco",
    slug: "tasty-taco",
    title: "Tasty Taco",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color a crunchy folded taco shell loaded with cheese, tomatoes, and salsa.",
    prompt: "Color the Tasty Taco!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["taco", "mexican food", "crispy", "snack"],
    emoji: "🌮",
    pdfFilename: "color-tasty-taco.pdf",
    svgType: "tasty-taco",
  },
  {
    id: "food-movie-popcorn",
    slug: "movie-popcorn",
    title: "Movie Popcorn",
    categoryId: "food",
    categoryName: "Food",
    subtitle: "Color a striped red-and-white bucket overflowing with buttery popcorn.",
    prompt: "Color the Movie Popcorn!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["popcorn", "movie", "cinema", "snack"],
    emoji: "🍿",
    pdfFilename: "color-movie-popcorn.pdf",
    svgType: "movie-popcorn",
  },

  // ── 8. SPACE ─────────────────────────────────────────────────────────────
  {
    id: "space-astronaut",
    slug: "astronaut-floating",
    title: "Astronaut Floating",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color a space suit, reflective visor, and zero-gravity tether in orbit.",
    prompt: "Color the Astronaut!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["astronaut", "spacewalk", "space", "cosmonaut"],
    emoji: "👨‍🚀",
    pdfFilename: "color-astronaut-floating.pdf",
    svgType: "astronaut-floating",
  },
  {
    id: "space-solar-system",
    slug: "solar-system-planets",
    title: "Solar System Planets",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color the Sun and all 8 orbiting planets in their cosmic orbits.",
    prompt: "Color the Solar System!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["planets", "sun", "solar system", "science"],
    emoji: "🪐",
    pdfFilename: "color-solar-system-planets.pdf",
    svgType: "solar-system-planets",
  },
  {
    id: "space-alien-ufo",
    slug: "friendly-alien-ufo",
    title: "Friendly Alien UFO",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color a flying saucer saucer beam and a waving cute little alien.",
    prompt: "Color the Alien UFO!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["alien", "ufo", "flying saucer", "space monster"],
    emoji: "🛸",
    pdfFilename: "color-friendly-alien-ufo.pdf",
    svgType: "friendly-alien-ufo",
  },
  {
    id: "space-planet-saturn",
    slug: "ringed-planet-saturn",
    title: "Planet Saturn",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color the magnificent cosmic dust rings and cloud bands of Saturn.",
    prompt: "Color Planet Saturn!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["saturn", "rings", "planet", "astronomy"],
    emoji: "🪐",
    pdfFilename: "color-ringed-planet-saturn.pdf",
    svgType: "ringed-planet-saturn",
  },
  {
    id: "space-deep-space-rocket",
    slug: "deep-space-rocket",
    title: "Deep Space Rocket",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color a sleek multi-stage rocket speeding through asteroid fields.",
    prompt: "Color the Space Rocket!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["rocket", "spacecraft", "stars", "speed"],
    emoji: "🚀",
    pdfFilename: "color-deep-space-rocket.pdf",
    svgType: "deep-space-rocket",
  },
  {
    id: "space-moon-rover",
    slug: "moon-surface-rover",
    title: "Moon Rover",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color heavy tread wheels exploring craters on the lunar surface.",
    prompt: "Color the Moon Rover!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["rover", "moon", "lunar", "robot"],
    emoji: "🚙",
    pdfFilename: "color-moon-surface-rover.pdf",
    svgType: "moon-surface-rover",
  },
  {
    id: "space-shooting-star",
    slug: "blazing-shooting-star",
    title: "Blazing Shooting Star",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color a bright glowing comet leaving a fiery trail across night skies.",
    prompt: "Color the Shooting Star!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["shooting star", "meteor", "comet", "wish"],
    emoji: "🌠",
    pdfFilename: "color-blazing-shooting-star.pdf",
    svgType: "blazing-shooting-star",
  },
  {
    id: "space-space-shuttle",
    slug: "space-shuttle-orbit",
    title: "Space Shuttle",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color the delta wings, heat shield tiles, and cargo bay of the shuttle.",
    prompt: "Color the Space Shuttle!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["shuttle", "nasa", "orbit", "spacecraft"],
    emoji: "🛰️",
    pdfFilename: "color-space-shuttle-orbit.pdf",
    svgType: "space-shuttle-orbit",
  },
  {
    id: "space-satellite",
    slug: "orbiting-satellite",
    title: "Orbiting Satellite",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color blue solar power panels and communications antennas in space.",
    prompt: "Color the Satellite!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["satellite", "solar panels", "technology", "orbit"],
    emoji: "📡",
    pdfFilename: "color-orbiting-satellite.pdf",
    svgType: "orbiting-satellite",
  },
  {
    id: "space-spiral-galaxy",
    slug: "spiral-galaxy-stars",
    title: "Spiral Galaxy",
    categoryId: "space",
    categoryName: "Space",
    subtitle: "Color swirling cosmic arms of millions of glowing stars in deep space.",
    prompt: "Color the Spiral Galaxy!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["galaxy", "milky way", "cosmos", "stars"],
    emoji: "🌌",
    pdfFilename: "color-spiral-galaxy-stars.pdf",
    svgType: "spiral-galaxy-stars",
  },

  // ── 9. PEOPLE & PROFESSIONS ──────────────────────────────────────────────
  {
    id: "professions-doctor",
    slug: "helpful-doctor",
    title: "Helpful Doctor",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color the white coat, stethoscope, and smiling face of a friendly doctor.",
    prompt: "Color the Helpful Doctor!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["doctor", "hospital", "medicine", "health"],
    emoji: "👩‍⚕️",
    pdfFilename: "color-helpful-doctor.pdf",
    svgType: "helpful-doctor",
  },
  {
    id: "professions-teacher",
    slug: "kind-teacher",
    title: "Kind Teacher",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color a teacher pointing to a classroom chalkboard with books.",
    prompt: "Color the Kind Teacher!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["teacher", "school", "classroom", "books"],
    emoji: "👨‍🏫",
    pdfFilename: "color-kind-teacher.pdf",
    svgType: "kind-teacher",
  },
  {
    id: "professions-firefighter",
    slug: "brave-firefighter",
    title: "Brave Firefighter",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color a yellow helmet, turnout coat, and water hose ready for action.",
    prompt: "Color the Brave Firefighter!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["firefighter", "rescue", "helmet", "hero"],
    emoji: "🧑‍🚒",
    pdfFilename: "color-brave-firefighter.pdf",
    svgType: "brave-firefighter",
  },
  {
    id: "professions-police-officer",
    slug: "police-officer",
    title: "Police Officer",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color the uniform, cap, and badge keeping neighborhood streets safe.",
    prompt: "Color the Police Officer!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["police", "badge", "safety", "officer"],
    emoji: "👮",
    pdfFilename: "color-police-officer.pdf",
    svgType: "police-officer",
  },
  {
    id: "professions-chef",
    slug: "master-chef",
    title: "Master Chef",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color the tall white toque chef hat, apron, and delicious cooking pot.",
    prompt: "Color the Master Chef!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["chef", "cook", "kitchen", "baking"],
    emoji: "👨‍🍳",
    pdfFilename: "color-master-chef.pdf",
    svgType: "master-chef",
  },
  {
    id: "professions-astronaut",
    slug: "space-astronaut",
    title: "Space Astronaut",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color the space helmet, mission patch, and moon exploration suit.",
    prompt: "Color the Astronaut!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["astronaut", "space", "moon", "science"],
    emoji: "👨‍🚀",
    pdfFilename: "color-space-astronaut.pdf",
    svgType: "space-astronaut",
  },
  {
    id: "professions-pilot",
    slug: "airplane-pilot",
    title: "Airplane Pilot",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color the pilot captain cap, wings pin, and flight cockpit controls.",
    prompt: "Color the Airplane Pilot!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["pilot", "aviation", "airplane", "captain"],
    emoji: "🧑‍✈️",
    pdfFilename: "color-airplane-pilot.pdf",
    svgType: "airplane-pilot",
  },
  {
    id: "professions-artist",
    slug: "creative-artist",
    title: "Painter Artist",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color a painter with beret holding a wooden palette and canvas easel.",
    prompt: "Color the Painter Artist!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["artist", "painter", "palette", "creativity"],
    emoji: "🧑‍🎨",
    pdfFilename: "color-creative-artist.pdf",
    svgType: "creative-artist",
  },
  {
    id: "professions-builder",
    slug: "construction-builder",
    title: "Construction Builder",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color a bright hardhat, tool belt, hammer, and building blueprints.",
    prompt: "Color the Builder!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["builder", "construction", "tools", "hardhat"],
    emoji: "👷",
    pdfFilename: "color-construction-builder.pdf",
    svgType: "construction-builder",
  },
  {
    id: "professions-scientist",
    slug: "lab-scientist",
    title: "Lab Scientist",
    categoryId: "people-and-professions",
    categoryName: "People & Professions",
    subtitle: "Color safety goggles, lab coat, and a bubbling test tube beaker.",
    prompt: "Color the Scientist!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["scientist", "laboratory", "chemistry", "experiments"],
    emoji: "🧑‍🔬",
    pdfFilename: "color-lab-scientist.pdf",
    svgType: "lab-scientist",
  },

  // ── 10. FANTASY & FAIRY TALES ────────────────────────────────────────────
  {
    id: "fantasy-unicorn",
    slug: "magical-unicorn",
    title: "Magical Unicorn",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color the spiral golden horn, rainbow mane, and magical stars.",
    prompt: "Color the Magical Unicorn!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["unicorn", "rainbow", "magic", "fantasy"],
    emoji: "🦄",
    pdfFilename: "color-magical-unicorn.pdf",
    svgType: "magical-unicorn",
  },
  {
    id: "fantasy-dragon",
    slug: "friendly-dragon",
    title: "Friendly Dragon",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color large dragon wings, soft belly scales, and a playful smile.",
    prompt: "Color the Friendly Dragon!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["dragon", "wings", "castle", "mythical"],
    emoji: "🐉",
    pdfFilename: "color-friendly-dragon.pdf",
    svgType: "friendly-dragon",
  },
  {
    id: "fantasy-castle",
    slug: "fairytale-castle",
    title: "Fairy Tale Castle",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color tall stone spires, flags, arched gates, and castle turrets.",
    prompt: "Color the Fairy Tale Castle!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["castle", "fairytale", "palace", "princess"],
    emoji: "🏰",
    pdfFilename: "color-fairytale-castle.pdf",
    svgType: "fairytale-castle",
  },
  {
    id: "fantasy-mermaid",
    slug: "beautiful-mermaid",
    title: "Beautiful Mermaid",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color glittering fish tail scales and seashell hair accessories.",
    prompt: "Color the Beautiful Mermaid!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["mermaid", "underwater", "ocean", "fairytale"],
    emoji: "🧜‍♀️",
    pdfFilename: "color-beautiful-mermaid.pdf",
    svgType: "beautiful-mermaid",
  },
  {
    id: "fantasy-forest-fairy",
    slug: "forest-fairy",
    title: "Winged Forest Fairy",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color glowing butterfly wings, a leaf dress, and a magic glitter wand.",
    prompt: "Color the Forest Fairy!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["fairy", "magic wand", "wings", "woodland"],
    emoji: "🧚",
    pdfFilename: "color-forest-fairy.pdf",
    svgType: "forest-fairy",
  },
  {
    id: "fantasy-magic-wizard",
    slug: "magic-wizard",
    title: "Magic Wizard",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color a starry pointy hat, long white beard, and glowing magic staff.",
    prompt: "Color the Magic Wizard!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["wizard", "spells", "magic hat", "potion"],
    emoji: "🧙",
    pdfFilename: "color-magic-wizard.pdf",
    svgType: "magic-wizard",
  },
  {
    id: "fantasy-brave-knight",
    slug: "brave-knight",
    title: "Brave Knight",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color the polished steel armor, royal crest shield, and feather helmet.",
    prompt: "Color the Brave Knight!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["knight", "armor", "shield", "medieval"],
    emoji: "🛡️",
    pdfFilename: "color-brave-knight.pdf",
    svgType: "brave-knight",
  },
  {
    id: "fantasy-flying-pegasus",
    slug: "flying-pegasus",
    title: "Flying Pegasus",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color the majestic feathered wings of this flying mythological horse.",
    prompt: "Color the Flying Pegasus!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["pegasus", "winged horse", "mythology", "clouds"],
    emoji: "🪽",
    pdfFilename: "color-flying-pegasus.pdf",
    svgType: "flying-pegasus",
  },
  {
    id: "fantasy-treasure-chest",
    slug: "treasure-chest",
    title: "Pirate Treasure Chest",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color gold coins, ruby jewels, and an ancient wooden pirate chest.",
    prompt: "Color the Treasure Chest!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["treasure", "pirate", "gold", "jewels"],
    emoji: "🪙",
    pdfFilename: "color-treasure-chest.pdf",
    svgType: "treasure-chest",
  },
  {
    id: "fantasy-genie-lamp",
    slug: "magic-genie-lamp",
    title: "Magic Genie Lamp",
    categoryId: "fantasy-and-fairy-tales",
    categoryName: "Fantasy & Fairy Tales",
    subtitle: "Color shimmering golden curves with magical smoke swirls rising out.",
    prompt: "Color the Magic Genie Lamp!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["genie", "magic lamp", "wishes", "arabian nights"],
    emoji: "🪔",
    pdfFilename: "color-magic-genie-lamp.pdf",
    svgType: "magic-genie-lamp",
  },

  // ── 11. FESTIVALS & HOLIDAYS ─────────────────────────────────────────────
  {
    id: "festivals-christmas-tree",
    slug: "christmas-tree",
    title: "Christmas Tree",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color ornaments, candy canes, glowing star topper, and gift boxes.",
    prompt: "Color the Christmas Tree!",
    difficulty: "Medium",
    ageRange: "Ages 3-8",
    tags: ["christmas", "tree", "ornaments", "holiday"],
    emoji: "🎄",
    pdfFilename: "color-christmas-tree.pdf",
    svgType: "christmas-tree",
  },
  {
    id: "festivals-santa-claus",
    slug: "santa-claus",
    title: "Jolly Santa Claus",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color Santa's bright red suit, fluffy white beard, and sack of toys.",
    prompt: "Color Jolly Santa Claus!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["santa", "christmas", "jolly", "winter"],
    emoji: "🎅",
    pdfFilename: "color-santa-claus.pdf",
    svgType: "santa-claus",
  },
  {
    id: "festivals-halloween-pumpkin",
    slug: "halloween-pumpkin",
    title: "Halloween Pumpkin",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color this friendly grinning Jack-o'-lantern pumpkin and bat friends.",
    prompt: "Color the Halloween Pumpkin!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["halloween", "pumpkin", "jackolantern", "autumn"],
    emoji: "🎃",
    pdfFilename: "color-halloween-pumpkin.pdf",
    svgType: "halloween-pumpkin",
  },
  {
    id: "festivals-easter-bunny",
    slug: "easter-bunny",
    title: "Happy Easter Bunny",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color a fluffy rabbit holding a basket packed with decorated Easter eggs.",
    prompt: "Color the Easter Bunny!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["easter", "bunny", "rabbit", "spring"],
    emoji: "🐰",
    pdfFilename: "color-easter-bunny.pdf",
    svgType: "easter-bunny",
  },
  {
    id: "festivals-diwali-diya",
    slug: "diwali-diya",
    title: "Diwali Diya Lamp",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color glowing clay oil lamps surrounded by floral rangoli patterns.",
    prompt: "Color the Diwali Diya!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["diwali", "diya", "lights", "festival"],
    emoji: "🪔",
    pdfFilename: "color-diwali-diya.pdf",
    svgType: "diwali-diya",
  },
  {
    id: "festivals-birthday-party",
    slug: "birthday-party",
    title: "Birthday Balloons Party",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color party hats, floating balloons, confetti, and wrapped present boxes.",
    prompt: "Color the Birthday Balloons!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["birthday", "party", "balloons", "celebration"],
    emoji: "🎈",
    pdfFilename: "color-birthday-party.pdf",
    svgType: "birthday-party",
  },
  {
    id: "festivals-thanksgiving-turkey",
    slug: "thanksgiving-turkey",
    title: "Thanksgiving Turkey",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color big fan tail feathers and pilgrim hat on a friendly turkey.",
    prompt: "Color the Thanksgiving Turkey!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["thanksgiving", "turkey", "autumn", "harvest"],
    emoji: "🦃",
    pdfFilename: "color-thanksgiving-turkey.pdf",
    svgType: "thanksgiving-turkey",
  },
  {
    id: "festivals-new-year-fireworks",
    slug: "new-year-fireworks",
    title: "New Year Fireworks",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color bursting sparklers and glowing fireworks over a city skyline.",
    prompt: "Color the New Year Fireworks!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["fireworks", "new year", "celebration", "sparklers"],
    emoji: "🎆",
    pdfFilename: "color-new-year-fireworks.pdf",
    svgType: "new-year-fireworks",
  },
  {
    id: "festivals-valentine-heart",
    slug: "valentine-heart",
    title: "Valentine Love Heart",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color ribbon bows, teddy bears, and floral hearts for Valentine's Day.",
    prompt: "Color the Valentine Heart!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["valentine", "heart", "love", "flowers"],
    emoji: "💖",
    pdfFilename: "color-valentine-heart.pdf",
    svgType: "valentine-heart",
  },
  {
    id: "festivals-gingerbread-man",
    slug: "gingerbread-man",
    title: "Gingerbread Man",
    categoryId: "festivals-and-holidays",
    categoryName: "Festivals & Holidays",
    subtitle: "Color sugary icing buttons, bow tie, and delicious cookie dough.",
    prompt: "Color the Gingerbread Man!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["gingerbread", "cookie", "christmas", "baking"],
    emoji: "🍪",
    pdfFilename: "color-gingerbread-man.pdf",
    svgType: "gingerbread-man",
  },

  // ── 12. SPORTS ───────────────────────────────────────────────────────────
  {
    id: "sports-soccer-goal",
    slug: "soccer-goal",
    title: "Soccer Ball & Goal",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color hexagon soccer ball patches soaring into the corner net.",
    prompt: "Color the Soccer Ball & Goal!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["soccer", "football", "goal", "sports"],
    emoji: "⚽",
    pdfFilename: "color-soccer-goal.pdf",
    svgType: "soccer-goal",
  },
  {
    id: "sports-basketball-hoop",
    slug: "basketball-hoop",
    title: "Basketball Hoop",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color an orange basketball swishing through the net rim.",
    prompt: "Color the Basketball Hoop!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["basketball", "hoop", "slam dunk", "court"],
    emoji: "🏀",
    pdfFilename: "color-basketball-hoop.pdf",
    svgType: "basketball-hoop",
  },
  {
    id: "sports-baseball-bat",
    slug: "baseball-bat",
    title: "Baseball & Bat",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color red stitches on the baseball, leather glove, and wooden bat.",
    prompt: "Color the Baseball & Bat!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["baseball", "glove", "home run", "bat"],
    emoji: "⚾",
    pdfFilename: "color-baseball-bat.pdf",
    svgType: "baseball-bat",
  },
  {
    id: "sports-tennis-racket",
    slug: "tennis-racket",
    title: "Tennis Racket",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color criss-cross tennis strings, yellow tennis ball, and court net.",
    prompt: "Color the Tennis Racket!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["tennis", "racket", "ball", "court"],
    emoji: "🎾",
    pdfFilename: "color-tennis-racket.pdf",
    svgType: "tennis-racket",
  },
  {
    id: "sports-swimmer-pool",
    slug: "swimmer-pool",
    title: "Swimmer in Pool",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color swimming goggles, splash ripples, and lane lines.",
    prompt: "Color the Swimmer in Pool!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["swimming", "pool", "water sport", "goggles"],
    emoji: "🏊",
    pdfFilename: "color-swimmer-pool.pdf",
    svgType: "swimmer-pool",
  },
  {
    id: "sports-cyclist",
    slug: "road-cyclist",
    title: "Road Cyclist",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color bike helmet, spinning racing wheels, and scenic mountain road.",
    prompt: "Color the Cyclist!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["bicycle", "cyclist", "racing", "helmet"],
    emoji: "🚴",
    pdfFilename: "color-road-cyclist.pdf",
    svgType: "road-cyclist",
  },
  {
    id: "sports-karate-kick",
    slug: "karate-kick",
    title: "Karate Kick",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color a white karate gi uniform and high-ranking black belt in action.",
    prompt: "Color the Karate Kick!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["karate", "martial arts", "kick", "taekwondo"],
    emoji: "🥋",
    pdfFilename: "color-karate-kick.pdf",
    svgType: "karate-kick",
  },
  {
    id: "sports-skateboarder",
    slug: "skateboard-trick",
    title: "Skateboarder Trick",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color skateboard deck grip tape, cool sneakers, and jump ramp.",
    prompt: "Color the Skateboarder!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["skateboard", "skater", "ollie", "ramp"],
    emoji: "🛹",
    pdfFilename: "color-skateboard-trick.pdf",
    svgType: "skateboard-trick",
  },
  {
    id: "sports-gymnast",
    slug: "gymnastics-ribbon",
    title: "Gymnastics Ribbon",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color swirling rhythmic gymnastics ribbon spirals and dance leap.",
    prompt: "Color the Gymnastics Ribbon!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["gymnastics", "ribbon", "dance", "acrobat"],
    emoji: "🤸",
    pdfFilename: "color-gymnastics-ribbon.pdf",
    svgType: "gymnastics-ribbon",
  },
  {
    id: "sports-ice-skater",
    slug: "ice-skating",
    title: "Ice Skating Champion",
    categoryId: "sports",
    categoryName: "Sports",
    subtitle: "Color graceful ice skating blades carving figure-eight loops on ice.",
    prompt: "Color the Ice Skater!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["ice skating", "figure skater", "winter sport", "ice"],
    emoji: "⛸️",
    pdfFilename: "color-ice-skating.pdf",
    svgType: "ice-skating",
  },

  // ── 13. PLACES & BUILDINGS ───────────────────────────────────────────────
  {
    id: "places-school-house",
    slug: "school-house",
    title: "School House",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color the schoolhouse clock tower, school bus, and playground flagpole.",
    prompt: "Color the School House!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["school", "building", "classroom", "education"],
    emoji: "🏫",
    pdfFilename: "color-school-house.pdf",
    svgType: "school-house",
  },
  {
    id: "places-cozy-home",
    slug: "cozy-home",
    title: "Cozy Country Home",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color chimney smoke, front garden fence, and paned cottage windows.",
    prompt: "Color the Cozy Country Home!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["house", "home", "cottage", "garden"],
    emoji: "🏡",
    pdfFilename: "color-cozy-home.pdf",
    svgType: "cozy-home",
  },
  {
    id: "places-castle-tower",
    slug: "castle-tower",
    title: "Castle Stone Tower",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color stone battlements, arched windows, and waving royal banner.",
    prompt: "Color the Castle Tower!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["castle", "tower", "medieval", "fortress"],
    emoji: "🏰",
    pdfFilename: "color-castle-tower.pdf",
    svgType: "castle-tower",
  },
  {
    id: "places-ocean-lighthouse",
    slug: "ocean-lighthouse",
    title: "Ocean Lighthouse",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color bold spiral stripes, bright light beam, and seaside rocky cliffs.",
    prompt: "Color the Ocean Lighthouse!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["lighthouse", "coast", "ocean", "beacon"],
    emoji: "🗼",
    pdfFilename: "color-ocean-lighthouse.pdf",
    svgType: "ocean-lighthouse",
  },
  {
    id: "places-farm-barn",
    slug: "farm-barn",
    title: "Red Farm Barn",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color big barn doors, weather vane rooster, and hay silos.",
    prompt: "Color the Red Farm Barn!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["barn", "farm", "countryside", "animals"],
    emoji: "🚜",
    pdfFilename: "color-farm-barn.pdf",
    svgType: "farm-barn",
  },
  {
    id: "places-dutch-windmill",
    slug: "dutch-windmill",
    title: "Dutch Windmill",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color four spinning sail blades surrounded by blooming tulip fields.",
    prompt: "Color the Dutch Windmill!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["windmill", "tulips", "holland", "architecture"],
    emoji: "🌾",
    pdfFilename: "color-dutch-windmill.pdf",
    svgType: "dutch-windmill",
  },
  {
    id: "places-city-skyline",
    slug: "city-skyline",
    title: "City Skyline",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color tall modern skyscrapers, window grids, and cityscape streets.",
    prompt: "Color the City Skyline!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["city", "skyline", "skyscrapers", "urban"],
    emoji: "🏙️",
    pdfFilename: "color-city-skyline.pdf",
    svgType: "city-skyline",
  },
  {
    id: "places-secret-treehouse",
    slug: "secret-treehouse",
    title: "Secret Treehouse",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color a wooden treehouse cabin with rope ladder and leafy canopy.",
    prompt: "Color the Secret Treehouse!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["treehouse", "adventure", "hideout", "kids"],
    emoji: "🛖",
    pdfFilename: "color-secret-treehouse.pdf",
    svgType: "secret-treehouse",
  },
  {
    id: "places-arctic-igloo",
    slug: "arctic-igloo",
    title: "Arctic Snow Igloo",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color carved ice blocks, entry tunnel, and chilly arctic icebergs.",
    prompt: "Color the Snow Igloo!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["igloo", "snow", "arctic", "winter"],
    emoji: "🧊",
    pdfFilename: "color-arctic-igloo.pdf",
    svgType: "arctic-igloo",
  },
  {
    id: "places-great-pyramid",
    slug: "great-pyramid",
    title: "Great Pyramid",
    categoryId: "places-and-buildings",
    categoryName: "Places & Buildings",
    subtitle: "Color ancient stone pyramid steps under the bright desert sun.",
    prompt: "Color the Great Pyramid!",
    difficulty: "Easy",
    ageRange: "Ages 4-9",
    tags: ["pyramid", "egypt", "ancient", "history"],
    emoji: "🏛️",
    pdfFilename: "color-great-pyramid.pdf",
    svgType: "great-pyramid",
  },

  // ── 14. EDUCATIONAL COLORING ─────────────────────────────────────────────
  {
    id: "educational-alphabet-abc",
    slug: "alphabet-abc-fun",
    title: "Alphabet ABC Fun",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color big capital letters A, B, C with Apple, Ball, and Cat icons.",
    prompt: "Color the Alphabet ABC Fun!",
    difficulty: "Easy",
    ageRange: "Ages 3-6",
    tags: ["abc", "alphabet", "phonics", "preschool"],
    emoji: "🔤",
    pdfFilename: "color-alphabet-abc-fun.pdf",
    svgType: "alphabet-abc-fun",
  },
  {
    id: "educational-numbers-1-10",
    slug: "number-counting-10",
    title: "Number Counting 1–10",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color big friendly numbers 1, 2, 3 with countable stars and dots.",
    prompt: "Color Number Counting 1–10!",
    difficulty: "Easy",
    ageRange: "Ages 3-6",
    tags: ["numbers", "counting", "math", "kindergarten"],
    emoji: "🔢",
    pdfFilename: "color-number-counting-10.pdf",
    svgType: "number-counting-10",
  },
  {
    id: "educational-shapes-world",
    slug: "shapes-world",
    title: "Geometric Shapes World",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color Circle, Square, Triangle, Star, and Hexagon character friends.",
    prompt: "Color the Geometric Shapes!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["shapes", "geometry", "circle", "square"],
    emoji: "🔺",
    pdfFilename: "color-shapes-world.pdf",
    svgType: "shapes-world",
  },
  {
    id: "educational-color-by-number",
    slug: "color-by-number",
    title: "Color by Number Garden",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Match numbers 1 to 5 with colors to reveal a secret garden flower.",
    prompt: "Color by Number Garden!",
    difficulty: "Medium",
    ageRange: "Ages 4-8",
    tags: ["color by number", "puzzle", "number match", "activity"],
    emoji: "🎨",
    pdfFilename: "color-color-by-number.pdf",
    svgType: "color-by-number",
  },
  {
    id: "educational-telling-time",
    slug: "telling-time-clock",
    title: "Telling Time Clock",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color clock numbers 1 to 12 and draw the hour & minute clock hands.",
    prompt: "Color the Telling Time Clock!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["clock", "time", "hours", "math"],
    emoji: "⏰",
    pdfFilename: "color-telling-time-clock.pdf",
    svgType: "telling-time-clock",
  },
  {
    id: "educational-body-parts",
    slug: "body-parts-fun",
    title: "Human Body Parts",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color head, shoulders, knees, toes, eyes, ears, and smile.",
    prompt: "Color the Human Body Parts!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["body", "anatomy", "science", "health"],
    emoji: "🧍",
    pdfFilename: "color-body-parts-fun.pdf",
    svgType: "body-parts-fun",
  },
  {
    id: "educational-solar-map",
    slug: "solar-system-map",
    title: "Solar System Orbit Map",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color Mercury to Neptune with labeled planet orbits and name tags.",
    prompt: "Color the Solar System Map!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["space", "solar system", "planets", "science"],
    emoji: "🪐",
    pdfFilename: "color-solar-system-map.pdf",
    svgType: "solar-system-map",
  },
  {
    id: "educational-emotions",
    slug: "emotions-faces",
    title: "Emotions & Feelings",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color happy, excited, calm, thoughtful, and silly cartoon faces.",
    prompt: "Color the Emotions & Feelings!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["emotions", "feelings", "faces", "social learning"],
    emoji: "😊",
    pdfFilename: "color-emotions-faces.pdf",
    svgType: "emotions-faces",
  },
  {
    id: "educational-habitats",
    slug: "animal-habitats",
    title: "Animal Habitats Jungle",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Color forest, ocean, desert, and polar animals in their home biomes.",
    prompt: "Color the Animal Habitats!",
    difficulty: "Medium",
    ageRange: "Ages 5-10",
    tags: ["habitats", "biomes", "nature", "science"],
    emoji: "🌍",
    pdfFilename: "color-animal-habitats.pdf",
    svgType: "animal-habitats",
  },
  {
    id: "educational-color-wheel",
    slug: "rainbow-color-wheel",
    title: "Rainbow Color Wheel",
    categoryId: "educational-coloring",
    categoryName: "Educational Coloring",
    subtitle: "Learn Primary and Secondary colors by filling in the 6-part color wheel.",
    prompt: "Color the Rainbow Color Wheel!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["color wheel", "art theory", "primary colors", "learning"],
    emoji: "🎯",
    pdfFilename: "color-rainbow-color-wheel.pdf",
    svgType: "rainbow-color-wheel",
  },

  // ── 15. SEASONS & WEATHER ────────────────────────────────────────────────
  {
    id: "seasons-summer-beach",
    slug: "sunny-summer-beach",
    title: "Sunny Summer Day",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color a bright smiling sun with sunglasses, beach ball, and ice pop.",
    prompt: "Color the Sunny Summer Day!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["summer", "sun", "beach ball", "vacation"],
    emoji: "☀️",
    pdfFilename: "color-sunny-summer-beach.pdf",
    svgType: "sunny-summer-beach",
  },
  {
    id: "seasons-winter-snowman",
    slug: "winter-snowman",
    title: "Winter Snowman",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color a carrot nose, top hat, warm scarf, and falling snowflakes.",
    prompt: "Color the Winter Snowman!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["snowman", "winter", "snow", "holidays"],
    emoji: "⛄",
    pdfFilename: "color-winter-snowman.pdf",
    svgType: "winter-snowman",
  },
  {
    id: "seasons-autumn-leaves",
    slug: "autumn-falling-leaves",
    title: "Autumn Falling Leaves",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color maple, oak, and birch leaves swirling in the autumn wind.",
    prompt: "Color Autumn Falling Leaves!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["autumn", "fall", "leaves", "acorn"],
    emoji: "🍂",
    pdfFilename: "color-autumn-falling-leaves.pdf",
    svgType: "autumn-falling-leaves",
  },
  {
    id: "seasons-spring-blooms",
    slug: "spring-garden-blooms",
    title: "Spring Garden Blooms",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color fresh sprouting buds, watering can, and cheerful ladybug.",
    prompt: "Color Spring Garden Blooms!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["spring", "garden", "sprouts", "ladybug"],
    emoji: "🌱",
    pdfFilename: "color-spring-garden-blooms.pdf",
    svgType: "spring-garden-blooms",
  },
  {
    id: "seasons-rainy-umbrella",
    slug: "rainy-day-umbrella",
    title: "Rainy Day Umbrella",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color colorful striped umbrella, rain boots, and splashing water puddles.",
    prompt: "Color the Rainy Day Umbrella!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["rain", "umbrella", "boots", "puddles"],
    emoji: "☂️",
    pdfFilename: "color-rainy-day-umbrella.pdf",
    svgType: "rainy-day-umbrella",
  },
  {
    id: "seasons-windy-kite",
    slug: "windy-flying-kite",
    title: "Windy Flying Kite",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color diamond kite with bow ribbons soaring on a breezy spring day.",
    prompt: "Color the Windy Flying Kite!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["kite", "windy", "breeze", "spring"],
    emoji: "🪁",
    pdfFilename: "color-windy-flying-kite.pdf",
    svgType: "windy-flying-kite",
  },
  {
    id: "seasons-stormy-cloud",
    slug: "stormy-thundercloud",
    title: "Stormy Thundercloud",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color lightning bolts, rain drops, and dramatic thundercloud puffs.",
    prompt: "Color the Stormy Thundercloud!",
    difficulty: "Easy",
    ageRange: "Ages 4-8",
    tags: ["storm", "lightning", "thunder", "weather"],
    emoji: "⛈️",
    pdfFilename: "color-stormy-thundercloud.pdf",
    svgType: "stormy-thundercloud",
  },
  {
    id: "seasons-rainbow-sky",
    slug: "beautiful-rainbow-sky",
    title: "Beautiful Rainbow Sky",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color an arching 7-color rainbow shining above cheerful puffy clouds.",
    prompt: "Color the Rainbow Sky!",
    difficulty: "Easy",
    ageRange: "Ages 3-7",
    tags: ["rainbow", "sky", "sunshine", "cheerful"],
    emoji: "🌈",
    pdfFilename: "color-beautiful-rainbow-sky.pdf",
    svgType: "beautiful-rainbow-sky",
  },
  {
    id: "seasons-birdhouse",
    slug: "spring-birdhouse",
    title: "Spring Birdhouse & Nest",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color a wooden hanging birdhouse with tiny eggs resting in a nest.",
    prompt: "Color the Spring Birdhouse!",
    difficulty: "Easy",
    ageRange: "Ages 3-8",
    tags: ["birdhouse", "nest", "spring", "birds"],
    emoji: "🪺",
    pdfFilename: "color-spring-birdhouse.pdf",
    svgType: "spring-birdhouse",
  },
  {
    id: "seasons-pumpkin-patch",
    slug: "autumn-pumpkin-patch",
    title: "Autumn Pumpkin Patch",
    categoryId: "seasons-and-weather",
    categoryName: "Seasons & Weather",
    subtitle: "Color ripe harvest pumpkins, leafy vines, and autumn scarecrow.",
    prompt: "Color the Pumpkin Patch!",
    difficulty: "Medium",
    ageRange: "Ages 4-9",
    tags: ["pumpkin patch", "autumn", "harvest", "farm"],
    emoji: "🎃",
    pdfFilename: "color-autumn-pumpkin-patch.pdf",
    svgType: "autumn-pumpkin-patch",
  },
];

// Helper lookups
export function getCategory(slugOrId: string): ColoringCategory | undefined {
  const norm = slugOrId.toLowerCase().trim();
  return COLORING_CATEGORIES.find((c) => c.slug === norm || c.id === norm);
}

export function getSheetsByCategory(categoryIdOrSlug: string): ColoringSheet[] {
  const cat = getCategory(categoryIdOrSlug);
  if (!cat) return [];
  return COLORING_SHEETS.filter((s) => s.categoryId === cat.id);
}

export function getSheet(categorySlug: string, sheetSlug: string): ColoringSheet | undefined {
  const cat = getCategory(categorySlug);
  if (!cat) return undefined;
  return COLORING_SHEETS.find(
    (s) => s.categoryId === cat.id && (s.slug === sheetSlug || s.id === sheetSlug)
  );
}

export function getAllColoringSheets(): ColoringSheet[] {
  return COLORING_SHEETS;
}
