import React from "react";

// Nature & Earth Scenes (1–20)
import {
  RockCycleScene,
  FoodChainScene,
  FoodWebScene,
  CarbonCycleScene,
  NitrogenCycleScene,
  WaterPollutionScene,
  RiverFormationScene,
  RaindropJourneyScene,
  SoilMadeScene,
  TreeLifeScene,
  VolcanoEruptScene,
  EarthquakeScene,
  MountainFormationScene,
  WaterCycleScene,
  CaveFormationScene,
  FossilFormationScene,
  GlacierLandformScene,
  OceanSalinityScene,
  BeachFormationScene,
  EarthLayersScene,
} from "./scenes/NatureScenes";

// Weather & Climate Scenes (21–40)
import {
  CloudFormationScene,
  WindJourneyScene,
  RainHappensScene,
  ThunderstormScene,
  SeasonsScene,
  SnowFormationScene,
  HurricaneScene,
  WeatherForecastingScene,
  SunlightJourneyScene,
  WeatherVsClimateScene,
  TornadoFormationScene,
  FogFormationScene,
  BlueSkyScatteringScene,
  HailFormationScene,
  DroughtCausesScene,
  FloodCausesScene,
  WeatherFrontScene,
  OceanCurrentsScene,
  GreenhouseEffectScene,
  DesertDrynessScene,
} from "./scenes/WeatherScenes";

// Space Scenes (41–60)
import {
  EarthAroundSunScene,
  DayNightScene,
  MoonPhasesScene,
  StarLifeCycleScene,
  SolarEclipseScene,
  LunarEclipseScene,
  SolarSystemScene,
  RocketPhysicsScene,
  AstronautLifeScene,
  NorthernLightsScene,
  SolarSystemFormedScene,
  WhatIsGravityScene,
  HowSatellitesWorkScene,
  BlackHoleScene,
  MoonFormationScene,
  WhyPlanetsOrbitScene,
  HowTelescopesWorkScene,
  WhatAreCometsScene,
  WhatAreAsteroidsScene,
  ExploreMarsScene,
} from "./scenes/SpaceScenes";

// Animal & Plant Life Scenes (61–80)
import {
  FrogLifeCycleScene,
  BeeLifeCycleScene,
  ChickenLifeCycleScene,
  LadybugLifeCycleScene,
  BirdNestScene,
  HoneyMakingScene,
  PhotosynthesisScene,
  AnimalAdaptationScene,
  AnimalDigestionScene,
  EcosystemScene,
  ButterflyLifeCycleScene,
  SeedGerminationScene,
  FlowerToFruitScene,
  PlantDrinkWaterScene,
  PollinationScene,
  LeavesColorChangeScene,
  FishBreatheUnderwaterScene,
  BirdFlightScene,
  AnimalHibernateScene,
  AnimalMigrateScene,
} from "./scenes/AnimalPlantScenes";

// Human Body Scenes (81–100)
import {
  HumanDigestionScene,
  BreathingScene,
  HeartPumpScene,
  SkeletonBonesScene,
  MuscleWorkScene,
  BrainMessagesScene,
  FiveSensesScene,
  ImmuneSystemScene,
  HumanGrowthScene,
  SleepScene,
  EyeVisionScene,
  EarHearingScene,
  KidneyFiltrationScene,
  SkinProtectionScene,
  WoundHealingScene,
  TeethGrowthScene,
  SkeletonGrowthScene,
  MemorySynapseScene,
  BodyBalanceScene,
  HungerHormonesScene,
} from "./scenes/HumanBodyScenes";

// Everyday Science Scenes (101–120)
import {
  ElectricityCircuitScene,
  MagnetsScene,
  SoundWavesScene,
  LightShadowsScene,
  RainbowFormationScene,
  StatesOfMatterScene,
  HeatTransferScene,
  SimpleMachinesScene,
  BatteryPhysicsScene,
  BridgeForcesScene,
  FrictionMechanicsScene,
  GravityAccelerationScene,
  MirrorReflectionScene,
  LensRefractionScene,
  BuoyancyFloatScene,
  AirplaneLiftScene,
  RefrigeratorCycleScene,
  SolarPanelElectricityScene,
  WifiRadioWavesScene,
  TouchscreenCapacitiveScene,
} from "./scenes/EverydayScienceScenes";

interface Props {
  slug: string;
  className?: string;
}

const SCENE_REGISTRY: Record<string, () => React.ReactElement> = {
  // ── Nature & Earth (1–20) ──────────────────────────────────────────────────
  "the-rock-cycle": RockCycleScene,
  "the-food-chain": FoodChainScene,
  "the-food-web": FoodWebScene,
  "the-carbon-cycle": CarbonCycleScene,
  "the-nitrogen-cycle": NitrogenCycleScene,
  "the-water-pollution-journey": WaterPollutionScene,
  "how-rivers-are-formed": RiverFormationScene,
  "the-journey-of-a-raindrop": RaindropJourneyScene,
  "how-soil-is-made": SoilMadeScene,
  "the-life-of-a-tree": TreeLifeScene,
  "how-volcanoes-erupt": VolcanoEruptScene,
  "how-earthquakes-happen": EarthquakeScene,
  "how-mountains-are-formed": MountainFormationScene,
  "the-water-cycle": WaterCycleScene,
  "how-caves-are-formed": CaveFormationScene,
  "how-fossils-are-made": FossilFormationScene,
  "how-glaciers-shape-the-land": GlacierLandformScene,
  "why-oceans-are-salty": OceanSalinityScene,
  "how-beaches-are-formed": BeachFormationScene,
  "inside-the-layers-of-the-earth": EarthLayersScene,

  // ── Weather & Climate (21–40) ──────────────────────────────────────────────
  "how-clouds-are-made": CloudFormationScene,
  "the-journey-of-the-wind": WindJourneyScene,
  "how-rain-happens": RainHappensScene,
  "how-thunderstorms-form": ThunderstormScene,
  "why-do-we-have-seasons": SeasonsScene,
  "how-snow-is-formed": SnowFormationScene,
  "the-life-cycle-of-a-hurricane": HurricaneScene,
  "how-weather-forecasting-works": WeatherForecastingScene,
  "the-journey-of-sunlight": SunlightJourneyScene,
  "weather-vs-climate": WeatherVsClimateScene,
  "how-tornadoes-form": TornadoFormationScene,
  "how-fog-forms": FogFormationScene,
  "why-the-sky-is-blue": BlueSkyScatteringScene,
  "how-hail-forms": HailFormationScene,
  "what-causes-a-drought": DroughtCausesScene,
  "how-floods-happen": FloodCausesScene,
  "how-a-weather-front-works": WeatherFrontScene,
  "what-causes-ocean-currents": OceanCurrentsScene,
  "how-the-greenhouse-effect-works": GreenhouseEffectScene,
  "why-deserts-are-so-dry": DesertDrynessScene,

  // ── Space (41–60) ──────────────────────────────────────────────────────────
  "journey-of-earth-around-sun": EarthAroundSunScene,
  "why-do-we-have-day-and-night": DayNightScene,
  "the-phases-of-the-moon": MoonPhasesScene,
  "the-life-cycle-of-a-star": StarLifeCycleScene,
  "how-a-solar-eclipse-happens": SolarEclipseScene,
  "how-a-lunar-eclipse-happens": LunarEclipseScene,
  "journey-through-our-solar-system": SolarSystemScene,
  "how-rockets-reach-space": RocketPhysicsScene,
  "how-astronauts-live-in-space": AstronautLifeScene,
  "what-causes-the-northern-lights": NorthernLightsScene,
  "how-the-solar-system-formed": SolarSystemFormedScene,
  "what-is-gravity": WhatIsGravityScene,
  "how-satellites-work": HowSatellitesWorkScene,
  "what-is-a-black-hole": BlackHoleScene,
  "how-the-moon-was-formed": MoonFormationScene,
  "why-planets-orbit-the-sun": WhyPlanetsOrbitScene,
  "how-telescopes-work": HowTelescopesWorkScene,
  "what-are-comets": WhatAreCometsScene,
  "what-are-asteroids": WhatAreAsteroidsScene,
  "how-scientists-explore-mars": ExploreMarsScene,

  // ── Animal & Plant Life (61–80) ────────────────────────────────────────────
  "the-life-cycle-of-a-frog": FrogLifeCycleScene,
  "the-life-cycle-of-a-bee": BeeLifeCycleScene,
  "the-life-cycle-of-a-chicken": ChickenLifeCycleScene,
  "the-life-cycle-of-a-ladybug": LadybugLifeCycleScene,
  "how-birds-build-nests": BirdNestScene,
  "how-bees-make-honey": HoneyMakingScene,
  "how-plants-make-their-food": PhotosynthesisScene,
  "how-animals-adapt-to-their-environment": AnimalAdaptationScene,
  "the-journey-of-food-through-an-animal": AnimalDigestionScene,
  "how-ecosystems-work": EcosystemScene,
  "the-life-cycle-of-a-butterfly": ButterflyLifeCycleScene,
  "how-seeds-germinate": SeedGerminationScene,
  "how-flowers-become-fruit": FlowerToFruitScene,
  "how-plants-drink-water": PlantDrinkWaterScene,
  "how-pollination-works": PollinationScene,
  "why-leaves-change-color": LeavesColorChangeScene,
  "how-fish-breathe-underwater": FishBreatheUnderwaterScene,
  "how-birds-fly": BirdFlightScene,
  "how-animals-hibernate": AnimalHibernateScene,
  "how-animals-migrate": AnimalMigrateScene,

  // ── Human Body (81–100) ─────────────────────────────────────────────────────
  "journey-of-food-through-your-body": HumanDigestionScene,
  "how-we-breathe": BreathingScene,
  "how-the-heart-pumps-blood": HeartPumpScene,
  "how-bones-help-us-move": SkeletonBonesScene,
  "how-muscles-work": MuscleWorkScene,
  "how-our-brain-sends-messages": BrainMessagesScene,
  "how-our-five-senses-work": FiveSensesScene,
  "how-the-immune-system-protects-us": ImmuneSystemScene,
  "how-we-grow": HumanGrowthScene,
  "why-do-we-sleep": SleepScene,
  "how-your-eyes-see": EyeVisionScene,
  "how-your-ears-hear": EarHearingScene,
  "how-the-kidneys-clean-blood": KidneyFiltrationScene,
  "how-skin-protects-your-body": SkinProtectionScene,
  "how-a-cut-heals": WoundHealingScene,
  "how-teeth-grow": TeethGrowthScene,
  "how-your-skeleton-grows": SkeletonGrowthScene,
  "how-memory-works": MemorySynapseScene,
  "how-your-body-balances": BodyBalanceScene,
  "why-we-get-hungry": HungerHormonesScene,

  // ── Everyday Science (101–120) ──────────────────────────────────────────────
  "how-electricity-travels": ElectricityCircuitScene,
  "how-magnets-work": MagnetsScene,
  "how-sound-travels": SoundWavesScene,
  "how-light-creates-shadows": LightShadowsScene,
  "how-a-rainbow-is-formed": RainbowFormationScene,
  "the-three-states-of-matter": StatesOfMatterScene,
  "the-journey-of-heat": HeatTransferScene,
  "how-simple-machines-make-work-easier": SimpleMachinesScene,
  "how-a-battery-works": BatteryPhysicsScene,
  "how-bridges-stay-strong": BridgeForcesScene,
  "how-friction-works": FrictionMechanicsScene,
  "how-gravity-affects-us": GravityAccelerationScene,
  "how-mirrors-work": MirrorReflectionScene,
  "how-lenses-bend-light": LensRefractionScene,
  "why-objects-float-or-sink": BuoyancyFloatScene,
  "how-airplanes-fly": AirplaneLiftScene,
  "how-refrigerators-keep-food-cold": RefrigeratorCycleScene,
  "how-solar-panels-make-electricity": SolarPanelElectricityScene,
  "how-wi-fi-carries-information": WifiRadioWavesScene,
  "how-touchscreens-work": TouchscreenCapacitiveScene,

  // Legacy Aliases
  "water-life-cycle": RaindropJourneyScene,
  "butterfly-life-cycle": ButterflyLifeCycleScene,
  "seed-to-plant-cycle": TreeLifeScene,
  "decomposer-soil-cycle": SoilMadeScene,
  "oxygen-carbon-dioxide-breath-swap": BreathingScene,
};

export default function KnowledgeArt({ slug, className }: Props) {
  const SceneComponent = SCENE_REGISTRY[slug] || RaindropJourneyScene;
  return (
    <div className={className}>
      <SceneComponent />
    </div>
  );
}


