import type { InterviewSheetSpec } from "../interview-pdf-builder";

export const specificInterviews: InterviewSheetSpec[] = [
  // ── Java / JVM ──────────────────────────────────────────────────────────
  {
    name: "Spring Boot",
    subtitle: "Core concepts, configuration, and production patterns",
    accentHex: "#6DB33F",
    questions: [
      "What is Spring Boot and how does its auto-configuration mechanism differ from traditional Spring XML configuration?",
      "Explain the purpose of @SpringBootApplication and what three annotations it meta-composes.",
      "How does Spring Boot externalize configuration? Explain properties files, YAML, and environment variable precedence.",
      "What is Spring Boot Actuator? Name three key endpoints and how you would secure them in production.",
      "How does Spring Boot's embedded server work? How do you replace Tomcat with Jetty or Undertow?",
      "Explain the stereotype annotations: @Component, @Service, @Repository, @Controller — what are their differences?",
      "How does Spring Data JPA simplify data access in Spring Boot? Explain derived query method naming conventions.",
      "How do you implement global exception handling in Spring Boot using @RestControllerAdvice and @ExceptionHandler?",
      "Explain the difference between singleton and prototype bean scopes and when you would choose each.",
      "How do you write a Spring Boot integration test using @SpringBootTest with MockMvc or WebTestClient?",
    ],
  },
  {
    name: "Spring Framework",
    subtitle: "IoC, AOP, transaction management, and Spring MVC internals",
    accentHex: "#6DB33F",
    questions: [
      "Explain Dependency Injection (DI) and Inversion of Control (IoC) and how the Spring IoC container implements them.",
      "Describe the Spring Bean lifecycle from instantiation to destruction, including key callback interfaces.",
      "What is the difference between BeanFactory and ApplicationContext? When would you use each?",
      "Explain Spring's bean scopes: singleton, prototype, request, session, and application.",
      "How does Spring AOP work? Define joinpoint, pointcut, advice, and aspect with examples.",
      "Explain Spring's declarative transaction management and the @Transactional annotation's propagation levels.",
      "Walk through the Spring MVC DispatcherServlet request lifecycle from HTTP request to response.",
      "How does @Autowired resolve dependency ambiguities? Explain @Qualifier and @Primary.",
      "What is Spring's ApplicationEvent system and how do you publish and consume custom events?",
      "Explain Spring's cache abstraction. How do @Cacheable, @CachePut, and @CacheEvict work?",
    ],
  },
  {
    name: "Spring Security",
    subtitle: "Authentication, authorization, OAuth2, and security testing",
    accentHex: "#6DB33F",
    questions: [
      "Describe the Spring Security filter chain. In what order do key filters like UsernamePasswordAuthenticationFilter run?",
      "What is the difference between Authentication and Authorization in Spring Security?",
      "How do you implement stateless JWT-based authentication in a Spring Security application?",
      "Explain UserDetailsService and UserDetails. How do you load users from a database?",
      "What are SpEL security expressions: hasRole(), hasAuthority(), isAuthenticated(), and @PreAuthorize?",
      "How do you enable and configure method-level security with @EnableMethodSecurity?",
      "What is Spring Security OAuth2 Resource Server and how does it validate JWT tokens?",
      "How do you configure CORS in Spring Security and why must it be done before other filters?",
      "Explain CSRF protection in Spring Security. When is it safe to disable it and why?",
      "How do you write security tests in Spring Boot using @WithMockUser and @WithSecurityContext?",
    ],
  },
  {
    name: "Spring Cloud",
    subtitle: "Microservices, service discovery, resilience, and distributed config",
    accentHex: "#6DB33F",
    questions: [
      "What problems does Spring Cloud solve in a microservices architecture?",
      "Explain service discovery with Spring Cloud Netflix Eureka: how do services register and resolve each other?",
      "What is Spring Cloud Gateway? How does it differ from Zuul and how do you configure routes and filters?",
      "How does Spring Cloud Config Server provide distributed configuration management?",
      "Explain circuit breaking with Resilience4j in Spring Cloud: how do fallbacks and half-open state work?",
      "What is Spring Cloud Sleuth and Zipkin? How does distributed tracing work across microservices?",
      "How does client-side load balancing work in Spring Cloud using Spring Cloud LoadBalancer?",
      "What is Spring Cloud Stream and how does it abstract Kafka/RabbitMQ messaging behind a unified API?",
      "Explain the Saga pattern for distributed transactions and how you would implement it with Spring Cloud.",
      "How do you secure inter-service communication in Spring Cloud using OAuth2 token relay?",
    ],
  },
  {
    name: "Hibernate",
    subtitle: "ORM internals, caching, relationships, and query strategies",
    accentHex: "#59666C",
    questions: [
      "What is Hibernate and how does the ORM model map Java objects to relational database tables?",
      "Explain the Hibernate Session entity lifecycle states: transient, persistent, detached, and removed.",
      "What is the difference between Session.get(), Session.load(), and EntityManager.find() in Hibernate?",
      "Explain lazy vs eager fetching in Hibernate. What is the FetchType default for @OneToMany?",
      "Describe the two levels of Hibernate caching: Session (L1) and SessionFactory (L2). How is L2 configured?",
      "How do you map bidirectional @OneToMany and @ManyToOne relationships? Who owns the relationship?",
      "What is HQL (Hibernate Query Language) and how does it differ from SQL and Criteria API?",
      "Explain optimistic and pessimistic locking in Hibernate. How do you use @Version for optimistic locks?",
      "What causes the N+1 select problem in Hibernate and what are three strategies to solve it?",
      "How do you use Hibernate with Flyway or Liquibase for database schema migrations?",
    ],
  },
  {
    name: "JPA",
    subtitle: "Entity lifecycle, JPQL, relationships, and Spring Data repositories",
    accentHex: "#007396",
    questions: [
      "What is the JPA specification and how does it relate to Hibernate as a JPA provider?",
      "Explain the JPA entity lifecycle states: New, Managed, Detached, and Removed.",
      "What is the EntityManager's role in JPA? How do persist(), merge(), and remove() differ?",
      "How do you write JPQL queries? Explain named queries and how they are validated at startup.",
      "What is the difference between @Entity, @MappedSuperclass, and @Embeddable annotations?",
      "Explain the three JPA inheritance mapping strategies: SINGLE_TABLE, TABLE_PER_CLASS, and JOINED.",
      "How do derived query methods work in Spring Data JPA? Give an example for findByEmailAndActive.",
      "What is the @Transactional annotation's role in JPA? Explain propagation and isolation levels.",
      "How do you map composite primary keys in JPA using @EmbeddedId or @IdClass?",
      "What is the difference between a JPQL query returning an entity vs a DTO projection?",
    ],
  },
  {
    name: "Jakarta EE",
    subtitle: "CDI, JAX-RS, EJB, JMS, and enterprise security",
    accentHex: "#ED8B00",
    questions: [
      "What is Jakarta EE and how does it evolve from Java EE? What is the role of the Jakarta EE specification process?",
      "Explain CDI (Contexts and Dependency Injection). What are the built-in bean scopes (@RequestScoped, @SessionScoped, @ApplicationScoped)?",
      "How do you build a RESTful service with JAX-RS? Explain @Path, @GET, @POST, @Produces, @Consumes.",
      "What are EJBs (Enterprise JavaBeans)? Explain @Stateless, @Stateful, and @Singleton and their use cases.",
      "How does JMS work? What is the difference between a Queue and a Topic, and how do you send messages?",
      "How do you configure persistence in Jakarta EE using persistence.xml and @PersistenceContext?",
      "What are servlet filters in Jakarta EE and how do they differ from CDI interceptors?",
      "Explain Jakarta Security. What are the authentication mechanisms: @FormAuthenticationMechanismDefinition and others?",
      "What is JNDI and how do you look up resources like DataSources and EJBs by JNDI name?",
      "How do Jakarta EE applications differ in packaging: WAR, EAR, and JAR with embedded servers?",
    ],
  },
  {
    name: "Quarkus",
    subtitle: "Cloud-native Java, GraalVM native image, CDI, and Panache",
    accentHex: "#4695EB",
    questions: [
      "What is Quarkus and what properties make it optimized for containers and cloud-native environments?",
      "How does Quarkus native compilation with GraalVM reduce startup time and memory footprint?",
      "Explain Quarkus's build-time CDI model. How does it differ from Jakarta EE's runtime CDI?",
      "How do you build REST endpoints in Quarkus using JAX-RS and RESTEasy Reactive?",
      "What are Quarkus Dev Services and how do they automatically start required infrastructure in dev mode?",
      "How does Quarkus handle reactive programming with SmallRye Mutiny (Uni and Multi types)?",
      "What is Quarkus Panache and how does it simplify JPA entity management with active record pattern?",
      "How do you configure and consume Kafka messages in Quarkus with SmallRye Reactive Messaging?",
      "Explain how Quarkus extensions work. What happens at augmentation (build) time vs runtime?",
      "How do you write and run integration tests in Quarkus using @QuarkusTest and @QuarkusIntegrationTest?",
    ],
  },
  {
    name: "Micronaut",
    subtitle: "Compile-time DI, AOT, reactive, and GraalVM native",
    accentHex: "#1CBFCF",
    questions: [
      "What is Micronaut and how does compile-time dependency injection (AOT) differ from Spring's runtime reflection?",
      "Explain Micronaut's AOP model. How do interceptors work without runtime proxies?",
      "How do you define a REST controller in Micronaut and handle path variables and query params?",
      "What is Micronaut Data and how does it support multiple databases (JPA, JDBC, MongoDB) with compile-time query validation?",
      "How does Micronaut's GraalVM native image support simplify the configuration compared to vanilla GraalVM?",
      "Explain Micronaut's service discovery integration with Consul and how you declare a declarative HTTP client.",
      "How does Micronaut support reactive programming with Project Reactor and RxJava?",
      "Describe Micronaut's configuration system: application.yml, environments, and @Property injection.",
      "How does Micronaut Security implement JWT authentication and how do you secure endpoints?",
      "How do you write unit and integration tests in Micronaut using @MicronautTest?",
    ],
  },

  // ── Python ──────────────────────────────────────────────────────────────
  {
    name: "Django",
    subtitle: "MTV architecture, ORM, views, authentication, and testing",
    accentHex: "#0C4B33",
    questions: [
      "Explain Django's MTV (Model–Template–View) architecture and how it maps to the traditional MVC pattern.",
      "How does the Django ORM work? Explain model fields, migrations, and how to run db migrations.",
      "What is the difference between Function-Based Views (FBVs) and Class-Based Views (CBVs) in Django?",
      "Explain Django's URL routing: how urlpatterns, path converters, and include() work together.",
      "What is Django REST Framework (DRF)? How do serializers and ViewSets simplify API development?",
      "How does Django's authentication system handle user sessions, permissions, and groups?",
      "What is Django middleware and how does request/response processing flow through the middleware stack?",
      "Explain Django's template engine: template inheritance, blocks, and context processors.",
      "How do you configure caching in Django? Name three supported cache backends and how cache_page works.",
      "How do you write unit and integration tests in Django using TestCase, Client, and APIClient?",
    ],
  },
  {
    name: "Flask",
    subtitle: "WSGI, Blueprints, application context, and extension ecosystem",
    accentHex: "#000000",
    questions: [
      "What is Flask and how does it handle requests as a WSGI application?",
      "Explain Flask's application factory pattern and why it is preferred over module-level app creation.",
      "How does Flask's routing work? Explain @app.route, variable rules, and Blueprints for modularization.",
      "What is Flask-SQLAlchemy and how does it manage the database session lifecycle per request?",
      "Explain Flask's request context and application context. What goes in g, current_app, and request?",
      "How does Flask-Login handle session-based authentication and protect routes with @login_required?",
      "How do you build a JSON API in Flask using jsonify, or with Flask-RESTful/Flask-RESTX?",
      "How do you handle file uploads in Flask and what validation should you perform on uploaded files?",
      "How do you integrate Flask with Celery for background task processing?",
      "How do you write unit tests for Flask views using the Flask test client and pytest fixtures?",
    ],
  },
  {
    name: "FastAPI",
    subtitle: "Type hints, async, Pydantic, dependency injection, and OpenAPI",
    accentHex: "#009688",
    questions: [
      "What is FastAPI and how does it leverage Python type hints to drive automatic validation and documentation?",
      "How do Pydantic models work in FastAPI for request body validation and response serialization?",
      "Explain FastAPI's dependency injection system. How do you use Depends() and share a database session?",
      "How does FastAPI handle path operation ordering to avoid route shadowing issues?",
      "What is the difference between async def and def in FastAPI endpoints, and how does asyncio fit in?",
      "How do you implement OAuth2 password flow with JWT tokens in FastAPI?",
      "How does FastAPI auto-generate interactive OpenAPI docs? How do you customize schemas and metadata?",
      "How do you add CORS middleware and configure allowed origins in a FastAPI application?",
      "How do you integrate SQLAlchemy with FastAPI in an async context using AsyncSession?",
      "How do you write tests for FastAPI endpoints using TestClient and pytest, including mocking dependencies?",
    ],
  },
  {
    name: "Celery",
    subtitle: "Distributed task queues, brokers, scheduling, and monitoring",
    accentHex: "#A9CC51",
    questions: [
      "What is Celery and what problem does it solve? Explain the role of a message broker in its architecture.",
      "What are the main components of Celery: broker, worker, beat scheduler, and result backend?",
      "How do you define a Celery task using the @app.task decorator and configure its queue and routing?",
      "What is the difference between task.delay() and task.apply_async()? When do you use apply_async kwargs?",
      "How does Celery handle task retries? How do you configure max_retries, countdown, and autoretry_for?",
      "What is Celery Beat and how do you define periodic tasks using a schedule in the Celery config?",
      "Explain Celery workflow primitives: chain, group, and chord. Give a use case for chord.",
      "How do you monitor Celery workers using Flower? What metrics does Flower expose?",
      "How do you route tasks to specific queues and why would you want multiple queues in a system?",
      "How do you test Celery tasks in unit tests without a running broker using CELERY_TASK_ALWAYS_EAGER or task_always_eager?",
    ],
  },
  {
    name: "Tornado",
    subtitle: "Non-blocking I/O, IOLoop, WebSockets, and async handlers",
    accentHex: "#EE3244",
    questions: [
      "What is Tornado and what makes its non-blocking I/O model suitable for long-lived connections?",
      "Explain the Tornado IOLoop. How does it drive the event loop and what replaces it in modern Python?",
      "How do you define a request handler in Tornado? What are the HTTP verb methods you can override?",
      "What is the difference between using @tornado.gen.coroutine with yield and native async/await in Tornado?",
      "How does Tornado's WebSocket handler work? How do you handle open(), on_message(), and on_close()?",
      "How does Tornado's template engine work and how does it differ from Jinja2 in escaping behavior?",
      "How do you handle authentication in Tornado using get_current_user and login_required?",
      "How do you configure Tornado's HTTPServer to use SSL/TLS certificates?",
      "How do you run Tornado in a multi-process mode to utilize multiple CPU cores?",
      "How do you write async tests for Tornado handlers using AsyncHTTPTestCase and gen_test?",
    ],
  },

  // ── Node.js ──────────────────────────────────────────────────────────────
  {
    name: "Node.js",
    subtitle: "Event loop, streams, clustering, and async error handling",
    accentHex: "#339933",
    questions: [
      "Explain the Node.js event loop phases: timers, poll, check, and close callbacks.",
      "What is the difference between process.nextTick(), setImmediate(), and setTimeout(() => {}, 0)?",
      "How does the Node.js cluster module distribute incoming connections across worker processes?",
      "What are Node.js streams? Explain Readable, Writable, Transform, and the significance of backpressure.",
      "What is the difference between CommonJS require() modules and ES module import syntax in Node.js?",
      "How do you handle errors in async Node.js code using callbacks, Promises, and async/await?",
      "What is the Node.js Buffer class? When is it used vs a regular string?",
      "How do worker_threads differ from the cluster module? When should you choose worker threads?",
      "What is the libuv threadpool in Node.js and which operations use it (e.g., fs.readFile, crypto)?",
      "How do you profile a Node.js application to find CPU bottlenecks using the built-in profiler or clinic.js?",
    ],
  },
  {
    name: "Express.js",
    subtitle: "Middleware pipeline, routing, error handling, and security",
    accentHex: "#000000",
    questions: [
      "Explain the Express.js middleware pipeline. How do request, response, and next() flow through middleware?",
      "What is the difference between app.use(), app.get(), and app.all() for defining middleware and routes?",
      "How do you implement error-handling middleware in Express and why must it have 4 parameters (err, req, res, next)?",
      "Explain Express Router. How do you modularize routes into separate files using express.Router()?",
      "How do you serve static files with Express and configure a template engine like Pug or EJS?",
      "How do you parse different request body types (JSON, URL-encoded, multipart) in Express?",
      "How do you implement session management in Express using express-session and a session store?",
      "What security middleware do you use in Express (Helmet, express-rate-limit, CORS) and what does each protect against?",
      "How do you connect Express to MongoDB using Mongoose? Explain the Schema and Model pattern.",
      "How do you write integration tests for Express routes using Supertest and Jest or Mocha?",
    ],
  },
  {
    name: "NestJS",
    subtitle: "Modular architecture, DI, guards, pipes, and interceptors",
    accentHex: "#E0234E",
    questions: [
      "Explain NestJS's modular architecture. What are the roles of Modules, Controllers, and Providers?",
      "How does NestJS's dependency injection container work? How do you scope a provider as request-scoped?",
      "What are NestJS decorators (@Get, @Post, @Body, @Param, @Query) and how do they bind HTTP metadata?",
      "How do NestJS pipes work? How do you use ValidationPipe with class-validator DTOs?",
      "What are NestJS Guards and how do you implement role-based access control (RBAC)?",
      "Explain NestJS exception filters. How do you create a custom filter for unified error responses?",
      "What are NestJS interceptors and how do you use them for response transformation and logging?",
      "How do you integrate TypeORM with NestJS for database operations and dependency injection?",
      "How do you implement microservice communication in NestJS using TCP or NATS message patterns?",
      "How do you write unit tests and e2e tests in NestJS using Jest and the NestJS testing module?",
    ],
  },
  {
    name: "Fastify",
    subtitle: "Performance, schema validation, plugin system, and serialization",
    accentHex: "#000000",
    questions: [
      "What makes Fastify faster than Express.js? Explain its JSON schema serialization and routing algorithm.",
      "How does Fastify's plugin system work? What is encapsulation and how do fastify-plugin and register() work?",
      "How does Fastify validate requests and responses using JSON Schema? What happens when validation fails?",
      "Explain Fastify's request lifecycle hooks: onRequest, preHandler, onSend, and onResponse.",
      "How do you implement JWT authentication in Fastify using @fastify/jwt?",
      "How does Fastify's serialization differ from JSON.stringify()? Why is it faster?",
      "How do you add CORS, rate limiting, and security headers in a Fastify application?",
      "What are Fastify decorators and how do you extend the fastify, request, and reply instances?",
      "How do you integrate PostgreSQL with Fastify using @fastify/postgres or an ORM like Prisma?",
      "How do you write tests for Fastify routes using fastify.inject() and a test framework like tap or Jest?",
    ],
  },
  {
    name: "Koa",
    subtitle: "Async middleware, context object, error handling, and ecosystem",
    accentHex: "#33333D",
    questions: [
      "What is Koa and how does it differ from Express in its use of async/await and middleware composition?",
      "Explain how Koa's cascading middleware works with async functions and await next().",
      "What is Koa's context object (ctx)? How does ctx.request, ctx.response, and ctx.state relate?",
      "How do you define routes in Koa using koa-router? How do you apply middleware to specific routes?",
      "What is the difference between setting ctx.body vs ctx.response.body in Koa?",
      "How do you implement centralized error handling in Koa using a try/catch at the top of the middleware stack?",
      "How do you handle file uploads in a Koa application using koa-multer or busboy?",
      "What are the most commonly used Koa middleware packages and what does each add (bodyparser, session, jwt)?",
      "How do you implement CORS in Koa and what cross-origin headers must you configure?",
      "How do you write tests for a Koa application using supertest or koa's own server listen pattern?",
    ],
  },

  // ── .NET / Go / PHP / Ruby ───────────────────────────────────────────────
  {
    name: "ASP.NET Core",
    subtitle: "Request pipeline, DI, routing, Minimal API, and Identity",
    accentHex: "#512BD4",
    questions: [
      "Describe the ASP.NET Core request pipeline and how middleware is registered and ordered in Program.cs.",
      "Explain the three service lifetimes in ASP.NET Core DI: Singleton, Scoped, and Transient. What are the captive dependency risks?",
      "How does ASP.NET Core attribute routing work? How do you handle route constraints and route templates?",
      "What is model binding in ASP.NET Core? How does it differ from [FromBody], [FromQuery], and [FromRoute]?",
      "What is the Minimal API pattern in ASP.NET Core 6+? When would you choose it over controllers?",
      "How do you implement JWT Bearer authentication in ASP.NET Core using AddAuthentication and AddJwtBearer?",
      "How does appsettings.json configuration work in ASP.NET Core? Explain IConfiguration and Options pattern.",
      "What is Entity Framework Core and how do you configure DbContext in a dependency-injected ASP.NET Core app?",
      "How does ASP.NET Core handle filters: action filters, resource filters, and exception filters?",
      "How do you write integration tests for ASP.NET Core using WebApplicationFactory<T> and HttpClient?",
    ],
  },
  {
    name: ".NET",
    subtitle: "CLR, async/await, LINQ, generics, and garbage collection",
    accentHex: "#512BD4",
    questions: [
      "What is the Common Language Runtime (CLR) and how does JIT compilation work in .NET?",
      "Explain the difference between .NET Framework, .NET Core, and the unified .NET 5+ platform.",
      "How does the .NET Garbage Collector work? Explain the generational collection model (Gen0, Gen1, Gen2).",
      "Explain async/await in .NET. What is a Task, how does ConfigureAwait(false) affect context capture?",
      "What is LINQ? Explain deferred execution and the difference between IQueryable and IEnumerable.",
      "What is the difference between value types and reference types in .NET? Explain boxing and unboxing.",
      "How does the .NET generic type system work? Why are generics preferred over object-based collections?",
      "What is NuGet and how do you create and publish a reusable class library as a NuGet package?",
      "Explain the Span<T> and Memory<T> types and when you would use them for performance optimization.",
      "How do you write unit tests in .NET using xUnit or NUnit? Explain mocking with Moq.",
    ],
  },
  {
    name: "Entity Framework Core",
    subtitle: "Code-First, migrations, relationships, performance, and testing",
    accentHex: "#512BD4",
    questions: [
      "What is Entity Framework Core? Explain Code-First vs Database-First approaches.",
      "How do you configure a DbContext? What is the difference between OnConfiguring and using DI with AddDbContext?",
      "How do you define entity relationships using Fluent API vs Data Annotations? Give a @OneToMany example.",
      "What are EF Core migrations? How do you create, apply, and roll back a migration?",
      "Explain eager loading (Include), lazy loading (proxy), and explicit loading (Load) in EF Core.",
      "How do you execute raw SQL queries in EF Core safely using FromSqlRaw and ExecuteSqlRaw?",
      "What are the Repository and Unit of Work patterns and how do they layer over EF Core?",
      "How does EF Core handle optimistic concurrency? What is the [ConcurrencyCheck] or RowVersion attribute?",
      "What are compiled queries in EF Core and when do they improve performance significantly?",
      "How do you test EF Core code using the in-memory provider vs SQLite in-memory for integration tests?",
    ],
  },
  {
    name: "Blazor",
    subtitle: "Component model, data binding, JS interop, and state management",
    accentHex: "#512BD4",
    questions: [
      "What is Blazor? Explain the key differences between Blazor Server, Blazor WebAssembly, and Blazor Hybrid.",
      "How does the Blazor component lifecycle work? Explain OnInitializedAsync, OnParametersSetAsync, and ShouldRender.",
      "Explain two-way data binding in Blazor using @bind and @bind:event.",
      "How does Blazor's JavaScript interop work using IJSRuntime.InvokeAsync and JSInvokable?",
      "What are cascading parameters in Blazor and how do you use CascadingValue and [CascadingParameter]?",
      "How does Blazor's routing work with the @page directive and NavigationManager?",
      "How do you validate forms in Blazor using EditForm, DataAnnotationsValidator, and ValidationSummary?",
      "How do you manage shared state in a Blazor application: services, cascading values, or state containers?",
      "What are RenderFragments in Blazor and how do you create templated components?",
      "How do you make HTTP requests in Blazor WebAssembly using a typed HttpClient?",
    ],
  },
  {
    name: "Gin",
    subtitle: "Go HTTP routing, middleware, JSON binding, and testing",
    accentHex: "#00ACD7",
    questions: [
      "What is Gin and what performance advantages does it have over the standard net/http package in Go?",
      "How do you define route groups in Gin and apply middleware to a subset of routes?",
      "How do you write custom Gin middleware? Explain c.Next() and c.Abort() in the middleware chain.",
      "How does Gin handle JSON request binding with ShouldBindJSON and validate structs with binding tags?",
      "What are Gin's built-in rendering methods and how do you return JSON, XML, or HTML templates?",
      "How do you handle errors in Gin using c.AbortWithStatusJSON() and a custom error handler middleware?",
      "What is gin.Context and what request/response information does it expose?",
      "How do you serve static files and embedded HTML templates in a Gin application?",
      "How do you configure and start a Gin server with TLS? What are the key gin.Engine options?",
      "How do you write unit tests for Gin handlers using httptest.NewRecorder and httptest.NewRequest?",
    ],
  },
  {
    name: "Echo",
    subtitle: "Go web framework: routing, middleware, binding, and testing",
    accentHex: "#00ACD7",
    questions: [
      "What is Echo and how does it compare to Gin and the standard net/http package in Go?",
      "How does Echo's middleware chain work? How do you apply middleware globally vs to a group?",
      "How does Echo handle request binding? Explain Bind(), Validate(), and how to wire a custom validator.",
      "What is an Echo Group and how do you use it to apply shared middleware to a set of routes?",
      "How does Echo's error handling work? How do you define a custom HTTPErrorHandler?",
      "What does echo.Context provide? How do you retrieve path params, query params, and form values?",
      "How do you implement JWT authentication in Echo using echojwt middleware?",
      "What are Echo's response helpers (JSON, XML, HTML, NoContent, Redirect) and their signatures?",
      "How do you handle WebSocket connections in Echo using gorilla/websocket or nhooyr/websocket?",
      "How do you test Echo handlers using httptest.NewRecorder without starting an HTTP server?",
    ],
  },
  {
    name: "Fiber",
    subtitle: "Go Fasthttp-based framework: routing, context, and performance",
    accentHex: "#00ACD7",
    questions: [
      "What is Fiber and why is it built on Fasthttp instead of the standard Go net/http package?",
      "How does Fiber's Express-like routing API work? How do you define routes and named parameters?",
      "How does Fiber's middleware system work? Write an example of a simple request-logging middleware.",
      "What is the Fiber Ctx object and what methods does it provide for reading requests and writing responses?",
      "How does Fiber handle JSON parsing with BodyParser() and JSON serialization with JSON()?",
      "How do you create route groups in Fiber and attach middleware to specific groups?",
      "How do you implement JWT-based authentication middleware in Fiber?",
      "What are Fiber's performance characteristics and what tradeoffs come from using Fasthttp?",
      "How do you connect Fiber to a PostgreSQL database using pgxpool or an ORM like GORM?",
      "How do you write tests for Fiber handlers using the app.Test() method with http.NewRequest?",
    ],
  },
  {
    name: "Chi",
    subtitle: "Go lightweight router: middleware, context, and net/http compatibility",
    accentHex: "#00ACD7",
    questions: [
      "What is Chi and how does its composable, lightweight design differ from full-framework approaches like Gin?",
      "How do you chain middleware in Chi using chi.Use() and group-scoped middleware?",
      "How does Chi's router handle URL parameters, wildcards, and regexp constraints?",
      "What is chi.Mount() and how do you use it to build a sub-router for modular route organization?",
      "How does Chi maintain compatibility with standard net/http handlers and middleware?",
      "How do you pass data between middleware and handlers in Chi using context.WithValue and chi.URLParam?",
      "How do you implement JWT authentication in a Chi application using a custom middleware?",
      "What built-in middleware does Chi provide (middleware.Logger, Recoverer, Throttle, Heartbeat)?",
      "How do you handle HTTP method routing for a RESTful resource in Chi (GET, POST, PUT, DELETE)?",
      "How do you write tests for Chi handlers using net/http/httptest.NewRecorder and httptest.NewRequest?",
    ],
  },
  {
    name: "Laravel",
    subtitle: "MVC, Eloquent, routing, service container, and queues",
    accentHex: "#FF2D20",
    questions: [
      "Describe the Laravel request lifecycle from HTTP request entry to the response being sent.",
      "How does Laravel Eloquent ORM work? Define a model with a belongsTo and hasMany relationship.",
      "Explain Laravel's routing system: route groups, middleware assignment, and named routes with route().",
      "What is the Laravel service container and how does it resolve dependencies via the constructor injection?",
      "What is Laravel Artisan? Name five useful artisan commands and what they do.",
      "How does Laravel Sanctum handle API token authentication for SPAs and mobile apps?",
      "How do you dispatch and process a Laravel queue job? What are the queue driver options?",
      "Explain Laravel Blade: @extends, @section, @yield, and how Blade components work.",
      "How do you write feature tests and unit tests in Laravel using PHPUnit and Laravel's TestCase helpers?",
      "What is Laravel Livewire and how does it enable reactive UI updates without writing JavaScript?",
    ],
  },
  {
    name: "Symfony",
    subtitle: "Components, DI container, Doctrine, events, and security",
    accentHex: "#000000",
    questions: [
      "What is Symfony's component architecture? How does Symfony Flex automate bundle management via recipes?",
      "Explain Symfony's dependency injection container: how are services defined, autowired, and tagged?",
      "How does Symfony routing work? Compare annotations/attributes, YAML, and PHP configuration approaches.",
      "What is Doctrine ORM and how does it differ from an Active Record pattern? Explain the EntityManager.",
      "Explain the Symfony event dispatcher. How do you listen to kernel.request and create a custom subscriber?",
      "How does Symfony Security handle firewalls, authentication providers, and access control rules?",
      "How do you build, validate, and render a Symfony Form? Explain FormType, constraints, and form rendering.",
      "What is the Symfony Console component? How do you create a custom CLI command with input/output?",
      "How does Symfony's cache component work with PSR-6 CacheInterface and tagged cache invalidation?",
      "How do you write functional tests in Symfony using WebTestCase and Symfony's BrowserKit client?",
    ],
  },
  {
    name: "CodeIgniter",
    subtitle: "MVC, routing, Query Builder, validation, and RESTful resources",
    accentHex: "#DD4814",
    questions: [
      "What is CodeIgniter and how does it implement the MVC pattern? Explain the request routing flow.",
      "How does CodeIgniter 4's routing work? How do you define resourceful routes with $routes->resource()?",
      "Explain CodeIgniter's Query Builder. How do you safely build parameterized SELECT and INSERT queries?",
      "What are CodeIgniter 4 Models? How do Entity classes map to database rows and provide casting?",
      "How does CodeIgniter's built-in library system work? How do you load and configure a library like Email?",
      "How does CodeIgniter's validation library work? How do you define rules inline vs in a config file?",
      "How does CodeIgniter 4 handle sessions? How does it differ from PHP's native session management?",
      "How do you handle file uploads in CodeIgniter 4 using the Files API and validate MIME type and size?",
      "What is a CodeIgniter RESTful Resource Controller and what methods does it expose by default?",
      "How do you write tests for CodeIgniter 4 controllers and models using PHPUnit and CIUnitTestCase?",
    ],
  },
  {
    name: "Ruby on Rails",
    subtitle: "Convention over configuration, Active Record, and testing",
    accentHex: "#CC0000",
    questions: [
      "What does 'Convention over Configuration' mean in Rails and how does it shape folder structure and naming?",
      "Walk through the Rails request lifecycle from a browser request to the rendered HTML response.",
      "What is Active Record? How do you define a has_many/belongs_to association and use joins in a query?",
      "How do Rails migrations work? How do you create, run, and roll back a migration safely in production?",
      "Explain Rails routes: resources, namespace, nested routes, and how to inspect routes with rails routes.",
      "What are Rails concerns and how do you use them to share behavior between models or controllers?",
      "How does Rails asset management work with Propshaft/Importmap vs the old Sprockets pipeline?",
      "What is Rails Action Cable? How does it provide WebSocket support within the Rails framework?",
      "How do you process background jobs in Rails with Active Job backed by Sidekiq?",
      "How do you write model unit tests with RSpec or Minitest and use factories with FactoryBot?",
    ],
  },
  {
    name: "Sinatra",
    subtitle: "Lightweight Ruby DSL: routing, middleware, and templating",
    accentHex: "#CC0000",
    questions: [
      "What is Sinatra and how does its DSL-based approach differ from Ruby on Rails?",
      "How do you define routes in Sinatra using HTTP verb helpers (get, post, put, delete, patch)?",
      "Explain Sinatra's request and response objects. What helpers are available for params, headers, and status?",
      "How does Sinatra handle templates? Which template engines does it support and how do you render ERB?",
      "How do you define and use Sinatra helper methods inside routes and templates?",
      "How do Sinatra's before/after filters work and how do they differ from Rack middleware?",
      "How do you define custom error handlers in Sinatra using error 404 and error blocks?",
      "What is the difference between Sinatra's classic style (require 'sinatra') and modular style (Sinatra::Base)?",
      "How do you manage sessions and cookies in a Sinatra application?",
      "How do you test a Sinatra application using Rack::Test and RSpec or Minitest?",
    ],
  },
];
