import type { CheatSheetSpec } from "../tech-pdf-builder";

export const javaBackend: CheatSheetSpec[] = [
  {
    name: "Spring Boot",
    subtitle: "Auto-Config · REST · Data JPA · Actuator",
    emoji: "🌱",
    accentHex: "#6DB33F",
    sections: [
      { title: "SETUP & STARTER", lines: [
        "§ <parent>spring-boot-starter-parent</parent>",
        "§ <dep>spring-boot-starter-web</dep>",
        "Bootstrap via start.spring.io",
        "BOM manages all dependency versions",
        "§ mvn spring-boot:run  /  ./gradlew bootRun",
      ]},
      { title: "MAIN CLASS", lines: [
        "§ @SpringBootApplication",
        "§ public class App {",
        "§   public static void main(String[] a) {",
        "§     SpringApplication.run(App.class, a);",
        "§   }",
        "§ }",
        "Combines @Config+@EnableAutoConfig+@Scan",
      ]},
      { title: "REST CONTROLLER", lines: [
        "§ @RestController",
        "§ @RequestMapping(\"/api/users\")",
        "§ public class UserController {",
        "§   @GetMapping(\"/{id}\")",
        "§   public User get(@PathVariable Long id){...}",
        "§   @PostMapping",
        "§   public User create(@RequestBody User u){...}",
      ]},
      { title: "SPRING DATA JPA", lines: [
        "§ @Entity public class User { @Id @GeneratedValue Long id; }",
        "§ interface UserRepo extends JpaRepository<User,Long>{}",
        "§ List<User> findByEmail(String email);",
        "Derives queries from method names",
        "§ @Query(\"SELECT u FROM User u WHERE u.active=true\")",
      ]},
      { title: "DEPENDENCY INJECTION", lines: [
        "§ @Service / @Repository / @Component",
        "§ @Autowired  // field injection (avoid)",
        "Constructor injection preferred:",
        "§ public UserSvc(UserRepo repo){ this.repo=repo; }",
        "§ @Bean  // manual bean in @Configuration class",
      ]},
      { title: "CONFIGURATION", lines: [
        "§ application.properties / application.yml",
        "§ server.port=8080",
        "§ spring.datasource.url=jdbc:postgresql://...",
        "§ @Value(\"${app.secret}\")  private String secret;",
        "§ @ConfigurationProperties(prefix=\"app\")",
      ]},
      { title: "PROFILES", lines: [
        "§ application-dev.yml  /  application-prod.yml",
        "§ spring.profiles.active=dev",
        "§ @Profile(\"prod\")  class ProdBean {}",
        "§ -Dspring.profiles.active=prod  (JVM arg)",
        "§ SPRING_PROFILES_ACTIVE=prod  (env var)",
      ]},
      { title: "EXCEPTION HANDLING", lines: [
        "§ @RestControllerAdvice",
        "§ @ExceptionHandler(UserNotFoundException.class)",
        "§ public ResponseEntity<Error> handle(ex) {",
        "§   return ResponseEntity.status(404)...",
        "§ }",
        "§ @ResponseStatus(HttpStatus.NOT_FOUND)",
      ]},
      { title: "VALIDATION", lines: [
        "§ @NotNull @Size(min=2,max=50) String name;",
        "§ @Email String email;",
        "§ @Min(0) int age;",
        "§ public User create(@Valid @RequestBody User u){}",
        "Add spring-boot-starter-validation dep",
        "§ @ControllerAdvice handles MethodArgumentNotValidException",
      ]},
      { title: "ACTUATOR", lines: [
        "§ <dep>spring-boot-starter-actuator</dep>",
        "§ management.endpoints.web.exposure.include=*",
        "§ GET /actuator/health  /actuator/metrics",
        "§ GET /actuator/env  /actuator/beans",
        "Custom: implement HealthIndicator interface",
      ]},
      { title: "LOGGING", lines: [
        "§ private static final Logger log =",
        "§   LoggerFactory.getLogger(MyClass.class);",
        "§ log.info(\"User {} created\", user.getId());",
        "§ logging.level.com.example=DEBUG",
        "Uses Logback by default, SLF4J facade",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Circular bean deps — use @Lazy or constructor refactor",
        "OpenEntityManagerInViewFilter N+1 queries",
        "Transaction must be on public methods only",
        "@SpringBootTest loads full context — use slices",
        "Flyway/Liquibase for DB migrations, not auto-ddl in prod",
      ]},
    ],
  },

  {
    name: "Spring Framework",
    subtitle: "IoC · AOP · MVC · SpEL · Transactions",
    emoji: "🌿",
    accentHex: "#6DB33F",
    sections: [
      { title: "APPLICATION CONTEXT", lines: [
        "§ AnnotationConfigApplicationContext ctx =",
        "§   new AnnotationConfigApplicationContext(AppConfig.class);",
        "§ MyBean b = ctx.getBean(MyBean.class);",
        "ctx.close() destroys singletons",
        "BeanFactory is leaner; ApplicationContext extends it",
      ]},
      { title: "JAVA CONFIG & BEANS", lines: [
        "§ @Configuration",
        "§ public class AppConfig {",
        "§   @Bean public DataSource ds(){ return new ...}",
        "§   @Bean @Scope(\"prototype\") Foo foo(){ ... }",
        "§ }",
        "§ @Import(OtherConfig.class)",
      ]},
      { title: "STEREOTYPE ANNOTATIONS", lines: [
        "§ @Component    // generic",
        "§ @Service      // business layer",
        "§ @Repository   // converts SQL exceptions",
        "§ @Controller   // MVC controller",
        "§ @RestController = @Controller + @ResponseBody",
        "§ @ComponentScan(\"com.example\")",
      ]},
      { title: "DEPENDENCY INJECTION", lines: [
        "Constructor injection (preferred):",
        "§ public Svc(Repo r){ this.r = r; }",
        "§ @Autowired  (field / setter)",
        "§ @Qualifier(\"beanName\") to disambiguate",
        "§ @Primary on preferred bean",
        "§ @Lazy delays initialization",
      ]},
      { title: "AOP", lines: [
        "§ @Aspect @Component",
        "§ @Before(\"execution(* com.ex.service.*.*(..))\")",
        "§ public void before(JoinPoint jp){}",
        "§ @Around, @After, @AfterReturning, @AfterThrowing",
        "AOP proxy wraps bean at runtime (JDK or CGLIB)",
        "Self-invocation bypasses proxy — use AopContext",
      ]},
      { title: "SPRING MVC", lines: [
        "§ @RequestMapping(method=GET, path=\"/items\")",
        "§ @GetMapping  @PostMapping  @PutMapping",
        "§ @PathVariable @RequestParam @RequestBody",
        "§ @RequestHeader  @CookieValue",
        "§ ModelAndView or return String view name",
        "§ @ResponseBody for direct JSON/XML output",
      ]},
      { title: "BEAN LIFECYCLE", lines: [
        "§ @PostConstruct void init(){}",
        "§ @PreDestroy   void destroy(){}",
        "Implements InitializingBean / DisposableBean",
        "Scopes: singleton (default), prototype, request, session",
        "§ @Lazy on @Bean defers until first use",
      ]},
      { title: "TRANSACTIONS", lines: [
        "§ @EnableTransactionManagement",
        "§ @Transactional(propagation=REQUIRED, rollbackFor=Exception.class)",
        "Works on public methods via proxy",
        "Propagation: REQUIRED, REQUIRES_NEW, NESTED, SUPPORTS",
        "§ @Transactional(readOnly=true) for queries",
      ]},
      { title: "SpEL", lines: [
        "§ @Value(\"#{systemProperties['user.home']}\")",
        "§ @Value(\"#{myBean.someValue + 10}\")",
        "§ @ConditionalOnExpression(\"#{env['mode']=='prod'}\")",
        "Used in security, caching, scheduled tasks",
        "ExpressionParser API for programmatic use",
      ]},
      { title: "CONFIGURATION & PROFILES", lines: [
        "§ @PropertySource(\"classpath:app.properties\")",
        "§ @Profile(\"dev\") @Configuration",
        "§ @ConditionalOnProperty(name=\"feature.x\",havingValue=\"true\")",
        "§ Environment env — env.getProperty(\"key\")",
        "§ @TestPropertySource overrides in tests",
      ]},
      { title: "TESTING", lines: [
        "§ @ExtendWith(SpringExtension.class)",
        "§ @SpringJUnitConfig(AppConfig.class)",
        "§ @MockBean  replaces bean with Mockito mock",
        "§ @Autowired MockMvc mvc — for MVC layer tests",
        "§ @DataJpaTest / @WebMvcTest (slices)",
        "§ @Sql to run SQL scripts before/after tests",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Self-invocation skips AOP proxy",
        "Prototype bean in singleton: use ObjectProvider",
        "@Transactional on private/final methods ignored",
        "@ComponentScan must include all config packages",
        "LazyInitializationException — open-session-in-view trap",
      ]},
    ],
  },

  {
    name: "Spring Security",
    subtitle: "Auth · JWT · OAuth2 · Method Security",
    emoji: "🔒",
    accentHex: "#6DB33F",
    sections: [
      { title: "SECURITY FILTER CHAIN", lines: [
        "§ @Bean SecurityFilterChain chain(HttpSecurity http){",
        "§   return http",
        "§     .authorizeHttpRequests(a ->",
        "§       a.requestMatchers(\"/public/**\").permitAll()",
        "§        .anyRequest().authenticated())",
        "§     .build();",
        "§ }",
      ]},
      { title: "USERDETAILSSERVICE", lines: [
        "§ @Service class UserSvc implements UserDetailsService{",
        "§   public UserDetails loadUserByUsername(String u){",
        "§     User user = repo.findByEmail(u);",
        "§     return new org.springframework.security.core",
        "§       .userdetails.User(user.email, user.pwHash,",
        "§       mapRoles(user.roles));",
        "§   }",
        "§ }",
      ]},
      { title: "PASSWORD ENCODING", lines: [
        "§ @Bean PasswordEncoder encoder(){",
        "§   return new BCryptPasswordEncoder();",
        "§ }",
        "§ encoder.encode(rawPassword)",
        "§ encoder.matches(raw, stored)",
        "BCrypt strength 10–12; use Argon2 for new projects",
      ]},
      { title: "JWT FILTER", lines: [
        "§ class JwtFilter extends OncePerRequestFilter{",
        "§   void doFilterInternal(req, res, chain){",
        "§     String token = extractToken(req);",
        "§     if(jwtUtil.validate(token)){",
        "§       var auth = jwtUtil.getAuthentication(token);",
        "§       SecurityContextHolder.getContext().setAuthentication(auth);",
        "§     }",
        "§     chain.doFilter(req, res);",
        "§   }",
        "§ }",
      ]},
      { title: "OAUTH2 / OIDC", lines: [
        "§ <dep>spring-boot-starter-oauth2-client</dep>",
        "§ spring.security.oauth2.client.registration",
        "§   .google.client-id=...",
        "§   .google.client-secret=...",
        "§ http.oauth2Login(withDefaults())",
        "OAuth2User / OidcUser principals available",
      ]},
      { title: "METHOD SECURITY", lines: [
        "§ @EnableMethodSecurity",
        "§ @PreAuthorize(\"hasRole('ADMIN')\")",
        "§ @PostAuthorize(\"returnObject.owner == authentication.name\")",
        "§ @Secured({\"ROLE_USER\",\"ROLE_ADMIN\"})",
        "§ @RolesAllowed(\"ADMIN\") (JSR-250)",
      ]},
      { title: "CORS & CSRF", lines: [
        "§ http.cors(cors -> cors.configurationSource(source))",
        "§ CorsConfiguration cfg = new CorsConfiguration();",
        "§ cfg.addAllowedOrigin(\"https://myapp.com\");",
        "CSRF enabled by default; disable for stateless APIs:",
        "§ http.csrf(AbstractHttpConfigurer::disable)",
      ]},
      { title: "RBAC PATTERN", lines: [
        "§ .requestMatchers(\"/admin/**\").hasRole(\"ADMIN\")",
        "§ .requestMatchers(\"/api/**\").hasAuthority(\"SCOPE_read\")",
        "Role = ROLE_ prefix; Authority = any string",
        "§ GrantedAuthority interface",
        "Hierarchy: RoleHierarchyImpl for nested roles",
      ]},
      { title: "EXCEPTION HANDLING", lines: [
        "§ http.exceptionHandling(e ->",
        "§   e.authenticationEntryPoint(myEntryPoint)",
        "§    .accessDeniedHandler(myHandler))",
        "401 Unauthorized vs 403 Forbidden",
        "§ AuthenticationEntryPoint: commence(req,res,ex)",
        "§ AccessDeniedHandler: handle(req,res,ex)",
      ]},
      { title: "SECURITY CONTEXT", lines: [
        "§ Authentication auth = SecurityContextHolder",
        "§   .getContext().getAuthentication();",
        "§ String name = auth.getName();",
        "§ Collection<? extends GrantedAuthority> roles = auth.getAuthorities();",
        "§ @AuthenticationPrincipal UserDetails user — in controllers",
      ]},
      { title: "TESTING", lines: [
        "§ @WithMockUser(roles=\"ADMIN\")",
        "§ @WithUserDetails(\"admin@example.com\")",
        "§ mvc.perform(get(\"/admin\")).andExpect(status().isOk())",
        "§ @WithSecurityContext for custom auth",
        "§ SecurityMockMvcRequestPostProcessors.csrf() for POST",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "CSRF must be disabled for REST APIs with JWT",
        "Roles need ROLE_ prefix in hasRole()",
        "SecurityContextHolder clears after request by default",
        "Don't store sensitive data in JWT — it's not encrypted",
        "HTTPS required in prod; use HSTS header",
      ]},
    ],
  },

  {
    name: "Spring Cloud",
    subtitle: "Config · Eureka · Gateway · Resilience4j",
    emoji: "☁️",
    accentHex: "#6DB33F",
    sections: [
      { title: "SETUP & BOM", lines: [
        "§ <dep>spring-cloud-dependencies BOM</dep>",
        "§ spring-cloud-starter-config",
        "§ spring-cloud-starter-netflix-eureka-client",
        "§ spring-cloud-starter-gateway",
        "Match Spring Cloud release train to Spring Boot version",
      ]},
      { title: "CONFIG SERVER", lines: [
        "§ @EnableConfigServer @SpringBootApplication",
        "§ spring.cloud.config.server.git.uri=https://...",
        "§ spring.cloud.config.server.git.search-paths=config",
        "§ GET /{application}/{profile} returns merged config",
        "Config stored in git repo as {app}-{profile}.yml",
      ]},
      { title: "CONFIG CLIENT", lines: [
        "§ spring.config.import=optional:configserver:",
        "§ spring.cloud.config.uri=http://config-server:8888",
        "§ spring.cloud.config.fail-fast=true",
        "§ @RefreshScope on beans to reload on /actuator/refresh",
        "§ spring.cloud.bus (Kafka/RabbitMQ) for broadcast refresh",
      ]},
      { title: "SERVICE DISCOVERY (EUREKA)", lines: [
        "Server: @EnableEurekaServer",
        "§ eureka.instance.hostname=eureka-server",
        "Client: @EnableEurekaClient (or auto if dep present)",
        "§ eureka.client.serviceUrl.defaultZone=http://...",
        "§ spring.application.name=my-service (= service ID)",
        "Clients fetch registry every 30s by default",
      ]},
      { title: "API GATEWAY", lines: [
        "§ spring.cloud.gateway.routes:",
        "§   - id: user-service",
        "§     uri: lb://USER-SERVICE",
        "§     predicates:",
        "§       - Path=/api/users/**",
        "§     filters:",
        "§       - StripPrefix=1",
        "lb:// = client-side load balancing",
      ]},
      { title: "CIRCUIT BREAKER (RESILIENCE4J)", lines: [
        "§ @CircuitBreaker(name=\"userSvc\", fallbackMethod=\"fallback\")",
        "§ @Retry(name=\"userSvc\")",
        "§ @TimeLimiter(name=\"userSvc\")",
        "§ resilience4j.circuitbreaker.instances.userSvc",
        "§   .slidingWindowSize=10",
        "§   .failureRateThreshold=50",
      ]},
      { title: "FEIGN CLIENT", lines: [
        "§ @EnableFeignClients",
        "§ @FeignClient(name=\"user-service\")",
        "§ interface UserClient {",
        "§   @GetMapping(\"/users/{id}\")",
        "§   User getUser(@PathVariable Long id);",
        "§ }",
        "Integrates with Eureka and Resilience4j",
      ]},
      { title: "LOAD BALANCING", lines: [
        "§ <dep>spring-cloud-starter-loadbalancer</dep>",
        "§ @LoadBalanced RestTemplate template",
        "§ template.getForObject(\"http://USER-SERVICE/\", User.class)",
        "§ WebClient.Builder with @LoadBalanced",
        "Round-robin by default; pluggable strategy",
      ]},
      { title: "DISTRIBUTED TRACING", lines: [
        "§ <dep>spring-cloud-starter-sleuth</dep>",
        "§ <dep>zipkin-brave-spring-cloud-sleuth</dep>",
        "MDC populated with traceId, spanId",
        "§ spring.zipkin.base-url=http://zipkin:9411",
        "§ spring.sleuth.sampler.probability=1.0",
      ]},
      { title: "SPRING CLOUD BUS", lines: [
        "§ <dep>spring-cloud-starter-bus-kafka</dep>",
        "§ POST /actuator/busrefresh — triggers all clients",
        "Propagates config refresh via message broker",
        "§ spring.cloud.bus.enabled=true",
        "Requires Kafka or RabbitMQ broker",
      ]},
      { title: "RETRY & RATE LIMITING", lines: [
        "§ @Retry(name=\"user\", fallbackMethod=\"fb\")",
        "§ resilience4j.retry.instances.user",
        "§   .maxAttempts=3",
        "§   .waitDuration=1s",
        "Rate limiter: RequestRateLimiter filter in Gateway",
        "§   redis-rate-limiter.replenishRate=10",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Release train version mismatch causes NoSuchMethod errors",
        "Feign client needs @EnableFeignClients on main class",
        "Config Server needs to start before clients (health check)",
        "Ribbon deprecated — use spring-cloud-starter-loadbalancer",
        "Sleuth auto-adds trace headers; verify sampling rate in prod",
      ]},
    ],
  },

  {
    name: "Hibernate",
    subtitle: "ORM · Session · HQL · Caching · Associations",
    emoji: "🐘",
    accentHex: "#59666C",
    sections: [
      { title: "SETUP & CONFIG", lines: [
        "§ <dep>hibernate-core 6.x</dep>",
        "§ hibernate.cfg.xml OR persistence.xml",
        "§ hibernate.dialect=PostgreSQLDialect",
        "§ hibernate.connection.url=jdbc:postgresql://...",
        "§ hibernate.hbm2ddl.auto=validate (prod)",
      ]},
      { title: "SESSION FACTORY / SESSION", lines: [
        "§ SessionFactory sf = new Configuration()",
        "§   .configure().buildSessionFactory();",
        "§ try(Session s = sf.openSession()){",
        "§   s.beginTransaction();",
        "§   s.persist(entity);",
        "§   s.getTransaction().commit();",
        "§ }",
      ]},
      { title: "ENTITY MAPPING", lines: [
        "§ @Entity @Table(name=\"users\")",
        "§ public class User {",
        "§   @Id @GeneratedValue(strategy=IDENTITY)",
        "§   private Long id;",
        "§   @Column(nullable=false, unique=true)",
        "§   private String email;",
        "§ }",
      ]},
      { title: "ASSOCIATIONS", lines: [
        "§ @OneToMany(mappedBy=\"user\", cascade=ALL)",
        "§ private List<Order> orders = new ArrayList<>();",
        "§ @ManyToOne @JoinColumn(name=\"user_id\")",
        "§ private User user;",
        "§ @ManyToMany @JoinTable(...)",
        "Owning side has @JoinColumn / @JoinTable",
      ]},
      { title: "HQL QUERIES", lines: [
        "§ Query<User> q = session.createQuery(",
        "§   \"FROM User WHERE email = :email\", User.class);",
        "§ q.setParameter(\"email\", email);",
        "§ List<User> users = q.list();",
        "§ session.get(User.class, id)  // load by PK",
        "HQL uses entity names, not table names",
      ]},
      { title: "CRITERIA API", lines: [
        "§ CriteriaBuilder cb = session.getCriteriaBuilder();",
        "§ CriteriaQuery<User> cq = cb.createQuery(User.class);",
        "§ Root<User> r = cq.from(User.class);",
        "§ cq.select(r).where(cb.equal(r.get(\"active\"),true));",
        "§ session.createQuery(cq).list();",
        "Type-safe, refactor-friendly alternative to HQL",
      ]},
      { title: "LAZY vs EAGER LOADING", lines: [
        "LAZY (default for collections): loads on access",
        "EAGER: loads with parent query (N+1 risk)",
        "§ @OneToMany(fetch = FetchType.LAZY)",
        "Fix N+1: JOIN FETCH in HQL",
        "§ \"FROM User u JOIN FETCH u.orders\"",
        "§ @BatchSize(size=20) for batch loading",
      ]},
      { title: "CACHING", lines: [
        "L1 Cache: per-session, automatic",
        "L2 Cache: shared across sessions",
        "§ @Cacheable  (entity or collection)",
        "§ hibernate.cache.region.factory_class=EhcacheRegionFactory",
        "§ @Cache(usage=READ_WRITE)",
        "Query cache: .setCacheable(true) on query",
      ]},
      { title: "TRANSACTIONS", lines: [
        "§ session.beginTransaction();",
        "§ // ... do work",
        "§ session.getTransaction().commit();",
        "§ session.getTransaction().rollback(); // on error",
        "Use JTA for distributed transactions",
        "Never use AUTO flush mode in production",
      ]},
      { title: "CASCADE & ORPHAN REMOVAL", lines: [
        "§ cascade = {CascadeType.PERSIST, MERGE, REMOVE}",
        "§ cascade = CascadeType.ALL  // use with care",
        "§ orphanRemoval = true  // deletes removed children",
        "§ @OneToMany(cascade=ALL, orphanRemoval=true)",
        "Only set on owning side; avoid cascade from child to parent",
      ]},
      { title: "COMMON ANNOTATIONS", lines: [
        "§ @Entity @Table @Column @Id @GeneratedValue",
        "§ @OneToOne @OneToMany @ManyToOne @ManyToMany",
        "§ @JoinColumn @JoinTable @Embedded @Embeddable",
        "§ @Temporal(DATE/TIME/TIMESTAMP)",
        "§ @Enumerated(STRING/ORDINAL)",
        "§ @Version  (optimistic locking)",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "LazyInitializationException — session closed before access",
        "N+1 problem with EAGER or no JOIN FETCH",
        "cascade=ALL + orphanRemoval on ManyToMany = data loss",
        "Detached entity passed to persist = error",
        "hbm2ddl.auto=create drops tables on startup!",
      ]},
    ],
  },

  {
    name: "JPA",
    subtitle: "EntityManager · JPQL · Criteria · Relationships",
    emoji: "🗄️",
    accentHex: "#007396",
    sections: [
      { title: "SETUP & PERSISTENCE.XML", lines: [
        "§ <persistence-unit name=\"myPU\" transaction-type=\"RESOURCE_LOCAL\">",
        "§   <class>com.example.User</class>",
        "§   <properties>..db props..</properties>",
        "§ </persistence-unit>",
        "§ @PersistenceUnit EntityManagerFactory emf;",
      ]},
      { title: "ENTITY MANAGER", lines: [
        "§ EntityManager em = emf.createEntityManager();",
        "§ em.getTransaction().begin();",
        "§ em.persist(entity);   // INSERT",
        "§ em.merge(entity);     // UPDATE detached",
        "§ em.remove(entity);    // DELETE",
        "§ em.find(User.class, id); // SELECT by PK",
        "§ em.getTransaction().commit();",
      ]},
      { title: "ENTITY MAPPING", lines: [
        "§ @Entity @Table(name=\"users\")",
        "§ public class User implements Serializable {",
        "§   @Id @GeneratedValue(strategy=GenerationType.IDENTITY)",
        "§   private Long id;",
        "§   @Column(nullable=false,length=100)",
        "§   private String name;",
        "§ }",
      ]},
      { title: "JPQL QUERIES", lines: [
        "§ TypedQuery<User> q = em.createQuery(",
        "§   \"SELECT u FROM User u WHERE u.active = :a\", User.class);",
        "§ q.setParameter(\"a\", true);",
        "§ List<User> list = q.getResultList();",
        "§ User u = q.getSingleResult();",
        "JPQL uses entity/field names, not SQL table/column names",
      ]},
      { title: "NAMED QUERIES", lines: [
        "§ @NamedQuery(name=\"User.findByEmail\",",
        "§   query=\"SELECT u FROM User u WHERE u.email=:e\")",
        "§ em.createNamedQuery(\"User.findByEmail\", User.class)",
        "§   .setParameter(\"e\", email).getSingleResult();",
        "Parsed at startup — fail fast on typos",
      ]},
      { title: "RELATIONSHIPS", lines: [
        "§ @OneToOne  @OneToMany  @ManyToOne  @ManyToMany",
        "§ @JoinColumn(name=\"user_id\")  — FK column",
        "§ @JoinTable  — for ManyToMany bridge table",
        "mappedBy on non-owning (inverse) side",
        "Bidirectional: manage both sides in code",
      ]},
      { title: "FETCH TYPES", lines: [
        "LAZY (default for *ToMany): loads on first access",
        "EAGER (default for *ToOne): loads with parent",
        "§ @OneToMany(fetch = FetchType.EAGER) // N+1 risk",
        "Fix N+1: use JOIN FETCH in JPQL",
        "§ \"FROM Order o JOIN FETCH o.items\"",
        "§ @EntityGraph for ad-hoc fetch plans",
      ]},
      { title: "CASCADE & ORPHAN REMOVAL", lines: [
        "§ @OneToMany(cascade=CascadeType.ALL, orphanRemoval=true)",
        "CascadeType: PERSIST, MERGE, REMOVE, REFRESH, DETACH, ALL",
        "orphanRemoval=true auto-deletes children removed from list",
        "Cascade REMOVE on Many side = delete all children",
        "Only cascade from parent to child, not vice versa",
      ]},
      { title: "ENTITY LIFECYCLE CALLBACKS", lines: [
        "§ @PrePersist  @PostPersist",
        "§ @PreUpdate   @PostUpdate",
        "§ @PreRemove   @PostRemove",
        "§ @PostLoad",
        "§ @EntityListeners(AuditListener.class)",
        "Used for auditing: createdAt, updatedAt auto-fill",
      ]},
      { title: "TRANSACTIONS", lines: [
        "§ @Transactional  // Spring integration",
        "§ em.getTransaction().begin()  // resource-local",
        "§ @PersistenceContext EntityManager em  // injected",
        "JTA: container-managed in Jakarta EE",
        "§ @Transactional(propagation=REQUIRES_NEW)",
      ]},
      { title: "CRITERIA API", lines: [
        "§ CriteriaBuilder cb = em.getCriteriaBuilder();",
        "§ CriteriaQuery<User> cq = cb.createQuery(User.class);",
        "§ Root<User> r = cq.from(User.class);",
        "§ cq.where(cb.equal(r.get(\"status\"),\"active\"));",
        "§ em.createQuery(cq).getResultList();",
        "Type-safe; use metamodel (User_.name) for extra safety",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Detached entities: merge() instead of persist()",
        "LazyInitializationException outside transaction scope",
        "Bidirectional — always sync both sides",
        "GenerationType.AUTO may use SEQUENCE on PostgreSQL",
        "@Transactional only works on Spring-managed beans",
      ]},
    ],
  },

  {
    name: "Jakarta EE",
    subtitle: "CDI · JAX-RS · Servlet · JPA · EJB",
    emoji: "🏢",
    accentHex: "#007396",
    sections: [
      { title: "SETUP & APP SERVER", lines: [
        "§ WildFly / GlassFish / Payara / OpenLiberty",
        "§ <packaging>war</packaging>",
        "§ <dep>jakarta.jakartaee-api 10</dep> (provided)",
        "§ @ApplicationPath(\"/api\") class AppConfig extends Application{}",
        "Deploys as .war on servlet container or app server",
      ]},
      { title: "CDI BEANS", lines: [
        "§ @RequestScoped / @SessionScoped / @ApplicationScoped",
        "§ @Dependent (default — lifecycle follows owner)",
        "§ @Inject  — field, constructor, or setter",
        "§ @Named(\"myBean\")  — EL accessible",
        "§ @Produces  — factory method for CDI",
        "§ @Qualifier  — disambiguate multiple impls",
      ]},
      { title: "JAX-RS ENDPOINTS", lines: [
        "§ @Path(\"/users\") @ApplicationScoped",
        "§ public class UserResource {",
        "§   @GET @Path(\"/{id}\") @Produces(APPLICATION_JSON)",
        "§   public User getUser(@PathParam(\"id\") Long id){...}",
        "§   @POST @Consumes(APPLICATION_JSON)",
        "§   public Response create(User u){...}",
        "§ }",
      ]},
      { title: "SERVLETS", lines: [
        "§ @WebServlet(\"/hello\")",
        "§ public class HelloServlet extends HttpServlet{",
        "§   protected void doGet(HttpServletRequest req,",
        "§                        HttpServletResponse res){",
        "§     res.getWriter().write(\"Hello\");",
        "§   }",
        "§ }",
      ]},
      { title: "JPA INTEGRATION", lines: [
        "§ @PersistenceContext EntityManager em;",
        "§ @Stateless  // or @RequestScoped + @Transactional",
        "§ public List<User> findAll(){",
        "§   return em.createQuery(\"FROM User\",User.class).getResultList();",
        "§ }",
        "JTA transactions managed by container",
      ]},
      { title: "BEAN VALIDATION", lines: [
        "§ @NotNull @Size(min=2,max=50) String name;",
        "§ @Email String email;",
        "§ @Min(0) int age;",
        "§ @Valid in JAX-RS params triggers validation",
        "§ Validator v = Validation.buildDefaultValidatorFactory().getValidator();",
        "§ Set<ConstraintViolation<T>> errs = v.validate(obj);",
      ]},
      { title: "JMS MESSAGING", lines: [
        "§ @Inject @JMSConnectionFactory(\"jms/cf\")",
        "§ JMSContext ctx;",
        "§ @Resource(lookup=\"jms/queue\") Queue q;",
        "§ ctx.createProducer().send(q, \"message\");",
        "§ @MessageDriven(activationConfig={...})",
        "§ void onMessage(Message m){...}  // MDB",
      ]},
      { title: "EJB BASICS", lines: [
        "§ @Stateless  — no state, pooled",
        "§ @Stateful   — conversational state per client",
        "§ @Singleton  @Startup  — one instance",
        "Container manages transactions on @Stateless by default",
        "§ @TransactionAttribute(REQUIRED/REQUIRES_NEW/NOT_SUPPORTED)",
        "EJBs deprecated in favor of CDI for new projects",
      ]},
      { title: "INTERCEPTORS", lines: [
        "§ @Interceptor @LoggingBinding",
        "§ public class LoggingInterceptor{",
        "§   @AroundInvoke",
        "§   public Object log(InvocationContext ctx) throws Exception{",
        "§     log.info(\"Calling \"+ctx.getMethod().getName());",
        "§     return ctx.proceed();",
        "§   }",
        "§ }",
      ]},
      { title: "WEBSOCKET", lines: [
        "§ @ServerEndpoint(\"/ws/chat\")",
        "§ public class ChatEndpoint{",
        "§   @OnOpen void onOpen(Session s){}",
        "§   @OnMessage void onMsg(String msg, Session s){}",
        "§   @OnClose void onClose(Session s){}",
        "§ }",
        "Full-duplex communication over HTTP upgrade",
      ]},
      { title: "SECURITY", lines: [
        "§ @DeclareRoles({\"admin\",\"user\"})",
        "§ @RolesAllowed(\"admin\") on method or class",
        "§ @PermitAll / @DenyAll",
        "§ SecurityContext.isUserInRole(\"admin\")",
        "§ @WebSecurityDef (Soteria 2.0 — Jakarta Security)",
        "§ @LoginConfig(authMethod=\"FORM\") in web.xml",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "EJB must not be new'd directly — use @Inject",
        "CDI @RequestScoped doesn't work in async/scheduler",
        "JAX-RS providers need @Provider on the class",
        "persistence.xml required even with Spring-style JPA",
        "Application server version must match API version",
      ]},
    ],
  },

  {
    name: "Quarkus",
    subtitle: "Native · CDI · Panache · Reactive · Dev Mode",
    emoji: "⚡",
    accentHex: "#4695EB",
    sections: [
      { title: "SETUP & CLI", lines: [
        "§ quarkus create app com.example:my-app",
        "§   --extension=resteasy-reactive,hibernate-orm-panache",
        "§ mvn quarkus:dev  (live reload)",
        "§ mvn package -Dnative  (GraalVM native image)",
        "§ quarkus extension add smallrye-health",
      ]},
      { title: "REST ENDPOINTS", lines: [
        "§ @Path(\"/items\") @ApplicationScoped",
        "§ public class ItemResource {",
        "§   @GET @Produces(APPLICATION_JSON)",
        "§   public List<Item> list(){ return Item.listAll(); }",
        "§   @POST",
        "§   @Transactional",
        "§   public void create(Item i){ i.persist(); }",
        "§ }",
      ]},
      { title: "CDI BEANS", lines: [
        "§ @ApplicationScoped / @RequestScoped / @Singleton",
        "§ @Inject MyService svc;",
        "§ @ConfigProperty(name=\"greeting\") String greeting;",
        "§ @Produces  for custom beans",
        "CDI context is compile-time — no runtime scanning",
        "§ application.properties for all config",
      ]},
      { title: "PANACHE ENTITIES", lines: [
        "§ @Entity public class Item extends PanacheEntity{",
        "§   public String name;",
        "§   public static List<Item> findByName(String n){",
        "§     return list(\"name\",n);",
        "§   }",
        "§ }",
        "§ Item.findAll() / Item.count() / Item.listAll()",
      ]},
      { title: "REACTIVE PROGRAMMING", lines: [
        "§ @GET @Path(\"/{id}\")",
        "§ public Uni<Item> getItem(@PathParam Long id){",
        "§   return Item.findById(id);",
        "§ }",
        "§ Multi<Item> stream = Item.streamAll();",
        "§ <dep>quarkus-resteasy-reactive + hibernate-reactive-panache</dep>",
      ]},
      { title: "NATIVE IMAGE BUILD", lines: [
        "§ mvn package -Pnative  (requires GraalVM)",
        "§ mvn package -Pnative -Dquarkus.native.container-build=true",
        "Results in ./target/my-app-runner binary",
        "Startup <50ms; reduced memory footprint",
        "Limitations: reflection, dynamic proxies need registration",
        "§ @RegisterForReflection on needed classes",
      ]},
      { title: "CONFIGURATION", lines: [
        "§ # application.properties",
        "§ greeting=Hello",
        "§ %prod.greeting=Hi there",
        "§ @ConfigProperty(name=\"greeting\",defaultValue=\"Hey\")",
        "§ String greeting;",
        "Profiles: dev / test / prod auto-applied",
      ]},
      { title: "TESTING", lines: [
        "§ @QuarkusTest",
        "§ class ItemResourceTest {",
        "§   @Test void testList(){",
        "§     given().when().get(\"/items\")",
        "§       .then().statusCode(200);",
        "§   }",
        "§ }",
        "§ @QuarkusIntegrationTest for native testing",
      ]},
      { title: "HEALTH CHECKS", lines: [
        "§ <dep>quarkus-smallrye-health</dep>",
        "§ @Liveness / @Readiness",
        "§ public class MyCheck implements HealthCheck{",
        "§   public HealthCheckResponse call(){",
        "§     return HealthCheckResponse.up(\"db\");",
        "§   }",
        "§ }",
        "§ GET /q/health/live  /q/health/ready",
      ]},
      { title: "MESSAGING (KAFKA)", lines: [
        "§ @Incoming(\"prices\") void process(double price){}",
        "§ @Outgoing(\"prices-out\") Multi<Double> generate(){}",
        "§ <dep>quarkus-smallrye-reactive-messaging-kafka</dep>",
        "§ mp.messaging.incoming.prices.topic=prices-topic",
        "§ mp.messaging.incoming.prices.bootstrap.servers=...",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "CDI beans are resolved at build time — runtime classloading fails",
        "Native: reflection-heavy libs need @RegisterForReflection",
        "Hibernate Reactive: can't mix blocking and reactive sessions",
        "Dev mode hot reload works for config and code, not schema",
        "Extension versions must match Quarkus BOM version",
      ]},
    ],
  },

  {
    name: "Micronaut",
    subtitle: "AOT · DI · HTTP Client · GraalVM · Cloud",
    emoji: "🚀",
    accentHex: "#1F2937",
    sections: [
      { title: "SETUP & CLI", lines: [
        "§ mn create-app com.example.demo",
        "§   --features=data-jpa,security-jwt,graalvm",
        "§ ./mvnw mn:run  (or gradle mnRun)",
        "§ mn create-controller Hello --lang kotlin",
        "All compile-time DI — no Spring-like runtime scanning",
      ]},
      { title: "MAIN APPLICATION", lines: [
        "§ @MicronautApplication",
        "§ public class Application{",
        "§   public static void main(String[] a){",
        "§     Micronaut.run(Application.class, a);",
        "§   }",
        "§ }",
        "Starts in <100ms; tiny memory footprint",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ @Controller(\"/api/users\")",
        "§ public class UserController {",
        "§   @Get(\"/{id}\") @Produces(APPLICATION_JSON)",
        "§   public HttpResponse<User> get(@PathVariable Long id){...}",
        "§   @Post @Consumes(APPLICATION_JSON)",
        "§   public HttpResponse<User> create(@Body User u){...}",
        "§ }",
      ]},
      { title: "DEPENDENCY INJECTION", lines: [
        "§ @Singleton / @Prototype / @RequestScope",
        "§ @Inject / constructor injection",
        "§ @Requires(property=\"feature.x\") — conditional bean",
        "§ @Primary / @Secondary for disambiguation",
        "DI processed at compile time by annotation processor",
        "No reflection — AOT proxy generation",
      ]},
      { title: "CONFIGURATION", lines: [
        "§ application.yml  /  application-prod.yml",
        "§ @ConfigurationProperties(\"app\")",
        "§ public class AppConfig {",
        "§   private String name;  // maps to app.name",
        "§ }",
        "§ @Value(\"${greeting:Hello}\") String greeting;",
        "Env vars override properties automatically",
      ]},
      { title: "DATA REPOSITORIES", lines: [
        "§ @Repository",
        "§ interface UserRepo extends CrudRepository<User,Long>{",
        "§   List<User> findByEmail(String email);",
        "§   @Query(\"SELECT * FROM users WHERE active=true\")",
        "§   List<User> findActive();",
        "§ }",
        "Micronaut Data generates SQL at compile time",
      ]},
      { title: "AOP & INTERCEPTORS", lines: [
        "§ @Around",
        "§ @Type(LogInterceptor.class)",
        "§ public @interface Logged {}",
        "§ @Singleton @InterceptorBean(Logged.class)",
        "§ class LogInterceptor implements MethodInterceptor{",
        "§   Object intercept(MethodInvocationContext ctx){...}",
        "§ }",
      ]},
      { title: "DECLARATIVE HTTP CLIENT", lines: [
        "§ @Client(\"http://user-service\")",
        "§ interface UserClient {",
        "§   @Get(\"/users/{id}\")",
        "§   User getUser(@PathVariable Long id);",
        "§ }",
        "§ @Inject UserClient client;",
        "Compile-time generated — no reflection, native-compatible",
      ]},
      { title: "COMPILE-TIME DI / AOT", lines: [
        "Annotation processors run during compilation",
        "DI metadata baked into bytecode (not reflection)",
        "No runtime classpath scanning",
        "Much faster startup than Spring",
        "GraalVM native: mn:nativeCompile",
        "§ ./target/myapp  starts in <20ms",
      ]},
      { title: "TESTING", lines: [
        "§ @MicronautTest",
        "§ class UserControllerTest {",
        "§   @Inject @Client(\"/\") HttpClient client;",
        "§   @Test void testGet(){",
        "§     var resp = client.toBlocking().exchange(\"/users/1\");",
        "§     assertEquals(200, resp.status().getCode());",
        "§   }",
        "§ }",
      ]},
      { title: "COMMON ANNOTATIONS", lines: [
        "§ @MicronautApplication @Controller @Get @Post @Put @Delete",
        "§ @Singleton @Inject @Value @ConfigurationProperties",
        "§ @Client @Body @PathVariable @QueryValue",
        "§ @Introspected  // for reflection-less serialization",
        "§ @Requires  // conditional beans",
        "§ @Validated @NotNull @Min @Max — bean validation",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "@Introspected needed on data classes for native image",
        "Circular deps: Micronaut fails at compile time (good!)",
        "AOP only works on injected beans, not new'd instances",
        "HTTP client must match server's content-type exactly",
        "Config refresh requires restart — no @RefreshScope",
      ]},
    ],
  },
];
