import type { CheatSheetSpec } from "../tech-pdf-builder";

export const dotnetGoPhpRuby: CheatSheetSpec[] = [
  // ── .NET / C# ──────────────────────────────────────────────────────────────
  {
    name: "ASP.NET Core",
    subtitle: "Minimal API · Controllers · DI · Middleware · Auth",
    emoji: "🔷",
    accentHex: "#512BD4",
    sections: [
      { title: "SETUP & PROGRAM.CS", lines: [
        "§ var builder = WebApplication.CreateBuilder(args);",
        "§ builder.Services.AddControllers();",
        "§ builder.Services.AddEndpointsApiExplorer();",
        "§ builder.Services.AddSwaggerGen();",
        "§ var app = builder.Build();",
        "§ app.UseRouting(); app.MapControllers();",
        "§ app.Run();",
      ]},
      { title: "MINIMAL APIs", lines: [
        "§ app.MapGet('/users', async (UserRepo repo) =>",
        "§     await repo.GetAllAsync());",
        "§ app.MapPost('/users', async (User u, UserRepo r) => {",
        "§     await r.AddAsync(u);",
        "§     return Results.Created($'/users/{u.Id}', u);",
        "§ });",
        "§ app.MapPut('/users/{id}', ...).RequireAuthorization();",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ [ApiController] [Route(\"api/[controller]\")]",
        "§ public class UsersController : ControllerBase {",
        "§   [HttpGet] public async Task<IActionResult> GetAll()",
        "§     => Ok(await _svc.GetAllAsync());",
        "§   [HttpPost] public async Task<IActionResult> Create(CreateUserDto dto)",
        "§     => CreatedAtAction(nameof(GetById), new{id=...}, result);",
        "§ }",
      ]},
      { title: "ROUTING", lines: [
        "§ [Route(\"api/[controller]/[action]\")]",
        "§ [HttpGet(\"{id:int}\")]",
        "§ [HttpGet(\"{slug:regex(^[a-z-]+$)}\")]",
        "§ app.MapControllerRoute(\"default\", \"{controller=Home}/{action=Index}\")",
        "§ app.MapGet(\"/\", () => \"Hello World!\")",
      ]},
      { title: "DEPENDENCY INJECTION", lines: [
        "§ builder.Services.AddScoped<IUserService, UserService>();",
        "§ builder.Services.AddSingleton<ICache, MemoryCache>();",
        "§ builder.Services.AddTransient<IEmailSender, SmtpSender>();",
        "§ public class Ctrl(IUserService svc) { ... } // constructor inject",
        "Lifetimes: Transient(new each time), Scoped(per request), Singleton(app lifetime)",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ app.Use(async (ctx, next) => {",
        "§   // before",
        "§   await next(ctx);",
        "§   // after",
        "§ });",
        "§ app.UseExceptionHandler('/error');",
        "§ app.UseHsts(); app.UseHttpsRedirection();",
        "§ app.UseAuthentication(); app.UseAuthorization();",
        "Order matters: HTTPS → Routing → Auth → Endpoints",
      ]},
      { title: "CONFIGURATION", lines: [
        "§ var conn = builder.Configuration.GetConnectionString(\"Default\");",
        "§ var secret = builder.Configuration[\"Jwt:Secret\"];",
        "§ builder.Services.Configure<AppSettings>(",
        "§   builder.Configuration.GetSection(\"App\"));",
        "§ // appsettings.json overridden by appsettings.{env}.json",
        "§ // Environment variables override config files",
      ]},
      { title: "MODEL BINDING", lines: [
        "§ [FromRoute] int id",
        "§ [FromQuery] string? filter",
        "§ [FromBody] CreateUserDto dto",
        "§ [FromHeader(Name=\"X-Api-Key\")] string apiKey",
        "§ [FromForm] IFormFile file",
        "§ [FromServices] IService svc  // DI in action params",
      ]},
      { title: "AUTH & AUTHORIZATION", lines: [
        "§ builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)",
        "§   .AddJwtBearer(opts => { opts.TokenValidationParameters = ... });",
        "§ [Authorize]  [Authorize(Roles=\"Admin\")]",
        "§ [AllowAnonymous]",
        "§ builder.Services.AddAuthorization(opts =>",
        "§   opts.AddPolicy(\"Admin\", p => p.RequireRole(\"Admin\")));",
      ]},
      { title: "FILTERS", lines: [
        "§ [ServiceFilter(typeof(LoggingFilter))]",
        "§ public class LoggingFilter : IActionFilter {",
        "§   public void OnActionExecuting(ActionExecutingContext ctx) {}",
        "§   public void OnActionExecuted(ActionExecutedContext ctx) {}",
        "§ }",
        "Filter types: Authorization, Resource, Action, Exception, Result",
      ]},
      { title: "LOGGING", lines: [
        "§ private readonly ILogger<UsersController> _logger;",
        "§ _logger.LogInformation(\"Getting user {Id}\", id);",
        "§ _logger.LogError(ex, \"Failed to create user\");",
        "§ // appsettings.json:",
        "§ \"Logging\": { \"LogLevel\": { \"Default\": \"Information\" } }",
        "§ builder.Logging.AddConsole().AddDebug();",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "UseAuthentication() must come before UseAuthorization()",
        "AddDbContext() is Scoped — don't inject into Singleton",
        "async void in controllers hides exceptions",
        "Nullable annotations on DTOs prevent null surprises",
        "CORS must be configured before UseRouting()",
      ]},
    ],
  },

  {
    name: ".NET",
    subtitle: "C# · LINQ · Async/Await · Generics · NuGet",
    emoji: "🔷",
    accentHex: "#512BD4",
    sections: [
      { title: "SETUP & CLI", lines: [
        "§ dotnet new console -n MyApp",
        "§ dotnet new webapi -n MyApi",
        "§ dotnet add package Newtonsoft.Json",
        "§ dotnet build  /  dotnet run  /  dotnet test",
        "§ dotnet publish -c Release -o ./publish",
        "§ dotnet tool install -g dotnet-ef",
      ]},
      { title: "BASIC SYNTAX", lines: [
        "§ var name = \"Alice\";  // type inferred",
        "§ string? maybeNull = null;  // nullable reference type",
        "§ int[] numbers = { 1, 2, 3 };",
        "§ (string First, int Age) tuple = (\"Bob\", 30);",
        "§ Console.WriteLine($\"Hello {name}\");",
        "§ using var stream = File.OpenRead(\"f.txt\");  // auto-dispose",
      ]},
      { title: "DATA TYPES", lines: [
        "§ int long float double decimal bool char string",
        "§ byte short uint ulong",
        "§ DateTime DateTimeOffset TimeSpan",
        "§ Guid  (new Guid() or Guid.NewGuid())",
        "§ object? anything = null;",
        "§ dynamic d = \"hello\"; d = 42; // runtime type",
        "§ record Person(string Name, int Age); // immutable by default",
      ]},
      { title: "CLASSES & RECORDS", lines: [
        "§ public class User {",
        "§   public required string Name { get; init; }",
        "§   public int Age { get; set; }",
        "§ }",
        "§ // Record (value-equality, immutable):",
        "§ public record Product(string Name, decimal Price);",
        "§ var p2 = p1 with { Price = 19.99m }; // non-destructive update",
      ]},
      { title: "COLLECTIONS", lines: [
        "§ List<T>  Dictionary<K,V>  HashSet<T>",
        "§ Queue<T>  Stack<T>  LinkedList<T>",
        "§ IEnumerable<T>  IReadOnlyList<T>",
        "§ var list = new List<int> { 1, 2, 3 };",
        "§ var dict = new Dictionary<string,int> {{ \"a\",1 }};",
        "§ Span<T>  Memory<T>  — zero-copy slices",
      ]},
      { title: "LINQ", lines: [
        "§ var evens = numbers.Where(n => n % 2 == 0);",
        "§ var names = users.Select(u => u.Name);",
        "§ var sorted = users.OrderBy(u => u.Age).ThenBy(u => u.Name);",
        "§ var first = users.First(u => u.IsAdmin);",
        "§ var groups = users.GroupBy(u => u.Role);",
        "§ var flat = lists.SelectMany(l => l.Items);",
        "§ users.Any() / .All() / .Count() / .Sum() / .Average()",
      ]},
      { title: "ASYNC / AWAIT", lines: [
        "§ public async Task<User> GetUserAsync(int id)",
        "§ {",
        "§   var user = await _repo.FindAsync(id);",
        "§   return user ?? throw new NotFoundException();",
        "§ }",
        "§ var result = await Task.WhenAll(t1, t2, t3);",
        "§ await using var res = new AsyncResource();",
        "§ var cts = new CancellationTokenSource(timeout: TimeSpan.FromSeconds(5));",
      ]},
      { title: "EXCEPTION HANDLING", lines: [
        "§ try {",
        "§   var result = await GetDataAsync();",
        "§ } catch (HttpRequestException ex) when (ex.StatusCode == 404) {",
        "§   throw new NotFoundException(\"Resource not found\", ex);",
        "§ } finally {",
        "§   logger.LogDebug(\"Cleanup\");",
        "§ }",
        "§ throw new InvalidOperationException(\"msg\");",
      ]},
      { title: "GENERICS", lines: [
        "§ public T Find<T>(IEnumerable<T> items, Func<T, bool> predicate)",
        "§   => items.FirstOrDefault(predicate);",
        "§ public class Repository<T> where T : class, IEntity",
        "§ { ... }",
        "§ where T : struct  // value type constraint",
        "§ where T : new()   // must have parameterless ctor",
      ]},
      { title: "INTERFACES & INHERITANCE", lines: [
        "§ public interface IRepository<T> {",
        "§   Task<T?> FindAsync(int id);",
        "§   Task SaveAsync(T entity);",
        "§ }",
        "§ public class UserRepo : BaseRepo, IRepository<User> { ... }",
        "§ sealed  // prevent further inheritance",
        "§ abstract  // cannot be instantiated",
      ]},
      { title: "NULLABLE REFERENCE TYPES", lines: [
        "§ <Nullable>enable</Nullable>  // in .csproj",
        "§ string? nullableName = null;",
        "§ string nonNull = nullableName ?? throw new Exception();",
        "§ if (name is not null) { Console.Write(name.Length); }",
        "§ name?.Length  // null-conditional",
        "§ user!.Name    // null-forgiving (I know it's not null)",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "async void = unobserved exceptions — always use async Task",
        "LINQ is lazy — evaluate with .ToList()/.ToArray() when needed",
        "ConfigureAwait(false) in library code to avoid deadlocks",
        "String comparison: StringComparer.OrdinalIgnoreCase",
        "DateTime.Now is local; DateTime.UtcNow is UTC — prefer UTC",
      ]},
    ],
  },

  {
    name: "Entity Framework Core",
    subtitle: "DbContext · Migrations · LINQ · Relationships",
    emoji: "🗄️",
    accentHex: "#512BD4",
    sections: [
      { title: "SETUP & DBCONTEXT", lines: [
        "§ dotnet add package Microsoft.EntityFrameworkCore.SqlServer",
        "§ dotnet add package Microsoft.EntityFrameworkCore.Tools",
        "§ public class AppDbContext : DbContext {",
        "§   public DbSet<User> Users { get; set; }",
        "§   public DbSet<Order> Orders { get; set; }",
        "§   protected override void OnConfiguring(DbContextOptionsBuilder o)",
        "§     => o.UseSqlServer(connectionString);",
        "§ }",
      ]},
      { title: "ENTITY CONFIG", lines: [
        "§ // Data Annotations:",
        "§ [Table(\"users\")] [Key] [Required]",
        "§ [MaxLength(100)] [Column(\"full_name\")]",
        "§ // Fluent API (in OnModelCreating):",
        "§ modelBuilder.Entity<User>().HasKey(u => u.Id);",
        "§ modelBuilder.Entity<User>().Property(u => u.Email)",
        "§   .IsRequired().HasMaxLength(200).IsUnicode(false);",
      ]},
      { title: "CRUD OPERATIONS", lines: [
        "§ // Create:",
        "§ db.Users.Add(new User { Name = \"Alice\" });",
        "§ await db.SaveChangesAsync();",
        "§ // Read:",
        "§ var user = await db.Users.FindAsync(id);",
        "§ var users = await db.Users.Where(u => u.Active).ToListAsync();",
        "§ // Update: load → modify → SaveChanges()",
        "§ // Delete: Remove(entity) → SaveChanges()",
      ]},
      { title: "MIGRATIONS", lines: [
        "§ dotnet ef migrations add InitialCreate",
        "§ dotnet ef database update",
        "§ dotnet ef migrations remove  (last uncommitted)",
        "§ dotnet ef database update 20240101_AddEmail  (target)",
        "§ dotnet ef database update 0  (rollback all)",
        "§ dotnet ef migrations script  (generate SQL)",
      ]},
      { title: "LINQ QUERIES", lines: [
        "§ db.Users.Where(u => u.Role == \"Admin\")",
        "§   .OrderBy(u => u.Name)",
        "§   .Select(u => new { u.Id, u.Name })",
        "§   .Skip(20).Take(10)",
        "§   .ToListAsync()",
        "§ db.Users.AnyAsync(u => u.Email == email)",
        "§ db.Users.CountAsync(u => u.Active)",
      ]},
      { title: "RELATIONSHIPS", lines: [
        "§ // One-to-many:",
        "§ public class User { public ICollection<Order> Orders { get; set; } }",
        "§ public class Order { public int UserId { get; set; }",
        "§                      public User User { get; set; } }",
        "§ // Config:",
        "§ modelBuilder.Entity<Order>().HasOne(o => o.User)",
        "§   .WithMany(u => u.Orders).HasForeignKey(o => o.UserId);",
      ]},
      { title: "EAGER/LAZY/EXPLICIT LOADING", lines: [
        "§ // Eager:",
        "§ db.Orders.Include(o => o.User).Include(o => o.Items).ToList()",
        "§ // Lazy (requires proxies + virtual nav props):",
        "§ var user = await db.Users.FindAsync(id);",
        "§ var orders = user.Orders; // lazy loaded",
        "§ // Explicit:",
        "§ await db.Entry(user).Collection(u => u.Orders).LoadAsync();",
      ]},
      { title: "TRACKING vs NO-TRACKING", lines: [
        "§ // Tracked (default) — change detection runs on SaveChanges",
        "§ var user = await db.Users.FindAsync(id);",
        "§ user.Name = \"New\"; await db.SaveChangesAsync(); // auto-UPDATE",
        "§ // No-tracking (read-only, faster):",
        "§ db.Users.AsNoTracking().Where(u => u.Active).ToListAsync()",
        "Use AsNoTracking() for pure read operations",
      ]},
      { title: "TRANSACTIONS", lines: [
        "§ using var tx = await db.Database.BeginTransactionAsync();",
        "§ try {",
        "§   await db.SaveChangesAsync();",
        "§   await db.SaveChangesAsync(); // second operation",
        "§   await tx.CommitAsync();",
        "§ } catch { await tx.RollbackAsync(); throw; }",
        "§ // SaveChanges is a single implicit transaction",
      ]},
      { title: "RAW SQL", lines: [
        "§ var users = db.Users.FromSqlRaw(",
        "§   \"SELECT * FROM users WHERE status = {0}\", status);",
        "§ db.Database.ExecuteSqlRaw(",
        "§   \"UPDATE users SET active = 1 WHERE id = {0}\", id);",
        "§ // Interpolated (parameterized automatically):",
        "§ db.Users.FromSqlInterpolated($\"SELECT * FROM users WHERE id={id}\");",
      ]},
      { title: "COMMON ANNOTATIONS", lines: [
        "§ [Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]",
        "§ [Required] [MaxLength(200)] [Column(\"col_name\")]",
        "§ [Table(\"table_name\")] [Index(nameof(Email), IsUnique=true)]",
        "§ [NotMapped]  // exclude property from DB",
        "§ [Timestamp]  // optimistic concurrency token",
        "§ [ForeignKey(nameof(UserId))]",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "DbContext is not thread-safe — one per request (Scoped)",
        "N+1 queries — always Include() navigation properties",
        "Mixing tracked and untracked entities causes conflicts",
        "Cascade delete enabled by default for required relationships",
        "Complex queries: check generated SQL with .ToQueryString()",
      ]},
    ],
  },

  {
    name: "Blazor",
    subtitle: "Components · Data Binding · Routing · JS Interop",
    emoji: "🔷",
    accentHex: "#512BD4",
    sections: [
      { title: "SETUP", lines: [
        "§ dotnet new blazorserver -n MyApp",
        "§ dotnet new blazorwasm -n MyApp  (standalone)",
        "§ dotnet run",
        "§ Blazor Server: real-time SignalR connection",
        "§ Blazor WASM: runs .NET in browser via WebAssembly",
        "§ dotnet add package Microsoft.AspNetCore.Components.Web",
      ]},
      { title: "COMPONENTS", lines: [
        "§ @* Counter.razor *@",
        "§ <h1>Count: @count</h1>",
        "§ <button @onclick=\"Increment\">+</button>",
        "§ @code {",
        "§   private int count = 0;",
        "§   private void Increment() => count++;",
        "§ }",
      ]},
      { title: "DATA BINDING", lines: [
        "§ <input @bind=\"name\" />         // two-way binding",
        "§ <input @bind-value=\"name\"",
        "§        @bind-value:event=\"oninput\" />",
        "§ <p>@name.ToUpper()</p>         // one-way from C# to HTML",
        "§ @bind:format=\"yyyy-MM-dd\"",
        "§ <select @bind=\"selectedValue\">",
        "§   @foreach (var o in options) { <option>@o</option> }",
        "§ </select>",
      ]},
      { title: "ROUTING", lines: [
        "§ @page \"/counter\"",
        "§ @page \"/counter/{StartCount:int}\"",
        "§ [Parameter] public int StartCount { get; set; }",
        "§ <NavLink href=\"/counter\" Match=NavLinkMatch.All>Counter</NavLink>",
        "§ @inject NavigationManager Nav",
        "§ Nav.NavigateTo(\"/home\")",
        "§ Nav.Uri  // current URL",
      ]},
      { title: "PARAMETERS & CASCADING", lines: [
        "§ @* Child.razor *@",
        "§ [Parameter] public string Title { get; set; }",
        "§ [Parameter] public EventCallback<int> OnChange { get; set; }",
        "§ [CascadingParameter] public MyTheme Theme { get; set; }",
        "§ @* Parent usage *@",
        "§ <Child Title=\"Hello\" OnChange=\"HandleChange\" />",
        "§ <CascadingValue Value=\"theme\"><Child /></CascadingValue>",
      ]},
      { title: "EVENT HANDLING", lines: [
        "§ <button @onclick=\"HandleClick\">Click</button>",
        "§ <button @onclick=\"() => count++\">Add</button>",
        "§ <button @onclick=\"@(e => HandleClick(e))\">Click</button>",
        "§ private async Task HandleClick(MouseEventArgs e) {",
        "§   await JS.InvokeVoidAsync(\"alert\", \"clicked!\");",
        "§ }",
        "§ @onfocus @oninput @onkeydown @onsubmit",
      ]},
      { title: "LIFECYCLE METHODS", lines: [
        "§ protected override void OnInitialized()",
        "§ protected override async Task OnInitializedAsync()",
        "§ protected override void OnParametersSet()",
        "§ protected override async Task OnParametersSetAsync()",
        "§ protected override void OnAfterRender(bool firstRender)",
        "§ protected override bool ShouldRender() => canRender;",
        "§ public void Dispose() { ... }  // IDisposable",
      ]},
      { title: "DEPENDENCY INJECTION", lines: [
        "§ @inject IHttpClientFactory HttpFactory",
        "§ @inject NavigationManager Nav",
        "§ @inject IJSRuntime JS",
        "§ // In Program.cs:",
        "§ builder.Services.AddScoped<WeatherService>();",
        "§ builder.Services.AddHttpClient<ApiClient>(",
        "§   c => c.BaseAddress = new Uri(\"https://api.myapp.com\"));",
      ]},
      { title: "JS INTEROP", lines: [
        "§ @inject IJSRuntime JS",
        "§ await JS.InvokeVoidAsync(\"console.log\", \"Hello from .NET\");",
        "§ var width = await JS.InvokeAsync<int>(\"getWindowWidth\");",
        "§ // JS calling .NET:",
        "§ [JSInvokable]",
        "§ public static string GetData() => \"from .NET\";",
        "§ // In JS: DotNet.invokeMethodAsync('MyApp','GetData')",
      ]},
      { title: "FORMS & VALIDATION", lines: [
        "§ <EditForm Model=\"user\" OnValidSubmit=\"HandleSubmit\">",
        "§   <DataAnnotationsValidator />",
        "§   <ValidationSummary />",
        "§   <InputText @bind-Value=\"user.Name\" />",
        "§   <ValidationMessage For=\"() => user.Name\" />",
        "§   <button type=\"submit\">Save</button>",
        "§ </EditForm>",
        "§ [Required][MaxLength(50)] public string Name { get; set; }",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Server-side Blazor: network latency on every interaction",
        "Blazor WASM: initial load slow (download .NET runtime)",
        "StateHasChanged() needed for external state changes",
        "Don't use @onclick on non-Blazor elements without @onclick:stopPropagation",
        "IDisposable on components that subscribe to events",
      ]},
    ],
  },

  // ── Go Backends ─────────────────────────────────────────────────────────────
  {
    name: "Gin",
    subtitle: "Routing · Middleware · Binding · JSON",
    emoji: "🍸",
    accentHex: "#00ACD7",
    sections: [
      { title: "SETUP & ROUTER", lines: [
        "§ go get github.com/gin-gonic/gin",
        "§ r := gin.Default()  // includes Logger+Recovery",
        "§ r.Run(\":8080\")      // listen and serve",
        "§ r := gin.New()      // bare router (no middleware)",
        "§ gin.SetMode(gin.ReleaseMode) // production",
      ]},
      { title: "ROUTES & HTTP METHODS", lines: [
        "§ r.GET(\"/users\", listUsers)",
        "§ r.POST(\"/users\", createUser)",
        "§ r.PUT(\"/users/:id\", updateUser)",
        "§ r.DELETE(\"/users/:id\", deleteUser)",
        "§ r.PATCH  r.HEAD  r.OPTIONS  r.Any",
        "§ r.NoRoute(func(c *gin.Context){ c.JSON(404, gin.H{\"error\":\"not found\"}) })",
      ]},
      { title: "ROUTE PARAMS & QUERY", lines: [
        "§ r.GET(\"/users/:id\", func(c *gin.Context) {",
        "§   id := c.Param(\"id\")",
        "§   page := c.DefaultQuery(\"page\", \"1\")",
        "§   search := c.Query(\"q\")",
        "§   c.JSON(200, gin.H{\"id\": id, \"page\": page})",
        "§ })",
        "§ c.QueryArray(\"ids\")  // repeated ?ids=1&ids=2",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ // Global:",
        "§ r.Use(gin.Logger(), gin.Recovery())",
        "§ r.Use(CorsMiddleware())",
        "§ // Group-level:",
        "§ api := r.Group(\"/api\", AuthMiddleware())",
        "§ // Custom:",
        "§ func AuthMiddleware() gin.HandlerFunc {",
        "§   return func(c *gin.Context) {",
        "§     if !isValid(c) { c.AbortWithStatus(401); return }",
        "§     c.Next()",
        "§   }",
        "§ }",
      ]},
      { title: "REQUEST BINDING", lines: [
        "§ // Bind JSON body:",
        "§ var req CreateUserReq",
        "§ if err := c.ShouldBindJSON(&req); err != nil {",
        "§   c.JSON(400, gin.H{\"error\": err.Error()})",
        "§   return",
        "§ }",
        "§ // Bind query params:",
        "§ c.ShouldBindQuery(&params)",
        "§ // Bind form:",
        "§ c.ShouldBind(&form)",
        "§ // With validation tags: `binding:\"required,email\"`",
      ]},
      { title: "RESPONSE RENDERING", lines: [
        "§ c.JSON(200, gin.H{\"users\": users})",
        "§ c.JSON(http.StatusCreated, newUser)",
        "§ c.String(200, \"Hello %s\", name)",
        "§ c.XML(200, xmlData)",
        "§ c.File(\"./static/index.html\")",
        "§ c.Stream(200, func(w io.Writer) bool { ... })",
        "§ c.Status(204)  // no body",
      ]},
      { title: "GROUPING ROUTES", lines: [
        "§ v1 := r.Group(\"/v1\")",
        "§ {",
        "§   v1.GET(\"/users\", ...)   // /v1/users",
        "§   v1.POST(\"/users\", ...)",
        "§   admin := v1.Group(\"/admin\", AdminOnly())",
        "§   admin.GET(\"/stats\", ...)  // /v1/admin/stats",
        "§ }",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ c.Error(err)  // attach error to context",
        "§ c.AbortWithStatusJSON(401, gin.H{\"error\": \"unauthorized\"})",
        "§ c.AbortWithStatus(403)",
        "§ // Global error handler:",
        "§ r.Use(func(c *gin.Context) {",
        "§   c.Next()",
        "§   for _, e := range c.Errors { log.Error(e) }",
        "§ })",
      ]},
      { title: "VALIDATION", lines: [
        "§ type CreateUser struct {",
        "§   Name  string `json:\"name\" binding:\"required,min=2,max=50\"`",
        "§   Email string `json:\"email\" binding:\"required,email\"`",
        "§   Age   int    `json:\"age\" binding:\"gte=0,lte=130\"`",
        "§ }",
        "§ // Custom validator:",
        "§ v, _ := binding.Validator.Engine().(*validator.Validate)",
        "§ v.RegisterValidation(\"isbn\", validateISBN)",
      ]},
      { title: "COMMON CONTEXT METHODS", lines: [
        "§ c.Set(\"user\", user)       // set value in context",
        "§ c.Get(\"user\")             // retrieve (returns any, bool)",
        "§ c.MustGet(\"user\")         // panics if not found",
        "§ c.Request                  // *http.Request",
        "§ c.Writer                   // http.ResponseWriter",
        "§ c.ClientIP()               // client IP",
        "§ c.GetHeader(\"Authorization\")",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "c.JSON() after c.Abort() still writes — always return after Abort",
        "Bind() calls c.Abort on failure; ShouldBind() doesn't",
        "gin.H is just map[string]any",
        "ReleaseMode silences debug logs — enable in production",
        "Goroutines in handlers: copy context values before starting",
      ]},
    ],
  },

  {
    name: "Echo",
    subtitle: "Routing · Middleware · Binding · Groups",
    emoji: "🔊",
    accentHex: "#00ACD7",
    sections: [
      { title: "SETUP & INSTANCE", lines: [
        "§ go get github.com/labstack/echo/v4",
        "§ e := echo.New()",
        "§ e.Use(middleware.Logger())",
        "§ e.Use(middleware.Recover())",
        "§ e.Start(\":8080\")",
        "§ e.Logger.SetLevel(log.DEBUG)",
      ]},
      { title: "ROUTING", lines: [
        "§ e.GET(\"/users\", listUsers)",
        "§ e.POST(\"/users\", createUser)",
        "§ e.PUT(\"/users/:id\", updateUser)",
        "§ e.DELETE(\"/users/:id\", deleteUser)",
        "§ e.Static(\"/static\", \"public\")",
        "§ e.File(\"/favicon.ico\", \"public/favicon.ico\")",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ e.Use(middleware.Logger())",
        "§ e.Use(middleware.Recover())",
        "§ e.Use(middleware.CORS())",
        "§ e.Use(middleware.RateLimiter(...))",
        "§ // Custom:",
        "§ e.Use(func(next echo.HandlerFunc) echo.HandlerFunc {",
        "§   return func(c echo.Context) error {",
        "§     // before",
        "§     return next(c)",
        "§   }",
        "§ })",
      ]},
      { title: "REQUEST & RESPONSE", lines: [
        "§ c.Param(\"id\")           // route param",
        "§ c.QueryParam(\"page\")    // query string",
        "§ c.FormValue(\"name\")     // form field",
        "§ return c.JSON(200, user)",
        "§ return c.String(200, \"Hello\")",
        "§ return c.XML(200, xmlData)",
        "§ return c.File(\"index.html\")",
        "§ return c.Redirect(301, \"/new\")",
      ]},
      { title: "BINDING & VALIDATION", lines: [
        "§ type CreateUserReq struct {",
        "§   Name  string `json:\"name\" validate:\"required\"`",
        "§   Email string `json:\"email\" validate:\"required,email\"`",
        "§ }",
        "§ var req CreateUserReq",
        "§ if err := c.Bind(&req); err != nil { return err }",
        "§ if err := c.Validate(&req); err != nil { return err }",
        "§ e.Validator = &CustomValidator{v: validator.New()}",
      ]},
      { title: "GROUPING", lines: [
        "§ g := e.Group(\"/api/v1\")",
        "§ g.Use(JWTMiddleware())",
        "§ g.GET(\"/users\", listUsers)    // /api/v1/users",
        "§ admin := g.Group(\"/admin\")",
        "§ admin.Use(AdminOnly())",
        "§ admin.GET(\"/stats\", getStats) // /api/v1/admin/stats",
      ]},
      { title: "STATIC FILES", lines: [
        "§ e.Static(\"/static\", \"assets\")",
        "§ e.StaticFS(\"/static\", echo.MustSubFS(os.DirFS(\".\"), \"assets\"))",
        "§ // Serve index.html for SPA:",
        "§ e.GET(\"/*\", func(c echo.Context) error {",
        "§   return c.File(\"public/index.html\")",
        "§ })",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ e.HTTPErrorHandler = func(err error, c echo.Context) {",
        "§   code := http.StatusInternalServerError",
        "§   if he, ok := err.(*echo.HTTPError); ok { code = he.Code }",
        "§   c.JSON(code, map[string]string{\"error\": err.Error()})",
        "§ }",
        "§ return echo.NewHTTPError(http.StatusBadRequest, \"invalid input\")",
      ]},
      { title: "COMMON CONTEXT METHODS", lines: [
        "§ c.Set(\"user\", user)   // store in context",
        "§ c.Get(\"user\")        // retrieve value",
        "§ c.Request()           // *http.Request",
        "§ c.Response()         // *echo.Response",
        "§ c.RealIP()           // client IP respecting X-Real-IP",
        "§ c.Logger()           // scoped logger",
        "§ c.IsWebSocket()      // check WebSocket upgrade",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Return errors from handlers — don't just log and continue",
        "Validator must be set on echo instance before validation",
        "echo.HTTPError message is returned to client — don't expose internals",
        "Middleware order matters — Logger before Recover",
        "Use c.Set/c.Get for request-scoped data, not global vars",
      ]},
    ],
  },

  {
    name: "Fiber",
    subtitle: "Express-style · Fast · Middleware · WebSockets",
    emoji: "⚡",
    accentHex: "#00ACD7",
    sections: [
      { title: "SETUP & APP", lines: [
        "§ go get github.com/gofiber/fiber/v2",
        "§ app := fiber.New(fiber.Config{",
        "§   Prefork: true,           // multi-process",
        "§   BodyLimit: 4 * 1024 * 1024, // 4MB",
        "§ })",
        "§ app.Listen(\":3000\")",
        "§ app.ListenTLS(\":443\", \"cert.pem\", \"key.pem\")",
      ]},
      { title: "ROUTING", lines: [
        "§ app.Get(\"/users\", listUsers)",
        "§ app.Post(\"/users\", createUser)",
        "§ app.Put(\"/users/:id\", updateUser)",
        "§ app.Delete(\"/users/:id\", deleteUser)",
        "§ app.All(\"/debug\", handler)  // all methods",
        "§ app.Use(handler)  // matches all paths",
      ]},
      { title: "CTX METHODS", lines: [
        "§ c.Params(\"id\")           // route param",
        "§ c.Query(\"page\", \"1\")    // query string with default",
        "§ c.Body()                 // raw request body",
        "§ c.BodyParser(&req)       // unmarshal body to struct",
        "§ return c.JSON(data)      // send JSON",
        "§ return c.Status(201).JSON(data)",
        "§ return c.SendString(\"text\")",
        "§ return c.SendFile(\"./file.pdf\")",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ import 'github.com/gofiber/fiber/v2/middleware/logger'",
        "§ app.Use(logger.New())",
        "§ app.Use(recover.New())",
        "§ app.Use(cors.New(cors.Config{AllowOrigins: \"*\"}))",
        "§ // Custom:",
        "§ app.Use(func(c *fiber.Ctx) error {",
        "§   c.Locals(\"requestID\", uuid.New())",
        "§   return c.Next()",
        "§ })",
      ]},
      { title: "GROUPING", lines: [
        "§ api := app.Group(\"/api\")",
        "§ v1 := api.Group(\"/v1\", JWTMiddleware())",
        "§ v1.Get(\"/users\", listUsers)",
        "§ admin := v1.Group(\"/admin\", AdminOnly())",
        "§ admin.Get(\"/stats\", getStats)",
        "Group middleware applies to all routes in group",
      ]},
      { title: "STATIC FILES", lines: [
        "§ app.Static(\"/\", \"./public\")",
        "§ app.Static(\"/public\", \"./public\", fiber.Static{",
        "§   Compress: true,",
        "§   CacheDuration: 10 * time.Second,",
        "§   MaxAge: 3600,",
        "§ })",
        "§ // SPA fallback:",
        "§ app.Static(\"*\", \"./public/index.html\")",
      ]},
      { title: "BODY PARSING", lines: [
        "§ type User struct {",
        "§   Name string `json:\"name\" validate:\"required\"`",
        "§ }",
        "§ var u User",
        "§ if err := c.BodyParser(&u); err != nil {",
        "§   return c.Status(400).JSON(fiber.Map{\"error\": err.Error()})",
        "§ }",
        "§ // File upload:",
        "§ file, _ := c.FormFile(\"document\")",
        "§ c.SaveFile(file, \"uploads/\"+file.Filename)",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ app.Use(func(c *fiber.Ctx) error {",
        "§   err := c.Next()",
        "§   if err != nil {",
        "§     code := fiber.StatusInternalServerError",
        "§     if e, ok := err.(*fiber.Error); ok { code = e.Code }",
        "§     return c.Status(code).JSON(fiber.Map{\"error\": err.Error()})",
        "§   }",
        "§   return nil",
        "§ })",
        "§ return fiber.NewError(fiber.StatusBadRequest, \"invalid\")",
      ]},
      { title: "COMMON CTX METHODS", lines: [
        "§ c.Locals(\"key\", val)   // request-scoped storage",
        "§ c.Locals(\"key\")        // retrieve",
        "§ c.IP()                  // client IP",
        "§ c.Get(\"Authorization\") // request header",
        "§ c.Set(\"X-Custom\", val) // response header",
        "§ c.Method()             // GET POST etc",
        "§ c.Path()               // URL path",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Fiber uses fasthttp — net/http handlers incompatible",
        "c.Body() returns []byte, not io.Reader — save before parsing",
        "Prefork mode: goroutines/channels don't work across processes",
        "c.Locals() cleared after request — don't use as global cache",
        "JSON tags required on structs — unexported fields ignored",
      ]},
    ],
  },

  {
    name: "Chi",
    subtitle: "Lightweight · Middleware · Router · RESTful",
    emoji: "🐿️",
    accentHex: "#00ACD7",
    sections: [
      { title: "SETUP & ROUTER", lines: [
        "§ go get github.com/go-chi/chi/v5",
        "§ r := chi.NewRouter()",
        "§ r.Use(middleware.Logger)",
        "§ r.Use(middleware.Recoverer)",
        "§ http.ListenAndServe(\":3000\", r)",
      ]},
      { title: "ROUTING", lines: [
        "§ r.Get(\"/users\", listUsers)",
        "§ r.Post(\"/users\", createUser)",
        "§ r.Put(\"/users/{id}\", updateUser)",
        "§ r.Delete(\"/users/{id}\", deleteUser)",
        "§ r.Patch  r.Head  r.Options",
        "§ r.HandleFunc(\"/path\", handler)  // net/http compat",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ r.Use(middleware.RequestID)",
        "§ r.Use(middleware.RealIP)",
        "§ r.Use(middleware.Logger)",
        "§ r.Use(middleware.Recoverer)",
        "§ r.Use(middleware.Compress(5))",
        "§ r.Use(middleware.Timeout(60 * time.Second))",
        "§ r.Use(middleware.Throttle(100))",
      ]},
      { title: "ROUTE GROUPS & MOUNTING", lines: [
        "§ r.Route(\"/api\", func(r chi.Router) {",
        "§   r.Use(JWTMiddleware)",
        "§   r.Get(\"/users\", listUsers)",
        "§   r.Post(\"/users\", createUser)",
        "§ })",
        "§ // Mount sub-router:",
        "§ r.Mount(\"/admin\", adminRouter())",
      ]},
      { title: "URL PARAMS", lines: [
        "§ func getUser(w http.ResponseWriter, r *http.Request) {",
        "§   id := chi.URLParam(r, \"id\")",
        "§   // or from context:",
        "§   id := r.Context().Value(chi.RouteCtxKey).(*chi.Context).URLParam(\"id\")",
        "§   w.Header().Set(\"Content-Type\", \"application/json\")",
        "§   json.NewEncoder(w).Encode(user)",
        "§ }",
      ]},
      { title: "SUB-ROUTERS", lines: [
        "§ func usersRouter() http.Handler {",
        "§   r := chi.NewRouter()",
        "§   r.Use(AuthRequired)",
        "§   r.Get(\"/\", listUsers)",
        "§   r.Post(\"/\", createUser)",
        "§   r.Route(\"/{id}\", func(r chi.Router) {",
        "§     r.Use(UserCtx)",
        "§     r.Get(\"/\", getUser)",
        "§     r.Put(\"/\", updateUser)",
        "§   })",
        "§   return r",
        "§ }",
      ]},
      { title: "RESTFUL PATTERN", lines: [
        "§ r.Route(\"/articles/{id}\", func(r chi.Router) {",
        "§   r.Use(ArticleCtx)  // load article from DB",
        "§   r.Get(\"/\", getArticle)",
        "§   r.Put(\"/\", updateArticle)",
        "§   r.Delete(\"/\", deleteArticle)",
        "§ })",
        "§ // ArticleCtx middleware sets article in context",
        "§ ctx := context.WithValue(r.Context(), articleKey, article)",
      ]},
      { title: "BUILT-IN MIDDLEWARE", lines: [
        "§ middleware.RequestID   // adds X-Request-Id header",
        "§ middleware.RealIP      // sets RemoteAddr to X-Real-IP",
        "§ middleware.Logger      // structured request logging",
        "§ middleware.Recoverer   // recover from panics",
        "§ middleware.Compress(5) // gzip (level 5)",
        "§ middleware.Timeout(t)  // request timeout",
        "§ middleware.CleanPath   // normalize URL paths",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Chi uses {param} not :param style",
        "Wildcard: r.Get(\"/files/*\", serveFiles)",
        "Context values require typed keys to avoid collisions",
        "r.Mount strips path prefix from sub-router",
        "middleware.Logger prints to stdout — use custom for structured logs",
      ]},
    ],
  },

  // ── PHP ─────────────────────────────────────────────────────────────────────
  {
    name: "Laravel",
    subtitle: "Eloquent · Blade · Artisan · Middleware · Auth",
    emoji: "🎸",
    accentHex: "#FF2D20",
    sections: [
      { title: "SETUP & ARTISAN", lines: [
        "§ composer create-project laravel/laravel myapp",
        "§ php artisan serve",
        "§ php artisan make:controller UserController --resource",
        "§ php artisan make:model User -m  (with migration)",
        "§ php artisan migrate",
        "§ php artisan tinker  (REPL)",
      ]},
      { title: "ROUTING", lines: [
        "§ Route::get('/users', [UserController::class, 'index']);",
        "§ Route::post('/users', [UserController::class, 'store']);",
        "§ Route::apiResource('users', UserController::class);",
        "§ Route::get('/profile', fn() => view('profile'))->middleware('auth');",
        "§ Route::prefix('api')->group(fn() => { Route::get('/users',...); });",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ class UserController extends Controller {",
        "§   public function index() {",
        "§     return User::paginate(15);",
        "§   }",
        "§   public function store(StoreUserRequest $req) {",
        "§     $user = User::create($req->validated());",
        "§     return response()->json($user, 201);",
        "§   }",
        "§ }",
      ]},
      { title: "ELOQUENT ORM", lines: [
        "§ User::all();",
        "§ User::find(1);",
        "§ User::where('active', true)->orderBy('name')->get();",
        "§ User::firstOrCreate(['email' => $email], ['name' => $name]);",
        "§ $user->save(); / $user->delete();",
        "§ User::create(['name' => 'Alice']);  // mass assignment",
        "§ User::chunk(100, fn($users) => ...);  // batches",
      ]},
      { title: "MIGRATIONS", lines: [
        "§ Schema::create('users', function (Blueprint $table) {",
        "§   $table->id();",
        "§   $table->string('name');",
        "§   $table->string('email')->unique();",
        "§   $table->timestamps();",
        "§ });",
        "§ php artisan migrate  /  migrate:rollback  /  migrate:fresh",
      ]},
      { title: "BLADE TEMPLATES", lines: [
        "§ {{ $user->name }}  {!! $html !!}",
        "§ @if($user->isAdmin()) Admin @endif",
        "§ @foreach($users as $user) {{ $user->name }} @endforeach",
        "§ @extends('layouts.app')",
        "§ @section('content') ... @endsection",
        "§ @component('alert', ['type' => 'error'])",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ php artisan make:middleware EnsureUserIsAdmin",
        "§ public function handle(Request $req, Closure $next) {",
        "§   if (!$req->user()->isAdmin()) abort(403);",
        "§   return $next($req);",
        "§ }",
        "§ // Register in app/Http/Kernel.php or bootstrap/app.php",
        "§ Route::middleware(['auth', 'admin'])->group(...);",
      ]},
      { title: "VALIDATION", lines: [
        "§ $validated = $request->validate([",
        "§   'name' => 'required|string|max:255',",
        "§   'email' => 'required|email|unique:users',",
        "§   'age' => 'nullable|integer|min:0',",
        "§ ]);",
        "§ // Form Request:",
        "§ class StoreUserRequest extends FormRequest {",
        "§   public function rules(): array { ... }",
        "§ }",
      ]},
      { title: "ELOQUENT RELATIONSHIPS", lines: [
        "§ // User.php:",
        "§ public function orders(): HasMany {",
        "§   return $this->hasMany(Order::class);",
        "§ }",
        "§ public function role(): BelongsTo {",
        "§   return $this->belongsTo(Role::class);",
        "§ }",
        "§ // Eager loading:",
        "§ User::with('orders', 'role')->get();",
      ]},
      { title: "QUERY BUILDER", lines: [
        "§ DB::table('users')",
        "§   ->select('name', 'email')",
        "§   ->where('active', true)",
        "§   ->orderBy('name')",
        "§   ->paginate(15);",
        "§ DB::table('users')->insert(['name'=>'Alice']);",
        "§ DB::transaction(function() { ... });",
      ]},
      { title: "COMMON ARTISAN COMMANDS", lines: [
        "§ php artisan make:model/controller/middleware/job/event/listener",
        "§ php artisan route:list  /  cache:clear  /  config:cache",
        "§ php artisan queue:work  /  queue:listen",
        "§ php artisan storage:link  /  key:generate",
        "§ php artisan schedule:work  (runs scheduler locally)",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Mass assignment: $fillable or $guarded on model",
        "N+1 queries: always use with() for relationships",
        "APP_KEY required — generate with artisan key:generate",
        "Storage link needed for public disk file access",
        "Eloquent soft deletes need SoftDeletes trait + deleted_at column",
      ]},
    ],
  },

  {
    name: "Symfony",
    subtitle: "Components · Doctrine · DI · Console · Twig",
    emoji: "🎻",
    accentHex: "#000000",
    sections: [
      { title: "SETUP & CONSOLE", lines: [
        "§ composer create-project symfony/skeleton myapp",
        "§ composer require symfony/webapp-pack",
        "§ php bin/console server:start",
        "§ php bin/console make:controller User",
        "§ php bin/console doctrine:migrations:migrate",
        "§ php bin/console debug:router",
      ]},
      { title: "ROUTING", lines: [
        "§ // PHP Attribute style:",
        "§ #[Route('/users', name: 'user_list', methods: ['GET'])]",
        "§ public function index(): Response { ... }",
        "§ // YAML (config/routes.yaml):",
        "§ user_list:",
        "§   path: /users",
        "§   controller: App\\Controller\\UserController::index",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ class UserController extends AbstractController {",
        "§   #[Route('/users', methods:['GET'])]",
        "§   public function index(UserRepository $repo): Response {",
        "§     return $this->json($repo->findAll());",
        "§   }",
        "§   #[Route('/users/{id}', methods:['GET'])]",
        "§   public function show(User $user): Response {",
        "§     return $this->json($user);  // ParamConverter",
        "§   }",
        "§ }",
      ]},
      { title: "TWIG TEMPLATES", lines: [
        "§ return $this->render('user/index.html.twig', ['users'=>$users]);",
        "§ {{ user.name }}  {# comment #}",
        "§ {% for u in users %}{{ u.name }}{% endfor %}",
        "§ {% if user.admin %}Admin{% endif %}",
        "§ {% extends 'base.html.twig' %}",
        "§ {% block body %}...{% endblock %}",
        "§ {{ path('user_list') }}",
      ]},
      { title: "DOCTRINE ORM", lines: [
        "§ #[ORM\\Entity] #[ORM\\Table(name:'users')]",
        "§ class User {",
        "§   #[ORM\\Id] #[ORM\\GeneratedValue]",
        "§   #[ORM\\Column] private ?int $id = null;",
        "§   #[ORM\\Column(length: 180, unique: true)]",
        "§   private string $email;",
        "§ }",
        "§ $em->persist($user); $em->flush();",
        "§ $repo->find(1) / $repo->findBy(['active'=>true])",
      ]},
      { title: "SERVICES & DI", lines: [
        "§ // Auto-wiring: constructor injection works automatically",
        "§ public function __construct(",
        "§   private readonly UserRepository $repo,",
        "§   private readonly MailerInterface $mailer",
        "§ ) {}",
        "§ // config/services.yaml:",
        "§ services: App\\: resource: '../src/'",
        "§ # Everything in src/ is auto-registered as a service",
      ]},
      { title: "FORMS", lines: [
        "§ $form = $this->createForm(UserType::class, $user);",
        "§ $form->handleRequest($request);",
        "§ if ($form->isSubmitted() && $form->isValid()) {",
        "§   $em->persist($user); $em->flush();",
        "§   return $this->redirectToRoute('user_list');",
        "§ }",
        "§ return $this->render('user/edit.html.twig', ['form'=>$form]);",
      ]},
      { title: "VALIDATION", lines: [
        "§ use Symfony\\Component\\Validator\\Constraints as Assert;",
        "§ #[Assert\\NotBlank]",
        "§ #[Assert\\Email]",
        "§ private string $email;",
        "§ $errors = $validator->validate($user);",
        "§ if (count($errors) > 0) throw new ValidationFailedException($user, $errors);",
        "§ // Form validation is automatic via FormType",
      ]},
      { title: "SECURITY", lines: [
        "§ // security.yaml:",
        "§ firewalls:",
        "§   main:",
        "§     stateless: true",
        "§     jwt: ~   # LexikJWTAuthBundle",
        "§ access_control:",
        "§   - { path: ^/api/admin, roles: ROLE_ADMIN }",
        "§ // In controller:",
        "§ $this->denyAccessUnlessGranted('ROLE_ADMIN');",
      ]},
      { title: "CONSOLE COMMANDS", lines: [
        "§ #[AsCommand(name: 'app:send-emails')]",
        "§ class SendEmailsCommand extends Command {",
        "§   protected function execute(InputInterface $in, OutputInterface $out): int {",
        "§     $out->writeln('Sending...');",
        "§     return Command::SUCCESS;",
        "§   }",
        "§ }",
        "§ php bin/console app:send-emails",
      ]},
      { title: "COMMON COMMANDS", lines: [
        "§ php bin/console debug:container  // list services",
        "§ php bin/console debug:router     // list routes",
        "§ php bin/console cache:clear",
        "§ php bin/console make:entity/controller/form",
        "§ php bin/console doctrine:database:create",
        "§ php bin/console doctrine:migrations:diff  // generate migration",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Services are private by default — inject, don't fetch from container",
        "Auto-wiring uses type-hints: same type = one service conflict",
        "Doctrine: flush() is needed to persist to DB",
        "ParamConverter: {id} param auto-loads entity by ID",
        "Twig escaping: use |raw only for trusted HTML",
      ]},
    ],
  },

  {
    name: "CodeIgniter",
    subtitle: "MVC · ActiveRecord · Routing · Sessions",
    emoji: "🔥",
    accentHex: "#DD4814",
    sections: [
      { title: "SETUP & CONFIG", lines: [
        "§ composer create-project codeigniter4/appstarter myapp",
        "§ php spark serve",
        "§ .env: CI_ENVIRONMENT = development",
        "§ .env: database.default.hostname = localhost",
        "§ app/Config/Routes.php for routing configuration",
      ]},
      { title: "ROUTING", lines: [
        "§ $routes->get('/users', 'UserController::index');",
        "§ $routes->post('/users', 'UserController::create');",
        "§ $routes->resource('users');  // RESTful resource routes",
        "§ $routes->get('/users/(:num)', 'UserController::show/$1');",
        "§ $routes->group('api', function($routes) { ... });",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ class UserController extends BaseController {",
        "§   public function index(): string {",
        "§     $model = new UserModel();",
        "§     $data = ['users' => $model->findAll()];",
        "§     return view('users/index', $data);",
        "§   }",
        "§   public function show(int $id): ResponseInterface {",
        "§     return $this->response->setJSON(model(UserModel::class)->find($id));",
        "§   }",
        "§ }",
      ]},
      { title: "MODELS", lines: [
        "§ class UserModel extends Model {",
        "§   protected $table = 'users';",
        "§   protected $allowedFields = ['name', 'email'];",
        "§   protected $useTimestamps = true;",
        "§   protected $validationRules = ['email' => 'required|valid_email'];",
        "§ }",
        "§ $user = $model->find(1);",
        "§ $model->save(['name'=>'Alice','email'=>'a@b.com']);",
        "§ $model->where('active', 1)->findAll();",
      ]},
      { title: "VIEWS", lines: [
        "§ // In controller: return view('users/index', $data);",
        "§ <?= esc($user->name) ?>",
        "§ <?php foreach ($users as $user): ?>",
        "§   <li><?= esc($user->name) ?></li>",
        "§ <?php endforeach ?>",
        "§ <?= view('partials/header') ?>",
        "§ <?= form_open('users/create') ?>",
        "§ <?= form_input('name', '', ['class'=>'form-control']) ?>",
      ]},
      { title: "QUERY BUILDER", lines: [
        "§ $builder = $db->table('users');",
        "§ $query = $builder->select('name,email')",
        "§   ->where('active', 1)",
        "§   ->orderBy('name')",
        "§   ->get(10, 0);  // limit 10, offset 0",
        "§ $results = $query->getResultArray();",
        "§ $builder->insert(['name'=>'Alice','email'=>'a@b.com']);",
        "§ $db->transStart(); ... $db->transComplete();",
      ]},
      { title: "FORM VALIDATION", lines: [
        "§ $rules = [",
        "§   'name' => 'required|min_length[2]|max_length[100]',",
        "§   'email' => 'required|valid_email|is_unique[users.email]',",
        "§ ];",
        "§ if (!$this->validate($rules)) {",
        "§   return redirect()->back()->withInput()",
        "§     ->with('errors', $this->validator->getErrors());",
        "§ }",
      ]},
      { title: "LIBRARIES & HELPERS", lines: [
        "§ $email = \\Config\\Services::email();",
        "§ $email->setTo('a@b.com'); $email->send();",
        "§ // Load helper functions:",
        "§ helper(['url', 'form', 'text']);",
        "§ base_url('assets/css/main.css')",
        "§ site_url('users')  // includes index.php if needed",
      ]},
      { title: "SESSIONS", lines: [
        "§ $session = session();",
        "§ $session->set('user_id', $user->id);",
        "§ $session->get('user_id');",
        "§ $session->remove('user_id');",
        "§ $session->destroy();",
        "§ // Flash data (one-time):",
        "§ $session->setFlashdata('success', 'Saved!');",
        "§ $session->getFlashdata('success');",
      ]},
      { title: "COMMON HELPERS", lines: [
        "§ url_title($str)   // 'My Article' → 'my-article'",
        "§ word_wrap($str, 76)",
        "§ excerpt($str, $phrase, $radius)",
        "§ character_limiter($str, 100)",
        "§ number_to_currency($n, 'USD')",
        "§ php spark make:controller/model/migration/entity",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "$allowedFields prevents mass assignment vulnerabilities",
        "esc() everything from user input — prevent XSS",
        "CSRF protection enabled by default for POST requests",
        "Remove index.php from URL: configure RewriteBase in .htaccess",
        "Config files in app/Config — don't edit vendor files",
      ]},
    ],
  },

  // ── Ruby ──────────────────────────────────────────────────────────────────
  {
    name: "Ruby on Rails",
    subtitle: "MVC · ActiveRecord · Routes · Gems · Convention",
    emoji: "💎",
    accentHex: "#CC0000",
    sections: [
      { title: "SETUP & CLI", lines: [
        "§ gem install rails",
        "§ rails new myapp --api --database=postgresql",
        "§ rails server  (or rails s)",
        "§ rails generate scaffold User name:string email:string",
        "§ rails db:migrate",
        "§ rails console  (REPL)",
      ]},
      { title: "MVC STRUCTURE", lines: [
        "app/models/       — ActiveRecord models",
        "app/controllers/  — ApplicationController subclasses",
        "app/views/        — ERB templates",
        "app/helpers/      — view helper methods",
        "config/routes.rb  — routing config",
        "db/migrate/       — migration files",
      ]},
      { title: "ROUTES", lines: [
        "§ resources :users  # CRUD routes",
        "§ resources :posts, only: [:index, :show, :create]",
        "§ namespace :api do",
        "§   resources :users",
        "§ end",
        "§ get '/login', to: 'sessions#new', as: :login",
        "§ root 'home#index'",
        "§ rails routes  # list all routes",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ class UsersController < ApplicationController",
        "§   before_action :authenticate_user!",
        "§   before_action :set_user, only: [:show, :update, :destroy]",
        "§   def index",
        "§     @users = User.all",
        "§     render json: @users",
        "§   end",
        "§   def create",
        "§     @user = User.new(user_params)",
        "§     if @user.save",
        "§       render json: @user, status: :created",
        "§     else",
        "§       render json: @user.errors, status: :unprocessable_entity",
        "§     end",
        "§   end",
        "§ end",
      ]},
      { title: "ACTIVE RECORD MODELS", lines: [
        "§ class User < ApplicationRecord",
        "§   validates :email, presence: true, uniqueness: true",
        "§   validates :name, length: { minimum: 2 }",
        "§   has_many :orders, dependent: :destroy",
        "§   belongs_to :team, optional: true",
        "§   before_save :downcase_email",
        "§ end",
      ]},
      { title: "MIGRATIONS", lines: [
        "§ rails generate migration AddPhoneToUsers phone:string",
        "§ class AddPhoneToUsers < ActiveRecord::Migration[7.0]",
        "§   def change",
        "§     add_column :users, :phone, :string",
        "§     add_index :users, :email, unique: true",
        "§   end",
        "§ end",
        "§ rails db:migrate  /  db:rollback  /  db:schema:load",
      ]},
      { title: "VIEWS (ERB)", lines: [
        "§ <%= @user.name %>  <%# comment %>",
        "§ <% @users.each do |u| %><%= u.name %><% end %>",
        "§ <%= render 'shared/header' %>",
        "§ <%= link_to 'Edit', edit_user_path(@user) %>",
        "§ <%= form_with model: @user do |f| %>",
        "§   <%= f.text_field :name, class: 'form-control' %>",
        "§ <% end %>",
      ]},
      { title: "ACTIVE RECORD ASSOCIATIONS", lines: [
        "§ has_one  has_many  belongs_to  has_and_belongs_to_many",
        "§ has_many :comments, through: :posts  # join model",
        "§ # Eager loading:",
        "§ User.includes(:orders, :role).all",
        "§ User.eager_load(:orders).where(orders: {status: 'paid'})",
        "§ User.preload(:orders)",
      ]},
      { title: "VALIDATIONS", lines: [
        "§ validates :name, presence: true",
        "§ validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }",
        "§ validates :age, numericality: { greater_than: 0 }",
        "§ validates :role, inclusion: { in: %w[admin user] }",
        "§ validate :custom_validation",
        "§ def custom_validation",
        "§   errors.add(:base, 'Custom error') if condition",
        "§ end",
      ]},
      { title: "QUERY INTERFACE", lines: [
        "§ User.all / User.find(1) / User.find_by(email: 'a@b.com')",
        "§ User.where('active = ?', true).order(:name).limit(10)",
        "§ User.where(active: true, role: 'admin')",
        "§ User.joins(:orders).where(orders: {status: 'paid'})",
        "§ User.select(:id, :name).distinct",
        "§ User.count / User.sum(:balance) / User.average(:age)",
      ]},
      { title: "RAILS GENERATORS", lines: [
        "§ rails g controller Api::Users index show create",
        "§ rails g model Post title:string body:text user:references",
        "§ rails g migration CreateJoinTableUsersRoles user role",
        "§ rails g job SendEmail",
        "§ rails g mailer UserMailer welcome_email",
        "§ bundle exec rails test  (or rspec with rspec-rails gem)",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "N+1: use includes/eager_load — never loop + lazy load",
        "Strong parameters: use permit() to whitelist params",
        "SECRET_KEY_BASE in credentials — use rails credentials:edit",
        "Time zones: always use Time.current, not Time.now",
        "Convention over configuration — follow Rails naming conventions",
      ]},
    ],
  },

  {
    name: "Sinatra",
    subtitle: "DSL · Routing · Lightweight · Rack · Modular",
    emoji: "🎤",
    accentHex: "#CC0000",
    sections: [
      { title: "SETUP & BASIC APP", lines: [
        "§ gem install sinatra",
        "§ # app.rb",
        "§ require 'sinatra'",
        "§ get '/' do",
        "§   'Hello World!'",
        "§ end",
        "§ ruby app.rb  # starts on port 4567",
        "§ rerun app.rb  # auto-reload on change",
      ]},
      { title: "ROUTES", lines: [
        "§ get '/users' do; json User.all; end",
        "§ post '/users' do",
        "§   user = User.create(JSON.parse(request.body.read))",
        "§   status 201; json user",
        "§ end",
        "§ put '/users/:id' do; ... end",
        "§ delete '/users/:id' do; User.find(params[:id]).destroy; end",
      ]},
      { title: "PARAMS", lines: [
        "§ get '/users/:id' do",
        "§   id = params[:id]   # route parameter",
        "§   User.find(id).to_json",
        "§ end",
        "§ get '/search' do",
        "§   q = params[:q]     # query string ?q=alice",
        "§   User.where(name: q).to_json",
        "§ end",
        "§ # POST body (form-encoded):",
        "§ name = params[:name]",
      ]},
      { title: "VIEWS", lines: [
        "§ # views/ directory with .erb files",
        "§ get '/users' do",
        "§   @users = User.all",
        "§   erb :users_index  # renders views/users_index.erb",
        "§ end",
        "§ get '/page' do",
        "§   haml :page   # or slim, liquid, etc",
        "§ end",
        "§ # Inline:",
        "§ erb '<%= @name %>', locals: { name: 'Alice' }",
      ]},
      { title: "BEFORE/AFTER FILTERS", lines: [
        "§ before do",
        "§   @current_user = User.find_by(token: request.env['HTTP_AUTHORIZATION'])",
        "§   halt 401, json(error: 'Unauthorized') unless @current_user",
        "§ end",
        "§ before '/admin/*' do",
        "§   halt 403 unless @current_user.admin?",
        "§ end",
        "§ after do",
        "§   headers 'Content-Type' => 'application/json'",
        "§ end",
      ]},
      { title: "SESSIONS", lines: [
        "§ enable :sessions",
        "§ set :session_secret, 'change-me-in-production'",
        "§ # In route:",
        "§ session[:user_id] = user.id",
        "§ user_id = session[:user_id]",
        "§ session.clear",
        "§ # Cookie-based by default; use rack-session-pool for server-side",
      ]},
      { title: "HALT & REDIRECT", lines: [
        "§ halt 404, 'Not found'",
        "§ halt 401, json(error: 'Unauthorized')",
        "§ redirect '/'",
        "§ redirect '/login', 302",
        "§ redirect back  # to referrer",
        "§ # In before filter:",
        "§ halt(401, {error: 'No token'}.to_json) unless token",
      ]},
      { title: "MODULAR vs CLASSIC", lines: [
        "§ # Classic (top-level DSL, one app):",
        "§ require 'sinatra'",
        "§ get '/' do; 'Hello'; end",
        "§ # Modular (multiple apps, explicit run):",
        "§ require 'sinatra/base'",
        "§ class MyApp < Sinatra::Base",
        "§   get '/' do; 'Hello'; end",
        "§ end",
        "§ # config.ru: run MyApp",
      ]},
      { title: "COMMON ROUTE HELPERS", lines: [
        "§ json(data)              # {Content-Type: application/json}",
        "§ status 201             # set response status",
        "§ headers 'X-Foo' => '1' # set response headers",
        "§ send_file 'file.pdf'   # file download",
        "§ stream { |out| out << 'chunk' } # streaming response",
        "§ request.body.read     # raw request body",
        "§ request.ip            # client IP address",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Classic mode pollutes global scope — use Modular for production",
        "enable :sessions stores in cookie — set strong secret",
        "Sinatra halts after first matching route",
        "request.body.read can only be read once — rewind if needed",
        "No built-in ORM — pair with Sequel, ActiveRecord, or ROM",
      ]},
    ],
  },
];
