import type { CheatSheetSpec } from "../tech-pdf-builder";

export const nodeBackend: CheatSheetSpec[] = [
  {
    name: "Node.js",
    subtitle: "Modules · HTTP · Streams · Events · Async",
    emoji: "🟢",
    accentHex: "#339933",
    sections: [
      { title: "SETUP & MODULES", lines: [
        "§ # CommonJS (CJS):",
        "§ const fs = require('fs')",
        "§ module.exports = { fn }",
        "§ # ESM (package.json: \"type\":\"module\"):",
        "§ import fs from 'fs'",
        "§ export const fn = () => {}",
        "§ node --version  /  nvm use 20",
      ]},
      { title: "NPM BASICS", lines: [
        "§ npm init -y",
        "§ npm install express  (saves to dependencies)",
        "§ npm install -D jest  (saves to devDependencies)",
        "§ npm run start  /  npm test",
        "§ npm ci  (clean install from package-lock.json)",
        "§ npx create-next-app  (run without install)",
      ]},
      { title: "HTTP SERVER", lines: [
        "§ import http from 'http'",
        "§ const server = http.createServer((req, res) => {",
        "§   res.writeHead(200, {'Content-Type': 'application/json'})",
        "§   res.end(JSON.stringify({ ok: true }))",
        "§ })",
        "§ server.listen(3000, () => console.log('listening'))",
        "Most projects use Express/Fastify on top of http",
      ]},
      { title: "FILE SYSTEM", lines: [
        "§ import { promises as fs } from 'fs'",
        "§ const data = await fs.readFile('./file.txt', 'utf8')",
        "§ await fs.writeFile('./out.txt', data)",
        "§ await fs.mkdir('./dir', { recursive: true })",
        "§ const files = await fs.readdir('./dir')",
        "§ await fs.rename(old, new) / fs.unlink(path)",
        "Always prefer async (promises) over sync methods",
      ]},
      { title: "EVENTS (EVENTEMITTER)", lines: [
        "§ import { EventEmitter } from 'events'",
        "§ const emitter = new EventEmitter()",
        "§ emitter.on('data', (payload) => { ... })",
        "§ emitter.once('end', () => cleanup())",
        "§ emitter.emit('data', { id: 1 })",
        "§ emitter.removeListener('data', handler)",
        "§ emitter.setMaxListeners(20) // avoid memory leak warn",
      ]},
      { title: "STREAMS", lines: [
        "§ import { createReadStream, createWriteStream } from 'fs'",
        "§ createReadStream('input.txt')",
        "§   .pipe(zlib.createGzip())",
        "§   .pipe(createWriteStream('output.gz'))",
        "§ // Async iteration:",
        "§ for await (const chunk of readableStream) {",
        "§   process(chunk)",
        "§ }",
      ]},
      { title: "ASYNC PATTERNS", lines: [
        "§ // Callback (legacy):",
        "§ fs.readFile('a.txt', (err, data) => {})",
        "§ // Promises:",
        "§ const data = await fs.promises.readFile('a.txt')",
        "§ // Parallel:",
        "§ const [a, b] = await Promise.all([fetch1(), fetch2()])",
        "§ // promisify legacy callbacks:",
        "§ const readFile = util.promisify(fs.readFile)",
      ]},
      { title: "BUFFERS", lines: [
        "§ const buf = Buffer.from('hello', 'utf8')",
        "§ buf.toString('base64')",
        "§ Buffer.alloc(256)  // zero-filled buffer",
        "§ buf.length  /  buf.slice(0, 4)",
        "§ Buffer.concat([buf1, buf2])",
        "Use for binary data, crypto, networking",
      ]},
      { title: "PROCESS & ENV VARS", lines: [
        "§ process.env.PORT ?? 3000",
        "§ process.env.NODE_ENV",
        "§ process.argv  // command-line args",
        "§ process.exit(0) / process.exit(1)",
        "§ process.cwd()  // current working directory",
        "§ process.on('uncaughtException', handler)",
        "§ process.on('unhandledRejection', handler)",
      ]},
      { title: "CHILD PROCESSES", lines: [
        "§ import { exec, spawn } from 'child_process'",
        "§ const { stdout } = await exec('ls -la')",
        "§ const child = spawn('node', ['script.js'])",
        "§ child.stdout.on('data', data => process.stdout.write(data))",
        "§ child.on('exit', code => console.log(code))",
        "spawn = streaming; exec = buffered; fork = for Node scripts",
      ]},
      { title: "COMMON GLOBALS", lines: [
        "§ __dirname  __filename   // CJS only",
        "§ import.meta.url        // ESM",
        "§ globalThis  global     // global object",
        "§ setTimeout setInterval clearTimeout clearInterval",
        "§ setImmediate() / process.nextTick()",
        "§ console.log warn error time timeEnd",
        "§ JSON.stringify / JSON.parse",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Single-threaded — blocking I/O blocks ALL requests",
        "Unhandled promise rejections crash process (Node ≥15)",
        "process.nextTick runs before I/O events — can starve I/O",
        "require() caches modules — mutations persist",
        "ESM vs CJS interop: .mjs vs .cjs extensions or package.json type",
      ]},
    ],
  },

  {
    name: "Express.js",
    subtitle: "Routing · Middleware · REST · Static Files",
    emoji: "🚂",
    accentHex: "#000000",
    sections: [
      { title: "SETUP & APP", lines: [
        "§ npm install express",
        "§ import express from 'express'",
        "§ const app = express()",
        "§ app.use(express.json())",
        "§ app.use(express.urlencoded({ extended: true }))",
        "§ app.listen(3000, () => console.log('Running on 3000'))",
      ]},
      { title: "ROUTING", lines: [
        "§ app.get('/users', getUsers)",
        "§ app.post('/users', createUser)",
        "§ app.put('/users/:id', updateUser)",
        "§ app.delete('/users/:id', deleteUser)",
        "§ app.all('/admin/*', adminMiddleware, adminController)",
        "§ app.route('/items').get(list).post(create)",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ app.use((req, res, next) => {",
        "§   console.log(req.method, req.url)",
        "§   next()        // call next middleware",
        "§ })",
        "§ app.use('/api', apiRouter)",
        "§ app.use('/static', express.static('public'))",
        "Order matters — middleware runs top-to-bottom",
      ]},
      { title: "REQUEST OBJECT", lines: [
        "§ req.params.id          // route :id",
        "§ req.query.page         // ?page=2",
        "§ req.body.email         // parsed JSON/form",
        "§ req.headers.authorization",
        "§ req.cookies.session    // (cookie-parser)",
        "§ req.ip  req.method  req.path  req.hostname",
      ]},
      { title: "RESPONSE OBJECT", lines: [
        "§ res.json({ users: [] })          // 200 JSON",
        "§ res.status(201).json({ id: 1 })",
        "§ res.status(404).json({ error: 'Not found' })",
        "§ res.send('Hello')               // text",
        "§ res.sendFile(path)              // file",
        "§ res.redirect('/login')",
        "§ res.set('X-Header', 'value')",
      ]},
      { title: "ROUTER", lines: [
        "§ // users.js",
        "§ const router = express.Router()",
        "§ router.get('/', listUsers)",
        "§ router.post('/', createUser)",
        "§ router.get('/:id', getUser)",
        "§ export default router",
        "§ // app.js",
        "§ app.use('/api/users', usersRouter)",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ app.use((err, req, res, next) => {",
        "§   console.error(err.stack)",
        "§   res.status(err.status ?? 500).json({",
        "§     error: err.message",
        "§   })",
        "§ })",
        "4-arg middleware = error handler; must be last",
        "§ next(err) to pass error to handler",
      ]},
      { title: "ROUTE PARAMS & QUERY", lines: [
        "§ app.get('/users/:id/posts/:postId', (req, res) => {",
        "§   const { id, postId } = req.params",
        "§   const { page = 1, limit = 10 } = req.query",
        "§   res.json({ userId: id, postId, page, limit })",
        "§ })",
        "§ app.param('id', (req, res, next, id) => {",
        "§   req.user = User.findById(id)",
        "§   next()",
        "§ })",
      ]},
      { title: "STATIC FILES", lines: [
        "§ app.use(express.static('public'))",
        "§ app.use('/assets', express.static('dist/assets'))",
        "§ // Serve with options:",
        "§ app.use(express.static('public', {",
        "§   maxAge: '1d',",
        "§   etag: true",
        "§ }))",
        "Files in 'public' served at root URL",
      ]},
      { title: "BODY PARSING", lines: [
        "§ app.use(express.json({ limit: '10mb' }))",
        "§ app.use(express.urlencoded({ extended: true }))",
        "§ // Multipart / file upload:",
        "§ import multer from 'multer'",
        "§ const upload = multer({ dest: 'uploads/' })",
        "§ app.post('/upload', upload.single('file'), handler)",
      ]},
      { title: "COMMON MIDDLEWARE", lines: [
        "§ helmet()        // security headers",
        "§ cors()          // CORS headers",
        "§ morgan('dev')   // request logging",
        "§ compression()   // gzip responses",
        "§ cookie-parser   // parse cookies",
        "§ express-rate-limit // rate limiting",
        "§ express-validator  // input validation",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Error handler must have 4 args (err,req,res,next)",
        "Missing next() call hangs request indefinitely",
        "Order of app.use() matters — put catch-all last",
        "express.json() body is undefined without middleware",
        "async errors need try/catch + next(err) pattern",
      ]},
    ],
  },

  {
    name: "NestJS",
    subtitle: "Modules · DI · Guards · Pipes · Decorators",
    emoji: "🐱",
    accentHex: "#E0234E",
    sections: [
      { title: "SETUP & CLI", lines: [
        "§ npm i -g @nestjs/cli",
        "§ nest new my-app",
        "§ nest generate module users",
        "§ nest generate controller users",
        "§ nest generate service users",
        "§ npm run start:dev  (watch mode)",
      ]},
      { title: "MODULES", lines: [
        "§ @Module({",
        "§   imports: [TypeOrmModule.forFeature([User])],",
        "§   controllers: [UsersController],",
        "§   providers: [UsersService],",
        "§   exports: [UsersService],",
        "§ })",
        "§ export class UsersModule {}",
        "Feature modules keep concerns isolated",
      ]},
      { title: "CONTROLLERS", lines: [
        "§ @Controller('users')",
        "§ export class UsersController {",
        "§   constructor(private readonly svc: UsersService) {}",
        "§   @Get() findAll(): Promise<User[]> { return this.svc.findAll() }",
        "§   @Get(':id') findOne(@Param('id') id: string) { ... }",
        "§   @Post() @HttpCode(201) create(@Body() dto: CreateUserDto) { ... }",
        "§   @Put(':id') update(@Param('id') id, @Body() dto) { ... }",
        "§   @Delete(':id') remove(@Param('id') id) { ... }",
      ]},
      { title: "PROVIDERS & SERVICES", lines: [
        "§ @Injectable()",
        "§ export class UsersService {",
        "§   constructor(",
        "§     @InjectRepository(User)",
        "§     private readonly repo: Repository<User>",
        "§   ) {}",
        "§   async findAll(): Promise<User[]> {",
        "§     return this.repo.find()",
        "§   }",
        "§ }",
      ]},
      { title: "DTOs & VALIDATION", lines: [
        "§ import { IsEmail, IsString, MinLength } from 'class-validator'",
        "§ export class CreateUserDto {",
        "§   @IsString() @MinLength(2)",
        "§   name: string",
        "§   @IsEmail()",
        "§   email: string",
        "§ }",
        "§ // main.ts:",
        "§ app.useGlobalPipes(new ValidationPipe({ whitelist: true }))",
      ]},
      { title: "GUARDS", lines: [
        "§ @Injectable()",
        "§ export class JwtAuthGuard extends AuthGuard('jwt') {}",
        "§ @UseGuards(JwtAuthGuard)",
        "§ @Get('profile')",
        "§ getProfile(@Request() req) { return req.user }",
        "§ @Injectable()",
        "§ export class RolesGuard implements CanActivate {",
        "§   canActivate(ctx: ExecutionContext): boolean { ... }",
        "§ }",
      ]},
      { title: "INTERCEPTORS", lines: [
        "§ @Injectable()",
        "§ export class LoggingInterceptor implements NestInterceptor {",
        "§   intercept(ctx: ExecutionContext, next: CallHandler): Observable<any> {",
        "§     console.log('Before...')",
        "§     return next.handle().pipe(",
        "§       tap(() => console.log('After...'))",
        "§     )",
        "§   }",
        "§ }",
        "§ @UseInterceptors(LoggingInterceptor)",
      ]},
      { title: "PIPES", lines: [
        "§ @Get(':id')",
        "§ findOne(@Param('id', ParseIntPipe) id: number) { ... }",
        "§ // Custom pipe:",
        "§ @Injectable()",
        "§ export class ParseIdPipe implements PipeTransform {",
        "§   transform(val: any): number {",
        "§     const n = parseInt(val)",
        "§     if (isNaN(n)) throw new BadRequestException()",
        "§     return n",
        "§   }",
        "§ }",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ @Injectable()",
        "§ export class LoggerMiddleware implements NestMiddleware {",
        "§   use(req: Request, res: Response, next: Function) {",
        "§     console.log(`${req.method} ${req.url}`)",
        "§     next()",
        "§   }",
        "§ }",
        "§ // In module:",
        "§ configure(consumer: MiddlewareConsumer) {",
        "§   consumer.apply(LoggerMiddleware).forRoutes('*')",
        "§ }",
      ]},
      { title: "EXCEPTION FILTERS", lines: [
        "§ @Catch(HttpException)",
        "§ export class HttpExceptionFilter implements ExceptionFilter {",
        "§   catch(ex: HttpException, host: ArgumentsHost) {",
        "§     const ctx = host.switchToHttp()",
        "§     const res = ctx.getResponse<Response>()",
        "§     res.status(ex.getStatus()).json({",
        "§       statusCode: ex.getStatus(),",
        "§       message: ex.message",
        "§     })",
        "§   }",
        "§ }",
      ]},
      { title: "COMMON DECORATORS", lines: [
        "§ @Controller @Get @Post @Put @Delete @Patch",
        "§ @Param @Body @Query @Headers @Request @Response",
        "§ @Injectable @Module @Guard @UseGuards @UseInterceptors",
        "§ @Catch @UseFilters  @UsePipes",
        "§ @SetMetadata('roles', ['admin'])",
        "§ @Reflector + Reflector.getAllAndOverride()",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Circular dependency: use forwardRef(() => ServiceB)",
        "ValidationPipe whitelist:true strips unknown props",
        "Global guards/pipes must be registered in main.ts",
        "TypeORM relations must be explicitly loaded or use eager",
        "Async providers: use async factory or useFactory",
      ]},
    ],
  },

  {
    name: "Fastify",
    subtitle: "Schema Validation · Hooks · Plugins · Logging",
    emoji: "⚡",
    accentHex: "#000000",
    sections: [
      { title: "SETUP & INSTANCE", lines: [
        "§ npm install fastify",
        "§ import Fastify from 'fastify'",
        "§ const fastify = Fastify({ logger: true })",
        "§ await fastify.listen({ port: 3000, host: '0.0.0.0' })",
        "§ fastify.log.info('Server started')",
        "Fastest Node.js HTTP framework (benchmarks #1 2024)",
      ]},
      { title: "ROUTES", lines: [
        "§ fastify.get('/users', async (request, reply) => {",
        "§   return { users: [] }  // auto-serialized",
        "§ })",
        "§ fastify.post('/users', {",
        "§   schema: { body: userSchema, response: { 201: userResponse } }",
        "§ }, async (req, reply) => {",
        "§   reply.status(201).send(newUser)",
        "§ })",
      ]},
      { title: "SCHEMA VALIDATION", lines: [
        "§ const schema = {",
        "§   body: {",
        "§     type: 'object',",
        "§     required: ['name','email'],",
        "§     properties: {",
        "§       name: { type: 'string', minLength: 2 },",
        "§       email: { type: 'string', format: 'email' }",
        "§     }",
        "§   }",
        "§ }",
        "JSON Schema via Ajv; also boosts serialization 2×",
      ]},
      { title: "HOOKS", lines: [
        "§ fastify.addHook('onRequest', async (req, reply) => {",
        "§   // auth check",
        "§ })",
        "§ fastify.addHook('preHandler', async (req, reply) => {",
        "§   // rate limiting",
        "§ })",
        "§ fastify.addHook('onSend', async (req, reply, payload) => payload)",
        "Hooks: onRequest→preParsing→preValidation→preHandler→onSend→onResponse",
      ]},
      { title: "PLUGINS", lines: [
        "§ import fp from 'fastify-plugin'",
        "§ const myPlugin = fp(async (fastify, opts) => {",
        "§   fastify.decorate('db', new DB(opts))",
        "§ })",
        "§ fastify.register(myPlugin, { uri: process.env.DB_URI })",
        "§ fastify.register(require('@fastify/cors'))",
        "§ fastify.register(require('@fastify/jwt'), { secret: '...' })",
        "fp() makes plugin available across encapsulation boundaries",
      ]},
      { title: "DECORATORS", lines: [
        "§ fastify.decorate('config', { port: 3000 })",
        "§ fastify.decorateRequest('user', null)",
        "§ fastify.decorateReply('sendError', function(code, msg) {",
        "§   this.status(code).send({ error: msg })",
        "§ })",
        "§ // In handler:",
        "§ request.user  /  reply.sendError(401, 'Unauthorized')",
      ]},
      { title: "REQUEST & REPLY", lines: [
        "§ request.body / request.params / request.query",
        "§ request.headers / request.ip / request.id",
        "§ reply.send(data)  // infers Content-Type",
        "§ reply.status(404).send({ error: 'Not found' })",
        "§ reply.type('text/html').send('<h1>Hi</h1>')",
        "§ reply.redirect('/new-url')",
        "§ reply.header('X-Custom', 'value')",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ fastify.setErrorHandler(async (error, request, reply) => {",
        "§   request.log.error(error)",
        "§   reply.status(error.statusCode ?? 500).send({",
        "§     error: error.message",
        "§   })",
        "§ })",
        "§ throw fastify.httpErrors.notFound('User not found')",
        "§ // Requires @fastify/sensible plugin",
      ]},
      { title: "LOGGING", lines: [
        "§ const fastify = Fastify({",
        "§   logger: {",
        "§     level: 'info',",
        "§     transport: { target: 'pino-pretty' }",
        "§   }",
        "§ })",
        "§ request.log.info({ userId: id }, 'Fetching user')",
        "§ fastify.log.error({ err }, 'Fatal error')",
        "Built on Pino — very fast structured logging",
      ]},
      { title: "COMMON PLUGINS", lines: [
        "§ @fastify/jwt    — JWT auth",
        "§ @fastify/cors   — CORS headers",
        "§ @fastify/static — static files",
        "§ @fastify/swagger — OpenAPI docs",
        "§ @fastify/rate-limit — rate limiting",
        "§ @fastify/compress — gzip/deflate",
        "§ @fastify/sensible — httpErrors helpers",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Schema must use additionalProperties:false or extra props pass",
        "Decorated properties must be initialized in decorateRequest/Reply",
        "Plugin encapsulation: fp() needed to share across contexts",
        "reply.send() after async handler = duplicate response error",
        "JSON schema 'format' requires ajv-formats plugin",
      ]},
    ],
  },

  {
    name: "Koa",
    subtitle: "Middleware · Context · Async/Await · Modular",
    emoji: "🌊",
    accentHex: "#33333D",
    sections: [
      { title: "SETUP & APP", lines: [
        "§ npm install koa koa-router koa-bodyparser",
        "§ import Koa from 'koa'",
        "§ const app = new Koa()",
        "§ app.keys = ['secret-key']  // for signed cookies",
        "§ app.use(bodyParser())",
        "§ app.listen(3000)",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ app.use(async (ctx, next) => {",
        "§   const start = Date.now()",
        "§   await next()  // call downstream middleware",
        "§   const ms = Date.now() - start",
        "§   ctx.set('X-Response-Time', `${ms}ms`)",
        "§ })",
        "Onion model: middleware wraps around each other",
      ]},
      { title: "CONTEXT OBJECT", lines: [
        "§ ctx.request  ctx.response  // Koa's enhanced versions",
        "§ ctx.req  ctx.res           // Node native",
        "§ ctx.state.user             // shared state across middleware",
        "§ ctx.session.userId         // (koa-session)",
        "§ ctx.app                    // app instance",
        "§ ctx.body = {}              // sets response body",
        "§ ctx.status = 200           // HTTP status code",
      ]},
      { title: "ROUTING (KOA-ROUTER)", lines: [
        "§ import Router from '@koa/router'",
        "§ const router = new Router({ prefix: '/api' })",
        "§ router.get('/users', async ctx => {",
        "§   ctx.body = await User.findAll()",
        "§ })",
        "§ router.post('/users', async ctx => {",
        "§   const user = await User.create(ctx.request.body)",
        "§   ctx.status = 201",
        "§   ctx.body = user",
        "§ })",
        "§ app.use(router.routes()).use(router.allowedMethods())",
      ]},
      { title: "ASYNC/AWAIT FLOW", lines: [
        "§ app.use(async (ctx, next) => {",
        "§   try {",
        "§     await next()",
        "§   } catch (err) {",
        "§     ctx.status = err.status || 500",
        "§     ctx.body = { error: err.message }",
        "§     ctx.app.emit('error', err, ctx)",
        "§   }",
        "§ })",
        "Error middleware must be first to catch downstream errors",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ app.on('error', (err, ctx) => {",
        "§   console.error('Server Error', err, ctx)",
        "§ })",
        "§ // Throw in handler:",
        "§ const { createError } = require('http-errors')",
        "§ throw createError(404, 'User not found')",
        "§ throw createError(400, 'Invalid input')",
        "ctx.throw(404, 'Not found')  // shorthand",
      ]},
      { title: "BODY PARSING", lines: [
        "§ import bodyParser from 'koa-bodyparser'",
        "§ app.use(bodyParser({",
        "§   enableTypes: ['json', 'form'],",
        "§   jsonLimit: '5mb',",
        "§ }))",
        "§ // Access parsed body:",
        "§ ctx.request.body  // JSON or form data",
        "§ // File uploads: koa-multer",
      ]},
      { title: "STATIC FILES", lines: [
        "§ import serve from 'koa-static'",
        "§ app.use(serve('./public', {",
        "§   maxAge: 86400,     // 1 day cache",
        "§   gzip: true,",
        "§ }))",
        "§ import mount from 'koa-mount'",
        "§ app.use(mount('/assets', serve('./dist')))",
      ]},
      { title: "COOKIES & SESSIONS", lines: [
        "§ ctx.cookies.get('session')  // unsigned",
        "§ ctx.cookies.set('token', value, { httpOnly: true })",
        "§ // Signed cookies (requires app.keys):",
        "§ ctx.cookies.get('session', { signed: true })",
        "§ // Session middleware:",
        "§ import session from 'koa-session'",
        "§ app.use(session({ key: 'sess', maxAge: 86400 }, app))",
      ]},
      { title: "COMMON MIDDLEWARE PACKAGES", lines: [
        "§ @koa/router    — routing",
        "§ koa-bodyparser — JSON/form parsing",
        "§ koa-static     — static file serving",
        "§ koa-session    — session management",
        "§ koa-compress   — gzip compression",
        "§ koa-logger     — request logging",
        "§ koa-helmet     — security headers",
        "§ koa-jwt        — JWT authentication",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Error catching middleware must be registered FIRST",
        "await next() is async — forgetting await breaks the chain",
        "ctx.body must be set or Koa returns 404 by default",
        "ctx.request.body only set after bodyparser middleware",
        "app.keys required for signed cookies or sessions",
      ]},
    ],
  },
];
