import type { CheatSheetSpec } from "../tech-pdf-builder";

export const pythonBackend: CheatSheetSpec[] = [
  {
    name: "Django",
    subtitle: "ORM · Templates · Admin · Auth · REST",
    emoji: "🦄",
    accentHex: "#092E20",
    sections: [
      { title: "SETUP & PROJECT", lines: [
        "§ pip install django",
        "§ django-admin startproject mysite",
        "§ python manage.py startapp blog",
        "§ python manage.py runserver",
        "§ python manage.py migrate",
        "INSTALLED_APPS must include new apps",
      ]},
      { title: "MODELS", lines: [
        "§ from django.db import models",
        "§ class Post(models.Model):",
        "§     title = models.CharField(max_length=200)",
        "§     body = models.TextField()",
        "§     created = models.DateTimeField(auto_now_add=True)",
        "§     author = models.ForeignKey(User, on_delete=models.CASCADE)",
        "§ class Meta: ordering = ['-created']",
      ]},
      { title: "VIEWS", lines: [
        "§ from django.views import View",
        "§ class PostListView(View):",
        "§     def get(self, request):",
        "§         posts = Post.objects.all()",
        "§         return render(request,'list.html',{'posts':posts})",
        "§ # Function-based:",
        "§ def post_list(request):",
        "§     return JsonResponse({'posts': list(...)}, safe=False)",
      ]},
      { title: "URLs & ROUTING", lines: [
        "§ # urls.py",
        "§ urlpatterns = [",
        "§     path('posts/', views.PostListView.as_view()),",
        "§     path('posts/<int:pk>/', views.PostDetailView.as_view()),",
        "§     path('api/', include('api.urls')),",
        "§ ]",
        "§ re_path(r'^old/(?P<slug>[-w]+)/$', view)",
      ]},
      { title: "ORM QUERYSETS", lines: [
        "§ Post.objects.all()",
        "§ Post.objects.filter(author=user, published=True)",
        "§ Post.objects.exclude(status='draft')",
        "§ Post.objects.get(pk=1)  # raises DoesNotExist",
        "§ Post.objects.order_by('-created')[:10]",
        "§ Post.objects.select_related('author')",
        "§ Post.objects.prefetch_related('tags')",
      ]},
      { title: "MIGRATIONS", lines: [
        "§ python manage.py makemigrations",
        "§ python manage.py migrate",
        "§ python manage.py showmigrations",
        "§ python manage.py migrate blog 0002",
        "§ python manage.py sqlmigrate blog 0001",
        "Never delete migrations in production",
      ]},
      { title: "TEMPLATES", lines: [
        "§ {{ variable }}  {# comment #}",
        "§ {% if user.is_authenticated %}...{% endif %}",
        "§ {% for post in posts %}...{% endfor %}",
        "§ {% extends 'base.html' %}",
        "§ {% block content %}...{% endblock %}",
        "§ {% url 'post-detail' pk=post.pk %}",
      ]},
      { title: "ADMIN", lines: [
        "§ from django.contrib import admin",
        "§ @admin.register(Post)",
        "§ class PostAdmin(admin.ModelAdmin):",
        "§     list_display = ['title','author','created']",
        "§     search_fields = ['title','body']",
        "§     list_filter = ['status','created']",
        "§ python manage.py createsuperuser",
      ]},
      { title: "AUTHENTICATION", lines: [
        "§ from django.contrib.auth.decorators import login_required",
        "§ @login_required(login_url='/login/')",
        "§ def dashboard(request): ...",
        "§ LoginView / LogoutView / PasswordResetView",
        "§ request.user.is_authenticated",
        "§ authenticate(username=u, password=p)",
        "§ login(request, user)  /  logout(request)",
      ]},
      { title: "MIDDLEWARE", lines: [
        "§ MIDDLEWARE = [",
        "§     'django.middleware.security.SecurityMiddleware',",
        "§     'django.contrib.sessions.middleware.SessionMiddleware',",
        "§     'django.middleware.csrf.CsrfViewMiddleware',",
        "§     'myapp.middleware.CustomMiddleware',",
        "§ ]",
        "Custom: define __init__(get_response) and __call__(request)",
      ]},
      { title: "FORMS & VALIDATION", lines: [
        "§ class PostForm(forms.ModelForm):",
        "§     class Meta:",
        "§         model = Post",
        "§         fields = ['title','body']",
        "§ form = PostForm(request.POST or None)",
        "§ if form.is_valid(): form.save()",
        "§ def clean_title(self): # custom validation",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "N+1: always use select_related/prefetch_related",
        "CSRF token required in all POST forms",
        "DEBUG=True exposes full tracebacks — disable in prod",
        "SECRET_KEY must be secret — use env vars",
        "Migrations in prod: always backup before migrate",
      ]},
    ],
  },

  {
    name: "Flask",
    subtitle: "Routing · Jinja2 · Blueprints · SQLAlchemy",
    emoji: "🌶️",
    accentHex: "#000000",
    sections: [
      { title: "SETUP & APP FACTORY", lines: [
        "§ pip install flask flask-sqlalchemy",
        "§ def create_app(config=None):",
        "§     app = Flask(__name__)",
        "§     app.config.from_object(config)",
        "§     db.init_app(app)",
        "§     app.register_blueprint(api_bp, url_prefix='/api')",
        "§     return app",
      ]},
      { title: "ROUTING", lines: [
        "§ @app.route('/users', methods=['GET','POST'])",
        "§ def users():",
        "§     if request.method == 'POST':",
        "§         data = request.get_json()",
        "§         return jsonify(data), 201",
        "§     return jsonify(User.query.all())",
        "§ @app.route('/users/<int:user_id>')",
      ]},
      { title: "REQUEST & RESPONSE", lines: [
        "§ request.method  request.args  request.form",
        "§ request.json  request.get_json()",
        "§ request.files  request.headers",
        "§ jsonify({'key': 'value'})",
        "§ make_response(body, 200, {'X-Custom': 'val'})",
        "§ redirect(url_for('index'))",
        "§ abort(404) / abort(401)",
      ]},
      { title: "TEMPLATES (JINJA2)", lines: [
        "§ return render_template('index.html', users=users)",
        "§ {{ user.name | upper }}",
        "§ {% for u in users %}{{ u.name }}{% endfor %}",
        "§ {% extends 'base.html' %}",
        "§ {% block body %}...{% endblock %}",
        "§ {{ url_for('users', _external=True) }}",
      ]},
      { title: "BLUEPRINTS", lines: [
        "§ api_bp = Blueprint('api', __name__)",
        "§ @api_bp.route('/users')",
        "§ def get_users(): ...",
        "§ # In factory:",
        "§ app.register_blueprint(api_bp, url_prefix='/api')",
        "Separate modules by feature; maintain isolation",
      ]},
      { title: "FLASK-SQLALCHEMY", lines: [
        "§ db = SQLAlchemy()",
        "§ class User(db.Model):",
        "§     id = db.Column(db.Integer, primary_key=True)",
        "§     email = db.Column(db.String(120), unique=True)",
        "§ User.query.filter_by(active=True).all()",
        "§ db.session.add(user) / db.session.commit()",
        "§ flask db upgrade  (Flask-Migrate)",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ @app.errorhandler(404)",
        "§ def not_found(e):",
        "§     return jsonify(error='Not found'), 404",
        "§ @app.errorhandler(Exception)",
        "§ def handle_exception(e):",
        "§     return jsonify(error=str(e)), 500",
        "§ try_except + abort() for controlled errors",
      ]},
      { title: "SESSIONS & COOKIES", lines: [
        "§ from flask import session",
        "§ session['user_id'] = user.id",
        "§ session.get('user_id')",
        "§ session.clear()",
        "§ app.secret_key = 'change-me'",
        "§ response.set_cookie('token', value, httponly=True)",
        "Session signed server-side with secret_key",
      ]},
      { title: "BEFORE/AFTER REQUESTS", lines: [
        "§ @app.before_request",
        "§ def auth_check():",
        "§     if not session.get('user_id') and request.endpoint != 'login':",
        "§         return jsonify(error='Unauthorized'), 401",
        "§ @app.after_request",
        "§ def add_headers(response):",
        "§     response.headers['X-Frame-Options'] = 'DENY'",
        "§     return response",
      ]},
      { title: "CONFIGURATION", lines: [
        "§ app.config.from_pyfile('config.py')",
        "§ app.config.from_envvar('APP_SETTINGS')",
        "§ app.config['DEBUG'] = os.environ.get('DEBUG', False)",
        "§ class ProductionConfig:",
        "§     SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']",
        "§     SECRET_KEY = os.environ['SECRET_KEY']",
      ]},
      { title: "POPULAR EXTENSIONS", lines: [
        "§ Flask-SQLAlchemy — ORM integration",
        "§ Flask-Migrate    — Alembic migrations",
        "§ Flask-Login      — user session management",
        "§ Flask-JWT-Extended — JWT tokens",
        "§ Flask-WTF        — CSRF + form validation",
        "§ Flask-CORS       — CORS headers",
        "§ Marshmallow      — serialization/validation",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Application context: push ctx for DB outside request",
        "Thread safety: don't store state on app object",
        "SECRET_KEY must be set or sessions won't work",
        "FLASK_ENV=development enables debugger",
        "Use factory pattern for testing — avoid module-level app",
      ]},
    ],
  },

  {
    name: "FastAPI",
    subtitle: "Async · OpenAPI · Pydantic · Dependency Injection",
    emoji: "⚡",
    accentHex: "#009688",
    sections: [
      { title: "SETUP & RUN", lines: [
        "§ pip install fastapi uvicorn[standard]",
        "§ from fastapi import FastAPI",
        "§ app = FastAPI(title='My API', version='1.0.0')",
        "§ uvicorn main:app --reload",
        "§ uvicorn main:app --host 0.0.0.0 --port 8000",
        "Docs: /docs (Swagger) and /redoc (ReDoc)",
      ]},
      { title: "PATH OPERATIONS", lines: [
        "§ @app.get('/items', response_model=List[Item])",
        "§ async def list_items():",
        "§     return await db.items.find_all()",
        "§ @app.post('/items', status_code=201)",
        "§ async def create(item: Item):",
        "§     return await db.items.insert(item)",
        "HTTP verbs: get post put patch delete head options",
      ]},
      { title: "PATH & QUERY PARAMS", lines: [
        "§ @app.get('/users/{user_id}')",
        "§ async def get_user(user_id: int):",
        "§     return {'id': user_id}",
        "§ @app.get('/search')",
        "§ async def search(q: str, limit: int = 10, skip: int = 0):",
        "§     ...",
        "Type annotations auto-validate and document",
      ]},
      { title: "REQUEST BODY (PYDANTIC)", lines: [
        "§ from pydantic import BaseModel, EmailStr",
        "§ class User(BaseModel):",
        "§     name: str",
        "§     email: EmailStr",
        "§     age: int = Field(ge=0, le=120)",
        "§ @app.post('/users')",
        "§ async def create(user: User): ...",
        "Automatic validation + OpenAPI schema generation",
      ]},
      { title: "DEPENDENCY INJECTION", lines: [
        "§ from fastapi import Depends",
        "§ def get_db() -> Generator:",
        "§     db = SessionLocal()",
        "§     try: yield db",
        "§     finally: db.close()",
        "§ async def get_current_user(token=Depends(oauth2_scheme)):",
        "§     ...",
        "§ def endpoint(db=Depends(get_db), user=Depends(get_current_user)):",
      ]},
      { title: "RESPONSE MODELS", lines: [
        "§ class UserOut(BaseModel):",
        "§     id: int",
        "§     name: str",
        "§     # no password field",
        "§ @app.get('/users/{id}', response_model=UserOut)",
        "§ async def get_user(id: int): ...",
        "§ response_model_exclude_unset=True  # skip defaults",
        "§ response_model_exclude={'password'}",
      ]},
      { title: "AUTH (OAUTH2 + JWT)", lines: [
        "§ from fastapi.security import OAuth2PasswordBearer",
        "§ oauth2_scheme = OAuth2PasswordBearer(tokenUrl='token')",
        "§ @app.post('/token')",
        "§ async def login(form: OAuth2PasswordRequestForm=Depends()):",
        "§     user = authenticate(form.username, form.password)",
        "§     token = create_jwt(user.id)",
        "§     return {'access_token': token, 'token_type': 'bearer'}",
      ]},
      { title: "MIDDLEWARE & CORS", lines: [
        "§ from fastapi.middleware.cors import CORSMiddleware",
        "§ app.add_middleware(CORSMiddleware,",
        "§     allow_origins=['https://myapp.com'],",
        "§     allow_methods=['*'],",
        "§     allow_headers=['*'])",
        "§ @app.middleware('http')",
        "§ async def add_header(request, call_next):",
        "§     response = await call_next(request)",
        "§     response.headers['X-Process-Time'] = str(t)",
        "§     return response",
      ]},
      { title: "ASYNC ENDPOINTS", lines: [
        "§ @app.get('/slow')",
        "§ async def slow_endpoint():",
        "§     result = await slow_io_operation()",
        "§     return result",
        "§ import asyncio",
        "§ await asyncio.gather(task1(), task2())",
        "Use sync def for CPU-bound (runs in threadpool)",
        "Use async def for I/O-bound operations",
      ]},
      { title: "BACKGROUND TASKS", lines: [
        "§ from fastapi import BackgroundTasks",
        "§ @app.post('/notify')",
        "§ def notify(bg: BackgroundTasks, email: str):",
        "§     bg.add_task(send_email, email, 'Welcome!')",
        "§     return {'message': 'queued'}",
        "For heavy work: use Celery + Redis instead",
      ]},
      { title: "TESTING", lines: [
        "§ from fastapi.testclient import TestClient",
        "§ client = TestClient(app)",
        "§ def test_create():",
        "§     resp = client.post('/users', json={'name':'Alice','email':'a@b.com'})",
        "§     assert resp.status_code == 201",
        "§     assert resp.json()['name'] == 'Alice'",
        "Override deps: app.dependency_overrides[get_db] = mock_db",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "async def needs await — forgetting await blocks event loop",
        "Pydantic V2 breaking changes vs V1 (field vs Field)",
        "Don't use sync I/O inside async endpoints",
        "global state is shared across requests — use Depends",
        "Response model strips extra fields — can miss data",
      ]},
    ],
  },

  {
    name: "Celery",
    subtitle: "Task Queue · Broker · Beat · Canvas · Retry",
    emoji: "🌿",
    accentHex: "#37814A",
    sections: [
      { title: "SETUP & BROKER", lines: [
        "§ pip install celery redis",
        "§ # celery.py",
        "§ from celery import Celery",
        "§ app = Celery('myapp',",
        "§     broker='redis://localhost:6379/0',",
        "§     backend='redis://localhost:6379/1')",
        "§ celery -A myapp worker -l info",
      ]},
      { title: "DEFINING TASKS", lines: [
        "§ @app.task(bind=True, max_retries=3)",
        "§ def send_email(self, to_addr, subject):",
        "§     try:",
        "§         mailer.send(to_addr, subject)",
        "§     except Exception as exc:",
        "§         raise self.retry(exc=exc, countdown=60)",
        "§ # Simple task:",
        "§ @app.task",
        "§ def add(x, y): return x + y",
      ]},
      { title: "CALLING TASKS", lines: [
        "§ add.delay(4, 4)          # fire and forget",
        "§ add.apply_async((4,4), countdown=30) # delayed",
        "§ add.apply_async((4,4), eta=datetime.utcnow()+timedelta(hours=1))",
        "§ result = add.delay(4,4)",
        "§ result.get(timeout=10)   # blocks until done",
        "§ result.status  # PENDING / STARTED / SUCCESS / FAILURE",
      ]},
      { title: "RESULTS & STATE", lines: [
        "§ res = add.apply_async((2,3))",
        "§ res.id             # task UUID",
        "§ res.ready()        # True if done",
        "§ res.successful()   # True if SUCCESS",
        "§ res.result         # return value",
        "§ res.traceback      # if FAILURE",
        "§ AsyncResult('uuid').get()  # by task ID",
      ]},
      { title: "PERIODIC TASKS (BEAT)", lines: [
        "§ from celery.schedules import crontab",
        "§ app.conf.beat_schedule = {",
        "§     'daily-report': {",
        "§         'task': 'tasks.send_report',",
        "§         'schedule': crontab(hour=8, minute=0),",
        "§     },",
        "§     'every-30s': {",
        "§         'task': 'tasks.heartbeat',",
        "§         'schedule': 30.0,",
        "§     },",
        "§ }",
        "§ celery -A myapp beat -l info",
      ]},
      { title: "RETRIES", lines: [
        "§ @app.task(bind=True, autoretry_for=(Exception,),",
        "§            retry_kwargs={'max_retries': 5},",
        "§            retry_backoff=True,",
        "§            retry_backoff_max=700,",
        "§            retry_jitter=True)",
        "§ def fetch_data(self, url): ...",
        "§ self.retry(exc=exc, countdown=2**self.request.retries)",
      ]},
      { title: "CANVAS: CHAIN & GROUP", lines: [
        "§ from celery import chain, group, chord",
        "§ # Chain (sequential):",
        "§ result = chain(task1.s(arg), task2.s(), task3.s())()",
        "§ # Group (parallel):",
        "§ job = group(add.s(i, i) for i in range(10))",
        "§ result = job.apply_async()",
        "§ # Chord (parallel then callback):",
        "§ chord(group(tasks))(callback.s())",
      ]},
      { title: "WORKER CLI", lines: [
        "§ celery -A proj worker --concurrency=4 -l info",
        "§ celery -A proj worker -P gevent -c 1000",
        "§ celery -A proj worker --queues=email,high",
        "§ celery -A proj inspect active",
        "§ celery -A proj purge  # clear all queued tasks",
        "§ celery -A proj events  # real-time monitoring",
        "§ celery -A proj flower  # web monitoring UI",
      ]},
      { title: "ROUTING & QUEUES", lines: [
        "§ @app.task(queue='high_priority')",
        "§ def urgent_task(): ...",
        "§ app.conf.task_routes = {",
        "§     'tasks.urgent_*': {'queue': 'high_priority'},",
        "§     'tasks.email_*': {'queue': 'email'},",
        "§ }",
        "§ celery worker -Q high_priority,email",
      ]},
      { title: "CONFIGURATION", lines: [
        "§ app.conf.update(",
        "§     task_serializer='json',",
        "§     accept_content=['json'],",
        "§     result_expires=3600,",
        "§     task_time_limit=300,      # hard time limit",
        "§     task_soft_time_limit=240, # soft (raises SoftTimeLimitExceeded)",
        "§     worker_max_tasks_per_child=1000,",
        "§ )",
      ]},
      { title: "SIGNALS", lines: [
        "§ from celery.signals import task_success, task_failure",
        "§ @task_success.connect",
        "§ def on_success(result, **kwargs):",
        "§     metrics.incr('task.success')",
        "§ @task_failure.connect",
        "§ def on_failure(exception, **kwargs):",
        "§     alert.send(str(exception))",
        "Signals: prerun, postrun, retry, revoke",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Don't pass ORM objects to tasks — pass IDs instead",
        "result.get() inside another task causes deadlock",
        "Pickle serializer security risk — use JSON",
        "Task imports must be accessible in worker environment",
        "Beat scheduler needs single instance (use RedBeat for HA)",
      ]},
    ],
  },

  {
    name: "Tornado",
    subtitle: "Async · WebSocket · IOLoop · Non-Blocking I/O",
    emoji: "🌪️",
    accentHex: "#333333",
    sections: [
      { title: "SETUP & APPLICATION", lines: [
        "§ pip install tornado",
        "§ import tornado.web, tornado.ioloop",
        "§ app = tornado.web.Application([",
        "§     (r'/hello', HelloHandler),",
        "§     (r'/ws', WebSocketHandler),",
        "§ ])",
        "§ app.listen(8888)",
        "§ tornado.ioloop.IOLoop.current().start()",
      ]},
      { title: "REQUEST HANDLERS", lines: [
        "§ class MainHandler(tornado.web.RequestHandler):",
        "§     async def get(self):",
        "§         name = self.get_argument('name', 'World')",
        "§         self.write(f'Hello {name}')",
        "§     async def post(self):",
        "§         data = tornado.escape.json_decode(self.request.body)",
        "§         self.set_status(201)",
        "§         self.write(data)",
      ]},
      { title: "ROUTING", lines: [
        "§ app = tornado.web.Application([",
        "§     (r'/', MainHandler),",
        "§     (r'/users/(?P<user_id>[0-9]+)', UserHandler),",
        "§     (r'/static/(.*)', tornado.web.StaticFileHandler,",
        "§          {'path': 'static'}),",
        "§ ])",
        "URL patterns are regexes; groups become positional args",
      ]},
      { title: "ASYNC HANDLERS", lines: [
        "§ class AsyncHandler(tornado.web.RequestHandler):",
        "§     async def get(self):",
        "§         result = await some_async_function()",
        "§         self.write({'result': result})",
        "§ # HTTP fetch:",
        "§ http = tornado.httpclient.AsyncHTTPClient()",
        "§ response = await http.fetch('http://example.com')",
      ]},
      { title: "WEBSOCKETS", lines: [
        "§ class ChatHandler(tornado.websocket.WebSocketHandler):",
        "§     def open(self):",
        "§         clients.add(self)",
        "§     def on_message(self, msg):",
        "§         for c in clients: c.write_message(msg)",
        "§     def on_close(self):",
        "§         clients.discard(self)",
        "§ # JS: ws = new WebSocket('ws://host/ws')",
      ]},
      { title: "TEMPLATES", lines: [
        "§ class PageHandler(tornado.web.RequestHandler):",
        "§     def get(self):",
        "§         self.render('index.html', title='Hi', items=[])",
        "§ # index.html:",
        "§ {% for item in items %}{{ item }}{% end %}",
        "§ {{ escape(user_input) }}",
        "Auto-escaping enabled by default",
      ]},
      { title: "REQUEST & RESPONSE", lines: [
        "§ self.request.method / .headers / .body",
        "§ self.get_argument('key', default=None)",
        "§ self.get_body_argument('key')",
        "§ self.request.files['file'][0]['body']",
        "§ self.set_header('Content-Type', 'application/json')",
        "§ self.set_status(200)",
        "§ self.write(json.dumps(data))",
      ]},
      { title: "COOKIES & SESSIONS", lines: [
        "§ self.set_cookie('user_id', str(user.id), httponly=True)",
        "§ self.get_cookie('user_id')",
        "§ # Secure signed cookie:",
        "§ self.set_secure_cookie('user_id', str(user.id))",
        "§ self.get_secure_cookie('user_id')",
        "§ cookie_secret='random-secret-key' in Application settings",
      ]},
      { title: "IOLOOP BASICS", lines: [
        "§ loop = tornado.ioloop.IOLoop.current()",
        "§ loop.run_sync(main_coroutine)",
        "§ # Periodic callback:",
        "§ cb = tornado.ioloop.PeriodicCallback(check, 5000)",
        "§ cb.start()",
        "§ # Schedule once:",
        "§ loop.call_later(30, one_time_task)",
        "Single-threaded event loop; never block the loop",
      ]},
      { title: "ERROR HANDLING", lines: [
        "§ def write_error(self, status_code, **kwargs):",
        "§     self.write({'error': self._reason})",
        "§ raise tornado.web.HTTPError(404, 'Not found')",
        "§ raise tornado.web.Finish()  # stop handler, no error",
        "§ # Unhandled exceptions return 500",
      ]},
      { title: "TESTING", lines: [
        "§ from tornado.testing import AsyncHTTPTestCase",
        "§ class Test(AsyncHTTPTestCase):",
        "§     def get_app(self): return app",
        "§     def test_get(self):",
        "§         resp = self.fetch('/hello')",
        "§         self.assertEqual(resp.code, 200)",
        "§         self.assertIn(b'Hello', resp.body)",
      ]},
      { title: "COMMON GOTCHAS", lines: [
        "Blocking I/O in handlers stalls all requests",
        "Use run_on_executor for CPU-bound code",
        "WebSocket check_origin() returns False by default for XSS",
        "Exceptions in callbacks must be handled or they're swallowed",
        "Don't use time.sleep() — use asyncio.sleep()",
      ]},
    ],
  },
];
