import type { CheatSheetSpec, Section } from "../tech-pdf-builder";

// ── Accent colors by category ─────────────────────────────────────────────────
const ACCENT_BY_CATEGORY: Record<string, string> = {
  "programming-languages": "#3B82F6",
  "web-technologies": "#F59E0B",
  "backend-technologies": "#10B981",
  "databases": "#0EA5E9",
  "data-platforms": "#6366F1",
  "data-engineering": "#8B5CF6",
  "cloud": "#0284C7",
  "devops": "#EF4444",
  "kubernetes": "#326CE5",
  "messaging-streaming": "#F97316",
  "caching": "#DC2626",
  "api-technologies": "#D97706",
  "ai-ml": "#7C3AED",
  "generative-ai": "#C026D3",
  "ai-agents": "#2563EB",
  "mlops-llmops": "#7C3AED",
  "security": "#059669",
  "testing": "#65A30D",
  "observability": "#D97706",
  "architecture": "#64748B",
  "microservices": "#0D9488",
  "mobile": "#6D28D9",
  "desktop": "#475569",
  "networking": "#0369A1",
  "iot-edge": "#16A34A",
  "blockchain-web3": "#F59E0B",
  "enterprise": "#334155",
  "content-management": "#0F766E",
  "bi-visualization": "#DB2777",
  "distributed-systems": "#1D4ED8",
  "emerging-technologies": "#9333EA",
  "build-package-management": "#92400E",
  "developer-tools": "#7C3AED",
  "robotics": "#16A34A",
  "os-systems": "#374151",
  "search": "#2563EB",
};

// ── Emoji by category ─────────────────────────────────────────────────────────
const EMOJI_BY_CATEGORY: Record<string, string> = {
  "programming-languages": "💻",
  "web-technologies": "🌐",
  "backend-technologies": "⚙️",
  "databases": "💾",
  "data-platforms": "🗄️",
  "data-engineering": "🔧",
  "cloud": "☁️",
  "devops": "🔄",
  "kubernetes": "🎛️",
  "messaging-streaming": "📨",
  "caching": "⚡",
  "api-technologies": "🔌",
  "ai-ml": "🧠",
  "generative-ai": "✨",
  "ai-agents": "🤖",
  "mlops-llmops": "🔬",
  "security": "🔒",
  "testing": "🧪",
  "observability": "👁️",
  "architecture": "🏗️",
  "microservices": "🧩",
  "mobile": "📱",
  "desktop": "🖥️",
  "networking": "🔗",
  "iot-edge": "📡",
  "blockchain-web3": "⛓️",
  "enterprise": "🏢",
  "content-management": "📝",
  "bi-visualization": "📊",
  "distributed-systems": "🌐",
  "emerging-technologies": "🚀",
  "build-package-management": "📦",
  "developer-tools": "🛠️",
};

// ── Section templates by category ─────────────────────────────────────────────

function langSections(name: string): Section[] {
  const n = name;
  return [
    { title: "OVERVIEW & INSTALL", lines: [
      `${n} — modern, expressive programming language`,
      `§ # Check version`,
      `§ ${n.toLowerCase()} --version`,
      `Install via official installer, package manager, or version manager`,
      `Popular package managers: cargo, pip, gem, npm, brew`,
    ]},
    { title: "BASIC SYNTAX", lines: [
      `Variables, control flow, expressions`,
      `§ // Variable declaration`,
      `§ let x = 10;`,
      `§ // Conditional`,
      `§ if x > 5 { ... } else { ... }`,
      `§ // Loop`,
      `§ for item in collection { ... }`,
    ]},
    { title: "DATA TYPES", lines: [
      `Primitive: integers, floats, booleans, strings`,
      `Composite: arrays, maps, tuples, structs`,
      `§ // Typed declaration`,
      `§ let name: String = "Alice";`,
      `§ let numbers: Vec<i32> = vec![1, 2, 3];`,
      `Strong typing prevents common runtime errors`,
    ]},
    { title: "FUNCTIONS", lines: [
      `§ fn greet(name: &str) -> String {`,
      `§   format!("Hello, {}!", name)`,
      `§ }`,
      `§ let result = greet("World");`,
      `First-class functions; lambdas/closures supported`,
      `§ let double = |x| x * 2;`,
    ]},
    { title: "OOP / MODULES", lines: [
      `Structs, classes, or records with methods`,
      `§ struct User { name: String, age: u32 }`,
      `§ impl User {`,
      `§   fn new(name: &str) -> Self { ... }`,
      `§   fn greet(&self) -> String { ... }`,
      `§ }`,
      `Interfaces / traits / protocols for polymorphism`,
    ]},
    { title: "COLLECTIONS", lines: [
      `§ // Array / slice`,
      `§ let arr = [1, 2, 3];`,
      `§ // Dynamic list`,
      `§ let mut list = Vec::new();`,
      `§ list.push(42);`,
      `§ // Map / dictionary`,
      `§ let mut map = HashMap::new();`,
      `§ map.insert("key", "value");`,
    ]},
    { title: "ERROR HANDLING", lines: [
      `Result/Option types or exceptions`,
      `§ fn read_file(path: &str) -> Result<String, Error> {`,
      `§   Ok(std::fs::read_to_string(path)?)`,
      `§ }`,
      `§ match result {`,
      `§   Ok(data) => process(data),`,
      `§   Err(e) => eprintln!("Error: {}", e),`,
      `§ }`,
    ]},
    { title: "CONCURRENCY / ASYNC", lines: [
      `Threads, async/await, or actor model`,
      `§ async fn fetch_data(url: &str) -> Result<String> {`,
      `§   let resp = client.get(url).await?;`,
      `§   resp.text().await`,
      `§ }`,
      `§ tokio::main / async_std / smol`,
      `Green threads or OS threads depending on runtime`,
    ]},
    { title: "TESTING", lines: [
      `Built-in or framework test support`,
      `§ #[test]`,
      `§ fn test_greet() {`,
      `§   assert_eq!(greet("Alice"), "Hello, Alice!");`,
      `§ }`,
      `§ cargo test  /  run test suite`,
      `Unit tests co-located with source code`,
    ]},
    { title: "ECOSYSTEM & PACKAGES", lines: [
      `Package registry and dependency management`,
      `§ # Add dependency`,
      `§ cargo add serde`,
      `§ # In Cargo.toml:`,
      `§ [dependencies]`,
      `§ serde = { version = "1.0", features = ["derive"] }`,
      `Curated ecosystem with popular libraries for HTTP, JSON, DB`,
    ]},
    { title: "CLI & BUILD TOOLS", lines: [
      `§ cargo build  — compile project`,
      `§ cargo run    — build and run`,
      `§ cargo test   — run tests`,
      `§ cargo fmt    — format code`,
      `§ cargo clippy — linting`,
      `§ cargo doc    — generate documentation`,
      `Integrated toolchain for build, test, and docs`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `Follow language-specific naming conventions`,
      `Understand ownership/borrowing/GC model for this language`,
      `Use idiomatic patterns — don't port code from other languages`,
      `Check community guidelines for error handling approach`,
      `Profile before optimizing — correctness first`,
    ]},
  ];
}

function databaseSections(name: string): Section[] {
  return [
    { title: "OVERVIEW & SETUP", lines: [
      `${name} — powerful database solution`,
      `§ # Install (Docker):`,
      `§ docker run -d --name mydb \\`,
      `§   -e DB_PASSWORD=secret \\`,
      `§   -p 5432:5432 ${name.toLowerCase()}:latest`,
      `Connect: host, port, user, password, database name`,
    ]},
    { title: "INSTALLATION & CONFIG", lines: [
      `§ # Package manager install`,
      `§ brew install ${name.toLowerCase()}`,
      `§ # Or download from official site`,
      `Config file: ${name.toLowerCase()}.conf or similar`,
      `Set max connections, memory, storage paths`,
      `§ # Start service`,
      `§ systemctl start ${name.toLowerCase()}`,
    ]},
    { title: "DATA MODELING", lines: [
      `Define schemas, tables/collections, data types`,
      `§ -- Create table (SQL example):`,
      `§ CREATE TABLE users (`,
      `§   id SERIAL PRIMARY KEY,`,
      `§   name VARCHAR(100) NOT NULL,`,
      `§   email VARCHAR(200) UNIQUE NOT NULL`,
      `§ );`,
      `Normalize for consistency; denormalize for performance`,
    ]},
    { title: "CRUD OPERATIONS", lines: [
      `§ -- INSERT`,
      `§ INSERT INTO users (name, email) VALUES ('Alice', 'a@b.com');`,
      `§ -- SELECT`,
      `§ SELECT * FROM users WHERE active = true;`,
      `§ -- UPDATE`,
      `§ UPDATE users SET name = 'Bob' WHERE id = 1;`,
      `§ -- DELETE`,
      `§ DELETE FROM users WHERE id = 1;`,
    ]},
    { title: "QUERYING", lines: [
      `§ SELECT u.*, o.total`,
      `§ FROM users u`,
      `§ JOIN orders o ON o.user_id = u.id`,
      `§ WHERE o.status = 'paid'`,
      `§ ORDER BY o.created_at DESC`,
      `§ LIMIT 10 OFFSET 20;`,
      `Use EXPLAIN/EXPLAIN ANALYZE to inspect query plans`,
    ]},
    { title: "INDEXING", lines: [
      `§ CREATE INDEX idx_users_email ON users(email);`,
      `§ CREATE UNIQUE INDEX idx_users_email_unique ON users(email);`,
      `§ -- Composite index:`,
      `§ CREATE INDEX idx_orders ON orders(user_id, status, created_at);`,
      `Index columns used in WHERE, JOIN, ORDER BY clauses`,
      `Too many indexes slow writes — profile before adding`,
    ]},
    { title: "TRANSACTIONS", lines: [
      `§ BEGIN;`,
      `§   UPDATE accounts SET balance = balance - 100 WHERE id = 1;`,
      `§   UPDATE accounts SET balance = balance + 100 WHERE id = 2;`,
      `§ COMMIT;`,
      `§ -- On error:`,
      `§ ROLLBACK;`,
      `ACID: Atomicity, Consistency, Isolation, Durability`,
    ]},
    { title: "REPLICATION & HA", lines: [
      `Primary-replica replication for read scaling`,
      `§ # Primary: enable binary logging / WAL`,
      `§ # Replica: point to primary host`,
      `Automatic failover with Patroni/Sentinel/etc`,
      `Read from replicas; write to primary only`,
      `Monitor replication lag — alert if > threshold`,
    ]},
    { title: "SECURITY", lines: [
      `Create least-privilege database users`,
      `§ CREATE USER appuser WITH PASSWORD 'secret';`,
      `§ GRANT SELECT, INSERT, UPDATE ON users TO appuser;`,
      `Enable SSL/TLS for connections in transit`,
      `Encrypt sensitive columns at application layer`,
      `Regular security updates and patches`,
    ]},
    { title: "MONITORING & PERF", lines: [
      `Monitor query performance, connections, disk I/O`,
      `§ -- Slow query log`,
      `§ SET log_min_duration_statement = 1000;  -- 1s`,
      `EXPLAIN ANALYZE for individual query tuning`,
      `Connection pooling: PgBouncer, ProxySQL, HikariCP`,
      `Vacuum/ANALYZE (PostgreSQL) or OPTIMIZE (MySQL)`,
    ]},
    { title: "CLI / TOOLS", lines: [
      `§ psql -h host -U user -d database`,
      `§ \\l  — list databases  \\dt — list tables`,
      `§ \\d users — describe table structure`,
      `§ -- Backup:`,
      `§ pg_dump dbname > backup.sql`,
      `§ -- Restore:`,
      `§ psql dbname < backup.sql`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `Never store plaintext passwords — use bcrypt/Argon2`,
      `Use connection pooling — raw connections are expensive`,
      `Always parameterize queries — prevent SQL injection`,
      `Regular backups with point-in-time recovery`,
      `Test failover procedures before production incidents`,
    ]},
  ];
}

function cloudSections(name: string): Section[] {
  return [
    { title: "OVERVIEW & SETUP", lines: [
      `${name} — managed cloud service`,
      `§ # Install CLI`,
      `§ aws configure  /  az login  /  gcloud auth login`,
      `§ # Set region`,
      `§ aws configure set region us-east-1`,
      `Use IAM roles in production, not access keys`,
    ]},
    { title: "AUTHENTICATION & IAM", lines: [
      `IAM Roles, Policies, and Least Privilege`,
      `§ # Assume role`,
      `§ aws sts assume-role --role-arn arn:aws:iam::123:role/MyRole \\`,
      `§   --role-session-name session`,
      `§ # Attach policy to role`,
      `§ aws iam attach-role-policy --role-name MyRole \\`,
      `§   --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess`,
    ]},
    { title: "CORE FEATURES", lines: [
      `Key capabilities and use cases for this service`,
      `§ # Create resource`,
      `§ aws <service> create-<resource> --name MyResource`,
      `§ # List resources`,
      `§ aws <service> list-<resources>`,
      `§ # Describe resource`,
      `§ aws <service> describe-<resource> --name MyResource`,
    ]},
    { title: "CONFIGURATION", lines: [
      `§ # AWS CLI config: ~/.aws/credentials`,
      `§ [default]`,
      `§ aws_access_key_id = AKIA...`,
      `§ aws_secret_access_key = ...`,
      `§ region = us-east-1`,
      `§ output = json`,
      `Prefer environment variables or instance profiles over config files`,
    ]},
    { title: "MONITORING & ALERTS", lines: [
      `Enable CloudWatch / Azure Monitor / Cloud Monitoring`,
      `§ # Create CloudWatch alarm`,
      `§ aws cloudwatch put-metric-alarm \\`,
      `§   --alarm-name HighCPU \\`,
      `§   --comparison-operator GreaterThanThreshold \\`,
      `§   --threshold 80`,
      `Set dashboards for key metrics before production launch`,
    ]},
    { title: "SECURITY BEST PRACTICES", lines: [
      `Enable encryption at rest and in transit`,
      `§ # Enable server-side encryption`,
      `§ --sse-algorithm aws:kms`,
      `§ --kms-key-id arn:aws:kms:...`,
      `Rotate credentials regularly`,
      `Enable CloudTrail / activity logs for audit`,
      `Use VPC for network isolation`,
    ]},
    { title: "SDK USAGE", lines: [
      `§ # Python (boto3)`,
      `§ import boto3`,
      `§ client = boto3.client('s3', region_name='us-east-1')`,
      `§ client.upload_file('file.txt', 'my-bucket', 'key')`,
      `§ # Node.js`,
      `§ const AWS = require('@aws-sdk/client-s3')`,
      `Use SDK over direct HTTP for automatic retry/signing`,
    ]},
    { title: "CLI COMMANDS", lines: [
      `§ aws <service> help`,
      `§ aws <service> list-<resources> --query '...' --output table`,
      `§ aws <service> create-<resource> --cli-input-json file://input.json`,
      `§ aws <service> delete-<resource> --name ...`,
      `§ aws cloudformation deploy --template-file template.yaml`,
    ]},
    { title: "INTEGRATION PATTERNS", lines: [
      `Event-driven: trigger functions on service events`,
      `§ # SNS → Lambda → SQS pattern`,
      `§ # API Gateway → Lambda → DB`,
      `Use managed services over self-hosted where possible`,
      `Infrastructure as Code: Terraform/CDK/CloudFormation`,
      `Multi-region for disaster recovery`,
    ]},
    { title: "PRICING & COST OPT", lines: [
      `Understand pricing model: per request, per GB, per hour`,
      `Use Reserved Instances / Committed Use for 30-70% savings`,
      `Enable Cost Explorer / budget alerts`,
      `Right-size resources regularly`,
      `§ # Tag resources for cost allocation`,
      `§ aws <service> tag-resource --tags Project=myapp Env=prod`,
    ]},
    { title: "DEPLOYMENT PATTERNS", lines: [
      `Blue/Green: shift traffic between environments`,
      `Canary: gradual traffic shift with rollback`,
      `§ # Infrastructure as Code`,
      `§ terraform init && terraform plan && terraform apply`,
      `§ # Or CloudFormation`,
      `§ aws cloudformation deploy --stack-name myapp \\`,
      `§   --template-file infra.yaml`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `Never commit credentials to git — use secrets manager`,
      `Check service quotas before scaling`,
      `Test in staging before production deployments`,
      `Enable MFA for root account and admin users`,
      `Review IAM policies regularly — remove unused permissions`,
    ]},
  ];
}

function devopsSections(name: string): Section[] {
  return [
    { title: "OVERVIEW & INSTALL", lines: [
      `${name} — DevOps and automation tool`,
      `§ # Install`,
      `§ brew install ${name.toLowerCase().replace(/\s/g, '-')}`,
      `§ # Or via official installer`,
      `§ curl -L https://... | sh`,
      `§ ${name.toLowerCase().split(' ')[0]} version`,
    ]},
    { title: "CORE CONCEPTS", lines: [
      `Key abstractions and terminology`,
      `Declarative configuration — define desired state`,
      `Reconciliation loop keeps actual state = desired state`,
      `§ # Check current state`,
      `§ ${name.toLowerCase().split(' ')[0]} status`,
      `Infrastructure as Code: version control your infra`,
    ]},
    { title: "CONFIGURATION", lines: [
      `§ # Main config file`,
      `§ ${name.toLowerCase().split(' ')[0]}.yaml / ${name.toLowerCase().split(' ')[0]}.tf / .${name.toLowerCase().split(' ')[0]}rc`,
      `§ # Set environment`,
      `§ export ${name.toUpperCase().replace(/\s/g, '_')}_HOME=/path/to/config`,
      `Use environment-specific configs for dev/staging/prod`,
      `§ # Validate config`,
      `§ ${name.toLowerCase().split(' ')[0]} validate`,
    ]},
    { title: "CORE COMMANDS", lines: [
      `§ ${name.toLowerCase().split(' ')[0]} init       # initialize`,
      `§ ${name.toLowerCase().split(' ')[0]} plan       # preview changes`,
      `§ ${name.toLowerCase().split(' ')[0]} apply      # apply changes`,
      `§ ${name.toLowerCase().split(' ')[0]} destroy    # tear down`,
      `§ ${name.toLowerCase().split(' ')[0]} --help     # help`,
      `§ ${name.toLowerCase().split(' ')[0]} version    # check version`,
    ]},
    { title: "INTEGRATION & CI/CD", lines: [
      `Integrate with GitHub Actions / GitLab CI / Jenkins`,
      `§ # GitHub Actions example`,
      `§ - name: Run ${name}`,
      `§   uses: ${name.toLowerCase().split(' ')[0]}-actions/github@v1`,
      `§   with:`,
      `§     command: apply`,
      `Automate validation and deployment in pipelines`,
    ]},
    { title: "SECURITY", lines: [
      `Follow principle of least privilege`,
      `Store secrets in vault (Vault, AWS Secrets Manager, etc)`,
      `Scan configs for security misconfigurations`,
      `§ # Example: secret management`,
      `§ secret = data.vault_secret.db_password.data["password"]`,
      `Enable audit logging for all changes`,
    ]},
    { title: "MONITORING & OBSERVABILITY", lines: [
      `Monitor deployment status and health`,
      `§ # Check status`,
      `§ ${name.toLowerCase().split(' ')[0]} status`,
      `§ ${name.toLowerCase().split(' ')[0]} logs`,
      `Set up alerts for deployment failures`,
      `Track drift between desired and actual state`,
    ]},
    { title: "SCALING & PERFORMANCE", lines: [
      `Scale horizontally — add more replicas`,
      `Use caching and batching for expensive operations`,
      `§ # Scale configuration`,
      `§ replicas: 3`,
      `§ resources:`,
      `§   requests: { cpu: "100m", memory: "128Mi" }`,
      `§   limits: { cpu: "500m", memory: "512Mi" }`,
    ]},
    { title: "BEST PRACTICES", lines: [
      `Version control all configuration files`,
      `Use GitOps: git as single source of truth`,
      `Implement drift detection — alert on manual changes`,
      `§ # Lint and validate before applying`,
      `§ ${name.toLowerCase().split(' ')[0]} validate && ${name.toLowerCase().split(' ')[0]} plan`,
      `Test in dev/staging before production`,
    ]},
    { title: "TROUBLESHOOTING", lines: [
      `§ ${name.toLowerCase().split(' ')[0]} status --verbose`,
      `§ ${name.toLowerCase().split(' ')[0]} logs --follow`,
      `Check events and error logs first`,
      `Verify network connectivity and credentials`,
      `§ # Debug mode`,
      `§ ${name.toUpperCase().split(' ')[0]}_LOG=debug ${name.toLowerCase().split(' ')[0]} apply`,
    ]},
    { title: "CLI REFERENCE", lines: [
      `§ ${name.toLowerCase().split(' ')[0]} --help           # full help`,
      `§ ${name.toLowerCase().split(' ')[0]} version          # show version`,
      `§ ${name.toLowerCase().split(' ')[0]} config           # manage config`,
      `§ ${name.toLowerCase().split(' ')[0]} apply -auto-approve # skip prompt`,
      `§ ${name.toLowerCase().split(' ')[0]} output           # show outputs`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `Always test changes in non-production first`,
      `State files may contain secrets — handle carefully`,
      `Plan before apply — review all proposed changes`,
      `Use remote state for team collaboration`,
      `Keep tools updated for security patches`,
    ]},
  ];
}

function aiMlSections(name: string): Section[] {
  return [
    { title: "OVERVIEW & SETUP", lines: [
      `${name} — AI/ML framework`,
      `§ pip install ${name.toLowerCase().replace(/\s/g, '-')}`,
      `§ # Verify installation`,
      `§ python -c "import ${name.toLowerCase().split('/')[0].replace(/\s/g, '_')}; print('OK')"`,
      `§ # GPU support check`,
      `§ import torch; print(torch.cuda.is_available())",`,
      `Use virtual environment: python -m venv venv`,
    ]},
    { title: "DATA PREPARATION", lines: [
      `§ import pandas as pd`,
      `§ df = pd.read_csv('data.csv')`,
      `§ X = df.drop('target', axis=1).values`,
      `§ y = df['target'].values`,
      `§ from sklearn.model_selection import train_test_split`,
      `§ X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)`,
      `Normalize/standardize features for best results`,
    ]},
    { title: "MODEL DEFINITION", lines: [
      `§ # Simple neural network:`,
      `§ import torch.nn as nn`,
      `§ class Model(nn.Module):`,
      `§   def __init__(self):`,
      `§     super().__init__()`,
      `§     self.layers = nn.Sequential(`,
      `§       nn.Linear(input_size, 128),`,
      `§       nn.ReLU(),`,
      `§       nn.Linear(128, num_classes)`,
      `§     )`,
      `§   def forward(self, x): return self.layers(x)`,
    ]},
    { title: "TRAINING LOOP", lines: [
      `§ optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)`,
      `§ criterion = nn.CrossEntropyLoss()`,
      `§ for epoch in range(num_epochs):`,
      `§   for batch_X, batch_y in dataloader:`,
      `§     optimizer.zero_grad()`,
      `§     output = model(batch_X)`,
      `§     loss = criterion(output, batch_y)`,
      `§     loss.backward()`,
      `§     optimizer.step()`,
    ]},
    { title: "EVALUATION", lines: [
      `§ from sklearn.metrics import accuracy_score, classification_report`,
      `§ model.eval()`,
      `§ with torch.no_grad():`,
      `§   preds = model(X_test)`,
      `§ accuracy = accuracy_score(y_test, preds.argmax(1))`,
      `§ print(classification_report(y_test, preds.argmax(1)))`,
      `Track precision, recall, F1; use confusion matrix`,
    ]},
    { title: "INFERENCE & SERVING", lines: [
      `§ # Save model`,
      `§ torch.save(model.state_dict(), 'model.pt')`,
      `§ # Load model`,
      `§ model.load_state_dict(torch.load('model.pt'))`,
      `§ model.eval()`,
      `§ # Inference`,
      `§ with torch.no_grad():`,
      `§   prediction = model(input_tensor)`,
    ]},
    { title: "HYPERPARAMETERS", lines: [
      `Learning rate: start with 1e-3, tune with scheduler`,
      `Batch size: 32-256 depending on GPU memory`,
      `Epochs: use early stopping to prevent overfitting`,
      `§ scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer)`,
      `§ scheduler.step(val_loss)`,
      `Grid search or Optuna for systematic tuning`,
    ]},
    { title: "DATASETS & LOADERS", lines: [
      `§ from torch.utils.data import Dataset, DataLoader`,
      `§ class MyDataset(Dataset):`,
      `§   def __len__(self): return len(self.data)`,
      `§   def __getitem__(self, idx): return self.data[idx]`,
      `§ loader = DataLoader(dataset, batch_size=32, shuffle=True, num_workers=4)`,
      `Pin memory for faster GPU data transfer`,
    ]},
    { title: "OPTIMIZATION TECHNIQUES", lines: [
      `Mixed precision: torch.cuda.amp.autocast()",`,
      `Gradient clipping: clip_grad_norm_(model.parameters(), 1.0)",`,
      `Batch normalization: nn.BatchNorm1d()",`,
      `Dropout: nn.Dropout(0.5) for regularization",`,
      `§ # Learning rate warmup`,
      `§ from transformers import get_linear_schedule_with_warmup`,
    ]},
    { title: "FRAMEWORKS & TOOLS", lines: [
      `§ TensorFlow / Keras    — production ML`,
      `§ PyTorch               — research & NLP`,
      `§ Scikit-learn          — classical ML`,
      `§ Hugging Face          — pretrained transformers`,
      `§ MLflow / W&B          — experiment tracking`,
      `§ ONNX                  — model export/portability`,
    ]},
    { title: "DEPLOYMENT", lines: [
      `§ # Export to ONNX`,
      `§ torch.onnx.export(model, dummy_input, 'model.onnx')`,
      `§ # FastAPI serving example`,
      `§ @app.post('/predict')`,
      `§ def predict(data: InputData):`,
      `§   tensor = preprocess(data)`,
      `§   return model(tensor).tolist()`,
      `Use TorchServe, BentoML, or Triton for production`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `Gradient explosion: use gradient clipping",`,
      `Memory leak: always zero_grad() before backward()",`,
      `Train/eval mode: model.train() vs model.eval()",`,
      `GPU-CPU mismatch: ensure all tensors on same device",`,
      `Data leakage: split before normalization, not after",`,
    ]},
  ];
}

function apiSections(name: string): Section[] {
  return [
    { title: "OVERVIEW", lines: [
      `${name} — API style/protocol for service communication`,
      `Key principles and design philosophy`,
      `Compare to REST, SOAP, GraphQL alternatives`,
      `§ # Typical request`,
      `§ curl -X POST https://api.example.com/graphql \\`,
      `§   -H 'Content-Type: application/json' \\`,
      `§   -d '{"query": "{ users { id name } }"}'`,
    ]},
    { title: "CORE CONCEPTS", lines: [
      `Schema: defines types, queries, mutations`,
      `Operations: Query (read), Mutation (write), Subscription (real-time)`,
      `Resolver: function that returns data for a field`,
      `§ # Schema example:`,
      `§ type User { id: ID!, name: String!, email: String! }`,
      `§ type Query { user(id: ID!): User, users: [User!]! }`,
    ]},
    { title: "SETUP & SERVER", lines: [
      `§ npm install apollo-server graphql`,
      `§ const { ApolloServer } = require('@apollo/server')`,
      `§ const server = new ApolloServer({ typeDefs, resolvers })`,
      `§ await server.listen({ port: 4000 })`,
      `§ # GraphQL Playground at http://localhost:4000`,
    ]},
    { title: "QUERIES & MUTATIONS", lines: [
      `§ # Query`,
      `§ query { user(id: "1") { name email } }`,
      `§ # Mutation`,
      `§ mutation { createUser(name: "Alice", email: "a@b.com") { id } }`,
      `§ # Variables`,
      `§ query GetUser($id: ID!) { user(id: $id) { name } }`,
      `§ { "id": "123" }`,
    ]},
    { title: "RESOLVERS", lines: [
      `§ const resolvers = {`,
      `§   Query: {`,
      `§     user: (_, { id }, ctx) => ctx.db.users.findById(id),`,
      `§     users: (_, __, ctx) => ctx.db.users.findAll(),`,
      `§   },`,
      `§   Mutation: {`,
      `§     createUser: (_, args, ctx) => ctx.db.users.create(args),`,
      `§   },`,
      `§ }`,
    ]},
    { title: "AUTH & SECURITY", lines: [
      `Add auth in context or middleware`,
      `§ const server = new ApolloServer({`,
      `§   context: async ({ req }) => ({`,
      `§     user: await authenticate(req.headers.authorization),`,
      `§     db,`,
      `§   }),`,
      `§ })`,
      `Validate and sanitize all inputs`,
      `Rate limit and depth-limit queries`,
    ]},
    { title: "ERROR HANDLING", lines: [
      `§ throw new UserInputError('Invalid input', { field: 'email' })`,
      `§ throw new AuthenticationError('Not authenticated')`,
      `§ throw new ForbiddenError('Not authorized')`,
      `Errors returned in errors[] array alongside data`,
      `Use formatError to sanitize error messages in production`,
    ]},
    { title: "SUBSCRIPTIONS", lines: [
      `§ type Subscription { messageAdded: Message! }`,
      `§ Subscription: {`,
      `§   messageAdded: {`,
      `§     subscribe: () => pubsub.asyncIterator(['MESSAGE_ADDED'])`,
      `§   }`,
      `§ }`,
      `§ pubsub.publish('MESSAGE_ADDED', { messageAdded: msg })`,
      `Requires WebSocket transport (subscriptions-transport-ws or graphql-ws)",`,
    ]},
    { title: "PERFORMANCE", lines: [
      `N+1 problem: use DataLoader for batching`,
      `§ const userLoader = new DataLoader(ids => batchLoadUsers(ids))`,
      `§ Query.user = (_, { id }) => userLoader.load(id)`,
      `Persisted queries: cache query document hash`,
      `Response caching: @cacheControl directive`,
      `Field-level tracing for performance analysis`,
    ]},
    { title: "TOOLING", lines: [
      `§ GraphQL Playground / Apollo Studio — interactive IDE`,
      `§ graphql-codegen   — generate types from schema`,
      `§ graphql-inspector — schema diff/validation`,
      `§ Apollo Client     — frontend integration`,
      `§ urql              — lightweight GraphQL client`,
      `§ graphql-shield    — permission layer`,
    ]},
    { title: "TESTING", lines: [
      `§ # Apollo Server integration test`,
      `§ const { query } = createTestClient(server)`,
      `§ const { data } = await query({ query: GET_USER, variables: { id: '1' } })`,
      `§ expect(data.user.name).toBe('Alice')`,
      `Test resolvers in isolation with mock context`,
      `Use Jest or Vitest as test runner`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `N+1 queries: always use DataLoader for relations`,
      `Query depth limiting: prevent DoS attacks`,
      `Don't expose internal error details in production`,
      `Schema-first vs code-first: choose one approach`,
      `Subscriptions need separate WebSocket transport setup`,
    ]},
  ];
}

function genericSections(name: string, category: string): Section[] {
  return [
    { title: "OVERVIEW & SETUP", lines: [
      `${name} — ${category} technology`,
      `§ # Install`,
      `§ npm install ${name.toLowerCase().replace(/\s/g, '-')}`,
      `§ # Or: pip install / gem install / go get`,
      `Check official documentation at docs.${name.toLowerCase().replace(/\s/g, '')}.com`,
      `Verify installation before proceeding`,
    ]},
    { title: "CORE CONCEPTS", lines: [
      `Key abstraction: understand the primary model`,
      `Configuration: define behavior through config/code`,
      `Integration: connects with existing systems`,
      `§ # Initialize`,
      `§ const client = new ${name.replace(/\s/g, '')}({ /* config */ })`,
    ]},
    { title: "QUICK START", lines: [
      `§ # Minimal working example`,
      `§ const app = new ${name.replace(/\s/g, '')}()`,
      `§ app.configure({ ... })`,
      `§ await app.start()`,
      `§ console.log('${name} is running')`,
      `See official quickstart guide for language-specific setup`,
    ]},
    { title: "CONFIGURATION", lines: [
      `§ # config.yaml or config.json`,
      `§ ${name.toLowerCase().split(' ')[0]}:`,
      `§   host: localhost`,
      `§   port: 8080`,
      `§   timeout: 30s`,
      `Use environment variables for secrets`,
      `§ export ${name.toUpperCase().replace(/\s/g, '_')}_SECRET=my-secret`,
    ]},
    { title: "BASIC OPERATIONS", lines: [
      `§ # Create / write`,
      `§ client.create({ name: 'example' })`,
      `§ # Read / query`,
      `§ const result = await client.find({ filter: {} })`,
      `§ # Update`,
      `§ await client.update(id, { field: newValue })`,
      `§ # Delete`,
      `§ await client.delete(id)`,
    ]},
    { title: "INTEGRATION", lines: [
      `Integrates with common frameworks and tools`,
      `§ # Express.js integration example`,
      `§ app.use(${name.replace(/\s/g, '')}Middleware({ config }))`,
      `SDK available for: Node.js, Python, Java, Go, .NET`,
      `REST API available for language-agnostic integration`,
      `Check community-maintained integrations`,
    ]},
    { title: "SECURITY", lines: [
      `Always use authentication and authorization`,
      `Encrypt data at rest and in transit (TLS/SSL)`,
      `§ # Enable TLS`,
      `§ tls: { cert: ./cert.pem, key: ./key.pem }`,
      `Rotate credentials and API keys regularly`,
      `Follow security best practices in official docs`,
    ]},
    { title: "MONITORING", lines: [
      `Expose health check endpoint`,
      `§ # Health check`,
      `§ GET /health → { status: 'ok', uptime: 1234 }`,
      `Monitor key metrics: latency, throughput, error rate`,
      `Set up alerts for anomalies`,
      `Log requests with structured logging (JSON format)`,
    ]},
    { title: "PERFORMANCE TIPS", lines: [
      `Use connection pooling for network resources`,
      `Enable caching for frequently accessed data`,
      `Batch operations to reduce round trips`,
      `§ # Async/parallel processing`,
      `§ await Promise.all([op1(), op2(), op3()])`,
      `Profile before optimizing — measure, then improve`,
    ]},
    { title: "TESTING", lines: [
      `§ # Unit test example`,
      `§ describe('${name}', () => {`,
      `§   it('should work', async () => {`,
      `§     const result = await client.doSomething()`,
      `§     expect(result).toBeDefined()`,
      `§   })`,
      `§ })`,
      `Use mocks for external dependencies in unit tests`,
    ]},
    { title: "CLI REFERENCE", lines: [
      `§ ${name.toLowerCase().split(' ')[0]} --help       # all commands`,
      `§ ${name.toLowerCase().split(' ')[0]} version      # version info`,
      `§ ${name.toLowerCase().split(' ')[0]} config       # configuration`,
      `§ ${name.toLowerCase().split(' ')[0]} status       # current status`,
      `§ ${name.toLowerCase().split(' ')[0]} logs         # view logs`,
    ]},
    { title: "COMMON GOTCHAS", lines: [
      `Read the changelog before upgrading major versions`,
      `Check resource limits (memory, connections, rate limits)`,
      `Implement graceful shutdown to avoid data loss`,
      `Keep dependencies updated for security patches`,
      `Test in staging environment before deploying to production`,
    ]},
  ];
}

// ── Main export ──────────────────────────────────────────────────────────────

export function generateGenericCheatSheet(
  name: string,
  slug: string,
  categorySlug: string,
  categoryLabel: string,
): CheatSheetSpec {
  const accent = ACCENT_BY_CATEGORY[categorySlug] ?? "#2563EB";
  const emoji = EMOJI_BY_CATEGORY[categorySlug] ?? "⚙️";

  let sections: Section[];

  if (categorySlug === "programming-languages") {
    sections = langSections(name);
  } else if (categorySlug === "databases") {
    sections = databaseSections(name);
  } else if (categorySlug === "cloud") {
    sections = cloudSections(name);
  } else if (categorySlug === "devops" || categorySlug === "kubernetes") {
    sections = devopsSections(name);
  } else if (categorySlug === "ai-ml" || categorySlug === "generative-ai" || categorySlug === "mlops-llmops") {
    sections = aiMlSections(name);
  } else if (categorySlug === "api-technologies") {
    sections = apiSections(name);
  } else {
    sections = genericSections(name, categoryLabel);
  }

  return {
    name,
    subtitle: `${categoryLabel} · Quick Reference`,
    emoji,
    accentHex: accent,
    sections,
  };
}
