import type { Question } from "../pdf-builder";

type Bank = Record<string, Question[]>;

const BANKS: Bank = {

"nouns": [
  { question: "A ___ is a naming word.", answer: "noun" },
  { question: "'Dog' is a ___ noun.", answer: "common" },
  { question: "'London' is a ___ noun.", answer: "proper" },
  { question: "'Happiness' is an ___ noun.", answer: "abstract" },
  { question: "'Flock' is a ___ noun.", answer: "collective" },
  { question: "Nouns can act as subject or ___ in a sentence.", answer: "object" },
  { question: "A noun that can be counted is a ___ noun.", answer: "countable" },
  { question: "'Water' is an ___ noun.", answer: "uncountable" },
  { question: "Plural of 'child' is ___.", answer: "children" },
  { question: "Plural of 'ox' is ___.", answer: "oxen" },
  { question: "Plural of 'leaf' is ___.", answer: "leaves" },
  { question: "Plural of 'city' is ___.", answer: "cities" },
  { question: "Plural of 'mouse' is ___.", answer: "mice" },
  { question: "'Team' is a ___ noun.", answer: "collective" },
  { question: "'Beauty' is an ___ noun.", answer: "abstract" },
  { question: "'River Nile' is a ___ noun.", answer: "proper" },
  { question: "Plural of 'knife' is ___.", answer: "knives" },
  { question: "Plural of 'tooth' is ___.", answer: "teeth" },
  { question: "Plural of 'goose' is ___.", answer: "geese" },
  { question: "'Courage' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'shelf' is ___.", answer: "shelves" },
  { question: "Plural of 'hero' is ___.", answer: "heroes" },
  { question: "'Army' is a ___ noun.", answer: "collective" },
  { question: "Plural of 'foot' is ___.", answer: "feet" },
  { question: "'India' is a ___ noun.", answer: "proper" },
  { question: "Plural of 'mango' is ___.", answer: "mangoes" },
  { question: "Plural of 'bench' is ___.", answer: "benches" },
  { question: "Plural of 'man' is ___.", answer: "men" },
  { question: "'Crowd' is a ___ noun.", answer: "collective" },
  { question: "A noun is the name of a person, place, or ___.", answer: "thing" },
  { question: "Plural of 'potato' is ___.", answer: "potatoes" },
  { question: "Plural of 'woman' is ___.", answer: "women" },
  { question: "'Anger' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'calf' is ___.", answer: "calves" },
  { question: "'Monday' is a ___ noun.", answer: "proper" },
  { question: "Plural of 'box' is ___.", answer: "boxes" },
  { question: "Plural of 'berry' is ___.", answer: "berries" },
  { question: "Plural of 'half' is ___.", answer: "halves" },
  { question: "'Knowledge' is an ___ noun.", answer: "abstract" },
  { question: "'Fleet' (of ships) is a ___ noun.", answer: "collective" },
  { question: "Plural of 'deer' is ___.", answer: "deer" },
  { question: "Plural of 'sheep' is ___.", answer: "sheep" },
  { question: "Plural of 'fish' is ___.", answer: "fish" },
  { question: "Plural of 'wolf' is ___.", answer: "wolves" },
  { question: "Plural of 'loaf' is ___.", answer: "loaves" },
  { question: "'Faith' is an ___ noun.", answer: "abstract" },
  { question: "'Class' is a ___ noun.", answer: "collective" },
  { question: "Plural of 'radius' is ___.", answer: "radii" },
  { question: "Plural of 'crisis' is ___.", answer: "crises" },
  { question: "Plural of 'phenomenon' is ___.", answer: "phenomena" },
  { question: "'Pride' (of lions) is a ___ noun.", answer: "collective" },
  { question: "Plural of 'axis' is ___.", answer: "axes" },
  { question: "'Parliament' is a ___ noun.", answer: "collective" },
  { question: "'Wisdom' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'torch' is ___.", answer: "torches" },
  { question: "Plural of 'baby' is ___.", answer: "babies" },
  { question: "Plural of 'knife' is ___.", answer: "knives" },
  { question: "'Loyalty' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'nucleus' is ___.", answer: "nuclei" },
  { question: "'Galaxy' is a ___ noun.", answer: "proper" },
  { question: "Plural of 'piano' is ___.", answer: "pianos" },
  { question: "Plural of 'roof' is ___.", answer: "roofs" },
  { question: "Plural of 'cliff' is ___.", answer: "cliffs" },
  { question: "'Amazon' (river) is a ___ noun.", answer: "proper" },
  { question: "'Justice' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'medium' is ___.", answer: "media" },
  { question: "Plural of 'memorandum' is ___.", answer: "memoranda" },
  { question: "'Poverty' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'echo' is ___.", answer: "echoes" },
  { question: "Plural of 'volcano' is ___.", answer: "volcanoes" },
  { question: "'Pride' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'ox' is ___.", answer: "oxen" },
  { question: "Plural of 'datum' is ___.", answer: "data" },
  { question: "'Bunch' (of grapes) is a ___ noun.", answer: "collective" },
  { question: "Plural of 'louse' is ___.", answer: "lice" },
  { question: "'Hiroshima' is a ___ noun.", answer: "proper" },
  { question: "Plural of 'pea' is ___.", answer: "peas" },
  { question: "'Envy' is an ___ noun.", answer: "abstract" },
  { question: "Plural of 'forum' is ___.", answer: "forums" },
  { question: "'Sympathy' is an ___ noun.", answer: "abstract" }
],

"pronouns": [
  { question: "A ___ replaces a noun.", answer: "pronoun" },
  { question: "'He', 'she', 'it' are ___ pronouns.", answer: "personal" },
  { question: "First person singular subject pronoun: ___.", answer: "I" },
  { question: "Object form of 'I' is ___.", answer: "me" },
  { question: "Object form of 'we' is ___.", answer: "us" },
  { question: "Object form of 'they' is ___.", answer: "them" },
  { question: "Object form of 'he' is ___.", answer: "him" },
  { question: "Object form of 'she' is ___.", answer: "her" },
  { question: "'Myself', 'yourself' are ___ pronouns.", answer: "reflexive" },
  { question: "'This', 'that' are ___ pronouns.", answer: "demonstrative" },
  { question: "'Who', 'which', 'that' are ___ pronouns.", answer: "relative" },
  { question: "'Everyone', 'nobody' are ___ pronouns.", answer: "indefinite" },
  { question: "Possessive pronoun for 'I' is ___.", answer: "mine" },
  { question: "Possessive pronoun for 'you' is ___.", answer: "yours" },
  { question: "Possessive pronoun for 'we' is ___.", answer: "ours" },
  { question: "Possessive pronoun for 'they' is ___.", answer: "theirs" },
  { question: "Possessive pronoun for 'he' is ___.", answer: "his" },
  { question: "'Each other' is a ___ pronoun.", answer: "reciprocal" },
  { question: "'Who' is used for ___.", answer: "persons" },
  { question: "'Which' is used for ___.", answer: "things/animals" },
  { question: "Plural of 'I' is ___.", answer: "we" },
  { question: "Plural of 'he/she' is ___.", answer: "they" },
  { question: "'Himself', 'itself' are ___ pronouns.", answer: "reflexive" },
  { question: "'These', 'those' are ___ pronouns.", answer: "demonstrative" },
  { question: "Subject pronoun for a male person is ___.", answer: "he" },
  { question: "Subject pronoun for a female person is ___.", answer: "she" },
  { question: "Subject pronoun for a thing is ___.", answer: "it" },
  { question: "'Whom' is the ___ form of 'who'.", answer: "object" },
  { question: "'Whose' shows ___.", answer: "possession" },
  { question: "'Someone', 'anyone' are ___ pronouns.", answer: "indefinite" },
  { question: "We use ___ pronouns to emphasize.", answer: "emphatic" },
  { question: "'What', 'which' as questions are ___ pronouns.", answer: "interrogative" },
  { question: "2nd person pronoun (singular/plural) is ___.", answer: "you" },
  { question: "Possessive adjective for 'it' is ___.", answer: "its" },
  { question: "Possessive pronoun for 'she' is ___.", answer: "hers" },
  { question: "Reflexive form of 'you' (plural) is ___.", answer: "yourselves" },
  { question: "Reflexive form of 'I' is ___.", answer: "myself" },
  { question: "'Each' is an ___ pronoun.", answer: "indefinite" },
  { question: "'Both', 'all' are ___ pronouns.", answer: "indefinite" },
  { question: "Antecedent is the noun a pronoun refers to — True or False?", answer: "True" },
  { question: "'None' is an ___ pronoun.", answer: "indefinite" },
  { question: "Reflexive form of 'they' is ___.", answer: "themselves" },
  { question: "Reflexive form of 'we' is ___.", answer: "ourselves" },
  { question: "'Either', 'neither' are ___ pronouns.", answer: "indefinite" },
  { question: "Demonstrative pronoun for a near object is ___.", answer: "this" },
  { question: "Demonstrative pronoun for a far plural object is ___.", answer: "those" },
  { question: "'Anything', 'nothing' are ___ pronouns.", answer: "indefinite" },
  { question: "The relative pronoun for possessive is ___.", answer: "whose" },
  { question: "'One another' is used for more than ___ persons.", answer: "two" },
  { question: "'Each other' is used for ___ persons.", answer: "two" }
],

"verbs": [
  { question: "A ___ shows action or state of being.", answer: "verb" },
  { question: "'Run', 'jump' are ___ verbs.", answer: "action" },
  { question: "'Is', 'am', 'are' are ___ verbs.", answer: "linking" },
  { question: "'Have', 'has', 'had' are ___ verbs.", answer: "auxiliary" },
  { question: "3rd person singular present of 'go' is ___.", answer: "goes" },
  { question: "Past tense of 'run' is ___.", answer: "ran" },
  { question: "Past tense of 'write' is ___.", answer: "wrote" },
  { question: "Past tense of 'eat' is ___.", answer: "ate" },
  { question: "Past tense of 'take' is ___.", answer: "took" },
  { question: "Past participle of 'write' is ___.", answer: "written" },
  { question: "Past participle of 'speak' is ___.", answer: "spoken" },
  { question: "Past participle of 'break' is ___.", answer: "broken" },
  { question: "Past participle of 'choose' is ___.", answer: "chosen" },
  { question: "Past participle of 'fly' is ___.", answer: "flown" },
  { question: "A transitive verb needs an ___.", answer: "object" },
  { question: "An intransitive verb does not need an ___.", answer: "object" },
  { question: "Past tense of 'swim' is ___.", answer: "swam" },
  { question: "Past tense of 'begin' is ___.", answer: "began" },
  { question: "Past tense of 'come' is ___.", answer: "came" },
  { question: "Past tense of 'see' is ___.", answer: "saw" },
  { question: "Infinitive uses 'to' + ___ form of verb.", answer: "base" },
  { question: "Past tense of 'fall' is ___.", answer: "fell" },
  { question: "Past tense of 'know' is ___.", answer: "knew" },
  { question: "Past tense of 'give' is ___.", answer: "gave" },
  { question: "Past tense of 'speak' is ___.", answer: "spoke" },
  { question: "Past tense of 'throw' is ___.", answer: "threw" },
  { question: "Past tense of 'grow' is ___.", answer: "grew" },
  { question: "Past tense of 'draw' is ___.", answer: "drew" },
  { question: "Past tense of 'drive' is ___.", answer: "drove" },
  { question: "Past tense of 'ride' is ___.", answer: "rode" },
  { question: "Past tense of 'rise' is ___.", answer: "rose" },
  { question: "Past tense of 'ring' is ___.", answer: "rang" },
  { question: "Past tense of 'sing' is ___.", answer: "sang" },
  { question: "Past tense of 'drink' is ___.", answer: "drank" },
  { question: "Past tense of 'shrink' is ___.", answer: "shrank" },
  { question: "Past participle of 'take' is ___.", answer: "taken" },
  { question: "Past participle of 'give' is ___.", answer: "given" },
  { question: "Past participle of 'eat' is ___.", answer: "eaten" },
  { question: "Past participle of 'fall' is ___.", answer: "fallen" },
  { question: "Past participle of 'see' is ___.", answer: "seen" },
  { question: "Past participle of 'come' is ___.", answer: "come" },
  { question: "Past participle of 'run' is ___.", answer: "run" },
  { question: "Past participle of 'go' is ___.", answer: "gone" },
  { question: "Past participle of 'do' is ___.", answer: "done" },
  { question: "Past participle of 'know' is ___.", answer: "known" },
  { question: "Past participle of 'grow' is ___.", answer: "grown" },
  { question: "Past participle of 'throw' is ___.", answer: "thrown" },
  { question: "Past participle of 'draw' is ___.", answer: "drawn" },
  { question: "Past participle of 'drive' is ___.", answer: "driven" },
  { question: "Past participle of 'ride' is ___.", answer: "ridden" },
  { question: "Past participle of 'rise' is ___.", answer: "risen" },
  { question: "Past participle of 'ring' is ___.", answer: "rung" },
  { question: "Past participle of 'sing' is ___.", answer: "sung" },
  { question: "Past participle of 'drink' is ___.", answer: "drunk" },
  { question: "Modal verb for ability: ___.", answer: "can" },
  { question: "Modal verb for permission (polite): ___.", answer: "may" },
  { question: "Modal verb for obligation: ___.", answer: "must" },
  { question: "Past form of 'can' is ___.", answer: "could" },
  { question: "Past form of 'will' is ___.", answer: "would" },
  { question: "Past form of 'shall' is ___.", answer: "should" },
  { question: "Past form of 'may' is ___.", answer: "might" },
  { question: "Gerund is the ___ form used as noun.", answer: "-ing" }
],

"adjectives": [
  { question: "An adjective modifies a ___.", answer: "noun" },
  { question: "Comparative of 'big' is ___.", answer: "bigger" },
  { question: "Superlative of 'big' is ___.", answer: "biggest" },
  { question: "Comparative of 'good' is ___.", answer: "better" },
  { question: "Superlative of 'good' is ___.", answer: "best" },
  { question: "Comparative of 'bad' is ___.", answer: "worse" },
  { question: "Superlative of 'bad' is ___.", answer: "worst" },
  { question: "Comparative of 'happy' is ___.", answer: "happier" },
  { question: "Superlative of 'happy' is ___.", answer: "happiest" },
  { question: "Comparative of 'beautiful' is ___.", answer: "more beautiful" },
  { question: "Superlative of 'beautiful' is ___.", answer: "most beautiful" },
  { question: "Comparative of 'far' is ___.", answer: "farther/further" },
  { question: "Superlative of 'far' is ___.", answer: "farthest/furthest" },
  { question: "Comparative of 'little' (amount) is ___.", answer: "less" },
  { question: "Superlative of 'little' is ___.", answer: "least" },
  { question: "Comparative of 'many/much' is ___.", answer: "more" },
  { question: "Superlative of 'many/much' is ___.", answer: "most" },
  { question: "Adjectives showing quantity are ___ adjectives.", answer: "quantitative" },
  { question: "Adjectives showing quality are ___ adjectives.", answer: "qualitative/descriptive" },
  { question: "'First', 'second' are ___ adjectives.", answer: "ordinal" },
  { question: "'One', 'two' are ___ adjectives.", answer: "numeral/cardinal" },
  { question: "'This', 'that' before nouns are ___ adjectives.", answer: "demonstrative" },
  { question: "'Whose book?' — 'whose' is an ___ adjective.", answer: "interrogative" },
  { question: "Adjective placed after a linking verb is a ___ adjective.", answer: "predicative" },
  { question: "Adjective placed before the noun is an ___ adjective.", answer: "attributive" },
  { question: "Superlative of 'tall' is ___.", answer: "tallest" },
  { question: "Comparative of 'tall' is ___.", answer: "taller" },
  { question: "Superlative of 'heavy' is ___.", answer: "heaviest" },
  { question: "Comparative of 'clever' is ___.", answer: "cleverer/more clever" },
  { question: "Superlative of 'clever' is ___.", answer: "cleverest/most clever" },
  { question: "Comparative of 'interesting' is ___.", answer: "more interesting" },
  { question: "Superlative of 'interesting' is ___.", answer: "most interesting" },
  { question: "Comparative of 'hot' is ___.", answer: "hotter" },
  { question: "Superlative of 'hot' is ___.", answer: "hottest" },
  { question: "Comparative of 'easy' is ___.", answer: "easier" },
  { question: "Superlative of 'easy' is ___.", answer: "easiest" },
  { question: "Comparative of 'wise' is ___.", answer: "wiser" },
  { question: "Superlative of 'wise' is ___.", answer: "wisest" },
  { question: "Comparative of 'old' (things) is ___.", answer: "older/elder" },
  { question: "Superlative of 'old' (things) is ___.", answer: "oldest/eldest" },
  { question: "Comparative of 'thin' is ___.", answer: "thinner" },
  { question: "Superlative of 'thin' is ___.", answer: "thinnest" },
  { question: "Comparative of 'early' is ___.", answer: "earlier" },
  { question: "Superlative of 'early' is ___.", answer: "earliest" },
  { question: "Comparative of 'fast' is ___.", answer: "faster" },
  { question: "Superlative of 'fast' is ___.", answer: "fastest" },
  { question: "Positive degree of 'worst' is ___.", answer: "bad" },
  { question: "Positive degree of 'best' is ___.", answer: "good" },
  { question: "Positive degree of 'most' is ___.", answer: "many/much" },
  { question: "Positive degree of 'least' is ___.", answer: "little" }
],

"tenses": [
  { question: "Simple present: She ___ (go) to school.", answer: "goes" },
  { question: "Simple past: He ___ (eat) lunch.", answer: "ate" },
  { question: "Simple future: They ___ (play) tomorrow.", answer: "will play" },
  { question: "Present continuous: She ___ (read) now.", answer: "is reading" },
  { question: "Past continuous: We ___ (play) when it rained.", answer: "were playing" },
  { question: "Present perfect: I ___ (finish) my work.", answer: "have finished" },
  { question: "Past perfect: She ___ (leave) before he came.", answer: "had left" },
  { question: "Future perfect: By 5 pm, I ___ (complete) it.", answer: "will have completed" },
  { question: "Future continuous: At 9 am, she ___ (study).", answer: "will be studying" },
  { question: "Present perfect continuous: I ___ (wait) since noon.", answer: "have been waiting" },
  { question: "Signal word for present perfect: ___ (just).", answer: "have/has" },
  { question: "Signal word for past perfect: ___.", answer: "had" },
  { question: "'Yesterday' signals ___ tense.", answer: "simple past" },
  { question: "'Tomorrow' signals ___ tense.", answer: "simple future" },
  { question: "'Since 2010' signals ___ tense.", answer: "present perfect" },
  { question: "'At this moment' signals ___ tense.", answer: "present continuous" },
  { question: "Simple present negative: She ___ not go.", answer: "does" },
  { question: "Simple past negative uses ___.", answer: "did not" },
  { question: "'Always', 'never' are used with ___ tense.", answer: "simple present" },
  { question: "Auxiliary for present perfect is ___.", answer: "have/has" },
  { question: "Auxiliary for past perfect is ___.", answer: "had" },
  { question: "Auxiliary for future is ___.", answer: "will/shall" },
  { question: "Present continuous: use ___ + -ing.", answer: "am/is/are" },
  { question: "Past continuous: use ___ + -ing.", answer: "was/were" },
  { question: "'For three hours' is used in ___ continuous.", answer: "present perfect" },
  { question: "Simple present 3rd person singular adds ___.", answer: "-s/-es" },
  { question: "Past tense of regular verbs adds ___.", answer: "-ed" },
  { question: "Present participle adds ___.", answer: "-ing" },
  { question: "Past perfect: She ___ (see) that film.", answer: "had seen" },
  { question: "Future perfect: By noon, I ___ (eat).", answer: "will have eaten" },
  { question: "I ___ (go) to school every day. (Simple present)", answer: "go" },
  { question: "He ___ (write) a letter now. (Pres. cont.)", answer: "is writing" },
  { question: "We ___ (visit) them last week. (Simple past)", answer: "visited" },
  { question: "They ___ (already/finish). (Present perfect)", answer: "have already finished" },
  { question: "She ___ (study) for 2 hours. (Pres.perf.cont.)", answer: "has been studying" },
  { question: "I ___ (never/be) to Paris. (Present perfect)", answer: "have never been" },
  { question: "Stative verbs like 'know' are NOT used in ___ form.", answer: "continuous" },
  { question: "The train ___ (just/arrive). (Present perfect)", answer: "has just arrived" },
  { question: "Before he came, I ___ (finish). (Past perfect)", answer: "had finished" },
  { question: "'Since' vs 'for' — 'since' marks a ___ point.", answer: "starting point" },
  { question: "Third conditional uses ___ + have + past participle.", answer: "would" },
  { question: "Zero conditional: If water boils, it ___.", answer: "turns to steam" },
  { question: "First conditional: If it rains, I ___ stay.", answer: "will" },
  { question: "Second conditional: If I ___ rich, I would travel.", answer: "were" },
  { question: "Past tense of 'teach' is ___.", answer: "taught" },
  { question: "Past tense of 'buy' is ___.", answer: "bought" },
  { question: "Past tense of 'catch' is ___.", answer: "caught" },
  { question: "Past tense of 'think' is ___.", answer: "thought" },
  { question: "Past tense of 'bring' is ___.", answer: "brought" },
  { question: "Past tense of 'fight' is ___.", answer: "fought" },
  { question: "Past tense of 'seek' is ___.", answer: "sought" }
],

"active and passive voice": [
  { question: "Active: The dog bit the man. Passive: The man was ___ by the dog.", answer: "bitten" },
  { question: "Passive voice uses ___ + past participle.", answer: "to be" },
  { question: "Active: She sings a song. Passive: A song ___ by her.", answer: "is sung" },
  { question: "In passive voice, the object becomes the ___.", answer: "subject" },
  { question: "Active: He wrote a letter. Passive: A letter ___ by him.", answer: "was written" },
  { question: "Active: They are playing a game. Passive: A game ___ by them.", answer: "is being played" },
  { question: "Active: We will complete the task. Passive: The task ___ by us.", answer: "will be completed" },
  { question: "Active: She has sent the parcel. Passive: The parcel ___ by her.", answer: "has been sent" },
  { question: "Active: He was reading a book. Passive: A book ___ by him.", answer: "was being read" },
  { question: "Passive of 'present perfect': has/have + been + ___.", answer: "past participle" },
  { question: "Active: I eat a mango. Passive: A mango ___ by me.", answer: "is eaten" },
  { question: "The doer in passive voice is introduced by ___.", answer: "by" },
  { question: "Passive of simple future: ___ + be + past participle.", answer: "will" },
  { question: "Active: They built a house. Passive: A house ___ by them.", answer: "was built" },
  { question: "Active voice emphasizes the ___.", answer: "doer/subject" },
  { question: "Passive voice emphasizes the ___.", answer: "receiver/object" },
  { question: "Active: She teaches math. Passive: Math ___ by her.", answer: "is taught" },
  { question: "Active: Workers repaired the road. Passive: The road ___ by workers.", answer: "was repaired" },
  { question: "Active: She has cooked food. Passive: Food ___ by her.", answer: "has been cooked" },
  { question: "Passive of modal 'can': ___ + be + past participle.", answer: "can" },
  { question: "Active: He can solve the problem. Passive: The problem ___ by him.", answer: "can be solved" },
  { question: "Passive of 'must': ___ + be + past participle.", answer: "must" },
  { question: "Agent is sometimes omitted when ___.", answer: "unknown/unimportant" },
  { question: "Active: They have eaten food. Passive: Food ___ by them.", answer: "has been eaten" },
  { question: "Active: The cat chased the rat. Passive: The rat ___ by the cat.", answer: "was chased" },
  { question: "'By whom was the letter written?' is a ___ question.", answer: "passive" },
  { question: "Passive voice of imperative: ___ + past participle.", answer: "let ... be" },
  { question: "Active: Open the door. Passive: Let the door ___ opened.", answer: "be" },
  { question: "Past participle of 'build' is ___.", answer: "built" },
  { question: "Past participle of 'send' is ___.", answer: "sent" },
  { question: "Past participle of 'pay' is ___.", answer: "paid" },
  { question: "Past participle of 'hold' is ___.", answer: "held" },
  { question: "Past participle of 'keep' is ___.", answer: "kept" },
  { question: "Past participle of 'make' is ___.", answer: "made" },
  { question: "Past participle of 'sell' is ___.", answer: "sold" },
  { question: "Past participle of 'tell' is ___.", answer: "told" },
  { question: "Past participle of 'win' is ___.", answer: "won" },
  { question: "Past participle of 'find' is ___.", answer: "found" },
  { question: "Past participle of 'lose' is ___.", answer: "lost" },
  { question: "Past participle of 'leave' is ___.", answer: "left" },
  { question: "Past participle of 'meet' is ___.", answer: "met" },
  { question: "Past participle of 'sit' is ___.", answer: "sat" },
  { question: "Past participle of 'stand' is ___.", answer: "stood" },
  { question: "Past participle of 'understand' is ___.", answer: "understood" },
  { question: "Past participle of 'read' is ___.", answer: "read" },
  { question: "Past participle of 'put' is ___.", answer: "put" },
  { question: "Past participle of 'cut' is ___.", answer: "cut" },
  { question: "Past participle of 'hit' is ___.", answer: "hit" },
  { question: "Past participle of 'set' is ___.", answer: "set" },
  { question: "Past participle of 'let' is ___.", answer: "let" }
],

"direct and indirect speech": [
  { question: "Direct speech uses ___ marks.", answer: "quotation" },
  { question: "Indirect speech is also called ___ speech.", answer: "reported" },
  { question: "The reporting verb for statement in past: 'said' changes to ___.", answer: "said/told" },
  { question: "In indirect speech, 'I' changes to ___ (speaker is 3rd person).", answer: "he/she" },
  { question: "Simple present changes to ___ in indirect speech.", answer: "simple past" },
  { question: "Simple past changes to ___ in indirect speech.", answer: "past perfect" },
  { question: "Present continuous changes to ___ in indirect speech.", answer: "past continuous" },
  { question: "Present perfect changes to ___ in indirect speech.", answer: "past perfect" },
  { question: "'Will' changes to ___ in indirect speech.", answer: "would" },
  { question: "'Can' changes to ___ in indirect speech.", answer: "could" },
  { question: "'May' changes to ___ in indirect speech.", answer: "might" },
  { question: "'Shall' changes to ___ in indirect speech.", answer: "should" },
  { question: "'This' changes to ___ in indirect speech.", answer: "that" },
  { question: "'These' changes to ___ in indirect speech.", answer: "those" },
  { question: "'Here' changes to ___ in indirect speech.", answer: "there" },
  { question: "'Now' changes to ___ in indirect speech.", answer: "then" },
  { question: "'Today' changes to ___ in indirect speech.", answer: "that day" },
  { question: "'Yesterday' changes to ___ in indirect speech.", answer: "the day before" },
  { question: "'Tomorrow' changes to ___ in indirect speech.", answer: "the next day" },
  { question: "'Ago' changes to ___ in indirect speech.", answer: "before" },
  { question: "For questions in indirect speech use 'if' or ___.", answer: "whether" },
  { question: "Imperative in indirect speech: reporting verb is ___.", answer: "told/ordered/asked" },
  { question: "Exclamatory in indirect speech: reporting verb is ___.", answer: "exclaimed" },
  { question: "Direct: 'I am tired', she said. Indirect: She said that she ___ tired.", answer: "was" },
  { question: "Direct: 'I will come'. Indirect: He said he ___ come.", answer: "would" },
  { question: "'Are you hungry?' in indirect: He asked if I ___ hungry.", answer: "was" },
  { question: "Direct: 'Sit down', he said. Indirect: He told me to ___.", answer: "sit down" },
  { question: "Direct: 'What a beautiful flower!' Indirect: She ___ it was a beautiful flower.", answer: "exclaimed that" },
  { question: "Indirect: She said she ___ seen that film. (Direct: I have seen)", answer: "had" },
  { question: "'Must' in direct speech can stay as ___ in indirect.", answer: "must/had to" },
  { question: "Direct: 'We are happy'. Indirect: They said they ___ happy.", answer: "were" },
  { question: "Direct: 'I know the answer'. Indirect: He said he ___ the answer.", answer: "knew" },
  { question: "In indirect Wh-question, word order is ___.", answer: "subject + verb" },
  { question: "Direct: 'Where do you live?' Indirect: He asked where I ___.", answer: "lived" },
  { question: "Direct: 'Please help me'. Indirect: She requested him to ___ her.", answer: "help" },
  { question: "'Isn't it a nice day?' type question is a ___ question.", answer: "rhetorical/tag" },
  { question: "Direct: 'I came here yesterday'. Indirect: He said he had come ___ the day before.", answer: "there" },
  { question: "Direct: 'Don't make noise'. Indirect: He told them not to ___ noise.", answer: "make" },
  { question: "'Could' in direct speech stays as ___ in indirect.", answer: "could" },
  { question: "Direct: 'I have done my homework'. Indirect: She said she ___ her homework.", answer: "had done" },
  { question: "Universal truth in indirect speech: tense does NOT change — True/False?", answer: "True" },
  { question: "Direct: 'I love this city'. Indirect: She said she loved ___ city.", answer: "that" },
  { question: "'Now' in direct speech becomes ___ in indirect.", answer: "then" },
  { question: "'This week' becomes ___ in indirect speech.", answer: "that week" },
  { question: "'Next year' becomes ___ in indirect speech.", answer: "the following year" },
  { question: "'Last night' becomes ___ in indirect speech.", answer: "the night before" },
  { question: "Direct: 'Has he left?' Indirect: She asked if he ___.", answer: "had left" },
  { question: "'Would' in direct stays as ___ in indirect.", answer: "would" },
  { question: "'Might' stays as ___ in indirect speech.", answer: "might" },
  { question: "Direct: 'I met her here'. Indirect: He said he had met her ___.", answer: "there" }
],

"synonyms": [
  { question: "Synonym of 'happy' is ___.", answer: "joyful/glad" },
  { question: "Synonym of 'sad' is ___.", answer: "unhappy/sorrowful" },
  { question: "Synonym of 'big' is ___.", answer: "large/huge" },
  { question: "Synonym of 'small' is ___.", answer: "tiny/little" },
  { question: "Synonym of 'fast' is ___.", answer: "quick/swift" },
  { question: "Synonym of 'brave' is ___.", answer: "courageous/bold" },
  { question: "Synonym of 'angry' is ___.", answer: "furious/irate" },
  { question: "Synonym of 'beautiful' is ___.", answer: "lovely/gorgeous" },
  { question: "Synonym of 'begin' is ___.", answer: "start/commence" },
  { question: "Synonym of 'end' is ___.", answer: "finish/conclude" },
  { question: "Synonym of 'old' is ___.", answer: "ancient/aged" },
  { question: "Synonym of 'new' is ___.", answer: "fresh/novel" },
  { question: "Synonym of 'difficult' is ___.", answer: "hard/tough" },
  { question: "Synonym of 'easy' is ___.", answer: "simple/effortless" },
  { question: "Synonym of 'rich' is ___.", answer: "wealthy/affluent" },
  { question: "Synonym of 'poor' is ___.", answer: "needy/impoverished" },
  { question: "Synonym of 'laugh' is ___.", answer: "chuckle/giggle" },
  { question: "Synonym of 'cry' is ___.", answer: "weep/sob" },
  { question: "Synonym of 'walk' is ___.", answer: "stroll/stride" },
  { question: "Synonym of 'afraid' is ___.", answer: "scared/frightened" },
  { question: "Synonym of 'clever' is ___.", answer: "intelligent/smart" },
  { question: "Synonym of 'show' is ___.", answer: "display/demonstrate" },
  { question: "Synonym of 'ask' is ___.", answer: "inquire/question" },
  { question: "Synonym of 'help' is ___.", answer: "assist/aid" },
  { question: "Synonym of 'choose' is ___.", answer: "select/pick" },
  { question: "Synonym of 'speak' is ___.", answer: "talk/utter" },
  { question: "Synonym of 'tired' is ___.", answer: "weary/exhausted" },
  { question: "Synonym of 'glad' is ___.", answer: "pleased/delighted" },
  { question: "Synonym of 'strange' is ___.", answer: "odd/peculiar" },
  { question: "Synonym of 'correct' is ___.", answer: "right/accurate" },
  { question: "Synonym of 'clear' is ___.", answer: "transparent/obvious" },
  { question: "Synonym of 'buy' is ___.", answer: "purchase/acquire" },
  { question: "Synonym of 'build' is ___.", answer: "construct/erect" },
  { question: "Synonym of 'save' is ___.", answer: "rescue/preserve" },
  { question: "Synonym of 'enemy' is ___.", answer: "foe/adversary" },
  { question: "Synonym of 'friend' is ___.", answer: "companion/ally" },
  { question: "Synonym of 'calm' is ___.", answer: "peaceful/serene" },
  { question: "Synonym of 'noisy' is ___.", answer: "loud/boisterous" },
  { question: "Synonym of 'gather' is ___.", answer: "collect/assemble" },
  { question: "Synonym of 'allow' is ___.", answer: "permit/let" },
  { question: "Synonym of 'finish' is ___.", answer: "complete/end" },
  { question: "Synonym of 'strong' is ___.", answer: "powerful/sturdy" },
  { question: "Synonym of 'weak' is ___.", answer: "feeble/frail" },
  { question: "Synonym of 'kind' is ___.", answer: "gentle/caring" },
  { question: "Synonym of 'cruel' is ___.", answer: "harsh/brutal" },
  { question: "Synonym of 'huge' is ___.", answer: "enormous/gigantic" },
  { question: "Synonym of 'thin' is ___.", answer: "slim/slender" },
  { question: "Synonym of 'silent' is ___.", answer: "quiet/still" },
  { question: "Synonym of 'quick' is ___.", answer: "fast/rapid" },
  { question: "Synonym of 'honest' is ___.", answer: "truthful/sincere" }
],

"antonyms": [
  { question: "Antonym of 'happy' is ___.", answer: "sad/unhappy" },
  { question: "Antonym of 'big' is ___.", answer: "small/tiny" },
  { question: "Antonym of 'hot' is ___.", answer: "cold" },
  { question: "Antonym of 'day' is ___.", answer: "night" },
  { question: "Antonym of 'fast' is ___.", answer: "slow" },
  { question: "Antonym of 'hard' is ___.", answer: "soft/easy" },
  { question: "Antonym of 'open' is ___.", answer: "close/shut" },
  { question: "Antonym of 'love' is ___.", answer: "hate" },
  { question: "Antonym of 'good' is ___.", answer: "bad/evil" },
  { question: "Antonym of 'right' is ___.", answer: "wrong/left" },
  { question: "Antonym of 'old' is ___.", answer: "young/new" },
  { question: "Antonym of 'start' is ___.", answer: "end/stop" },
  { question: "Antonym of 'tall' is ___.", answer: "short" },
  { question: "Antonym of 'light' is ___.", answer: "dark/heavy" },
  { question: "Antonym of 'loud' is ___.", answer: "quiet/soft" },
  { question: "Antonym of 'rich' is ___.", answer: "poor" },
  { question: "Antonym of 'strong' is ___.", answer: "weak" },
  { question: "Antonym of 'true' is ___.", answer: "false" },
  { question: "Antonym of 'empty' is ___.", answer: "full" },
  { question: "Antonym of 'clean' is ___.", answer: "dirty" },
  { question: "Antonym of 'inside' is ___.", answer: "outside" },
  { question: "Antonym of 'before' is ___.", answer: "after" },
  { question: "Antonym of 'above' is ___.", answer: "below/under" },
  { question: "Antonym of 'arrive' is ___.", answer: "depart/leave" },
  { question: "Antonym of 'buy' is ___.", answer: "sell" },
  { question: "Antonym of 'question' is ___.", answer: "answer" },
  { question: "Antonym of 'remember' is ___.", answer: "forget" },
  { question: "Antonym of 'accept' is ___.", answer: "reject/refuse" },
  { question: "Antonym of 'victory' is ___.", answer: "defeat" },
  { question: "Antonym of 'courage' is ___.", answer: "cowardice" },
  { question: "Antonym of 'generous' is ___.", answer: "stingy/miserly" },
  { question: "Antonym of 'honest' is ___.", answer: "dishonest" },
  { question: "Antonym of 'ancient' is ___.", answer: "modern/recent" },
  { question: "Antonym of 'shallow' is ___.", answer: "deep" },
  { question: "Antonym of 'narrow' is ___.", answer: "wide/broad" },
  { question: "Antonym of 'victory' is ___.", answer: "defeat" },
  { question: "Antonym of 'war' is ___.", answer: "peace" },
  { question: "Antonym of 'addition' is ___.", answer: "subtraction" },
  { question: "Antonym of 'export' is ___.", answer: "import" },
  { question: "Antonym of 'praise' is ___.", answer: "criticize/blame" },
  { question: "Antonym of 'loud' is ___.", answer: "soft/quiet" },
  { question: "Antonym of 'fresh' is ___.", answer: "stale/old" },
  { question: "Antonym of 'cruel' is ___.", answer: "kind/gentle" },
  { question: "Antonym of 'rough' is ___.", answer: "smooth" },
  { question: "Antonym of 'always' is ___.", answer: "never" },
  { question: "Antonym of 'maximum' is ___.", answer: "minimum" },
  { question: "Antonym of 'urban' is ___.", answer: "rural" },
  { question: "Antonym of 'compulsory' is ___.", answer: "optional/voluntary" },
  { question: "Antonym of 'domestic' is ___.", answer: "wild/foreign" },
  { question: "Antonym of 'permanent' is ___.", answer: "temporary" }
],

"prepositions": [
  { question: "The book is ___ the table. (on/under)", answer: "on" },
  { question: "She lives ___ London.", answer: "in" },
  { question: "He was born ___ Monday.", answer: "on" },
  { question: "We meet ___ 3 o'clock.", answer: "at" },
  { question: "They work ___ summer.", answer: "in" },
  { question: "The cat jumped ___ the wall.", answer: "over" },
  { question: "He sat ___ you and me.", answer: "between" },
  { question: "The birds flew ___ the sky.", answer: "across" },
  { question: "She ran ___ the dog.", answer: "away from" },
  { question: "He came ___ the USA.", answer: "from" },
  { question: "The key is ___ the lock.", answer: "in" },
  { question: "She arrived ___ midnight.", answer: "at" },
  { question: "He is good ___ maths.", answer: "at" },
  { question: "Write ___ a pen.", answer: "with" },
  { question: "I am looking ___ you.", answer: "for" },
  { question: "She agreed ___ me.", answer: "with" },
  { question: "He apologised ___ being late.", answer: "for" },
  { question: "The dog ran ___ the house.", answer: "around" },
  { question: "Preposition 'of' shows ___.", answer: "possession/belonging" },
  { question: "'At' is used with specific ___ or place.", answer: "time" },
  { question: "'In' is used with months, ___, and countries.", answer: "years" },
  { question: "'On' is used with ___ and dates.", answer: "days" },
  { question: "'Between' is for ___ things.", answer: "two" },
  { question: "'Among' is for more than ___ things.", answer: "two" },
  { question: "He spoke ___ a whisper.", answer: "in" },
  { question: "She is proud ___ her son.", answer: "of" },
  { question: "He is interested ___ science.", answer: "in" },
  { question: "She is worried ___ the exam.", answer: "about" },
  { question: "They arrived ___ the airport.", answer: "at" },
  { question: "The dog is hiding ___ the bed.", answer: "under" },
  { question: "She swam ___ the river.", answer: "across" },
  { question: "He walked ___ the door.", answer: "through" },
  { question: "She sat ___ the window.", answer: "beside/near" },
  { question: "He is ___ the phone.", answer: "on" },
  { question: "'Since' is used with ___ points in time.", answer: "starting" },
  { question: "'For' is used with a ___ of time.", answer: "duration" },
  { question: "She came ___ the corner.", answer: "around" },
  { question: "He waited ___ two hours.", answer: "for" },
  { question: "He has been here ___ Monday.", answer: "since" },
  { question: "The plane flew ___ the clouds.", answer: "above" },
  { question: "He put the box ___ the shelf.", answer: "on" },
  { question: "The school is ___ the park.", answer: "near/beside" },
  { question: "She is ___ love with him.", answer: "in" },
  { question: "He got ___ the bus.", answer: "on" },
  { question: "She got ___ the car.", answer: "into" },
  { question: "'Opposite to' means ___.", answer: "facing" },
  { question: "He ran ___ the road.", answer: "along" },
  { question: "She climbed ___ the ladder.", answer: "up" },
  { question: "He slid ___ the slide.", answer: "down" },
  { question: "She is known ___ her kindness.", answer: "for" }
],
};

// Generic fallback bank
const FALLBACK: Question[] = [
  { question: "A sentence starts with a ___ letter.", answer: "capital" },
  { question: "A sentence ends with a ___ mark.", answer: "full stop/period" },
  { question: "A question ends with a ___ mark.", answer: "question mark" },
  { question: "An exclamation ends with ___.", answer: "exclamation mark" },
  { question: "Comma is used to separate ___ in a list.", answer: "items" },
  { question: "An apostrophe shows ___ or contraction.", answer: "possession" },
  { question: "A compound sentence joins two clauses with a ___.", answer: "conjunction" },
  { question: "'And', 'but', 'or' are ___ conjunctions.", answer: "coordinating" },
  { question: "'Although', 'because' are ___ conjunctions.", answer: "subordinating" },
  { question: "'Not only...but also' is a ___ conjunction.", answer: "correlative" },
  { question: "A clause must have a subject and a ___.", answer: "verb" },
  { question: "Main clause is also called ___ clause.", answer: "independent" },
  { question: "Subordinate clause cannot stand ___.", answer: "alone" },
  { question: "Noun clause acts as a ___.", answer: "noun" },
  { question: "Adverb clause modifies a ___.", answer: "verb/adjective/adverb" },
  { question: "Adjective clause modifies a ___.", answer: "noun/pronoun" },
  { question: "An adverb modifies a ___.", answer: "verb/adjective/adverb" },
  { question: "Adverbs of manner answer ___.", answer: "how" },
  { question: "Adverbs of time answer ___.", answer: "when" },
  { question: "Adverbs of place answer ___.", answer: "where" },
];

function normalize(topic: string): string {
  return topic.toLowerCase().replace(/[^a-z ]/g, "").trim();
}

function findBank(topic: string): Question[] {
  const n = normalize(topic);
  for (const key of Object.keys(BANKS)) {
    if (n.includes(key)) return BANKS[key];
  }
  // Partial keyword match
  if (n.includes("noun")) return BANKS["nouns"];
  if (n.includes("pronoun")) return BANKS["pronouns"];
  if (n.includes("verb")) return BANKS["verbs"];
  if (n.includes("adjec")) return BANKS["adjectives"];
  if (n.includes("tense")) return BANKS["tenses"];
  if (n.includes("passive") || n.includes("active")) return BANKS["active and passive voice"];
  if (n.includes("indirect") || n.includes("direct") || n.includes("speech")) return BANKS["direct and indirect speech"];
  if (n.includes("synonym")) return BANKS["synonyms"];
  if (n.includes("antonym")) return BANKS["antonyms"];
  if (n.includes("preposition")) return BANKS["prepositions"];
  return FALLBACK;
}

export function generateEnglishQuestions(
  _gradeId: string,
  topicLabel: string,
  _sheetNumber: number
): Question[] {
  // Return the full bank; caller (question-router) applies seeded shuffle + slice
  return findBank(topicLabel);
}
