import type { Question } from "../pdf-builder";

const ALL: Question[] = [
  // National Symbols — India
  { question: "National animal of India is ___.", answer: "Bengal Tiger" },
  { question: "National bird of India is ___.", answer: "Peacock" },
  { question: "National flower of India is ___.", answer: "Lotus" },
  { question: "National fruit of India is ___.", answer: "Mango" },
  { question: "National tree of India is ___.", answer: "Banyan" },
  { question: "National game of India is ___.", answer: "Field Hockey" },
  { question: "National anthem of India is ___.", answer: "Jana Gana Mana" },
  { question: "National song of India is ___.", answer: "Vande Mataram" },
  { question: "National river of India is ___.", answer: "Ganga" },
  { question: "National currency of India is ___.", answer: "Rupee" },
  { question: "Capital of India is ___.", answer: "New Delhi" },
  { question: "National flag of India has ___ colors.", answer: "3" },
  { question: "The Ashoka Chakra on flag has ___ spokes.", answer: "24" },
  { question: "Emblem of India is from ___ (city).", answer: "Sarnath" },
  { question: "India's independence day is ___.", answer: "15 August" },
  { question: "India's Republic Day is ___.", answer: "26 January" },
  { question: "National calendar of India is ___.", answer: "Saka Calendar" },
  // States & Capitals (India)
  { question: "Capital of Maharashtra is ___.", answer: "Mumbai" },
  { question: "Capital of Rajasthan is ___.", answer: "Jaipur" },
  { question: "Capital of Tamil Nadu is ___.", answer: "Chennai" },
  { question: "Capital of West Bengal is ___.", answer: "Kolkata" },
  { question: "Capital of Kerala is ___.", answer: "Thiruvananthapuram" },
  { question: "Capital of Karnataka is ___.", answer: "Bengaluru" },
  { question: "Capital of Uttar Pradesh is ___.", answer: "Lucknow" },
  { question: "Capital of Gujarat is ___.", answer: "Gandhinagar" },
  { question: "Capital of Punjab is ___.", answer: "Chandigarh" },
  { question: "Capital of Assam is ___.", answer: "Dispur" },
  { question: "Capital of Odisha is ___.", answer: "Bhubaneswar" },
  { question: "Capital of Telangana is ___.", answer: "Hyderabad" },
  { question: "Capital of Madhya Pradesh is ___.", answer: "Bhopal" },
  { question: "Capital of Bihar is ___.", answer: "Patna" },
  { question: "Capital of Jharkhand is ___.", answer: "Ranchi" },
  { question: "Capital of Andhra Pradesh is ___.", answer: "Amaravati" },
  // World geography
  { question: "Largest continent is ___.", answer: "Asia" },
  { question: "Smallest continent is ___.", answer: "Australia" },
  { question: "Longest river in the world is ___.", answer: "Nile" },
  { question: "Largest ocean is ___.", answer: "Pacific Ocean" },
  { question: "Highest mountain in the world is ___.", answer: "Mount Everest" },
  { question: "Largest country by area is ___.", answer: "Russia" },
  { question: "Most populous country is ___.", answer: "India/China" },
  { question: "Smallest country in the world is ___.", answer: "Vatican City" },
  { question: "Capital of USA is ___.", answer: "Washington D.C." },
  { question: "Capital of UK is ___.", answer: "London" },
  { question: "Capital of France is ___.", answer: "Paris" },
  { question: "Capital of Japan is ___.", answer: "Tokyo" },
  { question: "Capital of Australia is ___.", answer: "Canberra" },
  { question: "Capital of China is ___.", answer: "Beijing" },
  { question: "Capital of Germany is ___.", answer: "Berlin" },
  { question: "Capital of Russia is ___.", answer: "Moscow" },
  { question: "Capital of Canada is ___.", answer: "Ottawa" },
  { question: "Capital of Brazil is ___.", answer: "Brasilia" },
  // Famous personalities
  { question: "Father of the Nation (India) is ___.", answer: "Mahatma Gandhi" },
  { question: "First Prime Minister of India was ___.", answer: "Jawaharlal Nehru" },
  { question: "First President of India was ___.", answer: "Dr. Rajendra Prasad" },
  { question: "First woman Prime Minister of India was ___.", answer: "Indira Gandhi" },
  { question: "Father of the Indian Constitution is ___.", answer: "Dr. B.R. Ambedkar" },
  { question: "Iron Man of India is ___.", answer: "Sardar Vallabhbhai Patel" },
  { question: "Missile Man of India is ___.", answer: "Dr. A.P.J. Abdul Kalam" },
  { question: "Nightingale of India is ___.", answer: "Sarojini Naidu" },
  { question: "Father of Indian Space Programme is ___.", answer: "Dr. Vikram Sarabhai" },
  // Inventions
  { question: "Telephone was invented by ___.", answer: "Alexander Graham Bell" },
  { question: "Electricity (bulb) was invented by ___.", answer: "Thomas Edison" },
  { question: "Penicillin was discovered by ___.", answer: "Alexander Fleming" },
  { question: "Radio was invented by ___.", answer: "Guglielmo Marconi" },
  { question: "Aeroplane was invented by ___.", answer: "Wright Brothers" },
  { question: "Computer was invented by ___.", answer: "Charles Babbage" },
  { question: "World Wide Web was invented by ___.", answer: "Tim Berners-Lee" },
  { question: "Theory of Relativity was given by ___.", answer: "Albert Einstein" },
  { question: "Gravity was discovered by ___.", answer: "Isaac Newton" },
  { question: "Vaccination was discovered by ___.", answer: "Edward Jenner" },
  // Sports
  { question: "Cricket's governing body is ___.", answer: "ICC" },
  { question: "Football's governing body is ___.", answer: "FIFA" },
  { question: "Olympic Games held every ___ years.", answer: "4" },
  { question: "Host city of 1st modern Olympics (1896) was ___.", answer: "Athens" },
  { question: "First Indian to win Olympic gold was ___.", answer: "Abhinav Bindra" },
  { question: "Sachin Tendulkar's nickname is ___.", answer: "Master Blaster" },
  { question: "The fastest man in the world (100m) is ___.", answer: "Usain Bolt" },
  { question: "Tennis Grand Slam events total ___.", answer: "4" },
  { question: "Chess originated in ___.", answer: "India" },
  { question: "Kabaddi is the national sport of ___.", answer: "Bangladesh" },
  // Animals
  { question: "Fastest animal on land is ___.", answer: "Cheetah" },
  { question: "Tallest animal is ___.", answer: "Giraffe" },
  { question: "Largest animal is ___.", answer: "Blue Whale" },
  { question: "Largest land animal is ___.", answer: "African Elephant" },
  { question: "Slowest animal is ___.", answer: "Sloth" },
  { question: "Animal known as 'ship of the desert' is ___.", answer: "Camel" },
  { question: "A group of lions is called a ___.", answer: "pride" },
  { question: "A group of fish is called a ___.", answer: "school" },
  { question: "A group of wolves is called a ___.", answer: "pack" },
  { question: "A group of bees is called a ___.", answer: "swarm" },
  // Science GK
  { question: "Hardest natural substance is ___.", answer: "Diamond" },
  { question: "Largest planet in solar system is ___.", answer: "Jupiter" },
  { question: "Nearest planet to Sun is ___.", answer: "Mercury" },
  { question: "Planet farthest from Sun is ___.", answer: "Neptune" },
  { question: "Sun is a ___.", answer: "star" },
  { question: "Light takes ___ minutes to reach Earth from Sun.", answer: "8" },
  { question: "Number of planets in solar system is ___.", answer: "8" },
  { question: "Chemical formula of water is ___.", answer: "H2O" },
  { question: "Chemical formula of salt is ___.", answer: "NaCl" },
  { question: "Gas used in balloons (lighter than air) is ___.", answer: "Helium" },
  // Space
  { question: "First man on Moon was ___.", answer: "Neil Armstrong" },
  { question: "First Indian in space was ___.", answer: "Rakesh Sharma" },
  { question: "ISRO stands for ___.", answer: "Indian Space Research Organisation" },
  { question: "India's first satellite was ___.", answer: "Aryabhata" },
  { question: "Chandrayaan-1 was launched in year ___.", answer: "2008" },
  { question: "Mars is also called the ___ planet.", answer: "Red" },
  { question: "A galaxy is a large system of ___.", answer: "stars" },
  { question: "Our galaxy is called ___.", answer: "Milky Way" },
  { question: "Black hole has very strong ___.", answer: "gravity" },
  { question: "A shooting star is actually a ___.", answer: "meteor" },
  // Festivals
  { question: "Festival of lights in India is ___.", answer: "Diwali" },
  { question: "Festival of colours in India is ___.", answer: "Holi" },
  { question: "Eid is a festival of ___.", answer: "Muslims" },
  { question: "Christmas celebrates birth of ___.", answer: "Jesus Christ" },
  { question: "Baisakhi is celebrated in ___.", answer: "Punjab" },
  { question: "Onam is the harvest festival of ___.", answer: "Kerala" },
  { question: "Pongal is celebrated in ___.", answer: "Tamil Nadu" },
  { question: "Durga Puja is mainly celebrated in ___.", answer: "West Bengal" },
  { question: "Navratri is a ___ festival.", answer: "Hindu" },
  { question: "Lohri is celebrated in ___.", answer: "Punjab/North India" },
  // Books & authors
  { question: "Discovery of India was written by ___.", answer: "Jawaharlal Nehru" },
  { question: "Gitanjali was written by ___.", answer: "Rabindranath Tagore" },
  { question: "Wings of Fire is autobiography of ___.", answer: "A.P.J. Abdul Kalam" },
  { question: "The God of Small Things was written by ___.", answer: "Arundhati Roy" },
  { question: "India Wins Freedom was written by ___.", answer: "Maulana Abul Kalam Azad" },
];

export function generateGkQuestions(
  _gradeId: string,
  topicLabel: string,
  sheetNumber: number
): Question[] {
  const start = ((sheetNumber - 1) * 20) % ALL.length;
  const end = start + 20;
  if (end <= ALL.length) return ALL.slice(start, end);
  return [...ALL.slice(start), ...ALL.slice(0, end - ALL.length)];
}
