import type { Question } from "../pdf-builder";

type Bank = Record<string, Question[]>;

const BANKS: Bank = {

"plants": [
  { question: "Plants make food through ___.", answer: "photosynthesis" },
  { question: "Chlorophyll is found in ___.", answer: "leaves" },
  { question: "The green pigment in plants is ___.", answer: "chlorophyll" },
  { question: "Plants need ___, water, and CO2 for photosynthesis.", answer: "sunlight" },
  { question: "Oxygen is released during ___.", answer: "photosynthesis" },
  { question: "The part of plant that absorbs water is ___.", answer: "roots" },
  { question: "Transport of water in plants occurs through ___.", answer: "xylem" },
  { question: "Food transport in plants occurs through ___.", answer: "phloem" },
  { question: "A plant that lives for one season is ___.", answer: "annual" },
  { question: "A plant that lives for two years is ___.", answer: "biennial" },
  { question: "A plant that lives for many years is ___.", answer: "perennial" },
  { question: "The root system of grass is ___.", answer: "fibrous" },
  { question: "The root system of a carrot is ___.", answer: "tap root" },
  { question: "Stomata are openings found in ___.", answer: "leaves" },
  { question: "Transpiration is loss of water through ___.", answer: "stomata" },
  { question: "Pollination is transfer of ___ to pistil.", answer: "pollen" },
  { question: "Seed dispersal by wind uses light, winged ___.", answer: "seeds" },
  { question: "The male part of a flower is ___.", answer: "stamen" },
  { question: "The female part of a flower is ___.", answer: "pistil" },
  { question: "Germination requires water, air, and ___.", answer: "warmth" },
  { question: "Photosynthesis stores energy in form of ___.", answer: "glucose" },
  { question: "Plants that grow in water are ___.", answer: "aquatic" },
  { question: "Cactus is a ___ plant.", answer: "desert/xerophyte" },
  { question: "The outer covering of a seed is called ___.", answer: "seed coat" },
  { question: "Ovary of a flower becomes the ___.", answer: "fruit" },
  { question: "Ovule becomes the ___.", answer: "seed" },
  { question: "Respiration in plants uses ___ and releases CO2.", answer: "oxygen" },
  { question: "Roots absorb ___ and minerals from soil.", answer: "water" },
  { question: "Leaves are the main site of ___.", answer: "photosynthesis" },
  { question: "Bees help in ___ pollination.", answer: "cross" },
  { question: "Venus flytrap is an example of ___ plant.", answer: "insectivorous" },
  { question: "Mushroom is not a plant — it is a ___.", answer: "fungus" },
  { question: "Ferns reproduce through ___.", answer: "spores" },
  { question: "Mosses are examples of ___ plants.", answer: "non-vascular" },
  { question: "Deciduous plants shed their ___ in autumn.", answer: "leaves" },
  { question: "Evergreen plants keep their leaves ___.", answer: "throughout the year" },
  { question: "The study of plants is called ___.", answer: "botany" },
  { question: "Epiphytes grow on other ___.", answer: "plants/trees" },
  { question: "Parasitic plants get food from ___.", answer: "host plants" },
  { question: "Turgor pressure in cells keeps plants ___.", answer: "upright/turgid" }
],

"animals": [
  { question: "Animals that eat only plants are ___.", answer: "herbivores" },
  { question: "Animals that eat only meat are ___.", answer: "carnivores" },
  { question: "Animals that eat both plants and meat are ___.", answer: "omnivores" },
  { question: "Cold-blooded animals are also called ___.", answer: "ectotherms" },
  { question: "Warm-blooded animals are also called ___.", answer: "endotherms" },
  { question: "Animals that feed on dead organisms are ___.", answer: "scavengers" },
  { question: "Amphibians can live in water and on ___.", answer: "land" },
  { question: "Reptiles breathe using ___.", answer: "lungs" },
  { question: "Mammals feed their young on ___.", answer: "milk" },
  { question: "Birds have ___ instead of teeth.", answer: "beaks" },
  { question: "Fish breathe through ___.", answer: "gills" },
  { question: "The process of an insect changing form is ___.", answer: "metamorphosis" },
  { question: "A caterpillar changes into a ___.", answer: "butterfly" },
  { question: "Vertebrates have a ___.", answer: "backbone/spine" },
  { question: "Invertebrates do NOT have a ___.", answer: "backbone" },
  { question: "An octopus is an example of ___.", answer: "invertebrate" },
  { question: "A shark is an example of ___.", answer: "fish" },
  { question: "Frogs undergo ___ metamorphosis.", answer: "complete" },
  { question: "Migration is movement of animals due to ___.", answer: "seasonal change" },
  { question: "Camouflage helps animals ___.", answer: "hide/blend" },
  { question: "Nocturnal animals are active at ___.", answer: "night" },
  { question: "Diurnal animals are active during the ___.", answer: "day" },
  { question: "Dolphins are ___ mammals.", answer: "aquatic" },
  { question: "Bats are the only flying ___.", answer: "mammals" },
  { question: "Snakes are ___.", answer: "reptiles" },
  { question: "An exoskeleton is found in ___.", answer: "insects/arthropods" },
  { question: "The study of animals is called ___.", answer: "zoology" },
  { question: "Animals that hibernate sleep through ___.", answer: "winter" },
  { question: "Producers in a food chain are ___.", answer: "plants" },
  { question: "Consumers in a food chain are ___.", answer: "animals" },
  { question: "Decomposers in a food chain are ___.", answer: "bacteria/fungi" },
  { question: "An ecosystem includes living and ___ components.", answer: "non-living" },
  { question: "Food chains begin with a ___.", answer: "producer" },
  { question: "Top of food chain is the ___ predator.", answer: "apex" },
  { question: "Endangered species are at risk of ___.", answer: "extinction" },
  { question: "Asexual reproduction requires ___ parent.", answer: "one" },
  { question: "Sexual reproduction requires ___ parents.", answer: "two" },
  { question: "A drone is a male ___.", answer: "bee" },
  { question: "Silk is produced by ___.", answer: "silkworms" },
  { question: "Honey is produced by ___.", answer: "bees" }
],

"human body": [
  { question: "The body system that pumps blood is ___.", answer: "circulatory" },
  { question: "The heart pumps ___ around the body.", answer: "blood" },
  { question: "The lungs are part of the ___ system.", answer: "respiratory" },
  { question: "Oxygen enters the blood in the ___.", answer: "lungs" },
  { question: "The brain is part of the ___ system.", answer: "nervous" },
  { question: "Bones form the ___ system.", answer: "skeletal" },
  { question: "Muscles are part of the ___ system.", answer: "muscular" },
  { question: "The stomach is part of the ___ system.", answer: "digestive" },
  { question: "Kidneys are part of the ___ system.", answer: "excretory" },
  { question: "Red blood cells carry ___.", answer: "oxygen" },
  { question: "White blood cells fight ___.", answer: "infection/disease" },
  { question: "Platelets help blood to ___.", answer: "clot" },
  { question: "The largest organ in the body is ___.", answer: "skin" },
  { question: "The smallest bone is in the ___.", answer: "ear" },
  { question: "Number of bones in adult body is ___.", answer: "206" },
  { question: "The biceps is a muscle in the ___.", answer: "arm" },
  { question: "Involuntary muscles are controlled by ___.", answer: "nervous system automatically" },
  { question: "The diaphragm helps in ___.", answer: "breathing" },
  { question: "Saliva begins ___ in the mouth.", answer: "digestion" },
  { question: "The small intestine absorbs ___.", answer: "nutrients" },
  { question: "The large intestine absorbs ___.", answer: "water" },
  { question: "The liver produces ___.", answer: "bile" },
  { question: "The pancreas produces ___.", answer: "insulin" },
  { question: "Neurons are cells of the ___ system.", answer: "nervous" },
  { question: "The spinal cord connects the brain and ___.", answer: "body" },
  { question: "The immune system protects against ___.", answer: "disease" },
  { question: "Vaccination introduces ___ into the body.", answer: "antigens/weakened pathogens" },
  { question: "Blood type is determined by ___ on red cells.", answer: "antigens" },
  { question: "The heart has ___ chambers.", answer: "4" },
  { question: "Arteries carry blood ___ from the heart.", answer: "away" },
  { question: "Veins carry blood ___ the heart.", answer: "toward" },
  { question: "Capillaries are the smallest ___.", answer: "blood vessels" },
  { question: "The trachea is part of the ___ system.", answer: "respiratory" },
  { question: "Alveoli are tiny sacs in the ___.", answer: "lungs" },
  { question: "The femur is in the ___.", answer: "thigh/leg" },
  { question: "The retina is part of the ___.", answer: "eye" },
  { question: "The cochlea is part of the ___.", answer: "ear" },
  { question: "Hormones are produced by ___ glands.", answer: "endocrine" },
  { question: "Insulin regulates ___.", answer: "blood sugar/glucose" },
  { question: "The thyroid gland produces ___.", answer: "thyroxine" }
],

"matter": [
  { question: "Matter has mass and occupies ___.", answer: "space" },
  { question: "The three states of matter are solid, liquid, and ___.", answer: "gas" },
  { question: "Solids have definite shape and ___.", answer: "volume" },
  { question: "Liquids have definite ___ but no definite shape.", answer: "volume" },
  { question: "Gases have no definite shape or ___.", answer: "volume" },
  { question: "Melting is change from solid to ___.", answer: "liquid" },
  { question: "Freezing is change from liquid to ___.", answer: "solid" },
  { question: "Evaporation is change from liquid to ___.", answer: "gas" },
  { question: "Condensation is change from gas to ___.", answer: "liquid" },
  { question: "Sublimation is change from solid directly to ___.", answer: "gas" },
  { question: "A mixture can be ___ by physical methods.", answer: "separated" },
  { question: "A compound has a fixed ___ composition.", answer: "chemical" },
  { question: "Elements cannot be broken into ___ substances.", answer: "simpler" },
  { question: "Atoms combine to form ___.", answer: "molecules" },
  { question: "Mass per unit volume is called ___.", answer: "density" },
  { question: "Density = mass / ___.", answer: "volume" },
  { question: "Ice melts at ___ degrees Celsius.", answer: "0" },
  { question: "Water boils at ___ degrees Celsius.", answer: "100" },
  { question: "Physical change does NOT form a new ___.", answer: "substance" },
  { question: "Chemical change forms a new ___.", answer: "substance" },
  { question: "Burning of wood is a ___ change.", answer: "chemical" },
  { question: "Melting of ice is a ___ change.", answer: "physical" },
  { question: "A solution is a ___ mixture.", answer: "homogeneous" },
  { question: "Solute + solvent = ___.", answer: "solution" },
  { question: "Salt dissolves in water — salt is the ___.", answer: "solute" },
  { question: "Water in a solution is the ___.", answer: "solvent" },
  { question: "Suspension is a ___ mixture.", answer: "heterogeneous" },
  { question: "Plasma is sometimes called the 4th state of ___.", answer: "matter" },
  { question: "Mass is measured in ___.", answer: "kg/g" },
  { question: "Volume is measured in ___.", answer: "liters/cm3" },
  { question: "Rusting of iron is a ___ change.", answer: "chemical" },
  { question: "Cutting paper is a ___ change.", answer: "physical" },
  { question: "Gas pressure increases when temperature ___.", answer: "increases" },
  { question: "Particles in a solid are closely ___.", answer: "packed" },
  { question: "Particles in a gas are widely ___.", answer: "spread/apart" },
  { question: "Brownian motion shows that particles are always ___.", answer: "moving" },
  { question: "Diffusion is mixing of particles by ___.", answer: "random motion" },
  { question: "Osmosis is movement of water through a ___ membrane.", answer: "semipermeable" },
  { question: "The process of separating salt from seawater is ___.", answer: "evaporation" },
  { question: "Alloys are ___ of metals.", answer: "mixtures" }
],

"force and motion": [
  { question: "Force can change the ___ of an object.", answer: "shape/speed/direction" },
  { question: "SI unit of force is ___.", answer: "Newton" },
  { question: "Gravity pulls objects ___.", answer: "downward" },
  { question: "Friction opposes ___.", answer: "motion" },
  { question: "Friction creates ___.", answer: "heat" },
  { question: "A smooth surface has ___ friction.", answer: "less" },
  { question: "Speed = distance / ___.", answer: "time" },
  { question: "Velocity includes speed and ___.", answer: "direction" },
  { question: "Acceleration = change in velocity / ___.", answer: "time" },
  { question: "Newton's 1st Law is the law of ___.", answer: "inertia" },
  { question: "Newton's 2nd Law: F = ___.", answer: "ma" },
  { question: "Newton's 3rd Law: every action has an equal and opposite ___.", answer: "reaction" },
  { question: "Weight = mass x ___.", answer: "gravity" },
  { question: "Gravitational force on moon is ___ of Earth's.", answer: "1/6th" },
  { question: "SI unit of mass is ___.", answer: "kg" },
  { question: "SI unit of weight is ___.", answer: "Newton" },
  { question: "Pressure = force / ___.", answer: "area" },
  { question: "Buoyancy is the ___ force on an object in fluid.", answer: "upward" },
  { question: "Archimedes' principle relates to ___.", answer: "buoyancy" },
  { question: "A body floats if its density is less than ___.", answer: "water/fluid" },
  { question: "Distance-time graph slope = ___.", answer: "speed" },
  { question: "Uniform motion has constant ___.", answer: "speed/velocity" },
  { question: "Non-uniform motion has changing ___.", answer: "speed" },
  { question: "A spring balance measures ___.", answer: "weight" },
  { question: "A beam balance measures ___.", answer: "mass" },
  { question: "Magnetic force is a ___ force.", answer: "non-contact" },
  { question: "Electrostatic force is a ___ force.", answer: "non-contact" },
  { question: "Friction can be reduced by ___.", answer: "lubrication" },
  { question: "Terminal velocity is reached when drag equals ___.", answer: "weight" },
  { question: "Work = force x ___.", answer: "distance" },
  { question: "Power = work / ___.", answer: "time" },
  { question: "SI unit of energy is ___.", answer: "Joule" },
  { question: "Kinetic energy is energy of ___.", answer: "motion" },
  { question: "Potential energy is energy of ___.", answer: "position" },
  { question: "KE = 0.5 x mass x ___.", answer: "velocity squared" },
  { question: "Conservation of energy: energy cannot be ___ or destroyed.", answer: "created" },
  { question: "Momentum = mass x ___.", answer: "velocity" },
  { question: "Impulse = force x ___.", answer: "time" },
  { question: "Rolling friction is ___ than sliding friction.", answer: "less" },
  { question: "Drag is friction in ___.", answer: "fluids/air/water" }
],

"light": [
  { question: "Light travels in ___ lines.", answer: "straight" },
  { question: "Speed of light is ___ m/s (approx).", answer: "300,000,000 / 3x10^8" },
  { question: "Reflection follows the law of ___.", answer: "reflection" },
  { question: "Angle of incidence = angle of ___.", answer: "reflection" },
  { question: "Refraction is bending of light when it changes ___.", answer: "medium" },
  { question: "A prism splits light into ___.", answer: "spectrum/rainbow colors" },
  { question: "The colors of the visible spectrum: VIBGYOR stands for ___.", answer: "Violet Indigo Blue Green Yellow Orange Red" },
  { question: "Convex lens converges (brings together) ___.", answer: "light" },
  { question: "Concave lens diverges (spreads apart) ___.", answer: "light" },
  { question: "A mirror reflects ___.", answer: "light" },
  { question: "Plane mirror forms a ___ image.", answer: "virtual" },
  { question: "Virtual image cannot be formed on ___.", answer: "screen" },
  { question: "Opaque objects do not allow light to ___.", answer: "pass through" },
  { question: "Transparent objects allow light to ___.", answer: "pass through" },
  { question: "Translucent objects allow ___ light to pass.", answer: "partial" },
  { question: "Shadows are formed when light is ___.", answer: "blocked" },
  { question: "Total internal reflection occurs when angle exceeds ___.", answer: "critical angle" },
  { question: "Optical fibers use ___.", answer: "total internal reflection" },
  { question: "Human eye has a ___ lens.", answer: "convex" },
  { question: "Retina converts light into ___.", answer: "nerve signals" },
  { question: "Myopia (short-sightedness) is corrected by ___ lens.", answer: "concave" },
  { question: "Hyperopia (long-sightedness) is corrected by ___ lens.", answer: "convex" },
  { question: "Primary colors of light are red, green, and ___.", answer: "blue" },
  { question: "White light is a ___ of all colors.", answer: "mixture" },
  { question: "Electromagnetic spectrum includes visible light and ___.", answer: "UV/IR/radio waves etc." },
  { question: "Photon is a particle of ___.", answer: "light" },
  { question: "Luminescent materials glow ___.", answer: "without heat" },
  { question: "Solar eclipse occurs when ___ blocks sunlight.", answer: "moon" },
  { question: "Umbra is the complete ___ region.", answer: "shadow/dark" },
  { question: "Penumbra is the partial ___.", answer: "shadow" }
],

"electricity": [
  { question: "Electric current is flow of ___.", answer: "electrons/charge" },
  { question: "SI unit of current is ___.", answer: "Ampere" },
  { question: "SI unit of resistance is ___.", answer: "Ohm" },
  { question: "SI unit of voltage is ___.", answer: "Volt" },
  { question: "Ohm's law: V = ___.", answer: "IR" },
  { question: "Good conductors have ___ resistance.", answer: "low" },
  { question: "Insulators have ___ resistance.", answer: "high" },
  { question: "A switch ___ or opens a circuit.", answer: "closes" },
  { question: "In series circuit, current is ___ everywhere.", answer: "same" },
  { question: "In parallel circuit, voltage is ___ everywhere.", answer: "same" },
  { question: "A fuse protects against ___.", answer: "overload/excess current" },
  { question: "Electric power = voltage x ___.", answer: "current" },
  { question: "SI unit of power is ___.", answer: "Watt" },
  { question: "SI unit of energy is ___.", answer: "Joule" },
  { question: "Energy = power x ___.", answer: "time" },
  { question: "kWh is the unit of electrical ___.", answer: "energy" },
  { question: "Electromagnet is made using current and ___.", answer: "iron core/coil" },
  { question: "Electric motor converts electrical to ___ energy.", answer: "mechanical" },
  { question: "Generator converts mechanical to ___ energy.", answer: "electrical" },
  { question: "Short circuit has ___ resistance path.", answer: "low" },
  { question: "Earthing provides safety against ___ shock.", answer: "electric" },
  { question: "Dry cell produces ___.", answer: "DC current" },
  { question: "AC stands for ___ current.", answer: "alternating" },
  { question: "DC stands for ___ current.", answer: "direct" },
  { question: "Resistance of conductors increases with ___.", answer: "temperature" },
  { question: "A rheostat is a variable ___.", answer: "resistor" },
  { question: "Bulb converts electrical energy to ___ and heat.", answer: "light" },
  { question: "Lightning conductor protects buildings from ___.", answer: "lightning" },
  { question: "Static electricity involves ___ on surfaces.", answer: "charge" },
  { question: "Charged objects attract ___.", answer: "opposite charges/neutral objects" }
],

"sound": [
  { question: "Sound needs a ___ to travel.", answer: "medium" },
  { question: "Sound cannot travel through ___.", answer: "vacuum" },
  { question: "Sound travels fastest in ___.", answer: "solids" },
  { question: "Frequency of sound is measured in ___.", answer: "Hertz" },
  { question: "High frequency sound has ___ pitch.", answer: "high" },
  { question: "Amplitude determines ___ of sound.", answer: "loudness" },
  { question: "Loudness is measured in ___.", answer: "decibels" },
  { question: "Echo is ___ of sound.", answer: "reflection" },
  { question: "Ultrasound has frequency above ___ Hz.", answer: "20,000" },
  { question: "Infrasound has frequency below ___ Hz.", answer: "20" },
  { question: "Human ear can hear ___ to 20,000 Hz.", answer: "20" },
  { question: "Speed of sound in air is about ___ m/s.", answer: "340/343" },
  { question: "Musical instruments use ___ to produce sound.", answer: "vibrations" },
  { question: "Sonar uses ___ to detect underwater objects.", answer: "ultrasound" },
  { question: "Reverberation is prolonged ___.", answer: "sound/echo" },
  { question: "Pitch depends on ___.", answer: "frequency" },
  { question: "Loudness depends on ___.", answer: "amplitude" },
  { question: "Sound is a ___ wave.", answer: "longitudinal" },
  { question: "Compressions and rarefactions are in ___ waves.", answer: "longitudinal" },
  { question: "Noise pollution can damage ___.", answer: "hearing/ears" },
  { question: "A tuning fork produces a ___ note.", answer: "pure/single" },
  { question: "Wavelength is distance between two ___.", answer: "compressions/rarefactions" },
  { question: "Speed = frequency x ___.", answer: "wavelength" },
  { question: "Bats use ___ for navigation.", answer: "echolocation" },
  { question: "Sonic boom occurs when object exceeds ___ of sound.", answer: "speed" },
  { question: "Resonance occurs when vibrations match ___ frequency.", answer: "natural" },
  { question: "Sound energy can be converted to ___ energy.", answer: "electrical" },
  { question: "Microphone converts sound to ___.", answer: "electrical signals" },
  { question: "Speaker converts electrical signals to ___.", answer: "sound" },
  { question: "Decibel (dB) scale is ___ (geometric/linear).", answer: "logarithmic" }
],
};

const FALLBACK: Question[] = [
  { question: "Science is the systematic study of the ___ world.", answer: "natural" },
  { question: "Hypothesis is a ___ explanation.", answer: "testable" },
  { question: "The independent variable is ___ by the experimenter.", answer: "changed" },
  { question: "The dependent variable is ___ in an experiment.", answer: "measured" },
  { question: "A controlled variable is kept ___.", answer: "constant" },
  { question: "Observations should be ___ and reproducible.", answer: "accurate" },
  { question: "The conclusion is based on ___.", answer: "data/evidence" },
  { question: "Peer review ensures scientific ___.", answer: "accuracy/validity" },
  { question: "SI system is used for ___ measurements.", answer: "standard" },
  { question: "The cell is the basic unit of ___.", answer: "life" },
  { question: "Cells were discovered by Robert ___.", answer: "Hooke" },
  { question: "DNA is found in the ___.", answer: "nucleus" },
  { question: "Mitochondria is the ___ of the cell.", answer: "powerhouse" },
  { question: "Cell membrane controls what ___ the cell.", answer: "enters/exits" },
  { question: "Plant cells have a ___ wall.", answer: "cell" },
  { question: "Chloroplasts are found in ___ cells.", answer: "plant" },
  { question: "Nucleus controls cell ___.", answer: "activities" },
  { question: "Unicellular organisms have ___ cell.", answer: "one" },
  { question: "Multicellular organisms have ___ cells.", answer: "many" },
  { question: "Bacteria are ___ organisms.", answer: "prokaryotic" }
];

function normalize(topic: string): string {
  return topic.toLowerCase().replace(/[^a-z ]/g, "").trim();
}

function findBank(topic: string): Question[] {
  const n = normalize(topic);
  for (const key of Object.keys(BANKS)) {
    if (n.includes(key)) return BANKS[key];
  }
  if (n.includes("plant")) return BANKS["plants"];
  if (n.includes("animal")) return BANKS["animals"];
  if (n.includes("body") || n.includes("human") || n.includes("nutrition")) return BANKS["human body"];
  if (n.includes("matter") || n.includes("material") || n.includes("state")) return BANKS["matter"];
  if (n.includes("force") || n.includes("motion") || n.includes("pressure")) return BANKS["force and motion"];
  if (n.includes("light") || n.includes("optic")) return BANKS["light"];
  if (n.includes("electric") || n.includes("magnet") || n.includes("current")) return BANKS["electricity"];
  if (n.includes("sound") || n.includes("wave")) return BANKS["sound"];
  return FALLBACK;
}

export function generateScienceQuestions(
  _gradeId: string,
  topicLabel: string,
  _sheetNumber: number
): Question[] {
  // Return the full bank; caller applies seeded shuffle + slice
  return findBank(topicLabel);
}
