import React from "react";

export function AirplaneFourForcesDiagram() {
  return (
    <div className="w-full bg-slate-950 rounded-2xl overflow-hidden border border-slate-800 shadow-xl p-4 sm:p-6">
      <div className="flex items-center justify-between mb-3">
        <span className="text-xs font-bold uppercase tracking-wider text-sky-400 bg-sky-950/80 px-2.5 py-1 rounded-full border border-sky-800/60">
          Flight Physics
        </span>
        <span className="text-xs text-slate-400 font-medium">The 4 Opposing Forces of Aerodynamics</span>
      </div>
      <svg viewBox="0 0 720 360" className="w-full h-auto" aria-label="Four Forces of Flight Diagram">
        <defs>
          <linearGradient id="aff-sky" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#0f172a" />
            <stop offset="100%" stopColor="#1e293b" />
          </linearGradient>
        </defs>

        <rect width="720" height="360" fill="url(#aff-sky)" rx="12" />

        {/* Clouds in background */}
        <g opacity="0.3">
          <ellipse cx="140" cy="100" rx="70" ry="25" fill="#ffffff" />
          <ellipse cx="190" cy="90" rx="50" ry="20" fill="#ffffff" />
          <ellipse cx="580" cy="240" rx="90" ry="30" fill="#ffffff" />
        </g>

        {/* Airplane Silhouette in Center */}
        <g transform="translate(360, 180)">
          {/* Fuselage */}
          <path d="M-130 0 C-100 -22 100 -22 140 -5 C160 5 130 18 100 18 L-100 18 C-125 15 -140 10 -130 0 Z" fill="#cbd5e1" stroke="#ffffff" strokeWidth="1.5" />
          {/* Cockpit Window */}
          <path d="M115 -8 L130 -3 L125 4 L110 0 Z" fill="#0284c7" />
          {/* Main Wing (Swept) */}
          <path d="M-20 5 L-50 85 L-10 85 L40 5 Z" fill="#94a3b8" stroke="#cbd5e1" strokeWidth="1" />
          {/* Tail Fin (Vertical Stabilizer) */}
          <path d="M-95 -12 L-135 -75 L-105 -75 L-70 -12 Z" fill="#94a3b8" stroke="#cbd5e1" strokeWidth="1" />
          {/* Tail Horizontal Stabilizer */}
          <path d="M-105 0 L-130 25 L-110 25 L-90 0 Z" fill="#64748b" />
          {/* Jet Engine under wing */}
          <ellipse cx="5" cy="55" rx="28" ry="12" fill="#475569" stroke="#94a3b8" strokeWidth="1.5" />
          <ellipse cx="-20" cy="55" rx="6" ry="11" fill="#f97316" />

          {/* ── FORCE 1: LIFT (UP - Emerald Green) ────────────────────── */}
          <line x1="0" y1="-25" x2="0" y2="-125" stroke="#22c55e" strokeWidth="6" strokeLinecap="round" />
          <polygon points="-10,-125 10,-125 0,-145" fill="#22c55e" />
          <g transform="translate(18, -115)">
            <rect width="135" height="40" rx="6" fill="#052e16" stroke="#22c55e" strokeWidth="1" />
            <text x="10" y="18" fill="#4ade80" fontSize="12" fontWeight="black">LIFT ⬆️</text>
            <text x="10" y="32" fill="#dcfce7" fontSize="9">Generated by wings</text>
          </g>

          {/* ── FORCE 2: WEIGHT / GRAVITY (DOWN - Crimson Red) ────────── */}
          <line x1="0" y1="20" x2="0" y2="120" stroke="#ef4444" strokeWidth="6" strokeLinecap="round" />
          <polygon points="-10,120 10,120 0,140" fill="#ef4444" />
          <g transform="translate(18, 95)">
            <rect width="145" height="40" rx="6" fill="#450a0a" stroke="#ef4444" strokeWidth="1" />
            <text x="10" y="18" fill="#f87171" fontSize="12" fontWeight="black">WEIGHT ⬇️</text>
            <text x="10" y="32" fill="#fee2e2" fontSize="9">Gravity pulls mass down</text>
          </g>

          {/* ── FORCE 3: THRUST (FORWARD/RIGHT - Cyan Blue) ────────────── */}
          <line x1="140" y1="5" x2="230" y2="5" stroke="#38bdf8" strokeWidth="6" strokeLinecap="round" />
          <polygon points="230,-5 230,15 250,5" fill="#38bdf8" />
          <g transform="translate(150, -50)">
            <rect width="140" height="40" rx="6" fill="#082f49" stroke="#38bdf8" strokeWidth="1" />
            <text x="10" y="18" fill="#38bdf8" fontSize="12" fontWeight="black">THRUST ➔</text>
            <text x="10" y="32" fill="#e0f2fe" fontSize="9">Engines push forward</text>
          </g>

          {/* ── FORCE 4: DRAG (BACKWARD/LEFT - Amber Yellow) ──────────── */}
          <line x1="-140" y1="5" x2="-230" y2="5" stroke="#f59e0b" strokeWidth="6" strokeLinecap="round" />
          <polygon points="-230,-5 -230,15 -250,5" fill="#f59e0b" />
          <g transform="translate(-295, -50)">
            <rect width="140" height="40" rx="6" fill="#451a03" stroke="#f59e0b" strokeWidth="1" />
            <text x="10" y="18" fill="#fde047" fontSize="12" fontWeight="black">⬅️ DRAG</text>
            <text x="10" y="32" fill="#fef3c7" fontSize="9">Air resistance friction</text>
          </g>
        </g>
      </svg>
      <p className="mt-3 text-xs text-slate-400 text-center">
        <strong>Dynamic Equilibrium:</strong> When an airplane flies in steady, level cruise, Lift equals Weight and Thrust equals Drag. To climb, Lift exceeds Weight; to accelerate, Thrust exceeds Drag.
      </p>
    </div>
  );
}

export function AirplaneAirfoilCamberDiagram() {
  return (
    <div className="w-full bg-slate-950 rounded-2xl overflow-hidden border border-slate-800 shadow-xl p-4 sm:p-6">
      <div className="flex items-center justify-between mb-3">
        <span className="text-xs font-bold uppercase tracking-wider text-emerald-400 bg-emerald-950/80 px-2.5 py-1 rounded-full border border-emerald-800/60">
          Aerodynamic Wing Profile
        </span>
        <span className="text-xs text-slate-400 font-medium">Bernoulli&apos;s Pressure &amp; Newton&apos;s Downwash</span>
      </div>
      <svg viewBox="0 0 720 320" className="w-full h-auto" aria-label="Airfoil Wing Camber Pressure Diagram">
        <defs>
          <linearGradient id="aac-lowp" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#38bdf8" stopOpacity="0.3" />
            <stop offset="100%" stopColor="#0284c7" stopOpacity="0.0" />
          </linearGradient>
          <linearGradient id="aac-highp" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#f59e0b" stopOpacity="0.0" />
            <stop offset="100%" stopColor="#ef4444" stopOpacity="0.3" />
          </linearGradient>
        </defs>

        <rect width="720" height="320" fill="#030712" rx="12" />

        {/* Airflow Streamlines over the top (Fast airflow / Curved up and over) */}
        <g stroke="#38bdf8" strokeWidth="2.5" fill="none" opacity="0.8">
          <path d="M30 90 Q220 50 360 40 Q500 50 690 120" strokeDasharray="8 4" />
          <path d="M30 115 Q220 75 360 65 Q500 80 690 145" strokeDasharray="8 4" />
          <path d="M30 140 Q220 100 360 90 Q500 115 690 170" strokeDasharray="8 4" />
        </g>
        <rect x="250" y="25" width="220" height="28" rx="6" fill="#082f49" stroke="#38bdf8" strokeWidth="1" />
        <text x="360" y="44" fill="#38bdf8" fontSize="11" fontWeight="black" textAnchor="middle">FAST AIRFLOW ➔ LOW PRESSURE (Bernoulli)</text>

        {/* The Airfoil Wing Profile in Center (Tilted at Angle of Attack) */}
        <g transform="translate(360, 160) rotate(-6)">
          {/* Curved teardrop airfoil */}
          <path d="M-190 0 C-150 -75 60 -65 190 0 C80 15 -100 15 -190 0 Z"
                fill="#cbd5e1" stroke="#f8fafc" strokeWidth="2.5" />
          {/* Chord Line */}
          <line x1="-190" y1="0" x2="190" y2="0" stroke="#f43f5e" strokeWidth="1.5" strokeDasharray="4 3" />
          <text x="0" y="4" fill="#475569" fontSize="11" fontWeight="bold" textAnchor="middle">Chord Line</text>

          {/* LIFT Vector Arrow straight up */}
          <line x1="0" y1="-35" x2="0" y2="-90" stroke="#22c55e" strokeWidth="5" markerEnd="url(#arrow)" />
          <text x="10" y="-65" fill="#4ade80" fontSize="12" fontWeight="black">LIFT ⬆️</text>
        </g>

        {/* Airflow Streamlines beneath (Slow airflow / High Pressure) */}
        <g stroke="#f59e0b" strokeWidth="2.5" fill="none" opacity="0.8">
          <path d="M30 180 Q220 175 360 185 Q500 205 690 240" strokeDasharray="8 4" />
          <path d="M30 205 Q220 200 360 215 Q500 235 690 270" strokeDasharray="8 4" />
        </g>
        <rect x="240" y="225" width="240" height="28" rx="6" fill="#451a03" stroke="#f59e0b" strokeWidth="1" />
        <text x="360" y="244" fill="#fde047" fontSize="11" fontWeight="black" textAnchor="middle">SLOWER AIRFLOW ➔ HIGH PRESSURE</text>

        {/* Newton's Downwash deflection arrow (Right) */}
        <g transform="translate(600, 210)">
          <path d="M0 0 L40 45" stroke="#ef4444" strokeWidth="4" markerEnd="url(#arrow)" />
          <text x="50" y="25" fill="#fca5a5" fontSize="10" fontWeight="black">Downwash ↘️</text>
          <text x="50" y="38" fill="#e2e8f0" fontSize="8">Newton&apos;s 3rd Law</text>
        </g>
      </svg>
      <p className="mt-3 text-xs text-slate-400 text-center">
        <strong>Dual Lift Mechanism:</strong> Air travels faster over the curved top, reducing air pressure (Bernoulli). At the same time, the angled wing deflects oncoming air sharply downward, pushing the aircraft upward (Newton).
      </p>
    </div>
  );
}

export function AirplaneFlightControlsDiagram() {
  return (
    <div className="w-full bg-slate-950 rounded-2xl overflow-hidden border border-slate-800 shadow-xl p-4 sm:p-6">
      <div className="flex items-center justify-between mb-3">
        <span className="text-xs font-bold uppercase tracking-wider text-amber-400 bg-amber-950/80 px-2.5 py-1 rounded-full border border-amber-800/60">
          Pilot Controls
        </span>
        <span className="text-xs text-slate-400 font-medium">The 3 Rotational Axes: Pitch, Roll, and Yaw</span>
      </div>
      <svg viewBox="0 0 720 300" className="w-full h-auto" aria-label="Airplane Flight Control Surfaces Diagram">
        <rect width="720" height="300" fill="#0b0f19" rx="12" />

        {/* ── 1. Ailerons (Roll) ───────────────────────────────────────── */}
        <g transform="translate(40, 30)">
          <rect width="195" height="235" rx="10" fill="#0f172a" stroke="#38bdf8" strokeWidth="1.5" />
          <text x="97" y="25" fill="#38bdf8" fontSize="13" fontWeight="black" textAnchor="middle">1. AILERONS</text>
          <text x="97" y="42" fill="#e2e8f0" fontSize="11" fontWeight="bold" textAnchor="middle">Controls ROLL (Bank)</text>

          {/* Wing silhouette */}
          <g transform="translate(97, 105)">
            <ellipse cx="0" cy="0" rx="75" ry="12" fill="#334155" />
            {/* Left Aileron Up */}
            <rect x="-70" y="-5" width="22" height="10" fill="#38bdf8" />
            <text x="-59" y="-10" fill="#38bdf8" fontSize="8" fontWeight="bold" textAnchor="middle">▲</text>
            {/* Right Aileron Down */}
            <rect x="48" y="-5" width="22" height="10" fill="#38bdf8" />
            <text x="59" y="18" fill="#38bdf8" fontSize="8" fontWeight="bold" textAnchor="middle">▼</text>
          </g>

          <text x="97" y="165" fill="#cbd5e1" fontSize="9" textAnchor="middle">Location: Outer wing edges</text>
          <text x="97" y="182" fill="#94a3b8" fontSize="8" textAnchor="middle">Move in opposite directions</text>
          <text x="97" y="205" fill="#fde047" fontSize="10" fontWeight="bold" textAnchor="middle">Banks plane left or right</text>
        </g>

        {/* ── 2. Elevators (Pitch) ─────────────────────────────────────── */}
        <g transform="translate(260, 30)">
          <rect width="195" height="235" rx="10" fill="#0f172a" stroke="#22c55e" strokeWidth="1.5" />
          <text x="97" y="25" fill="#22c55e" fontSize="13" fontWeight="black" textAnchor="middle">2. ELEVATORS</text>
          <text x="97" y="42" fill="#e2e8f0" fontSize="11" fontWeight="bold" textAnchor="middle">Controls PITCH (Nose)</text>

          {/* Horizontal tail stabilizer */}
          <g transform="translate(97, 105)">
            <ellipse cx="0" cy="0" rx="60" ry="10" fill="#334155" />
            {/* Movable elevator flap */}
            <rect x="-50" y="-3" width="100" height="8" fill="#22c55e" />
            <text x="0" y="-12" fill="#4ade80" fontSize="9" fontWeight="bold" textAnchor="middle">▲ Up = Nose UP</text>
            <text x="0" y="22" fill="#4ade80" fontSize="9" fontWeight="bold" textAnchor="middle">▼ Down = Nose DOWN</text>
          </g>

          <text x="97" y="165" fill="#cbd5e1" fontSize="9" textAnchor="middle">Location: Horizontal tail</text>
          <text x="97" y="182" fill="#94a3b8" fontSize="8" textAnchor="middle">Move together up or down</text>
          <text x="97" y="205" fill="#fde047" fontSize="10" fontWeight="bold" textAnchor="middle">Pitches nose up or down</text>
        </g>

        {/* ── 3. Rudder (Yaw) ─────────────────────────────────────────── */}
        <g transform="translate(480, 30)">
          <rect width="195" height="235" rx="10" fill="#0f172a" stroke="#f59e0b" strokeWidth="1.5" />
          <text x="97" y="25" fill="#f59e0b" fontSize="13" fontWeight="black" textAnchor="middle">3. RUDDER</text>
          <text x="97" y="42" fill="#e2e8f0" fontSize="11" fontWeight="bold" textAnchor="middle">Controls YAW (Turn)</text>

          {/* Vertical tail fin */}
          <g transform="translate(97, 105)">
            <polygon points="-15,20 0,-40 20,20" fill="#334155" />
            {/* Rudder flap */}
            <polygon points="5,-35 18,20 28,20 15,-35" fill="#f59e0b" />
            <text x="40" y="0" fill="#fde047" fontSize="8" fontWeight="bold">◀ Rudder ▶</text>
          </g>

          <text x="97" y="165" fill="#cbd5e1" fontSize="9" textAnchor="middle">Location: Vertical tail fin</text>
          <text x="97" y="182" fill="#94a3b8" fontSize="8" textAnchor="middle">Swings left or right</text>
          <text x="97" y="205" fill="#fde047" fontSize="10" fontWeight="bold" textAnchor="middle">Points nose left or right</text>
        </g>
      </svg>
    </div>
  );
}

export function AirplaneJetEngineDiagram() {
  return (
    <div className="w-full bg-slate-950 rounded-2xl overflow-hidden border border-slate-800 shadow-xl p-4 sm:p-6">
      <div className="flex items-center justify-between mb-3">
        <span className="text-xs font-bold uppercase tracking-wider text-rose-400 bg-rose-950/80 px-2.5 py-1 rounded-full border border-rose-800/60">
          Jet Propulsion
        </span>
        <span className="text-xs text-slate-400 font-medium">Inside a Commercial Turbofan Jet Engine</span>
      </div>
      <svg viewBox="0 0 720 300" className="w-full h-auto" aria-label="Turbofan Jet Engine Cutaway Diagram">
        <defs>
          <linearGradient id="aje-flame" x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor="#facc15" />
            <stop offset="50%" stopColor="#f97316" />
            <stop offset="100%" stopColor="#ef4444" />
          </linearGradient>
        </defs>

        <rect width="720" height="300" fill="#030712" rx="12" />

        {/* Engine Nacelle Casing */}
        <path d="M80 50 Q280 40 600 70 L580 100 Q280 80 100 80 Z" fill="#475569" stroke="#94a3b8" strokeWidth="1.5" />
        <path d="M80 250 Q280 260 600 230 L580 200 Q280 220 100 220 Z" fill="#475569" stroke="#94a3b8" strokeWidth="1.5" />

        {/* 1. Large Front Intake Fan */}
        <g transform="translate(100, 150)">
          <ellipse cx="0" cy="0" rx="14" ry="75" fill="#38bdf8" stroke="#ffffff" strokeWidth="2" />
          <circle cx="0" cy="0" r="18" fill="#1e293b" />
          <text x="-15" y="-90" fill="#38bdf8" fontSize="10" fontWeight="black" textAnchor="middle">1. Front Fan</text>
        </g>

        {/* Cold Bypass Airflow (Top & Bottom channels) */}
        <path d="M120 65 L570 85" stroke="#38bdf8" strokeWidth="6" strokeDasharray="6 4" />
        <text x="340" y="60" fill="#bae6fd" fontSize="9" fontWeight="bold" textAnchor="middle">Bypass Air Stream (80% of Thrust)</text>

        <path d="M120 235 L570 215" stroke="#38bdf8" strokeWidth="6" strokeDasharray="6 4" />
        <text x="340" y="250" fill="#bae6fd" fontSize="9" fontWeight="bold" textAnchor="middle">Quiet, High Fuel Efficiency</text>

        {/* Engine Core (Compressor ➔ Combustion ➔ Turbine) */}
        {/* 2. Compressor Stages */}
        <g transform="translate(220, 150)">
          <polygon points="-30,-40 30,-28 30,28 -30,40" fill="#0284c7" stroke="#38bdf8" strokeWidth="1" />
          <text x="0" y="5" fill="#ffffff" fontSize="8" fontWeight="bold" textAnchor="middle">Compressor</text>
          <text x="0" y="-50" fill="#38bdf8" fontSize="10" fontWeight="black" textAnchor="middle">2. Squashes Air</text>
        </g>

        {/* 3. Combustion Chamber (Burning Jet Fuel) */}
        <g transform="translate(330, 150)">
          <rect x="-35" y="-28" width="70" height="56" rx="6" fill="url(#aje-flame)" />
          <text x="0" y="5" fill="#ffffff" fontSize="9" fontWeight="black" textAnchor="middle">🔥 1,700°C</text>
          <text x="0" y="-45" fill="#fde047" fontSize="10" fontWeight="black" textAnchor="middle">3. Fuel Combustion</text>
        </g>

        {/* 4. Turbine Section */}
        <g transform="translate(440, 150)">
          <polygon points="-25,-28 25,-38 25,38 -25,28" fill="#ca8a04" stroke="#fde047" strokeWidth="1" />
          <text x="0" y="5" fill="#ffffff" fontSize="8" fontWeight="bold" textAnchor="middle">Turbine</text>
          <text x="0" y="-45" fill="#fde047" fontSize="10" fontWeight="black" textAnchor="middle">4. Spins Fan</text>
        </g>

        {/* 5. High-Velocity Exhaust Thrust */}
        <g transform="translate(560, 150)">
          <polygon points="0,-25 80,-40 80,40 0,25" fill="#ef4444" opacity="0.8" />
          <path d="M20 0 L100 0" stroke="#fde047" strokeWidth="4" markerEnd="url(#arrow)" />
          <text x="50" y="-48" fill="#fca5a5" fontSize="10" fontWeight="black" textAnchor="middle">5. High-Speed Exhaust</text>
          <text x="50" y="60" fill="#fde047" fontSize="11" fontWeight="black" textAnchor="middle">FORWARD THRUST ➔</text>
        </g>
      </svg>
    </div>
  );
}
