// Continent for every country in world-atlas/countries-110m (Natural Earth).
// Follows Natural Earth's own `continent` classification.

export type Continent =
  | "north-america"
  | "south-america"
  | "europe"
  | "africa"
  | "asia"
  | "oceania"
  | "antarctica";

export const CONTINENT_OF: Record<string, Continent> = {
  // ── North America ─────────────────────────────────────────────
  "Bahamas": "north-america",
  "Belize": "north-america",
  "Canada": "north-america",
  "Costa Rica": "north-america",
  "Cuba": "north-america",
  "Dominican Rep.": "north-america",
  "El Salvador": "north-america",
  "Greenland": "north-america",
  "Guatemala": "north-america",
  "Haiti": "north-america",
  "Honduras": "north-america",
  "Jamaica": "north-america",
  "Mexico": "north-america",
  "Nicaragua": "north-america",
  "Panama": "north-america",
  "Puerto Rico": "north-america",
  "Trinidad and Tobago": "north-america",
  "United States of America": "north-america",
  // ── South America ─────────────────────────────────────────────
  "Argentina": "south-america",
  "Bolivia": "south-america",
  "Brazil": "south-america",
  "Chile": "south-america",
  "Colombia": "south-america",
  "Ecuador": "south-america",
  "Falkland Is.": "south-america",
  "Guyana": "south-america",
  "Paraguay": "south-america",
  "Peru": "south-america",
  "Suriname": "south-america",
  "Uruguay": "south-america",
  "Venezuela": "south-america",
  // ── Europe ────────────────────────────────────────────────────
  "Albania": "europe",
  "Austria": "europe",
  "Belarus": "europe",
  "Belgium": "europe",
  "Bosnia and Herz.": "europe",
  "Bulgaria": "europe",
  "Croatia": "europe",
  "Czechia": "europe",
  "Denmark": "europe",
  "Estonia": "europe",
  "Finland": "europe",
  "France": "europe",
  "Germany": "europe",
  "Greece": "europe",
  "Hungary": "europe",
  "Iceland": "europe",
  "Ireland": "europe",
  "Italy": "europe",
  "Kosovo": "europe",
  "Latvia": "europe",
  "Lithuania": "europe",
  "Luxembourg": "europe",
  "Macedonia": "europe",
  "Moldova": "europe",
  "Montenegro": "europe",
  "Netherlands": "europe",
  "Norway": "europe",
  "Poland": "europe",
  "Portugal": "europe",
  "Romania": "europe",
  "Russia": "europe",
  "Serbia": "europe",
  "Slovakia": "europe",
  "Slovenia": "europe",
  "Spain": "europe",
  "Sweden": "europe",
  "Switzerland": "europe",
  "Ukraine": "europe",
  "United Kingdom": "europe",
  // ── Africa ────────────────────────────────────────────────────
  "Algeria": "africa",
  "Angola": "africa",
  "Benin": "africa",
  "Botswana": "africa",
  "Burkina Faso": "africa",
  "Burundi": "africa",
  "Cameroon": "africa",
  "Central African Rep.": "africa",
  "Chad": "africa",
  "Congo": "africa",
  "Côte d'Ivoire": "africa",
  "Dem. Rep. Congo": "africa",
  "Djibouti": "africa",
  "Egypt": "africa",
  "Eq. Guinea": "africa",
  "Eritrea": "africa",
  "eSwatini": "africa",
  "Ethiopia": "africa",
  "Gabon": "africa",
  "Gambia": "africa",
  "Ghana": "africa",
  "Guinea": "africa",
  "Guinea-Bissau": "africa",
  "Kenya": "africa",
  "Lesotho": "africa",
  "Liberia": "africa",
  "Libya": "africa",
  "Madagascar": "africa",
  "Malawi": "africa",
  "Mali": "africa",
  "Mauritania": "africa",
  "Morocco": "africa",
  "Mozambique": "africa",
  "Namibia": "africa",
  "Niger": "africa",
  "Nigeria": "africa",
  "Rwanda": "africa",
  "S. Sudan": "africa",
  "Senegal": "africa",
  "Sierra Leone": "africa",
  "Somalia": "africa",
  "Somaliland": "africa",
  "South Africa": "africa",
  "Sudan": "africa",
  "Tanzania": "africa",
  "Togo": "africa",
  "Tunisia": "africa",
  "Uganda": "africa",
  "W. Sahara": "africa",
  "Zambia": "africa",
  "Zimbabwe": "africa",
  // ── Asia ──────────────────────────────────────────────────────
  "Afghanistan": "asia",
  "Armenia": "asia",
  "Azerbaijan": "asia",
  "Bangladesh": "asia",
  "Bhutan": "asia",
  "Brunei": "asia",
  "Cambodia": "asia",
  "China": "asia",
  "Cyprus": "asia",
  "Georgia": "asia",
  "India": "asia",
  "Indonesia": "asia",
  "Iran": "asia",
  "Iraq": "asia",
  "Israel": "asia",
  "Japan": "asia",
  "Jordan": "asia",
  "Kazakhstan": "asia",
  "Kuwait": "asia",
  "Kyrgyzstan": "asia",
  "Laos": "asia",
  "Lebanon": "asia",
  "Malaysia": "asia",
  "Mongolia": "asia",
  "Myanmar": "asia",
  "N. Cyprus": "asia",
  "Nepal": "asia",
  "North Korea": "asia",
  "Oman": "asia",
  "Pakistan": "asia",
  "Palestine": "asia",
  "Philippines": "asia",
  "Qatar": "asia",
  "Saudi Arabia": "asia",
  "South Korea": "asia",
  "Sri Lanka": "asia",
  "Syria": "asia",
  "Taiwan": "asia",
  "Tajikistan": "asia",
  "Thailand": "asia",
  "Timor-Leste": "asia",
  "Turkey": "asia",
  "Turkmenistan": "asia",
  "United Arab Emirates": "asia",
  "Uzbekistan": "asia",
  "Vietnam": "asia",
  "Yemen": "asia",
  // ── Oceania ───────────────────────────────────────────────────
  "Australia": "oceania",
  "Fiji": "oceania",
  "New Caledonia": "oceania",
  "New Zealand": "oceania",
  "Papua New Guinea": "oceania",
  "Solomon Is.": "oceania",
  "Vanuatu": "oceania",
  // ── Antarctica ────────────────────────────────────────────────
  "Antarctica": "antarctica",
  "Fr. S. Antarctic Lands": "antarctica",
};

export const CONTINENT_LABEL: Record<Continent, string> = {
  "north-america": "North America",
  "south-america": "South America",
  "europe": "Europe",
  "africa": "Africa",
  "asia": "Asia",
  "oceania": "Australia",
  "antarctica": "Antarctica",
};

export const CONTINENT_FILL: Record<Continent, string> = {
  "north-america": "#e07a5f",
  "south-america": "#f2cc54",
  "europe": "#6a8ec9",
  "africa": "#e8a04e",
  "asia": "#7fb98c",
  "oceania": "#d9b48f",
  "antarctica": "#bcd6e6",
};
