// US state / territory name → 2-letter postal abbreviation + capital city.
export const US_STATE: Record<string, { abbr: string; capital: string }> = {
  "Alabama": { abbr: "AL", capital: "Montgomery" },
  "Alaska": { abbr: "AK", capital: "Juneau" },
  "Arizona": { abbr: "AZ", capital: "Phoenix" },
  "Arkansas": { abbr: "AR", capital: "Little Rock" },
  "California": { abbr: "CA", capital: "Sacramento" },
  "Colorado": { abbr: "CO", capital: "Denver" },
  "Connecticut": { abbr: "CT", capital: "Hartford" },
  "Delaware": { abbr: "DE", capital: "Dover" },
  "District of Columbia": { abbr: "DC", capital: "Washington" },
  "Florida": { abbr: "FL", capital: "Tallahassee" },
  "Georgia": { abbr: "GA", capital: "Atlanta" },
  "Hawaii": { abbr: "HI", capital: "Honolulu" },
  "Idaho": { abbr: "ID", capital: "Boise" },
  "Illinois": { abbr: "IL", capital: "Springfield" },
  "Indiana": { abbr: "IN", capital: "Indianapolis" },
  "Iowa": { abbr: "IA", capital: "Des Moines" },
  "Kansas": { abbr: "KS", capital: "Topeka" },
  "Kentucky": { abbr: "KY", capital: "Frankfort" },
  "Louisiana": { abbr: "LA", capital: "Baton Rouge" },
  "Maine": { abbr: "ME", capital: "Augusta" },
  "Maryland": { abbr: "MD", capital: "Annapolis" },
  "Massachusetts": { abbr: "MA", capital: "Boston" },
  "Michigan": { abbr: "MI", capital: "Lansing" },
  "Minnesota": { abbr: "MN", capital: "Saint Paul" },
  "Mississippi": { abbr: "MS", capital: "Jackson" },
  "Missouri": { abbr: "MO", capital: "Jefferson City" },
  "Montana": { abbr: "MT", capital: "Helena" },
  "Nebraska": { abbr: "NE", capital: "Lincoln" },
  "Nevada": { abbr: "NV", capital: "Carson City" },
  "New Hampshire": { abbr: "NH", capital: "Concord" },
  "New Jersey": { abbr: "NJ", capital: "Trenton" },
  "New Mexico": { abbr: "NM", capital: "Santa Fe" },
  "New York": { abbr: "NY", capital: "Albany" },
  "North Carolina": { abbr: "NC", capital: "Raleigh" },
  "North Dakota": { abbr: "ND", capital: "Bismarck" },
  "Ohio": { abbr: "OH", capital: "Columbus" },
  "Oklahoma": { abbr: "OK", capital: "Oklahoma City" },
  "Oregon": { abbr: "OR", capital: "Salem" },
  "Pennsylvania": { abbr: "PA", capital: "Harrisburg" },
  "Rhode Island": { abbr: "RI", capital: "Providence" },
  "South Carolina": { abbr: "SC", capital: "Columbia" },
  "South Dakota": { abbr: "SD", capital: "Pierre" },
  "Tennessee": { abbr: "TN", capital: "Nashville" },
  "Texas": { abbr: "TX", capital: "Austin" },
  "Utah": { abbr: "UT", capital: "Salt Lake City" },
  "Vermont": { abbr: "VT", capital: "Montpelier" },
  "Virginia": { abbr: "VA", capital: "Richmond" },
  "Washington": { abbr: "WA", capital: "Olympia" },
  "West Virginia": { abbr: "WV", capital: "Charleston" },
  "Wisconsin": { abbr: "WI", capital: "Madison" },
  "Wyoming": { abbr: "WY", capital: "Cheyenne" },
};
