import React from "react";

// [bgColor, fgColor, label] — label is 1–4 chars shown inside the icon
type BrandEntry = [string, string, string];

const BRANDS: Record<string, BrandEntry> = {
  // ── AI Agents ──────────────────────────────────────────────────────────────
  "ai agents":             ["#4F46E5", "#ffffff", "AI"],
  "agentic ai":            ["#7C3AED", "#ffffff", "Ag"],
  "tool calling":          ["#2563EB", "#ffffff", "TC"],
  "function calling":      ["#1D4ED8", "#ffffff", "FC"],
  "mcp":                   ["#374151", "#ffffff", "MCP"],
  "multi-agent systems":   ["#059669", "#ffffff", "MAS"],
  "agent memory":          ["#7C3AED", "#ffffff", "AM"],
  "planning":              ["#0891B2", "#ffffff", "Pl"],
  "reasoning":             ["#DB2777", "#ffffff", "Rz"],
  "react":                 ["#20232A", "#61DAFB", "⚛"],
  "langgraph":             ["#1C3C3C", "#22C55E", "LG"],
  "crewai":                ["#0F172A", "#F59E0B", "CA"],
  "autogen":               ["#2563EB", "#ffffff", "AG"],
  "semantic kernel":       ["#5C2D91", "#ffffff", "SK"],
  "openai agents sdk":     ["#412991", "#ffffff", "OAI"],
  "llamaindex":            ["#FF6B6B", "#ffffff", "LI"],

  // ── AI/ML ──────────────────────────────────────────────────────────────────
  "tensorflow":            ["#FF6F00", "#ffffff", "TF"],
  "pytorch":               ["#EE4C2C", "#ffffff", "PT"],
  "scikit-learn":          ["#F7931E", "#000000", "SK"],
  "xgboost":               ["#189AB4", "#ffffff", "XG"],
  "lightgbm":              ["#2AA876", "#ffffff", "LGB"],
  "keras":                 ["#D00000", "#ffffff", "Ke"],
  "cnn":                   ["#E91E63", "#ffffff", "CNN"],
  "rnn":                   ["#9C27B0", "#ffffff", "RNN"],
  "lstm":                  ["#673AB7", "#ffffff", "LSTM"],
  "gru":                   ["#3F51B5", "#ffffff", "GRU"],
  "transformer":           ["#FF6B35", "#ffffff", "TR"],
  "gan":                   ["#2196F3", "#ffffff", "GAN"],
  "autoencoder":           ["#00BCD4", "#ffffff", "AE"],
  "diffusion models":      ["#03A9F4", "#ffffff", "DM"],
  "llm":                   ["#5B21B6", "#ffffff", "LLM"],
  "slm":                   ["#795548", "#ffffff", "SLM"],
  "generative ai":         ["#FF5722", "#ffffff", "GenAI"],
  "multimodal ai":         ["#FFC107", "#000000", "MM"],
  "computer vision":       ["#8BC34A", "#000000", "CV"],
  "nlp":                   ["#FFEB3B", "#000000", "NLP"],
  "speech ai":             ["#FF9800", "#ffffff", "SA"],
  "reinforcement learning":["#00BCD4", "#ffffff", "RL"],
  "fine-tuning":           ["#009688", "#ffffff", "FT"],
  "distillation":          ["#4CAF50", "#ffffff", "Di"],
  "quantization":          ["#8BC34A", "#000000", "Qn"],

  // ── API Technologies ───────────────────────────────────────────────────────
  "rest":                  ["#009688", "#ffffff", "REST"],
  "soap":                  ["#F59E0B", "#000000", "SOAP"],
  "graphql":               ["#E10098", "#ffffff", "GQL"],
  "grpc":                  ["#244C5A", "#ffffff", "gRPC"],
  "websocket":             ["#4A90D9", "#ffffff", "WS"],
  "server-sent events":    ["#6366F1", "#ffffff", "SSE"],
  "webhooks":              ["#7C3AED", "#ffffff", "WH"],
  "postman":               ["#FF6C37", "#ffffff", "PM"],
  "swagger/openapi":       ["#85EA2D", "#000000", "OA"],
  "insomnia":              ["#4000BF", "#ffffff", "In"],
  "graphql playground":    ["#E10098", "#ffffff", "GP"],
  "kong":                  ["#003459", "#1CE1C1", "Ko"],
  "apache apisix":         ["#E0234E", "#ffffff", "AP"],
  "nginx":                 ["#009639", "#ffffff", "Nx"],
  "aws api gateway":       ["#FF9900", "#000000", "AG"],
  "azure api management":  ["#0078D4", "#ffffff", "AM"],
  "apigee":                ["#4285F4", "#ffffff", "Ap"],
  "traefik":               ["#24A1C1", "#ffffff", "Tr"],

  // ── Architecture ───────────────────────────────────────────────────────────
  "monolithic architecture":   ["#455A64", "#ffffff", "Mon"],
  "modular monolith":          ["#546E7A", "#ffffff", "MM"],
  "microservices":             ["#3F51B5", "#ffffff", "MS"],
  "serverless":                ["#FF9900", "#000000", "SLS"],
  "event-driven architecture": ["#E91E63", "#ffffff", "EDA"],
  "distributed systems":       ["#1565C0", "#ffffff", "DS"],
  "soa":                       ["#00ACC1", "#ffffff", "SOA"],
  "hexagonal architecture":    ["#607D8B", "#ffffff", "Hex"],
  "clean architecture":        ["#546E7A", "#ffffff", "CA"],
  "layered architecture":      ["#607D8B", "#ffffff", "LA"],
  "domain-driven design":      ["#673AB7", "#ffffff", "DDD"],
  "cqrs":                      ["#9C27B0", "#ffffff", "CQRS"],
  "event sourcing":            ["#3F51B5", "#ffffff", "ES"],
  "saga":                      ["#26A69A", "#ffffff", "Sg"],
  "strangler pattern":         ["#5D4037", "#ffffff", "SP"],
  "api gateway":               ["#FF9900", "#000000", "AG"],
  "backend for frontend":      ["#374151", "#ffffff", "BFF"],
  "strangler fig":             ["#5D4037", "#ffffff", "SF"],

  // ── BI & Visualization ─────────────────────────────────────────────────────
  "power bi":              ["#F2C811", "#000000", "PBI"],
  "tableau":               ["#E97627", "#ffffff", "Ta"],
  "looker":                ["#4285F4", "#ffffff", "Lo"],
  "qlik":                  ["#009845", "#ffffff", "Qk"],
  "apache superset":       ["#20A7C9", "#ffffff", "AS"],
  "grafana":               ["#F46800", "#ffffff", "Gr"],
  "kibana":                ["#005571", "#ffffff", "Ki"],

  // ── Backend Technologies ────────────────────────────────────────────────────
  "spring":                ["#6DB33F", "#ffffff", "Sp"],
  "spring boot":           ["#6DB33F", "#ffffff", "SB"],
  "spring cloud":          ["#6DB33F", "#ffffff", "SC"],
  "spring security":       ["#6DB33F", "#ffffff", "SS"],
  "hibernate":             ["#59666C", "#ffffff", "Hi"],
  "jpa":                   ["#4A90D9", "#ffffff", "JPA"],
  "jakarta ee":            ["#4285F4", "#ffffff", "JE"],
  "quarkus":               ["#4695EB", "#ffffff", "Qu"],
  "micronaut":             ["#09AFE5", "#ffffff", "Mn"],
  "django":                ["#092E20", "#ffffff", "Dj"],
  "flask":                 ["#000000", "#ffffff", "Fl"],
  "fastapi":               ["#009688", "#ffffff", "FA"],
  "tornado":               ["#F97316", "#ffffff", "To"],
  "celery":                ["#37814A", "#ffffff", "Ce"],
  "node.js":               ["#339933", "#ffffff", "No"],
  "express.js":            ["#000000", "#ffffff", "Ex"],
  "nestjs":                ["#E0234E", "#ffffff", "Nt"],
  "fastify":               ["#000000", "#ffffff", "Fy"],
  "koa":                   ["#33333D", "#ffffff", "Ko"],
  "asp.net core":          ["#512BD4", "#ffffff", "AS"],
  ".net":                  ["#512BD4", "#ffffff", ".N"],
  "entity framework core": ["#512BD4", "#ffffff", "EF"],
  "blazor":                ["#512BD4", "#ffffff", "Bl"],
  "gin":                   ["#00ADD8", "#ffffff", "Gi"],
  "echo":                  ["#00ADD8", "#ffffff", "Ec"],
  "fiber":                 ["#00ADD8", "#ffffff", "Fi"],
  "chi":                   ["#00ADD8", "#ffffff", "χ"],
  "laravel":               ["#FF2D20", "#ffffff", "La"],
  "symfony":               ["#000000", "#ffffff", "Sf"],
  "codeigniter":           ["#EF4223", "#ffffff", "CI"],
  "ruby on rails":         ["#CC0000", "#ffffff", "RoR"],
  "sinatra":               ["#1C1C1C", "#ffffff", "Si"],

  // ── Blockchain / Web3 ──────────────────────────────────────────────────────
  "bitcoin":               ["#F7931A", "#ffffff", "₿"],
  "ethereum":              ["#3C3C3D", "#ffffff", "Eth"],
  "solana":                ["#9945FF", "#ffffff", "Sol"],
  "hyperledger":           ["#2F3134", "#ffffff", "HL"],
  "solidity":              ["#363636", "#ffffff", "Sol"],
  "smart contracts":       ["#F7931A", "#ffffff", "SC"],
  "nfts":                  ["#9945FF", "#ffffff", "NFT"],
  "defi":                  ["#06B6D4", "#ffffff", "DeFi"],
  "web3":                  ["#F6851B", "#ffffff", "W3"],
  "wallets":               ["#374151", "#ffffff", "Wl"],
  "distributed ledger":    ["#374151", "#ffffff", "DL"],

  // ── Build & Package Management ─────────────────────────────────────────────
  "maven":                 ["#C71A36", "#ffffff", "Mv"],
  "gradle":                ["#02303A", "#ffffff", "Gr"],
  "npm":                   ["#CB3837", "#ffffff", "npm"],
  "yarn":                  ["#2C8EBB", "#ffffff", "Yn"],
  "pnpm":                  ["#F69220", "#000000", "pn"],
  "bun":                   ["#FBF0DF", "#000000", "Bun"],
  "pip":                   ["#3775A9", "#ffffff", "pip"],
  "poetry":                ["#60A5FA", "#000000", "Po"],
  "uv":                    ["#DE5FE9", "#ffffff", "uv"],
  "conda":                 ["#44A833", "#ffffff", "Cn"],
  "nuget":                 ["#004880", "#ffffff", "NuG"],
  "cmake":                 ["#064F8C", "#ffffff", "CM"],
  "make":                  ["#374151", "#ffffff", "Mk"],
  "conan":                 ["#6699CB", "#ffffff", "Co"],
  "vcpkg":                 ["#0078D4", "#ffffff", "VP"],

  // ── Caching ────────────────────────────────────────────────────────────────
  "redis":                 ["#DC382D", "#ffffff", "Re"],
  "memcached":             ["#6CB4E4", "#ffffff", "Mc"],
  "hazelcast":             ["#FF6600", "#ffffff", "Hz"],
  "ehcache":               ["#0033A0", "#ffffff", "EhC"],
  "caffeine":              ["#6DB33F", "#ffffff", "Caf"],
  "varnish":               ["#1A1A1A", "#ffffff", "Va"],

  // ── Cloud — AWS ────────────────────────────────────────────────────────────
  "ec2":                   ["#FF9900", "#000000", "EC2"],
  "ecs":                   ["#FF9900", "#000000", "ECS"],
  "eks":                   ["#FF9900", "#000000", "EKS"],
  "lambda":                ["#FF9900", "#000000", "λ"],
  "s3":                    ["#FF9900", "#000000", "S3"],
  "rds":                   ["#FF9900", "#000000", "RDS"],
  "dynamodb":              ["#FF9900", "#000000", "DDB"],
  "aurora":                ["#FF9900", "#000000", "Au"],
  "elasticache":           ["#FF9900", "#000000", "EC"],
  "cloudfront":            ["#FF9900", "#000000", "CF"],
  "sqs":                   ["#FF9900", "#000000", "SQS"],
  "sns":                   ["#FF9900", "#000000", "SNS"],
  "kinesis":               ["#FF9900", "#000000", "Ki"],
  "eventbridge":           ["#FF9900", "#000000", "EB"],
  "cloudformation":        ["#FF9900", "#000000", "CFn"],
  "bedrock":               ["#FF9900", "#000000", "BR"],
  // Cloud — Azure
  "azure vm":              ["#0078D4", "#ffffff", "VM"],
  "aks":                   ["#0078D4", "#ffffff", "AKS"],
  "azure functions":       ["#0062AD", "#ffffff", "AF"],
  "blob storage":          ["#0078D4", "#ffffff", "BS"],
  "azure sql":             ["#0078D4", "#ffffff", "SQL"],
  "cosmos db":             ["#0078D4", "#ffffff", "Cos"],
  "service bus":           ["#0078D4", "#ffffff", "SB"],
  "event hubs":            ["#0078D4", "#ffffff", "EH"],
  "azure devops":          ["#0078D4", "#ffffff", "ADO"],
  "azure openai":          ["#0078D4", "#ffffff", "AOI"],
  "api management":        ["#0078D4", "#ffffff", "APM"],
  // Cloud — GCP
  "compute engine":        ["#4285F4", "#ffffff", "CE"],
  "gke":                   ["#4285F4", "#ffffff", "GKE"],
  "cloud run":             ["#4285F4", "#ffffff", "CR"],
  "cloud functions":       ["#4285F4", "#ffffff", "CF"],
  "cloud storage":         ["#4285F4", "#ffffff", "CS"],
  "cloud sql":             ["#4285F4", "#ffffff", "SQL"],
  "bigquery":              ["#4285F4", "#ffffff", "BQ"],
  "pub/sub":               ["#4285F4", "#ffffff", "P/S"],
  "vertex ai":             ["#4285F4", "#ffffff", "VAI"],

  // ── Content Management ─────────────────────────────────────────────────────
  "wordpress":             ["#21759B", "#ffffff", "WP"],
  "drupal":                ["#0678BE", "#ffffff", "Dr"],
  "adobe experience manager": ["#FF0000", "#ffffff", "AEM"],
  "contentful":            ["#2478CC", "#ffffff", "Cf"],
  "strapi":                ["#4945FF", "#ffffff", "St"],
  "sanity":                ["#F03E2F", "#ffffff", "Sa"],
  "sitecore":              ["#EB3C00", "#ffffff", "SC"],
  "optimizely":            ["#003DFF", "#ffffff", "Op"],
  "edge delivery services":["#374151", "#ffffff", "EDS"],
  "headless cms":          ["#374151", "#ffffff", "HCMS"],
  "jamstack":              ["#F0047F", "#ffffff", "JAM"],
  "cdn":                   ["#F38020", "#ffffff", "CDN"],
  "edge computing":        ["#374151", "#ffffff", "Edge"],

  // ── Data Engineering ───────────────────────────────────────────────────────
  "apache airflow":        ["#017CEE", "#ffffff", "AF"],
  "apache nifi":           ["#728E9B", "#ffffff", "NiFi"],
  "talend":                ["#FF6D00", "#ffffff", "Ta"],
  "informatica":           ["#FF6C37", "#ffffff", "In"],
  "dbt":                   ["#FF694A", "#ffffff", "dbt"],
  "aws glue":              ["#FF9900", "#000000", "Gl"],
  "azure data factory":    ["#0078D4", "#ffffff", "ADF"],
  "google dataflow":       ["#4285F4", "#ffffff", "DF"],
  "apache hadoop":         ["#FFCC00", "#000000", "Hdp"],
  "apache spark":          ["#E25A1C", "#ffffff", "Sp"],
  "apache flink":          ["#E6526F", "#ffffff", "Fk"],
  "apache beam":           ["#FFAA00", "#000000", "Bm"],
  "hive":                  ["#FDEE21", "#000000", "Hv"],
  "presto":                ["#5890FF", "#ffffff", "Pr"],
  "trino":                 ["#DD00A1", "#ffffff", "Tr"],
  "pyspark":               ["#E25A1C", "#ffffff", "PyS"],
  "spark sql":             ["#E25A1C", "#ffffff", "SQL"],
  "kafka streams":         ["#231F20", "#ffffff", "KS"],
  "flink":                 ["#E6526F", "#ffffff", "Fk"],
  "pandas":                ["#150458", "#ffffff", "Pd"],
  "polars":                ["#CD792C", "#ffffff", "Pl"],
  "numpy":                 ["#4DABCF", "#000000", "Np"],

  // ── Data Platforms ─────────────────────────────────────────────────────────
  "snowflake":             ["#29B5E8", "#000000", "SF"],
  "google bigquery":       ["#4285F4", "#ffffff", "BQ"],
  "amazon redshift":       ["#FF9900", "#000000", "RS"],
  "azure synapse":         ["#0078D4", "#ffffff", "Sy"],
  "teradata":              ["#F37440", "#ffffff", "TD"],
  "databricks sql":        ["#FF3621", "#ffffff", "DBS"],
  "databricks":            ["#FF3621", "#ffffff", "DB"],
  "delta lake":            ["#003087", "#ffffff", "DL"],
  "apache iceberg":        ["#005F73", "#ffffff", "Ice"],
  "apache hudi":           ["#00B4D8", "#ffffff", "Hu"],
  "amazon s3":             ["#FF9900", "#000000", "S3"],
  "azure data lake storage": ["#0078D4", "#ffffff", "ADLS"],
  "google cloud storage":  ["#4285F4", "#ffffff", "GCS"],

  // ── Databases ──────────────────────────────────────────────────────────────
  "postgresql":            ["#336791", "#ffffff", "PG"],
  "mysql":                 ["#4479A1", "#ffffff", "My"],
  "mariadb":               ["#003545", "#ffffff", "MD"],
  "oracle database":       ["#F80000", "#ffffff", "Or"],
  "microsoft sql server":  ["#CC2927", "#ffffff", "SQL"],
  "ibm db2":               ["#1F70C1", "#ffffff", "DB2"],
  "sqlite":                ["#003B57", "#ffffff", "SL"],
  "cockroachdb":           ["#6933FF", "#ffffff", "CR"],
  "sql":                   ["#336791", "#ffffff", "SQL"],
  "pl/sql":                ["#F80000", "#ffffff", "PL/"],
  "t-sql":                 ["#CC2927", "#ffffff", "T-SQL"],
  "jdbc":                  ["#007396", "#ffffff", "JDB"],
  "odbc":                  ["#0078D4", "#ffffff", "ODB"],
  "mongodb":               ["#47A248", "#ffffff", "MG"],
  "couchdb":               ["#E42528", "#ffffff", "Co"],
  "amazon documentdb":     ["#FF9900", "#000000", "DDB"],
  "firebase firestore":    ["#FFCA28", "#000000", "FS"],
  "amazon dynamodb":       ["#FF9900", "#000000", "DDB"],
  "riak":                  ["#FF7D47", "#ffffff", "Ri"],
  "apache cassandra":      ["#1287B1", "#ffffff", "Cs"],
  "scylladb":              ["#6CD5E7", "#000000", "Sc"],
  "hbase":                 ["#FF0000", "#ffffff", "HB"],
  "google bigtable":       ["#4285F4", "#ffffff", "BT"],
  "neo4j":                 ["#008CC1", "#ffffff", "Neo"],
  "amazon neptune":        ["#FF9900", "#000000", "Nep"],
  "janusgraph":            ["#6A55F2", "#ffffff", "JG"],
  "arangodb":              ["#DDE072", "#000000", "ADB"],
  "influxdb":              ["#22ADF6", "#000000", "IF"],
  "timescaledb":           ["#FDB515", "#000000", "TS"],
  "opentsdb":              ["#4A90D9", "#ffffff", "OTS"],

  // ── Desktop ────────────────────────────────────────────────────────────────
  ".net/wpf":              ["#512BD4", "#ffffff", "WPF"],
  "winui":                 ["#0078D4", "#ffffff", "WUI"],
  "windows forms":         ["#0078D4", "#ffffff", "WF"],
  "javafx":                ["#007396", "#ffffff", "JFX"],
  "electron":              ["#47848F", "#ffffff", "El"],
  "qt":                    ["#41CD52", "#000000", "Qt"],
  "gtk":                   ["#7FE719", "#000000", "GTK"],
  "tauri":                 ["#FFC131", "#000000", "Ta"],

  // ── DevOps ─────────────────────────────────────────────────────────────────
  "docker":                ["#2496ED", "#ffffff", "Do"],
  "podman":                ["#892CA0", "#ffffff", "Po"],
  "containerd":            ["#575757", "#ffffff", "ct"],
  "cri-o":                 ["#C9001F", "#ffffff", "CRI"],
  "kubernetes":            ["#326CE5", "#ffffff", "K8s"],
  "openshift":             ["#EE0000", "#ffffff", "OS"],
  "amazon eks":            ["#FF9900", "#000000", "EKS"],
  "azure aks":             ["#0078D4", "#ffffff", "AKS"],
  "google gke":            ["#4285F4", "#ffffff", "GKE"],
  "jenkins":               ["#D24939", "#ffffff", "Jk"],
  "github actions":        ["#2088FF", "#ffffff", "GH"],
  "gitlab ci/cd":          ["#FC6D26", "#ffffff", "GL"],
  "circleci":              ["#343434", "#ffffff", "CC"],
  "argo cd":               ["#EF7B4D", "#ffffff", "AC"],
  "tekton":                ["#FD495C", "#ffffff", "Tk"],
  "terraform":             ["#7B42BC", "#ffffff", "Tf"],
  "opentofu":              ["#FFDA18", "#000000", "OTf"],
  "aws cloudformation":    ["#FF9900", "#000000", "CFn"],
  "azure bicep":           ["#5C2D91", "#ffffff", "Bi"],
  "pulumi":                ["#8A3391", "#ffffff", "Pu"],
  "ansible":               ["#EE0000", "#ffffff", "An"],

  // ── Developer Tools ────────────────────────────────────────────────────────
  "intellij idea":         ["#000000", "#FC801D", "IJ"],
  "visual studio":         ["#5C2D91", "#ffffff", "VS"],
  "visual studio code":    ["#007ACC", "#ffffff", "VSC"],
  "eclipse":               ["#2C2255", "#ffffff", "Ec"],
  "pycharm":               ["#000000", "#22D880", "PC"],
  "android studio":        ["#3DDC84", "#000000", "AS"],
  "xcode":                 ["#147EFB", "#ffffff", "Xc"],
  "cursor":                ["#000000", "#ffffff", "Cu"],
  "github copilot":        ["#181717", "#ffffff", "Co"],

  // ── Distributed Systems ────────────────────────────────────────────────────
  "distributed databases": ["#1565C0", "#ffffff", "DDB"],
  "distributed caching":   ["#DC382D", "#ffffff", "DC"],
  "distributed transactions": ["#1565C0", "#ffffff", "DT"],
  "consensus":             ["#374151", "#ffffff", "Cs"],
  "leader election":       ["#374151", "#ffffff", "LE"],
  "replication":           ["#374151", "#ffffff", "Rep"],
  "sharding":              ["#374151", "#ffffff", "Sh"],
  "partitioning":          ["#374151", "#ffffff", "Par"],
  "cap theorem":           ["#374151", "#ffffff", "CAP"],
  "eventual consistency":  ["#374151", "#ffffff", "EC"],
  "fault tolerance":       ["#374151", "#ffffff", "FT"],
  "load balancing":        ["#374151", "#ffffff", "LB"],
  "zookeeper":             ["#E24829", "#ffffff", "ZK"],
  "etcd":                  ["#419EDA", "#ffffff", "et"],
  "kafka":                 ["#231F20", "#ffffff", "KF"],
  "cassandra":             ["#1287B1", "#ffffff", "Cs"],
  "consul":                ["#CA2171", "#ffffff", "Co"],

  // ── Emerging Technologies ──────────────────────────────────────────────────
  "quantum computing":     ["#374151", "#ffffff", "QC"],
  "spatial computing":     ["#374151", "#ffffff", "SC"],
  "digital twins":         ["#374151", "#ffffff", "DT"],
  "neuromorphic computing":["#374151", "#ffffff", "NC"],
  "confidential computing":["#374151", "#ffffff", "CC"],
  "homomorphic encryption":["#374151", "#ffffff", "HE"],
  "ai coding":             ["#374151", "#ffffff", "AIC"],
  "edge ai":               ["#374151", "#ffffff", "EA"],
  "webassembly":           ["#654FF0", "#ffffff", "WA"],

  // ── Enterprise ─────────────────────────────────────────────────────────────
  "sap":                   ["#0FAAFF", "#000000", "SAP"],
  "salesforce":            ["#00A1E0", "#ffffff", "SF"],
  "servicenow":            ["#62D84E", "#000000", "SN"],
  "oracle":                ["#F80000", "#ffffff", "Or"],
  "microsoft dynamics":    ["#0078D4", "#ffffff", "MD"],
  "mulesoft":              ["#00A1DF", "#ffffff", "MS"],
  "boomi":                 ["#2196F3", "#ffffff", "Bm"],
  "ibm websphere":         ["#1F70C1", "#ffffff", "WS"],
  "red hat":               ["#EE0000", "#ffffff", "RH"],
  "pega":                  ["#00A2DD", "#ffffff", "Pg"],

  // ── Generative AI ──────────────────────────────────────────────────────────
  "gpt":                   ["#412991", "#ffffff", "GPT"],
  "claude":                ["#D4702B", "#ffffff", "Cl"],
  "gemini":                ["#4285F4", "#ffffff", "Gem"],
  "llama":                 ["#7C3AED", "#ffffff", "Ll"],
  "mistral":               ["#F54E42", "#ffffff", "Mi"],
  "qwen":                  ["#7346EE", "#ffffff", "Qw"],
  "deepseek":              ["#4A90D9", "#ffffff", "DS"],
  "langchain":             ["#1C3C3C", "#22C55E", "LC"],
  "haystack":              ["#1A1A1A", "#6AB187", "Hy"],
  "dspy":                  ["#2563EB", "#ffffff", "DS"],
  "rag":                   ["#7C3AED", "#ffffff", "RAG"],
  "hybrid search":         ["#6366F1", "#ffffff", "HS"],
  "semantic search":       ["#8B5CF6", "#ffffff", "Sm"],
  "chunking":              ["#374151", "#ffffff", "Ch"],
  "embeddings":            ["#1E40AF", "#ffffff", "Em"],
  "reranking":             ["#6D28D9", "#ffffff", "Rr"],
  "context engineering":   ["#0F766E", "#ffffff", "CE"],
  "prompt engineering":    ["#7C3AED", "#ffffff", "PE"],
  "agentic rag":           ["#4F46E5", "#ffffff", "AR"],
  "pinecone":              ["#000000", "#00B285", "Pi"],
  "milvus":                ["#00A1EA", "#ffffff", "Mv"],
  "weaviate":              ["#fa0171", "#ffffff", "Wv"],
  "qdrant":                ["#FF5722", "#ffffff", "Qd"],
  "chroma":                ["#F97316", "#ffffff", "Ch"],
  "pgvector":              ["#336791", "#ffffff", "pgV"],
  "elasticsearch":         ["#005571", "#ffffff", "ES"],
  "opensearch":            ["#005EB8", "#ffffff", "OS"],

  // ── IoT & Edge ─────────────────────────────────────────────────────────────
  "raspberry pi":          ["#A22846", "#ffffff", "RPi"],
  "arduino":               ["#00979D", "#ffffff", "Ard"],
  "esp32":                 ["#E7352C", "#ffffff", "E32"],
  "nvidia jetson":         ["#76B900", "#000000", "Jts"],
  "arm":                   ["#00979D", "#ffffff", "ARM"],
  "mqtt":                  ["#660066", "#ffffff", "MQ"],
  "coap":                  ["#6366F1", "#ffffff", "CoAP"],
  "opc-ua":                ["#0032A0", "#ffffff", "OPC"],
  "embedded c/c++":        ["#00599C", "#ffffff", "EC"],

  // ── Kubernetes Ecosystem ───────────────────────────────────────────────────
  "helm":                  ["#277A9F", "#ffffff", "He"],
  "kustomize":             ["#326CE5", "#ffffff", "Kz"],
  "istio":                 ["#466BB0", "#ffffff", "Is"],
  "linkerd":               ["#2BEDA7", "#000000", "Lk"],
  "envoy":                 ["#AC6199", "#ffffff", "En"],
  "argo rollouts":         ["#EF7B4D", "#ffffff", "AR"],
  "prometheus":            ["#E6522C", "#ffffff", "Pm"],
  "fluent bit":            ["#00B6C3", "#ffffff", "FB"],
  "opentelemetry":         ["#F5A800", "#000000", "OT"],
  "rancher":               ["#0075A8", "#ffffff", "Rn"],
  "fluentd":               ["#0E83C8", "#ffffff", "Fd"],
  "loki":                  ["#F46800", "#ffffff", "Lk"],

  // ── MLOps / LLMOps ────────────────────────────────────────────────────────
  "mlflow":                ["#0194E2", "#ffffff", "ML"],
  "kubeflow":              ["#326CE5", "#ffffff", "KF"],
  "weights & biases":      ["#FFBE00", "#000000", "W&B"],
  "dvc":                   ["#945DD6", "#ffffff", "DVC"],
  "airflow":               ["#017CEE", "#ffffff", "AF"],
  "feast":                 ["#2496ED", "#ffffff", "Fs"],
  "bentoml":               ["#FF6C37", "#ffffff", "BML"],
  "ray":                   ["#029CF5", "#000000", "Ray"],
  "nvidia triton":         ["#76B900", "#000000", "NvT"],
  "kserve":                ["#326CE5", "#ffffff", "KSv"],
  "prompt management":     ["#7C3AED", "#ffffff", "PM"],
  "model evaluation":      ["#7C3AED", "#ffffff", "ME"],
  "llm observability":     ["#7C3AED", "#ffffff", "LO"],
  "token monitoring":      ["#7C3AED", "#ffffff", "TM"],
  "guardrails":            ["#7C3AED", "#ffffff", "GR"],
  "ai safety":             ["#7C3AED", "#ffffff", "AS"],
  "model gateway":         ["#7C3AED", "#ffffff", "MG"],
  "model routing":         ["#7C3AED", "#ffffff", "MR"],
  "rag evaluation":        ["#7C3AED", "#ffffff", "RE"],

  // ── Messaging & Streaming ──────────────────────────────────────────────────
  "rabbitmq":              ["#FF6600", "#ffffff", "RQ"],
  "apache activemq":       ["#D3280C", "#ffffff", "AMQ"],
  "amazon sqs":            ["#FF9900", "#000000", "SQS"],
  "azure service bus":     ["#0078D4", "#ffffff", "SB"],
  "google pub/sub":        ["#4285F4", "#ffffff", "P/S"],
  "apache kafka":          ["#231F20", "#ffffff", "KF"],
  "apache pulsar":         ["#198FE3", "#ffffff", "Pu"],
  "amazon kinesis":        ["#FF9900", "#000000", "Kn"],
  "redpanda":              ["#E84142", "#ffffff", "RP"],
  "kafka connect":         ["#231F20", "#ffffff", "KC"],
  "schema registry":       ["#231F20", "#ffffff", "SR"],
  "ksqldb":                ["#231F20", "#ffffff", "KSQL"],

  // ── Microservices Patterns ─────────────────────────────────────────────────
  "service discovery":     ["#374151", "#ffffff", "SD"],
  "circuit breaker":       ["#374151", "#ffffff", "CB"],
  "strangler fig (micro)": ["#5D4037", "#ffffff", "SF"],
  "bulkhead":              ["#374151", "#ffffff", "BH"],
  "retry":                 ["#374151", "#ffffff", "RT"],
  "rate limiting":         ["#374151", "#ffffff", "RL"],
  "openfeign":             ["#374151", "#ffffff", "OF"],
  "eureka":                ["#374151", "#ffffff", "Eu"],

  // ── Mobile ────────────────────────────────────────────────────────────────
  "kotlin":                ["#7F52FF", "#ffffff", "Kt"],
  "java":                  ["#007396", "#ffffff", "Jv"],
  "android sdk":           ["#3DDC84", "#000000", "SDK"],
  "jetpack compose":       ["#4285F4", "#ffffff", "JC"],
  "swift":                 ["#FA7343", "#ffffff", "Sw"],
  "swiftui":               ["#FA7343", "#ffffff", "SwUI"],
  "objective-c":           ["#438EFF", "#ffffff", "OC"],
  "flutter":               ["#02569B", "#ffffff", "FL"],
  "react native":          ["#20232A", "#61DAFB", "RN"],
  ".net maui":             ["#512BD4", "#ffffff", "MAUI"],
  "ionic":                 ["#3880FF", "#ffffff", "Io"],
  "kotlin multiplatform":  ["#7F52FF", "#ffffff", "KMP"],

  // ── Networking ────────────────────────────────────────────────────────────
  "tcp/ip":                ["#374151", "#ffffff", "TCP"],
  "http/https":            ["#374151", "#ffffff", "HTTP"],
  "dns":                   ["#374151", "#ffffff", "DNS"],
  "dhcp":                  ["#374151", "#ffffff", "DHCP"],
  "ftp/sftp":              ["#374151", "#ffffff", "FTP"],
  "smtp":                  ["#374151", "#ffffff", "SMTP"],
  "ssh":                   ["#374151", "#ffffff", "SSH"],
  "tls":                   ["#374151", "#ffffff", "TLS"],
  "udp":                   ["#374151", "#ffffff", "UDP"],
  "quic":                  ["#374151", "#ffffff", "QUIC"],
  "load balancer":         ["#374151", "#ffffff", "LB"],
  "reverse proxy":         ["#374151", "#ffffff", "RP"],
  "vpn":                   ["#374151", "#ffffff", "VPN"],
  "sdn":                   ["#374151", "#ffffff", "SDN"],
  "service mesh":          ["#374151", "#ffffff", "SM"],
  "haproxy":               ["#374151", "#ffffff", "HA"],
  "cloudflare":            ["#F38020", "#ffffff", "CF"],
  "f5":                    ["#E4002B", "#ffffff", "F5"],

  // ── Observability ─────────────────────────────────────────────────────────
  "datadog":               ["#632CA6", "#ffffff", "DD"],
  "new relic":             ["#008C99", "#ffffff", "NR"],
  "logstash":              ["#005571", "#ffffff", "Ls"],
  "jaeger":                ["#60D0E4", "#000000", "Ja"],
  "zipkin":                ["#FF6600", "#ffffff", "Zi"],
  "dynatrace":             ["#1496FF", "#ffffff", "Dy"],
  "appdynamics":           ["#00A1DF", "#ffffff", "AD"],

  // ── Operating Systems ─────────────────────────────────────────────────────
  "linux":                 ["#FCC624", "#000000", "Li"],
  "windows":               ["#0078D4", "#ffffff", "Win"],
  "macos":                 ["#000000", "#ffffff", "Mac"],
  "unix":                  ["#374151", "#ffffff", "Unix"],
  "android":               ["#3DDC84", "#000000", "And"],
  "ios":                   ["#000000", "#ffffff", "iOS"],
  "ubuntu":                ["#E95420", "#ffffff", "Ub"],
  "red hat enterprise linux": ["#EE0000", "#ffffff", "RHEL"],
  "rocky linux":           ["#10B981", "#ffffff", "RL"],
  "debian":                ["#A81D33", "#ffffff", "De"],
  "alpine":                ["#0D597F", "#ffffff", "Al"],
  "centos stream":         ["#262577", "#ffffff", "CS"],

  // ── Programming Languages ─────────────────────────────────────────────────
  "python":                ["#3776AB", "#ffffff", "Py"],
  "c":                     ["#A8B9CC", "#000000", "C"],
  "c++":                   ["#00599C", "#ffffff", "C++"],
  "c#":                    ["#239120", "#ffffff", "C#"],
  "go":                    ["#00ADD8", "#ffffff", "Go"],
  "rust":                  ["#000000", "#ffffff", "Rs"],
  "javascript":            ["#F7DF1E", "#000000", "JS"],
  "typescript":            ["#3178C6", "#ffffff", "TS"],
  "php":                   ["#777BB4", "#ffffff", "PHP"],
  "ruby":                  ["#CC342D", "#ffffff", "Rb"],
  "dart":                  ["#0175C2", "#ffffff", "Da"],
  "r":                     ["#276DC3", "#ffffff", "R"],
  "julia":                 ["#9558B2", "#ffffff", "Jl"],
  "matlab":                ["#0076A8", "#ffffff", "ML"],
  "haskell":               ["#5D4F85", "#ffffff", "Hs"],
  "erlang":                ["#A90533", "#ffffff", "Er"],
  "elixir":                ["#4B275F", "#ffffff", "Ex"],
  "f#":                    ["#378BBA", "#ffffff", "F#"],
  "clojure":               ["#5881D8", "#ffffff", "Cl"],
  "cobol":                 ["#005CA5", "#ffffff", "CO"],
  "fortran":               ["#734F96", "#ffffff", "Fo"],
  "pl/i":                  ["#005CA5", "#ffffff", "PL/I"],
  "rpg":                   ["#0066CC", "#ffffff", "RPG"],
  "move":                  ["#4F46E5", "#ffffff", "Mv"],

  // ── Robotics ──────────────────────────────────────────────────────────────
  "ros/ros2":              ["#22314E", "#ffffff", "ROS"],
  "nvidia isaac":          ["#76B900", "#000000", "Isa"],
  "gazebo":                ["#374151", "#ffffff", "Gz"],
  "slam":                  ["#374151", "#ffffff", "SLAM"],
  "motion planning":       ["#374151", "#ffffff", "MP"],

  // ── Search ────────────────────────────────────────────────────────────────
  "apache solr":           ["#D9411E", "#ffffff", "So"],
  "algolia":               ["#003DFF", "#ffffff", "Al"],
  "typesense":             ["#E35E0D", "#ffffff", "Ts"],
  "meilisearch":           ["#FF5CAA", "#ffffff", "Me"],

  // ── Security ──────────────────────────────────────────────────────────────
  "oauth 2.0":             ["#EB5424", "#ffffff", "OA"],
  "openid connect":        ["#F78C40", "#000000", "OID"],
  "saml":                  ["#B03A2E", "#ffffff", "SAML"],
  "jwt":                   ["#000000", "#fb015b", "JWT"],
  "ldap":                  ["#00439C", "#ffffff", "LDAP"],
  "active directory":      ["#0078D4", "#ffffff", "AD"],
  "keycloak":              ["#008AAA", "#ffffff", "KC"],
  "auth0":                 ["#EB5424", "#ffffff", "A0"],
  "okta":                  ["#007DC1", "#ffffff", "Ok"],
  "waf":                   ["#232F3E", "#FF9900", "WAF"],
  "iam":                   ["#232F3E", "#FF9900", "IAM"],
  "zero trust":            ["#374151", "#ffffff", "ZT"],
  "siem":                  ["#374151", "#ffffff", "SIEM"],
  "secrets management":    ["#374151", "#ffffff", "SM"],
  "encryption":            ["#374151", "#ffffff", "Enc"],
  "pki":                   ["#374151", "#ffffff", "PKI"],
  "tls/ssl":               ["#374151", "#ffffff", "TLS"],
  "mtls":                  ["#374151", "#ffffff", "mTLS"],
  "hashicorp vault":       ["#000000", "#FFCA28", "Vt"],
  "cyberark":              ["#274B7A", "#ffffff", "CA"],
  "sonarqube":             ["#4E9BCD", "#ffffff", "SQ"],
  "snyk":                  ["#4C4A73", "#ffffff", "Sk"],
  "checkmarx":             ["#47A141", "#ffffff", "Cx"],
  "fortify":               ["#00ABE5", "#ffffff", "Fo"],

  // ── Testing ───────────────────────────────────────────────────────────────
  "junit":                 ["#25A162", "#ffffff", "JU"],
  "mockito":               ["#C5D928", "#000000", "Mo"],
  "jest":                  ["#C21325", "#ffffff", "Jt"],
  "vitest":                ["#6E9F18", "#ffffff", "Vt"],
  "pytest":                ["#0A9EDC", "#ffffff", "Py"],
  "nunit":                 ["#239120", "#ffffff", "NU"],
  "xunit":                 ["#512BD4", "#ffffff", "xU"],
  "rest assured":          ["#374151", "#ffffff", "RA"],
  "karate":                ["#374151", "#ffffff", "Ka"],
  "soapui":                ["#F47920", "#ffffff", "SUI"],
  "selenium":              ["#43B02A", "#ffffff", "Se"],
  "playwright":            ["#45BA4B", "#ffffff", "Pw"],
  "cypress":               ["#17202C", "#ffffff", "Cy"],
  "webdriverio":           ["#EA5906", "#ffffff", "WIO"],
  "jmeter":                ["#D22128", "#ffffff", "JM"],
  "gatling":               ["#FF9E2A", "#000000", "Ga"],
  "k6":                    ["#7D64FF", "#ffffff", "k6"],
  "locust":                ["#00BFB3", "#000000", "Lo"],
  "owasp zap":             ["#00549E", "#ffffff", "ZAP"],
  "burp suite":            ["#F47421", "#ffffff", "BS"],

  // ── Version Control ────────────────────────────────────────────────────────
  "git":                   ["#F05032", "#ffffff", "Git"],
  "github":                ["#181717", "#ffffff", "GH"],
  "gitlab":                ["#FC6D26", "#ffffff", "GL"],
  "bitbucket":             ["#0052CC", "#ffffff", "BB"],
  "azure repos":           ["#0078D4", "#ffffff", "AR"],
  "svn":                   ["#809CC9", "#ffffff", "SVN"],
  "perforce":              ["#F26724", "#ffffff", "P4"],

  // ── Web Technologies ───────────────────────────────────────────────────────
  "html":                  ["#E34F26", "#ffffff", "H5"],
  "css":                   ["#1572B6", "#ffffff", "CSS"],
  "web components":        ["#29ABE2", "#ffffff", "WC"],
  "ajax":                  ["#374151", "#ffffff", "AJAX"],
  "json":                  ["#000000", "#ffffff", "JSON"],
  "xml":                   ["#F80000", "#ffffff", "XML"],
  "angular":               ["#DD0031", "#ffffff", "Ng"],
  "vue.js":                ["#42B883", "#000000", "Vue"],
  "svelte":                ["#FF3E00", "#ffffff", "Sv"],
  "next.js":               ["#000000", "#ffffff", "Nxt"],
  "nuxt":                  ["#00C58E", "#000000", "Nx"],
  "astro":                 ["#FF5D01", "#ffffff", "As"],
  "remix":                 ["#000000", "#ffffff", "Rmx"],
  "lit":                   ["#324FFF", "#ffffff", "Lit"],
  "solidjs":               ["#2C4F7C", "#ffffff", "So"],
  "bootstrap":             ["#7952B3", "#ffffff", "BS"],
  "tailwind css":          ["#06B6D4", "#000000", "TW"],
  "material ui":           ["#0081CB", "#ffffff", "MUI"],
  "ant design":            ["#0170FE", "#ffffff", "AntD"],
  "sass":                  ["#CC6699", "#ffffff", "Sass"],
  "less":                  ["#1D365D", "#ffffff", "Less"],
  "chakra ui":             ["#319795", "#ffffff", "Cha"],
};

interface TechItemIconProps {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

export function TechItemIcon({ name, size = 32, className, style }: TechItemIconProps) {
  const key = name.toLowerCase();
  const brand = BRANDS[key];

  const bg  = brand ? brand[0] : "#374151";
  const fg  = brand ? brand[1] : "#ffffff";
  const raw = brand ? brand[2] : name.charAt(0).toUpperCase();

  const fontSize =
    raw.length <= 2 ? Math.round(size * 0.38) :
    raw.length === 3 ? Math.round(size * 0.3) :
    raw.length === 4 ? Math.round(size * 0.24) :
    Math.round(size * 0.19);

  return (
    <div
      className={className}
      style={{
        width: size,
        height: size,
        backgroundColor: bg,
        borderRadius: Math.max(4, Math.round(size * 0.22)),
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        fontFamily: "system-ui, -apple-system, 'Segoe UI', sans-serif",
        fontWeight: 800,
        color: fg,
        fontSize,
        letterSpacing: raw.length >= 3 ? "-0.04em" : "0",
        lineHeight: "1",
        userSelect: "none",
        ...style,
      }}
    >
      {raw}
    </div>
  );
}
